CLUSTAL format alignment by MAFFT FFT-NS-2 (v6.860b)


L7M074_9ACAR|Rh ----------------------------------MAAR--KSIIPGGYRDRVLFLLMMCG
G1MJ71_AILME|Ai ------------------------------------------MLALRLLNVVAPAYFLCI
G1KTK1_ANOCA|An ------------------------------------------MLVLRFLNVVAPAYFLCI
Q7PVS0_ANOGA|An ---------------------------------TMRIR--KHVLPRTLQDAVATAFMAGI
E1B987_BOVIN|Bo ------------------------------------------MLALRLLNVVAPAYFLCI
C3Z5I5_BRAFL|Br ---------------------MHRITMDMDISDMHWKIKGTSKFTRKGASILGVIYFFLF
F6Y2X5_CALJA|Ca ------------------------------------------MLALRLLNVVAPAYFLCI
E2AAM9_CAMFO|Ca ----------------------------------MIIR--KKIWPRTIGDLLSMIFVLVI
J9NZC5_CANFA|Ca ------------------------------------------MLALRLLNVVAPAYFLCI
H0W7M0_CAVPO|Ca ------------------------------------------MLALRLLNVVAPAYFLCI
E1C5D7_CHICK|Ga ------------------------------------------MLVLRLLNVVAPAYFLCI
B0WDA3_CULQU|Cu ----------------------------------MKIR--KRFLPRCVQDGVATLFMIGI
G6DDL9_DANPL|Da ------------------------------------------------------------
E7EY29_DANRE|Da --------------------------------------MLFKMGKLKLLNTIAPAYFYAA
B3MEE9_DROAN|Dr ----------------------------------MRIR--RNPLPRRLVDILCFLLIGIF
B4JHI4_DROGR|Dr MARIKWRLGA-----------------NQNIFSTFRLR----------------------
Q9I7L7_DROME|Dr ----------------------------------MRFRSLKNIWPKEKLEQFLFLFILCG
B4K9M3_DROMO|Dr MARITWRTSS-----------------TQNLVSKFRLR----------------------
B4GIR9_DROPE|Dr --MISNRSQSIPISTVPAVTQLAIECLTEDRGDDRRQRRTCCGCLESIFNWMPVIFIVGL
B5E105_DROPS|Dr --MISNRSQSIPIDTVPVVTQLAIECLTEDRGDDRRQRRTCCGCLESIFNWIPVIFIVCL
B4M137_DROVI|Dr MVRITWRTNS-----------------TQSLVSTFRLR----------------------
B4NJC4_DROWI|Dr --------------------------------------------MKNHGDGIVHIFHVIS
B4P7Y0_DROYA|Dr ----------------------------------MRIR--SNPLPRRLVDTTCFLIIGIF
G3NYI0_GASAC|Ga ------------------------------------------MLKLRLLNAVAPAYFFVA
G3R3R5_GORGO|Go ------------------------------------------MLALRLLNVVAPAYFLCI
G5B683_HETGA|He ------------------------------------------MLALRLLNVVAPAYFLCI
F6SFZ8_HORSE|Eq ------------------------------------------MLALRLLNVVAPAYFLCI
ZDH22_HUMAN|Hom ------------------------------------------MLALRLLNVVAPAYFLCI
H3AW31_LATCH|La --------------------------------------MLPKMFKLRLLNFIASTYFLSA
G3UIR0_LOXAF|Lo ------------------------------------------MLALRLLNVVAPAYFLCI
G7PB25_MACFA|Ma ------------------------------------------MLALRLLNVVAPAYFLCI
G7MYW0_MACMU|Ma ------------------------------------------MLALRLLNVVAPAYFLCI
G1NJK6_MELGA|Me ------------------------------------------MLVLRLLNVVAPAYFLCI
F7G5M0_MONDO|Mo ------------------------------------------MLILRLLNVVAPVYFLCI
ZDH22_MOUSE|Mus ------------------------------------------MLALRLLNVVAPAYFLCI
G9KYT5_MUSPF|Mu ---------------------------------------MGQPWAVGTGEGAPARLPLVL
G1PX45_MYOLU|My ------------------------------------------MLALRLLNVVAPAYFLCI
K7IP65_NASVI|Na ----------------------------------MLIR--RKILPRTASDILSTTFLLII
A7SWQ7_NEMVE|Ne ------------------------MFSQDPQYEKLSLA--KRVIPKKGSDAAAFVFMFVM
G1S3X2_NOMLE|No ------------------------------------------MLALRLLNVVAPAYFLCI
I3KWA6_ORENI|Or --------------------------------------MFTRMLKLRLLNAVAPAYFFTA
F6SE12_ORNAN|Or ----PGGGGQGGLGPVGLRARPRRDRPGGGAERTAEERGGGCALNHSIVSTAPSAY----
H2MNL7_ORYLA|Or --------------------------------------MFTRMLKLRLLNAVAPVYFFMA
H0XYR4_OTOGA|Ot ------------------------------------------MLALRLLNVVAPAYFLCI
H2RG61_PANTR|Pa ------------------------------------------MLALRLLNVVAPAYFLCI
K7GJD6_PELSI|Pe ------------------------------------------MLVLRVLNVVAPTYFLCI
F1S2N2_PIG|Sus  ------------------------------------------MLALRLLNVVAPAYFLCI
H2NLW0_PONAB|Po ------------------------------------------MLALRLLNVVAPAYFLCI
L5JNU0_PTEAL|Pt ------------------------------------------MLALRLLNVVAPAYFLCI
G1SNL9_RABIT|Or ------------------------------------------MLALRLLNVVAPAYFLCL
ZDH22_RAT|Rattu ------------------------------------------MLALRLLNVVAPAYFLCI
G3W6V0_SARHA|Sa ------------------------------------------MLILRLLNVVAPVYFLCI
I3LX43_SPETR|Sp ------------------------------------------MLALRLLNVVAPAYFLCI
H0ZPV6_TAEGU|Ta ------------------------------------------MLVLRLLNVVAPAYFLCI
H2VBD4_TAKRU|Ta ------------------------------------------MLKLRLLNVVAPVYFFTA
H3DJ29_TETNG|Te ------------------------------------------MLKLRLLNVVAPVYFFTA
F7DR35_XENTR|Xe ------------------------------------------------------------
                                                                            

L7M074_9ACAR|Rh IPVI-------VFFDFC----------------FVAPRYHDTFDKF-----MWVHSASAA
G1MJ71_AILME|Ai SLVT-------FALQLF----------------LFLPSMRQDPAATRLFPPALLHGALFL
G1KTK1_ANOCA|An SIVT-------FGLQLF----------------LFIPSMFQDPSANPLFSSALLHGVLFL
Q7PVS0_ANOGA|An IPIT-------FWFEVY----------------VVIPGIHGPDSVY-----NWVHFVPAV
E1B987_BOVIN|Bo ALVT-------LVLQLF----------------LFLPRMREDPTAARLFSPALLHGALFL
C3Z5I5_BRAFL|Br AGTI-------MWTTVV----------------HALPSLYPESTEG-----GKIHYFLIV
F6Y2X5_CALJA|Ca SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
E2AAM9_CAMFO|Ca VPLM-------YWFGLW----------------IVLPALYKDDILP-----YTLHFVLGN
J9NZC5_CANFA|Ca SLVT-------LALQLF----------------LFLPSMRQDPAAARLFPPALLHGALFL
H0W7M0_CAVPO|Ca SLVT-------FVLQLF----------------LFLPSMREDPAATRLLSPALLHGALFL
E1C5D7_CHICK|Ga SLVT-------FVLQIF----------------LFIPSMFRDPSTTPLFSPALLHGALFL
B0WDA3_CULQU|Cu IPVT-------FWFEVS----------------VVIPGIHGTNSGW-----NWIHLVPAL
G6DDL9_DANPL|Da ------------------------------------------------------------
E7EY29_DANRE|Da TVVT-------FALHFL----------------LFTPTIFQSSDVT-INPAMLAHISIFL
B3MEE9_DROAN|Dr LPVV-------FMFEIV----------------VVLPNFHDPGSFF-----HTLHFLMAM
B4JHI4_DROGR|Dr --WS-------YMKHCWHSLTINSHMNSSYAIDVCMTPIFWIVDNY-------THCLGPF
Q9I7L7_DROME|Dr LPAI-------YYVLME----------------IILPELSDYWSPG-----YVFQLLLGL
B4K9M3_DROMO|Dr --WS-------YMKHCWHSLTFNAHMNSSYATDVCMTPIFWIVDNY-------THCLGPF
B4GIR9_DROPE|Dr IVYS-------YYVYVWHLCLQNMRNHSAIVLGVVL---FW------------YHLLLLM
B5E105_DROPS|Dr IVYS-------YYVYVWHLCLQNMRNHSAIVLGVVL---FW------------YHLLLLM
B4M137_DROVI|Dr --WS-------YMNHCWHSLTFNAHMNSSYATDVCMTPIFWVVDNY-------THCLGPF
B4NJC4_DROWI|Dr FSLLMGITLFFFIYEVW----------------FILPILCDTRSWS-----YTFNCMLCI
B4P7Y0_DROYA|Dr LPVV-------FMFEIV----------------VVLPAFHEPGGFF-----HTFTFLMAM
G3NYI0_GASAC|Ga TAVT-------FILHFC----------------FFIPTIFSNPHAS-LSSSTALHTLVFL
G3R3R5_GORGO|Go SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
G5B683_HETGA|He SLVT-------FVLQLF----------------LFLPSMREDPAATPLLSPALLHGALFL
F6SFZ8_HORSE|Eq SLVT-------FVLQLF----------------LFLPSMREDPAAAPLFSPALLHGALFL
ZDH22_HUMAN|Hom SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
H3AW31_LATCH|La SVVT-------FALQLF----------------VFIPTVFGSPSIR-LSPSVLLHWGLFL
G3UIR0_LOXAF|Lo ALVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
G7PB25_MACFA|Ma SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
G7MYW0_MACMU|Ma SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
G1NJK6_MELGA|Me SLVT-------FVLQIF----------------LFIPSMFRDPSTTPLFSPALLHGALFL
F7G5M0_MONDO|Mo SLVT-------FILQLF----------------LFLPNMFKDPTITPLFSPALLHGALFL
ZDH22_MOUSE|Mus SLVT-------FVLQLF----------------LFLPSMREDPTATPLFSPAVLHGALFL
G9KYT5_MUSPF|Mu TALWAAAVGLELAY-VL----------------ILGPGPPPLGPLA-----RALQLVLAA
G1PX45_MYOLU|My SLVT-------FALQLF----------------LFLPSMREDPAA-RLCSPALLHGALFL
K7IP65_NASVI|Na VPLL-------YWFELW----------------VVLPNLYEPGSAM-----YIFHFCLGS
A7SWQ7_NEMVE|Ne LWVI-------SLFELL----------------VVLPIYHEFLSTW-----YLIHVFCGL
G1S3X2_NOMLE|No SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
I3KWA6_ORENI|Or TAVT-------FILHFG----------------FFIPTIFPSQGTS-LEGSKVLHTVIFL
F6SE12_ORNAN|Or SVRS-------AALSAWNGQVGNRWRPSLPNNGLTVPSAAPAPSPT---PAGTDQGDLKV
H2MNL7_ORYLA|Or TAVT-------NILHFF----------------FFIPTIFPYPETS-LMVSSTLHTVLVL
H0XYR4_OTOGA|Ot SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
H2RG61_PANTR|Pa SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
K7GJD6_PELSI|Pe SLVT-------FVLQLF----------------LFIPSMFKDPSTTPLFSPALLHGALFL
F1S2N2_PIG|Sus  SLVT-------FVLQLF----------------LFLPSMRQDPAAARIFSPALLHGALFL
H2NLW0_PONAB|Po SLVT-------FVLQLF----------------LFLPSMREDPAAARLFSPALLHGALFL
L5JNU0_PTEAL|Pt SLVT-------FVLQLF----------------LFLPSMREDPAAAPLFSPALLHGALFL
G1SNL9_RABIT|Or SLVT-------FALQLF----------------LFLPSMREDPAAAPLFPPALLHGALFL
ZDH22_RAT|Rattu SLVT-------FVLQLF----------------LFLPSMREDPTATPLFSPAVLHGALFL
G3W6V0_SARHA|Sa SLVT-------FILQLF----------------LFLPNMFKDPTITPLFSPALLHGALFL
I3LX43_SPETR|Sp SLVT-------FVLQLF----------------LFLPSMREDPAAAPLFSPALLHGALFL
H0ZPV6_TAEGU|Ta SLVT-------FVLQIF----------------VFIPSMFRDPSTTSLFSPALLHGALFL
H2VBD4_TAKRU|Ta TAVT-------FVFHFC----------------FFVPTIFPVPDAP-LWASTTLHTALFL
H3DJ29_TETNG|Te TAVT-------FVFHFC----------------FFLPTIFPVPDAS-LWASTSLHTALFL
F7DR35_XENTR|Xe --------------------------------------------------------SLFV
                                                                            

L7M074_9ACAR|Rh FILF--------------------------------------------------------
G1MJ71_AILME|Ai FLST--------------------------------------------------------
G1KTK1_ANOCA|An FLSA--------------------------------------------------------
Q7PVS0_ANOGA|An LLLF--------------------------------------------------------
E1B987_BOVIN|Bo FLSA--------------------------------------------------------
C3Z5I5_BRAFL|Br FLWG--------------------------------------------------------
F6Y2X5_CALJA|Ca FLSA--------------------------------------------------------
E2AAM9_CAMFO|Ca FIMF--------------------------------------------------------
J9NZC5_CANFA|Ca FLST--------------------------------------------------------
H0W7M0_CAVPO|Ca FLSA--------------------------------------------------------
E1C5D7_CHICK|Ga FLSA--------------------------------------------------------
B0WDA3_CULQU|Cu FLLY--------------------------------------------------------
G6DDL9_DANPL|Da ------------------------------------------------------------
E7EY29_DANRE|Da FLMG--------------------------------------------------------
B3MEE9_DROAN|Dr FLVF--------------------------------------------------------
B4JHI4_DROGR|Dr FVVGVAVLTTVVVSIAYWIGLPFWWAKSQLATILLLIFGNWVL-----------------
Q9I7L7_DROME|Dr FLFS--------------------------------------------------------
B4K9M3_DROMO|Dr FVVGTAILTTAVVSIAYWIGLPFWWAKSQAATIVLLIIGNWLL-----------------
B4GIR9_DROPE|Dr FL------------WSYWSSM---WAK------VMPIPAEWSIPDADWTRLIRANGLEER
B5E105_DROPS|Dr FL------------WSYWSSM---WAK------VMPIPAEWSIPDADWTRLIRANGLEER
B4M137_DROVI|Dr FVVGVAILTTAVVGIAYWIGLPFWWAKSQVATILLLIVGNWLL-----------------
B4NJC4_DROWI|Dr YTLH--------------------------------------------------------
B4P7Y0_DROYA|Dr FLVF--------------------------------------------------------
G3NYI0_GASAC|Ga FLMF--------------------------------------------------------
G3R3R5_GORGO|Go FLSA--------------------------------------------------------
G5B683_HETGA|He FLSA--------------------------------------------------------
F6SFZ8_HORSE|Eq FLST--------------------------------------------------------
ZDH22_HUMAN|Hom FLSA--------------------------------------------------------
H3AW31_LATCH|La SLSA--------------------------------------------------------
G3UIR0_LOXAF|Lo FLSA--------------------------------------------------------
G7PB25_MACFA|Ma FLSA--------------------------------------------------------
G7MYW0_MACMU|Ma FLSA--------------------------------------------------------
G1NJK6_MELGA|Me FLSA--------------------------------------------------------
F7G5M0_MONDO|Mo FLSA--------------------------------------------------------
ZDH22_MOUSE|Mus FLSA--------------------------------------------------------
G9KYT5_MUSPF|Mu FQLL--------------------------------------------------------
G1PX45_MYOLU|My FLST--------------------------------------------------------
K7IP65_NASVI|Na FIMI--------------------------------------------------------
A7SWQ7_NEMVE|Ne FMFL--------------------------------------------------------
G1S3X2_NOMLE|No FLSA--------------------------------------------------------
I3KWA6_ORENI|Or FLMF--------------------------------------------------------
F6SE12_ORNAN|Or IRRALRPASRREGR----------------------------------------------
H2MNL7_ORYLA|Or FLMF--------------------------------------------------------
H0XYR4_OTOGA|Ot FLSA--------------------------------------------------------
H2RG61_PANTR|Pa FLSA--------------------------------------------------------
K7GJD6_PELSI|Pe FLSA--------------------------------------------------------
F1S2N2_PIG|Sus  FLST--------------------------------------------------------
H2NLW0_PONAB|Po FLSA--------------------------------------------------------
L5JNU0_PTEAL|Pt FLST--------------------------------------------------------
G1SNL9_RABIT|Or FLSA--------------------------------------------------------
ZDH22_RAT|Rattu FLSA--------------------------------------------------------
G3W6V0_SARHA|Sa FLSA--------------------------------------------------------
I3LX43_SPETR|Sp FLSA--------------------------------------------------------
H0ZPV6_TAEGU|Ta FLSA--------------------------------------------------------
H2VBD4_TAKRU|Ta FSMF--------------------------------------------------------
H3DJ29_TETNG|Te FSMF--------------------------------------------------------
F7DR35_XENTR|Xe VLLV--------------------------------------------------------
                                                                            

L7M074_9ACAR|Rh -NIYANLFKLLLTDTSAH-------HTADDVLLPG-------WRY-------CPVCAMNV
G1MJ71_AILME|Ai -NALGNYVLVI-----------QNSPDDLD-----AC--QGPSAR-------RAPCP---
G1KTK1_ANOCA|An -NALGNYILVI-----------QNTPEDLR-----AQEDLGLTKL-------VAPESEEV
Q7PVS0_ANOGA|An -NVTAHMLATMLCDTSCSTELIQLPPAGVSTAGAGTGLSSKSWHL-------CATCEFIA
E1B987_BOVIN|Bo -NALGNYVLVI-----------QNSPDDLD-----AC--QGAEAR-------RALCP---
C3Z5I5_BRAFL|Br -NMLANYCLCCTTKSFYKDHEPKHVPEHWNY---------------------CLPCGKHL
F6Y2X5_CALJA|Ca -NALGNYVLVI-----------QNSPDDLG-----AC--QGASAT-------KAPCP---
E2AAM9_CAMFO|Ca -NIVGNFTYTVLCDTSTKRRIV---PVSTATVADG-------WRL-------CATCECLS
J9NZC5_CANFA|Ca -NALGNYVLVI-----------QNSPEDLD-----AC--QGPPAR-------RAPCP---
H0W7M0_CAVPO|Ca -NALGNYVLVI-----------QNSPDDLG-----AC--QGSSAR-------RALCP---
E1C5D7_CHICK|Ga -NALGNYILVI-----------QSSPEELG-----KGLNLGEGAEMVADWLDGSRSPGSA
B0WDA3_CULQU|Cu -NISTNMLATILCDTSCGTEVISVPPDVAVASGQG----SRSWHL-------CSTCEAVA
G6DDL9_DANPL|Da ------MILGIFTDTTIKMRAR----------------SHNCEEF-------CESCQMYR
E7EY29_DANRE|Da -NALGNYIMTI-----------RNPSESAN-----ET---------------VIPVCSPD
B3MEE9_DROAN|Dr -NIKSNMIACMMIDTSCDVKKI-EPPEDHSD-----------WRE-------CDICQKLA
B4JHI4_DROGR|Dr LNIIFHYVMAVITPPGHPPEGVSQVEAVSM----------------------CSKCITPK
Q9I7L7_DROME|Dr -NVMSNYVMCILVDPSIDPKLM------KNQLVRG--QHSEDWHE-------CDKCGILA
B4K9M3_DROMO|Dr LNIIFHYVMGVITPAGQPPEGISHVEAVSM----------------------CSKCISPK
B4GIR9_DROPE|Dr RHILSHVARRL------PITMCDQNGVVRY----------------------CGQCRLIK
B5E105_DROPS|Dr RHILSHVARRL------PITMCDQNGVVRY----------------------CGQCRLIK
B4M137_DROVI|Dr LNIIFHYVMAVITPAGQPPEGVSHVEAVSM----------------------CTKCISPK
B4NJC4_DROWI|Dr -NIIGNFLMCWLTDNSMKSL-----PNYRQHPPPT---EARFWHL-------CTQCQMMV
B4P7Y0_DROYA|Dr -NIKGNMIACIMIDSSVDVKKI-DPPGDQEN-----------WRE-------CGECQKLA
G3NYI0_GASAC|Ga -NALGNYIMTI-----------KYPAESAN-----ET---------------VVPVCSAH
G3R3R5_GORGO|Go -NALGNYVLVI-----------QNSPDDLG-----AC--QGASAR-------KTPCP---
G5B683_HETGA|He -NALGNYVLVV-----------QNSPDDLG-----AY--QGSSAR-------RAQCP---
F6SFZ8_HORSE|Eq -NALGNYVLVI-----------QNSPDDLD-----AC--QGASAK-------RAPCP---
ZDH22_HUMAN|Hom -NALGNYVLVI-----------QNSPDDLG-----AC--QGASAR-------KTPCP---
H3AW31_LATCH|La -NVLGNYALII-----------LNPSECLR-----NA---------------MGPHQAGD
G3UIR0_LOXAF|Lo -NALGNYVLVI-----------QNSPDDLG-----AC--QGTSAR-------RAACP---
G7PB25_MACFA|Ma -NALGNYVLVI-----------QNSPDDLG-----AC--QGASTR-------KVPCP---
G7MYW0_MACMU|Ma -NALGNYVLVI-----------QNSPDDLG-----AC--QGASTR-------KVPCP---
G1NJK6_MELGA|Me -NALGNYILVI-----------QSSPEELG-----KGLNLGEGAEMMADWLDGSRSPGSA
F7G5M0_MONDO|Mo -NALGNYILVI-----------QNSPEDMG-----TC--KNAGAR-------GVGTPSEW
ZDH22_MOUSE|Mus -NALGNYVLVI-----------QNSPDDLG-----TC--QGTMSQ-------RPQCP---
G9KYT5_MUSPF|Mu -NLLGNVGLFLRSDPSIRGVML-----AGRGLGQG-------WAY-------CYQCQSQV
G1PX45_MYOLU|My -NALGNYVLVI-----------QNSPDDLD-----AC--QGASAR-------KALCP---
K7IP65_NASVI|Na -NIVGNFTYTVLSDTSTQRVVV---PTSKMNIKEG-------WRL-------CAVCTSIA
A7SWQ7_NEMVE|Ne -NVFANLYKVITTDTTGAKLGM---P---SVLKPG-------WAY-------CPFCQLNS
G1S3X2_NOMLE|No -NALGNYVLVI-----------QNSPDDLG-----AC--QGASAR-------KTPCP---
I3KWA6_ORENI|Or -NALGNYIMTI-----------KYPAESAN-----ET---------------VIPVCSPH
F6SE12_ORNAN|Or SAGSGSSAPTL-----------SHPPDPQNFLPEHRARPPPPQKKLLQEARALLPFHSSR
H2MNL7_ORYLA|Or -NALGNYIMTI-----------IYPAESAN-----ET---------------LIPVCSPH
H0XYR4_OTOGA|Ot -NALGNYVLVI-----------QNSPDDLG-----AC--QGTSAR-------RASCP---
H2RG61_PANTR|Pa -NALGNYVLVI-----------QNSPDDLG-----AC--QGASAR-------KTPCP---
K7GJD6_PELSI|Pe -NALGNYILVI-----------QSSPEDLG-----KCLNSGGGAEAVAARPDGSRSPGSA
F1S2N2_PIG|Sus  -NALGNYVLVI-----------QNSPDDLD-----AC--QGAAAR-------RAPCP---
H2NLW0_PONAB|Po -NALGNYVLVI-----------QNSPDDLG-----AC--QGASAR-------KTPCP---
L5JNU0_PTEAL|Pt -NALGNYVLVI-----------QNSPDDMD-----AC--QGTSAR-------KALCP---
G1SNL9_RABIT|Or -NALGNYVLVI-----------QNSPDDLG-----AC--QGTPAR-------RAPCP---
ZDH22_RAT|Rattu -NALGNYILVV-----------QNSPDDLG-----AC--QGTSSQ-------RPQRP---
G3W6V0_SARHA|Sa -NALGNYILVI-----------QNSPEDLG-----TR--KNVGTK-------GAGSPSEW
I3LX43_SPETR|Sp -NALGNYVLVI-----------QNSPDDLD-----AC--QGTSSK-------RALCP---
H0ZPV6_TAEGU|Ta -NALGNYVLVI-----------QNSPEDLG-----KDLNLGKGAE-VADWLDGSRSPGSA
H2VBD4_TAKRU|Ta -NALGNYIMTI-----------RYPAASAG-----DS---------------TVPVCSPH
H3DJ29_TETNG|Te -NALGNYIMTI-----------RYPAASAG-----DS---------------AVPVCSPH
F7DR35_XENTR|Xe -NVLGNYILTI-----------WKSPHG--------------------------------
                                                                            

L7M074_9ACAR|Rh PPR----------SHHCSVCNECILKHDHHCMFTGRCIGFYNQRYFVVALFY-----MTA
G1MJ71_AILME|Ai PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
G1KTK1_ANOCA|An LPG----------THFCRLCARVTQRHDHHCFFTGNCIGSRNMRNFVMFCLH-----TSL
Q7PVS0_ANOGA|An PPR----------SWHCASCRTCILKRDHHCVFTGCCIGHKNHRYFILFVVY-----LFI
E1B987_BOVIN|Bo PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFILFCLY-----TSL
C3Z5I5_BRAFL|Br PPR----------AHHCLYCDRCVLKRDHHCFFTGSCVGYFNQRRFVIFNLY-----TCL
F6Y2X5_CALJA|Ca SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
E2AAM9_CAMFO|Ca PPR----------SWHCNTCDTCILKRDHHCVFTGCCVGHHNHRYFVMFLWY-----LFL
J9NZC5_CANFA|Ca PPS----------THFCRVCARVTLRHDHHCFFTGNCIGGRNMRNFVLFCLY-----TSL
H0W7M0_CAVPO|Ca PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
E1C5D7_CHICK|Ga LPS----------THYCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLY-----TSL
B0WDA3_CULQU|Cu PPR----------SWHCNACRTCVLKRDHHCVFTGCCIGHKNHRYFIMFVFH-----LFV
G6DDL9_DANPL|Da PAK----------AWHCKKCNACILKRDHHCFFFSRCIGLRNQRYYVTYLTY-----IFI
E7EY29_DANRE|Da CPDRIDAHYLLNGRHFCKVCKKVILKRDHHCFFTGNCIGNRNMRYFIMFSIY-----TSS
B3MEE9_DROAN|Dr PPR----------SWHCKICGVCVLKRDHHCIYTGCCIGHRNHRFFMGFIFY-----LFV
B4JHI4_DROGR|Dr PPR----------THHCSVCNRCILKMDHHCPWLNNCVGYANHRYFFLYMLY-----TTM
Q9I7L7_DROME|Dr PPR----------SRHCRKCGVCVLMRDHHCFFTGCCIGHENYRYFFYFLIY-----FFL
B4K9M3_DROMO|Dr PPR----------THHCSVCNRCILKMDHHCPWLNNCVGYANHRYFFLYMVY-----TTL
B4GIR9_DROPE|Dr PDR----------AHHCRICQRCILKMDHHCPWVNNCVHFHNYKFFLLFLIY-----ASL
B5E105_DROPS|Dr PDR----------AHHCRICQRCILKMDHHCPWVNNCVHFHNYKFFLLFLIY-----ASV
B4M137_DROVI|Dr PPR----------THHCSVCNRCILKMDHHCPWLNNCVGYANHRYFFLYMLY-----TTL
B4NJC4_DROWI|Dr PPR----------SWHCQSCRRCTLKRDHHCTFTANCIGHNNHRYFICMLFH-----LSV
B4P7Y0_DROYA|Dr PPR----------SWHCKICKVCILKRDHHCIYTGCCIGLRNHRFFMGFIFY-----LFV
G3NYI0_GASAC|Ga CSDKVDAHYLLNGRHFCKLCKKVILKRDHHCFFTGNCIGNKNMRYFIMFCIY-----TSC
G3R3R5_GORGO|Go SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
G5B683_HETGA|He TPS----------THFCRVCARVTLRHDHHCFFTGNCIGRRNMRNFVLFCLY-----TSL
F6SFZ8_HORSE|Eq PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
ZDH22_HUMAN|Hom SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
H3AW31_LATCH|La SADALP----VPGSHFCKLCKKVILRRDHHCFFTGCCIGKKNMRYFIMFCLY-----TSV
G3UIR0_LOXAF|Lo PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
G7PB25_MACFA|Ma SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
G7MYW0_MACMU|Ma SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
G1NJK6_MELGA|Me LPS----------THYCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLY-----TSL
F7G5M0_MONDO|Mo PEAGRKASSSSQNTHFCRLCARVTLRHDHHCFFTGNCIGSRNMRNFIMFCLY-----TSL
ZDH22_MOUSE|Mus PPS----------THFCRVCSRVTLRHDHHCFFTGNCIGSRNMRNFILFCLY-----TSL
G9KYT5_MUSPF|Mu PPR----------SGHCSACRVCVLRRDHHCRLLGRCVGFRNYRPFLCLLLHAAGVLLHV
G1PX45_MYOLU|My PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
K7IP65_NASVI|Na PPR----------SWHCTTCDTCILKRDHHCIFTACCVGHYNHRYFLMFIFY-----LFV
A7SWQ7_NEMVE|Ne PPR----------AYHCHVCDICVLRRDHHCIFAGKCVGHSNYRYYLFLAFY-----LWL
G1S3X2_NOMLE|No SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
I3KWA6_ORENI|Or CSDKVDAHYLLNGRHFCKLCKKVILKRDHHCFFTGNCIGNKNMRYFIMFCIY-----TSC
F6SE12_ORNAN|Or PPGENREKISLTS--------------------AGNCIGSRNMRNFIMFCLY-----TSL
H2MNL7_ORYLA|Or CSDKVDAHYLLNGRHFCKLCKKIILKRDHHCFFTGNCIGNKNMRYFLMFCIY-----TS-
H0XYR4_OTOGA|Ot SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
H2RG61_PANTR|Pa SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
K7GJD6_PELSI|Pe LPS----------THFCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLY-----TSL
F1S2N2_PIG|Sus  PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
H2NLW0_PONAB|Po SPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
L5JNU0_PTEAL|Pt PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
G1SNL9_RABIT|Or PPS----------THFCRVCARVTLRHDHHCFFTGNCIGGRNMRNFVLFCLY-----TSL
ZDH22_RAT|Rattu PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFILFCLY-----TSL
G3W6V0_SARHA|Sa PES----------THFCRLCARVTLRHDHHCFFTGNCIGSRNMRNFIMFCLY-----TSL
I3LX43_SPETR|Sp PPS----------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLY-----TSL
H0ZPV6_TAEGU|Ta LPG----------THFCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLY-----TSL
H2VBD4_TAKRU|Ta CSDKVDAHYLLNDRHFCKLCRKVILKRDHHCFFTGNCIGQKNMRYFIMFCIH-----TSC
H3DJ29_TETNG|Te CSDKVDAHYLLNDRHFCKLCRKVILKRDHHCFFTGNCIGKKNMRYFIMFCIH-----TSC
F7DR35_XENTR|Xe --NAMYAETELSGKPFCHLCARVMGEQEHHCFFTGTCIGRSNLRSFVLFCLH-----ASC
                                                    *:   * : :.    :        

L7M074_9ACAR|Rh GLLYS--------------------LWYKCPYVLE------------------------M
G1MJ71_AILME|Ai ACLYS---------TVA----GLAYISAALSTSFA-------------------------
G1KTK1_ANOCA|An ACLDS---------MVA----GVAYISSVLSTSFA-------------------------
Q7PVS0_ANOGA|An STLYA---------SVL----NNYFLWFVRGEEFR-------------------------
E1B987_BOVIN|Bo ACLYS---------MVA----GVAYISAVLSISFA-------------------------
C3Z5I5_BRAFL|Br SAVHV---------LGL----LLQYLEILNGPTME-------------------------
F6Y2X5_CALJA|Ca ACLYS---------MVA----GVAYISAVLSISFA-------------------------
E2AAM9_CAMFO|Ca GAAYA---------FSY----GSFFIWTRTSFEFP-------------------------
J9NZC5_CANFA|Ca ACLYS---------MVA----GVAYISAALSTSFA-------------------------
H0W7M0_CAVPO|Ca ACLYS---------MVA----GVAYISAVLSISFA-------------------------
E1C5D7_CHICK|Ga ACLDS---------LVA----GMAYISASLSMSFA-------------------------
B0WDA3_CULQU|Cu ATLYS---------SAL----NNYFIWYIHGEEFR-------------------------
G6DDL9_DANPL|Da SMVYSTYFNFYYVVSKY----DEYEIY---------------------------------
E7EY29_DANRE|Da SCLYS---------LVI----GVAYLTIEYSISFE-------------------------
B3MEE9_DROAN|Dr GSVYA---------LVY----NSIYLWVFQAHIYC-------------------------
B4JHI4_DROGR|Dr GCLLL---------IVAGVEIGHKYLWLDHSEPWTELEPLEGHPVQYNLSGHIIPVTHPH
Q9I7L7_DROME|Dr SCMIS---------LTS----SSIFIYVLHGGRYQ-------------------------
B4K9M3_DROMO|Dr GCLFL---------IVAGVEIGYKYLWLDHSEHWTELEPLEGHPVKFNQSGHVIAVTHPN
B4GIR9_DROPE|Dr YCLYV---------LVT--------LLLELHHAWG------------------------F
B5E105_DROPS|Dr YCLYV---------LVT--------LLLELHHAWG------------------------F
B4M137_DROVI|Dr GCLFL---------IVCGLEIGYKYLWLDHSEHWTELEPLEGHPVKFNLSGHAILVTHPH
B4NJC4_DROWI|Dr GCGIC---------LVF----NTIESYYAKSLFFA-------------------------
B4P7Y0_DROYA|Dr GSVYA---------LVY----NSIYLWVIHGHIYN-------------------------
G3NYI0_GASAC|Ga TCLYS---------LVL----GVAFLTVEYSLSFE-------------------------
G3R3R5_GORGO|Go ACLYS---------MVA----GVAYISAVLSISFA-------------------------
G5B683_HETGA|He ACLYS---------MVA----GVAYISAVLSVSFA-------------------------
F6SFZ8_HORSE|Eq ACLYS---------MVA----GVAYISAVLSISFA-------------------------
ZDH22_HUMAN|Hom ACLYS---------MVA----GVAYISAVLSISFA-------------------------
H3AW31_LATCH|La SSLYS---------LVL----GVAYITVKYSLSFE-------------------------
G3UIR0_LOXAF|Lo ACLYS---------MVA----GVAYISAVLSISFA-------------------------
G7PB25_MACFA|Ma ACLYS---------MVA----GVAYISAVLSISFA-------------------------
G7MYW0_MACMU|Ma ACLYS---------MVA----GVAYISAVLSISFA-------------------------
G1NJK6_MELGA|Me ACLDS---------LVA----GMAYISASLSMSFA-------------------------
F7G5M0_MONDO|Mo ACLYS---------MVA----GVAYISTVLSISFA-------------------------
ZDH22_MOUSE|Mus ACLYS---------MVA----GVAYISAVLSISFA-------------------------
G9KYT5_MUSPF|Mu SVLLG---------PAL----SAL-----------------------------------L
G1PX45_MYOLU|My ACLYS---------MVA----GVAYISAVLSISFA-------------------------
K7IP65_NASVI|Na ATVYS---------FAY----NNFFIWSRIHFEFP-------------------------
A7SWQ7_NEMVE|Ne GALYANLFHWEYVTSVM----DNFTLW---------------------------------
G1S3X2_NOMLE|No ACLYS---------MVA----GVAYISAVLSISFA-------------------------
I3KWA6_ORENI|Or TCLYS---------LVL----GVAFLTVEYSISFE-------------------------
F6SE12_ORNAN|Or ACLYS---------TVA----GAAYISTVLSVSFA-------------------------
H2MNL7_ORYLA|Or ------------------------------------------------------------
H0XYR4_OTOGA|Ot ACLYS---------MVA----GVAYISAVLSISFA-------------------------
H2RG61_PANTR|Pa ACLYS---------MVA----GVAYISAVLSISFA-------------------------
K7GJD6_PELSI|Pe ACLDS---------LVA----GVAYISAVLSVSFA-------------------------
F1S2N2_PIG|Sus  ACLYS---------MVA----GVAYISAVLSISFA-------------------------
H2NLW0_PONAB|Po A--------------------------QELTRSLR-------------------------
L5JNU0_PTEAL|Pt ACLYS---------MVA----GVAYISAVLSISFA-------------------------
G1SNL9_RABIT|Or ACLYS---------MVA----GVAYISAVLSVSFA-------------------------
ZDH22_RAT|Rattu ACLYS---------MVA----GVAYISAVLSISFA-------------------------
G3W6V0_SARHA|Sa ACLYS---------MVA----GVAYISAVLSISFA-------------------------
I3LX43_SPETR|Sp ACLYS---------MVA----GVAYISAVLSISFA-------------------------
H0ZPV6_TAEGU|Ta ACLHS---------LVA----GMAYISATLSMSFV-------------------------
H2VBD4_TAKRU|Ta TCMYS---------LVL----GVAFLTMEYSISFE-------------------------
H3DJ29_TETNG|Te TCMYS---------LVL----GVAFLTVEYSISFE-------------------------
F7DR35_XENTR|Xe SCFHA---------MVV----GVGYISESISLSLY-------------------------
                                                                            

L7M074_9ACAR|Rh LGGLNLVTVLHMVAP-----------HFGLLL----------------------------
G1MJ71_AILME|Ai -----HPLAFLTLLPTS---------ISRFFS----------------------------
G1KTK1_ANOCA|An -----SPMAFLTLLPNS---------ISQFFS----------------------------
Q7PVS0_ANOGA|An ----NWTSLVKIVFP-----------LAMLL-----------------------------
E1B987_BOVIN|Bo -----HPLAFLTLLPTS---------ISQFFS----------------------------
C3Z5I5_BRAFL|Br -----RLLTY--IFPVT---------VYEWYV----------------------------
F6Y2X5_CALJA|Ca -----HPLAFLTLLPTS---------ISQFFS----------------------------
E2AAM9_CAMFO|Ca ------MSVIKMVFP-----------VAIFFF----------------------------
J9NZC5_CANFA|Ca -----HPLAFLTLLPTS---------ISQFFS----------------------------
H0W7M0_CAVPO|Ca -----HPLAFLTLLPTS---------ISQFFS----------------------------
E1C5D7_CHICK|Ga -----NPLAFLTLLPHS---------ISQFFS----------------------------
B0WDA3_CULQU|Cu ----NWTSFIKMVFP-----------LAMLV-----------------------------
G6DDL9_DANPL|Da ------VSVCRIVNP-----------FLRYLI----------------------------
E7EY29_DANRE|Da -----NPLTFLTLLPLS---------TGYFFL----------------------------
B3MEE9_DROAN|Dr ----HWFTLFKLLNP-----------LFLLF-----------------------------
B4JHI4_DROGR|Dr EYDDILLPAAVHNLPTPAVHT-DES-----------------------------------
Q9I7L7_DROME|Dr --------LFMLTHPAPNSAYFNSLIIRIIYF----------------------------
B4K9M3_DROMO|Dr EYDDILLPPAVHHLPTPMADS-PDA-----------------------------------
B4GIR9_DROPE|Dr DFDNVDLNSLQTMIP---------------------------------------------
B5E105_DROPS|Dr DFDNVDLNSVQTMIP---------------------------------------------
B4M137_DROVI|Dr EYDDILLPAAVHHLPTPIADTLADS-----------------------------------
B4NJC4_DROWI|Dr --------------------------DSLILF----------------------------
B4P7Y0_DROYA|Dr ----NWLTLLKLFCP-----------MLHTV-----------------------------
G3NYI0_GASAC|Ga -----NPLTFLTLLPLS---------TGYFFT----------------------------
G3R3R5_GORGO|Go -----HPLAFLTLLPTS---------ISQFFS----------------------------
G5B683_HETGA|He -----HPLAFLTLLPTS---------ISQFFS----------------------------
F6SFZ8_HORSE|Eq -----HPLAFLTLLPTS---------ISQFFS----------------------------
ZDH22_HUMAN|Hom -----HPLAFLTLLPTS---------ISQFFS----------------------------
H3AW31_LATCH|La -----NPLAFLTLLPLA---------LSYFIL----------------------------
G3UIR0_LOXAF|Lo -----HPLAFLTLLPTS---------ISQFFS----------------------------
G7PB25_MACFA|Ma -----HPLAFLTLLPTS---------ISQFFS----------------------------
G7MYW0_MACMU|Ma -----HPLAFLTLLPTS---------ISQFFS----------------------------
G1NJK6_MELGA|Me -----NPLAFLTLLPHS---------ISQFFS----------------------------
F7G5M0_MONDO|Mo -----HPLAFLTLLPHS---------ISQFFS----------------------------
ZDH22_MOUSE|Mus -----HPLAFLTLLPTS---------ISQFFS----------------------------
G9KYT5_MUSPF|Mu RAHAPLHTAALLLLP-----------WLMLLT----------------------------
G1PX45_MYOLU|My -----HPLAFLTLLPTS---------ISQFFS----------------------------
K7IP65_NASVI|Na ------MTIVKLVFP-----------VAIFIF----------------------------
A7SWQ7_NEMVE|Ne -------TMFTMFMP-----------MLSWML----------------------------
G1S3X2_NOMLE|No -----HPLAFLTLLPTS---------ISQFFS----------------------------
I3KWA6_ORENI|Or -----NPLTFLTLLPFS---------TGYFFM----------------------------
F6SE12_ORNAN|Or -----HPLAFLTLLPHS---------ISQFFS----------------------------
H2MNL7_ORYLA|Or ------------------------------------------------------------
H0XYR4_OTOGA|Ot -----HPLAFLTLLPTS---------ISQFFS----------------------------
H2RG61_PANTR|Pa -----HPLAFLTLLPTS---------ISQFFS----------------------------
K7GJD6_PELSI|Pe -----SPLAFLTLLPHS---------ISQFFS----------------------------
F1S2N2_PIG|Sus  -----HPLAFLTLLPTS---------ISQFFS----------------------------
H2NLW0_PONAB|Po -----KEVAAGPAGPHV-------------------------------------------
L5JNU0_PTEAL|Pt -----HPLAFLTLLPTS---------ISQFFSAVVLPLSQICHQNMDWLAEIAAKCSFDI
G1SNL9_RABIT|Or -----HPLAFLTLLPTA---------ISQFFA----------------------------
ZDH22_RAT|Rattu -----HPLAFLTLLPTS---------ISQFFS----------------------------
G3W6V0_SARHA|Sa -----HPLAFLTLLPHS---------ISQFFS----------------------------
I3LX43_SPETR|Sp -----HPLAFLTLLPTS---------ISQFFS----------------------------
H0ZPV6_TAEGU|Ta -----DPLAFLTLLPHS---------ISQFFS----------------------------
H2VBD4_TAKRU|Ta -----DPLTFLTLLPLS---------TGYFFM----------------------------
H3DJ29_TETNG|Te -----DPLTFLTLLPLS---------TGYFFM----------------------------
F7DR35_XENTR|Xe -----DPMTFLRLLPLS---------ITRFFS----------------------------
                                                                            

L7M074_9ACAR|Rh ----------------------------------GL----------VDGWLFVCTLLNLV
G1MJ71_AILME|Ai ----------------------------------GA----------VLGSEMFVILMLYL
G1KTK1_ANOCA|An ----------------------------------GA----------LPSLEMFVILMLYL
Q7PVS0_ANOGA|An -----------------------------------I----------DTSTKQYYLVIYLI
E1B987_BOVIN|Bo ----------------------------------GA----------VLGSEMFVILMLYL
C3Z5I5_BRAFL|Br ----------------------------------GY----------MPTSTVLVVLEVYV
F6Y2X5_CALJA|Ca ----------------------------------GA----------VLGSEMFVILMLYL
E2AAM9_CAMFO|Ca ----------------------------------GF----------DSSIDQFYLLLYVV
J9NZC5_CANFA|Ca ----------------------------------GA----------VLGSEMFVILMLYL
H0W7M0_CAVPO|Ca ----------------------------------GA----------VLGSDMFVILMLYL
E1C5D7_CHICK|Ga ----------------------------------GA----------LLSSEMFVILMLYL
B0WDA3_CULQU|Cu -----------------------------------I----------DASTKQYYLVIYLI
G6DDL9_DANPL|Da ----------------------------------PE----------PMGMKDLYVFFLFL
E7EY29_DANRE|Da ----------------------------------GL----------ISGLQFFLVIMLYI
B3MEE9_DROAN|Dr -----------------------------------T----------GNFWSNMYLIFYGL
B4JHI4_DROGR|Dr ----------------------------------------------SPARRRILWFMAVT
Q9I7L7_DROME|Dr ----------------------------------KL----------PDIYELVFTLVFVL
B4K9M3_DROMO|Dr ----------------------------------------------TPTRRRVLWFMAVV
B4GIR9_DROPE|Dr ----------------------------------------------------IVLAMIFT
B5E105_DROPS|Dr ----------------------------------------------------IVLAMIFT
B4M137_DROVI|Dr ----------------------------------------------TPTRRRILWFMAVT
B4NJC4_DROWI|Dr ----------------------------------SIWGLIRQEIVDEHFWHIVSSCIIKL
B4P7Y0_DROYA|Dr -----------------------------------T----------GSFWSNMYLGFYSL
G3NYI0_GASAC|Ga ----------------------------------GT----------ISGLQLFLVLMLYV
G3R3R5_GORGO|Go ------------------------------------------------------------
G5B683_HETGA|He ----------------------------------GA----------VLGSEMFVILMLYL
F6SFZ8_HORSE|Eq ----------------------------------GA----------VLGSEMFVILMLYL
ZDH22_HUMAN|Hom ----------------------------------GA----------VLGSEMFVILMLYL
H3AW31_LATCH|La ----------------------------------GA----------ISGLELFLILLLYV
G3UIR0_LOXAF|Lo ----------------------------------GA----------VLGSEMFVILMLYL
G7PB25_MACFA|Ma ----------------------------------GA----------VLGSEMFVILMLYL
G7MYW0_MACMU|Ma ----------------------------------GA----------VLGSEMFVILMLYL
G1NJK6_MELGA|Me ----------------------------------GA----------LLSSEMFVILMLYL
F7G5M0_MONDO|Mo ----------------------------------GA----------VLGSEMFVILMLYL
ZDH22_MOUSE|Mus ----------------------------------GA----------VLGSDMFVILMLYL
G9KYT5_MUSPF|Mu ----------------------------------GR----------VSLAQFALAFVTDT
G1PX45_MYOLU|My ----------------------------------GA----------VLGSEMFVILMLYL
K7IP65_NASVI|Na ----------------------------------GF----------DGSMEQFYLMLYIV
A7SWQ7_NEMVE|Ne ----------------------------------GY----------TTIYQTFVTFITAI
G1S3X2_NOMLE|No ----------------------------------GA----------VLGSEMFVILMLYL
I3KWA6_ORENI|Or ----------------------------------GT----------ISGLQLFLVLMLYV
F6SE12_ORNAN|Or ----------------------------------GA----------VLGSEMFVILMLYL
H2MNL7_ORYLA|Or ------------------------------------------------------------
H0XYR4_OTOGA|Ot ----------------------------------GA----------VLGSEMFVILMLYL
H2RG61_PANTR|Pa ----------------------------------GA----------VLGSEMFVILMLYL
K7GJD6_PELSI|Pe ----------------------------------GA----------LLSSEMFVILMLYL
F1S2N2_PIG|Sus  ----------------------------------GA----------VLGSEMFVILMLYL
H2NLW0_PONAB|Po ------------------------------------------------------------
L5JNU0_PTEAL|Pt INLLLFLAESAYRDGSSVRGLSVKRFWCFPAPPAGA----------VLGSEMFVILMLYL
G1SNL9_RABIT|Or ----------------------------------GA----------VLGSEMFVILMLYL
ZDH22_RAT|Rattu ----------------------------------GA----------VLGSDMFVILMLYL
G3W6V0_SARHA|Sa ----------------------------------GA----------VLGSEMFVILMLYL
I3LX43_SPETR|Sp ----------------------------------GA----------VLGSEMFVILMLYL
H0ZPV6_TAEGU|Ta ----------------------------------GA----------LLSSEMFIILMLYL
H2VBD4_TAKRU|Ta ----------------------------------GT----------ISGLQLFLVLMLYV
H3DJ29_TETNG|Te ----------------------------------GT----------VSGLQLFLVLMLYV
F7DR35_XENTR|Xe ----------------------------------GT----------LLSSEMLVVLMIYL
                                                                            

L7M074_9ACAR|Rh ELVVFFLCAYLLAVELICVARNQTTYEK-------------S-HGIRTYG---RGLRRNL
G1MJ71_AILME|Ai WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAMRA---RPWRKNL
G1KTK1_ANOCA|An WLGIGLACAGFCCHQILLILRGQTRYQV-------------RKG-MAARA---RPWKKNL
Q7PVS0_ANOGA|An NMVGVMFTGVLLIYHGRLILSGAVVHER-------------K-APE--YD---MGRAENL
E1B987_BOVIN|Bo WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
C3Z5I5_BRAFL|Br CAVACIGCGGLFGWQIMIIRDGQTSYEA-------------VK---------------NI
F6Y2X5_CALJA|Ca WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
E2AAM9_CAMFO|Ca SAVGTLYTAVLCIYHFNLILRGVVGNES-------------N-KKDFTYD---MGWKDNV
J9NZC5_CANFA|Ca WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
H0W7M0_CAVPO|Ca WFAVGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---QPWRKNL
E1C5D7_CHICK|Ga WLGIGLACAGFCCHQLLLILRGQTQYQV-------------RKG-MVVRA---RPWRENL
B0WDA3_CULQU|Cu NMIGMLFTGVLLIYHGRLILSGSVVHEQ-------------N-GRD--FD---LGRMENL
G6DDL9_DANPL|Da NVGLVIWSGGLFVFHTRNVLRGETSHEY-------------KENTRSTFRNNLSAMKRNF
E7EY29_DANRE|Da WLGIGLVSVGFCCQQLLLVARGQTWCEL-------------QKGQLSECR---GTWRANL
B3MEE9_DROAN|Dr NILAFLYGVLLLAYHVPIILRGGVSADR-------------TLASKHRYD---RGVRQNL
B4JHI4_DROGR|Dr NVAVVIALGSLCTWHAKLITRGETSVESHINEAETKRFLQVNRIYINPYN---FGSKKNW
Q9I7L7_DROME|Dr LWIGVCVATYVAYDQWS---RGYFCYDF-------------E-LQNIPFD---RKLRRNF
B4K9M3_DROMO|Dr NVAVVIALGSLSIWHAKLITRGETSIEAHINEAERKRLLQLKRVYINPYN---FGTKKNW
B4GIR9_DROPE|Dr G-ATMIMLG----LHIYLLLLNRTTMES----AHAPMFCVGGRTR-KAFN---LGCCANL
B5E105_DROPS|Dr G-ATVIMLG----LHIYLLLLNRTTMES----AHAPMFCVGGRTR-KAFN---LGCCTNL
B4M137_DROVI|Dr NVAVVIALGTLCTWHAKLITRGETSVEAHINEAERKRFLQLKRIYINPYN---FGTKKNW
B4NJC4_DROWI|Dr NFFLTVLAIAQLVYQLIMLSRNSTCHRF-------------K---DCIYD---QGFKKNV
B4P7Y0_DROYA|Dr NVLALAYGVILLGYHVPIVLRGGVSADI-------------TKESKEKYD---RGVYQNL
G3NYI0_GASAC|Ga WLGIGLVCAGFCCQQVLLVARGRTWCQM-------------QRGQLVDNR---SPWRSNL
G3R3R5_GORGO|Go ------------------------------------------------------------
G5B683_HETGA|He WFAVGLACAGFCCHQLLLILRGQTRYQV-------------RKG-VAVRA---QPWRKNL
F6SFZ8_HORSE|Eq WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
ZDH22_HUMAN|Hom WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
H3AW31_LATCH|La WLGIGLTCAGFCCQQILLVSRGQTWHQV-------------RKG-LSMRH---GHWGENL
G3UIR0_LOXAF|Lo WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
G7PB25_MACFA|Ma WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
G7MYW0_MACMU|Ma WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
G1NJK6_MELGA|Me WLGIGLACAGFCCHQLLLILRGQTRYQV-------------RKG-MVVKA---RPWRENL
F7G5M0_MONDO|Mo WFGIGLACAGFCCHQLLLVLRGQTRHQV-------------RKG-MVVRA---RPWRKNL
ZDH22_MOUSE|Mus WFAVGLACAGFCCHQLLLILRGQTRYQV-------------RKG-MAVRA---RPWRKNL
G9KYT5_MUSPF|Mu CVAGALLCGAGLLFHGMLLLRGQTTWEW-------------A-RGQHSYD---LGPCHNL
G1PX45_MYOLU|My WFAVGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---GPWRKNL
K7IP65_NASVI|Na TVIGMLFTGALCVYHFNLLFNGCTSDER-------------N-KKNYSYS---LGWKQNI
A7SWQ7_NEMVE|Ne SLFAFVMFSGLLFFQLNIIARGQTSYER-------------K-RKRRIYD---KGWLRNF
G1S3X2_NOMLE|No WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
I3KWA6_ORENI|Or WLGIGLVCAGFCCQQVLLVARGQTWCQM-------------QRGQLAENR---NPWRANL
F6SE12_ORNAN|Or WFGIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VIVRA---RPWRRNL
H2MNL7_ORYLA|Or ------------------------------------------------------------
H0XYR4_OTOGA|Ot WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
H2RG61_PANTR|Pa WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
K7GJD6_PELSI|Pe WLGIGLACAGFCSHQILLILRGQTRYQV-------------RKG-MVVRA---RPWRKNL
F1S2N2_PIG|Sus  WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
H2NLW0_PONAB|Po --------------------------QC-------------RK-----------------
L5JNU0_PTEAL|Pt WFAIGLACAGFCCHQLLLILRGQTRHQV-------------RKG-VAVRA---RPWRKNL
G1SNL9_RABIT|Or WFAIGLACAGFCCHQLLLILRGQTRHQL-------------RKG-VAVRA---RPWRKNL
ZDH22_RAT|Rattu WFAVGLACAGFCCHQLLLILRGQTRYQV-------------RKG-VAVRA---RPWRKNL
G3W6V0_SARHA|Sa WFGIGLACAGFCCHQLLLVLRGQTRHQV-------------RKG-MVVRA---RPWRKNL
I3LX43_SPETR|Sp WFAIGLACAGFCCHQLLLILRGQTRHQA-------------RKG-VAVRA---RPWRKNL
H0ZPV6_TAEGU|Ta WLGIGLACAGFCFHQMLLILRGQTRYQV-------------RKG-VLVRA---RPWRENL
H2VBD4_TAKRU|Ta WLGIGLVCAGFCCQQVLLVARGQTWCQM-------------QQGRLQEIQ---SPWQNNL
H3DJ29_TETNG|Te WLGIGLVCAGFCCQQVLLVARGQTWCQM-------------QRGRLQGVQ---SPWQNNL
F7DR35_XENTR|Xe WFGVGVACAAFCCHHLILICRGSNGQQF-------------HTAEIRITN---G--KENL
                                                                            

L7M074_9ACAR|Rh KEALG-----AAWFLVWLSPWVHSPVPGDFDGRVVC-------VEKKVL------
G1MJ71_AILME|Ai QEVFG-----KRWLLGLLVPMFNVGGES--------SKQHDK-------------
G1KTK1_ANOCA|An EEVFG-----KRWLLGLLIPMLNVGSDY--------HRQKEK-------------
Q7PVS0_ANOGA|An RMVLG-----NRWYIAWLSPFVASELPHNGVNWE-T-------LQKQTLKSK---
E1B987_BOVIN|Bo QEVFG-----KRWLLGLLVPMFNVGSES--------CKQRDK-------------
C3Z5I5_BRAFL|Br K------------------------------------------------------
F6Y2X5_CALJA|Ca QEVFG-----KRWLLGLLVPMFNVGSES--------SKQQDK-------------
E2AAM9_CAMFO|Ca REVFG-----ERWYLAWLLPYIKSQLPHDGISWHYL-------CSKKD-------
J9NZC5_CANFA|Ca QEVFG-----KRWLLGLLVPMFNVGGES--------SKQRDK-------------
H0W7M0_CAVPO|Ca QEVFG-----KRWLLGLLVPMFNVGSEG--------SKPQDK-------------
E1C5D7_CHICK|Ga REVFG-----KRWLLGLLIPMLNVGSDC--------RRQKVK-------------
B0WDA3_CULQU|Cu RMVLG-----ERWHLAWLSPFVRSDLPHNGVDWD-R-------VQREAAKSK---
G6DDL9_DANPL|Da INVFG-----EKWYIALVWPLANSPLPETTEDRGDEY------------------
E7EY29_DANRE|Da TDVFG-----SHWVLGLFVPVPTVETVPGNWQVYHDHKHD---------------
B3MEE9_DROAN|Dr RSVFG-----NRMHLAWISPLIRSDLPDDGYHWKPT-------IDEQEKD-----
B4JHI4_DROGR|Dr KLFLGLVRGRSFWRTVLLPSWHRPEGNGLTF-------HTVHDAPFEDEWP----
Q9I7L7_DROME|Dr KTFLG-----RRMKWTWISGFVPSQLDHDGFDLDPDNERVADWCSETTIKDG---
B4K9M3_DROMO|Dr KLFLGLVRGRSFWRTVLLPSWHKPEGNGLSF-------HTVHDAPFEDEWP----
B4GIR9_DROPE|Dr CEVFG-----DRWYLWPLPV-YSSRGDGLTFPLREGSISSASSADF---------
B5E105_DROPS|Dr CEVFG-----NRWYLWPLPV-YSSRGDGLTFPLREGSISSASSADF---------
B4M137_DROVI|Dr KLFLGLVRGRSFWRTVLLPSWHRPEGNGLSF-------HTVHDAIFEDEWP----
B4NJC4_DROWI|Dr ELIMG-----RRKFWVLLSPFMDSPLPHDGTQWQ---------LAKHYL------
B4P7Y0_DROYA|Dr RSVFG-----IRMHLAWLSPLIRSDLPDDGYHWSVS-------TNKQD-------
G3NYI0_GASAC|Ga KDVFG-----TRWILGLILPVQTAETGSEDPDA---HKQD---------------
G3R3R5_GORGO|Go -------------------------------------------------------
G5B683_HETGA|He QEVFG-----KRWLLGLLVPMFNVGSES--------SKLKDK-------------
F6SFZ8_HORSE|Eq QEVFG-----KRWLLGLLVPMFNVGGES--------SKQRDK-------------
ZDH22_HUMAN|Hom QEVFG-----KRWLLGLLVPMFNVGSES--------SKQQDK-------------
H3AW31_LATCH|La QQVFG-----KRWLLGLFIPMATVE-----------YKQSAKTQEDKRN------
G3UIR0_LOXAF|Lo QEVFG-----KRWLLGLLVPMFNVGSES--------AKQRDK-------------
G7PB25_MACFA|Ma QEVFG-----KRWLLGLLVPMFNVGSES--------SKQQDK-------------
G7MYW0_MACMU|Ma QEVFG-----KRWLLGLLVPMFNVGSES--------SKQQDK-------------
G1NJK6_MELGA|Me REVFG-----KRWLLGLLIPMLNVGSDC--------RRQKVK-------------
F7G5M0_MONDO|Mo QEVFG-----KRWLLGLLIPMLNVGSDY--------PRHKGK-------------
ZDH22_MOUSE|Mus QEVFG-----KRWLLGLLVPMFNVGTES--------SKQQDK-------------
G9KYT5_MUSPF|Mu QAALG-----PRWVLVWLWPFLASPLPGDGVTFQTAADMGL--------------
G1PX45_MYOLU|My QEVFG-----KRWLLGLLVPMFNVGGES--------SKQRDK-------------
K7IP65_NASVI|Na KEVFG-----DKWYLVWLIPYVPSKLPQDGVSWH-R-------SSKWNMNNSKCK
A7SWQ7_NEMVE|Ne IEVLG-----ENWFLSWIWPKITSPLPHNGTDYTQA-------CNEELPKDM---
G1S3X2_NOMLE|No QEVFG-----KRWLLGLLVPMFNVGSES--------SKQQDK-------------
I3KWA6_ORENI|Or KDVFG-----TRWILGLILPVQTVETCSEDADV---HKQD---------------
F6SE12_ORNAN|Or QEVFG-----KRWLLGLLIPVLNVGSEY--------HQQKDK-------------
H2MNL7_ORYLA|Or -------------------------------------------------------
H0XYR4_OTOGA|Ot QEVFG-----KRWLLGLLVPTLNVGSES--------SKQWDK-------------
H2RG61_PANTR|Pa QEVFG-----KRWLLGLLVPMFNVGSES--------SKQQDK-------------
K7GJD6_PELSI|Pe QDVFG-----KRWLIGLLIPVLNVGSDC--------HRPKDK-------------
F1S2N2_PIG|Sus  QEVFG-----KRWLLGLLIPMFNVGSES--------SKQRDK-------------
H2NLW0_PONAB|Po -------------------------------------------------------
L5JNU0_PTEAL|Pt QEVFG-----KRWLLGLLVPMLNVGGES--------SKQRDK-------------
G1SNL9_RABIT|Or QEVFG-----KRWLLGLLVPMFNVGSES--------SKQWDK-------------
ZDH22_RAT|Rattu QEVFG-----KRWLLGLLVPMFNVGTES--------SKQQDK-------------
G3W6V0_SARHA|Sa QEVFG-----KRWLLGLLIPMLNVGSEY--------PRHKGK-------------
I3LX43_SPETR|Sp QEVFG-----KRWLLGLLVPMFNVGSES--------SKQQDK-------------
H0ZPV6_TAEGU|Ta QEVFG-----KKWLLGLFIPVQNTESSY--------RRQKEK-------------
H2VBD4_TAKRU|Ta KDVFG-----TRWILGLILPVQTVETCSEE-------KQD---------------
H3DJ29_TETNG|Te KDVFG-----TRWILGLILPVQTVETSLEE-------KQE---------------
F7DR35_XENTR|Xe QRVFG-----KKWLFAIFVPQ----------------------------------
                                                                       
