MUSCLE (3.8) multiple sequence alignment


L7M222_9ACAR|Rhipicephalus        MDEEVDPSCAPVYYTAGQGPCGGGASATSGGSGGDAGCRQSPPPRVPEEDYSSFDIVKAT
E2AAK6_CAMFO|Camponotus           --------MQTACQGEGTG------------EPDDPSSLHQEPARPAAQDCSSFDIVRAT
K7J8F5_NASVI|Nasonia              ---MYALQMQNACQGEGDGEPQPDPCSQ-----------NPEPAPTTTQDCSNFDIVRAT
G6DPC9_DANPL|Danaus               ------------------------------------------------------------
B4J3N8_DROGR|Drosophila           -------MYQSACNAATTGSCVPGAGNQLDNDRQAALIAQQPPTAPVEPDYSGFDIVKAT
B4KYH8_DROMO|Drosophila           -------MYQSACNAATTGSCVPGAGNQMDTDRQAALIAQQPPTAPVEPDYSGFDIVKAT
B4LDZ7_DROVI|Drosophila           -------MYQSACNAATTGSCVPGAGSQTDTDRQAALIAQQPPTAPVEPDYSGFDIVKAT
B4N727_DROWI|Drosophila           -------MYQSACNAATTGSCVPGGGTQP---PQSALIAQQPPTAPVEPDYSGFDIVKAT
B4H7T3_DROPE|Drosophila           -------MYQSACNAATTGSCVPGAGNQADNERQSALIAQQPPTAPVEPDYSGFDIVKAT
Q29D93_DROPS|Drosophila           -------MYQSACNAATTGSCVPGAGNQTDNERQSALIAQQPPTAPVEPDYSGFDIVKAT
B3M9T9_DROAN|Drosophila           -------MYQSACQAATTGSCVPGSSQQPDNERQSALIAQQPPTAPVEPDYSGFDIVKAT
Q9VUW9_DROME|Drosophila           -------MYQSACQAATTGSCVPGTGQQPDNERQSALIAQQPPTAPVEPDYSGFDIVKAT
B3NDQ1_DROER|Drosophila           -------MYQSACQAATTGSCVPGTGQQPDNERQSALIAQQPPTAPVEPDYSGFDIVKAT
B4ITV5_DROYA|Drosophila           -------MYQSACQAATTGSCVPGAGQQPDNERQSALIAQQPPTAPVEPDYSGFDIVKAT
B0W2T5_CULQU|Culex                ------------------------------------------------------------
Q7PZ51_ANOGA|Anopheles            -------MYQSACTAAAAGGC-----SEPERHDRDGLITHETAVAPVEHDYSGFDIVKAT
A7RWD7_NEMVE|Nematostella         ------------------------------------------------------------
C3ZCK2_BRAFL|Branchiostoma        ------------------------------------------------------------
H0W5P5_CAVPO|Cavia                ------------------------------------------------------------
G5ASE1_HETGA|Heterocephalus       ------------------------------------------------------------
ZDH12_MOUSE|Mus                   ------------------------------------------------------------
ZDH12_RAT|Rattus                  ------------------------------------------------------------
H0XYF8_OTOGA|Otolemur             ------------------------------------------------------------
G3U2Z9_LOXAF|Loxodonta            ------------------------------------------------------------
I3MFR4_SPETR|Spermophilus         ------------------------------------------------------------
G1PPR6_MYOLU|Myotis               ------------------------------------------------------------
L5K9R0_PTEAL|Pteropus             ------------------------------------------------------------
E2RQ98_CANFA|Canis                ------------------------------------------------------------
G1MB86_AILME|Ailuropoda           ------------------------------------------------------------
G9KYS3_MUSPF|Mustela              ------------------------------------------------------------
F6RCU4_HORSE|Equus                ------------------------------------------------------------
F6XST1_CALJA|Callithrix           ------------------------------------------------------------
G1S775_NOMLE|Nomascus             ------------------------------------------------------------
K7DHV8_PANTR|Pan                  ------------------------------------------------------------
G7PRE9_MACFA|Macaca               ------------------------------------------------------------
I0FVS9_MACMU|Macaca               ------------------------------------------------------------
ZDH12_HUMAN|Homo                  ------------------------------------------------------------
G3R6W9_GORGO|Gorilla              ------------------------------------------------------------
K7ETB9_PONAB|Pongo                ------------------------------------------------------------
E1B6X9_BOVIN|Bos                  ------------------------------------------------------------
F1RR67_PIG|Sus                    ------------------------------------------------------------
F7G3P7_ORNAN|Ornithorhynchus      ------------------------------------------------------------
F6TT20_MONDO|Monodelphis          ------------------------------------------------------------
G3X3J6_SARHA|Sarcophilus          ------------------------------------------------------------
H2SLY9_TAKRU|Takifugu             ------------------------------------------------------------
H2MTW9_ORYLA|Oryzias              ------------------------------------------------------------
G3PPJ8_GASAC|Gasterosteus         ------------------------------------------------------------
H3C8P8_TETNG|Tetraodon            ------------------------------------------------------------
E7F021_DANRE|Danio                ------------------------------------------------------------
I3JZC4_ORENI|Oreochromis          ------------------------------------------------------------
Q28DG2_XENTR|Xenopus              ------------------------------------------------------------
H3B581_LATCH|Latimeria            ------------------------------------------------------------
K7GJG6_PELSI|Pelodiscus           ------------------------------------------------------------
H0Z129_TAEGU|Taeniopygia          ------------------------------------------------------------
F1NH43_CHICK|Gallus               ------------------------------------------------------------
G1MZA7_MELGA|Meleagris            ------------------------------------------------------------
                                                                                              

L7M222_9ACAR|Rhipicephalus        QYGIFERCRYLVEVEGYNVNQPDAEDVTLLHWAAINNRREIVSFYISKGAVVDAIGGELR
E2AAK6_CAMFO|Camponotus           QYGALERVTELVE-AGADVNQPDSETVTLLHWAAINNRKDIVKYLIAKGAVVDAVGGELA
K7J8F5_NASVI|Nasonia              QYGALDRVTELVE-AGADVNQPDAETVTLLHWAAINNRKEIVKYLIAKGATVDAIGGE--
G6DPC9_DANPL|Danaus               ------------------------------------------------------------
B4J3N8_DROGR|Drosophila           QYGAIARVRDLIE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B4KYH8_DROMO|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B4LDZ7_DROVI|Drosophila           QYGAIARVRDLVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B4N727_DROWI|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B4H7T3_DROPE|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
Q29D93_DROPS|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B3M9T9_DROAN|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
Q9VUW9_DROME|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B3NDQ1_DROER|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B4ITV5_DROYA|Drosophila           QYGAIARVRELVE-SGWDVNQPDSETVTLLHWAAINNRRDIIRYFLEKGATVDAVGGELN
B0W2T5_CULQU|Culex                ------------------------------------------------------------
Q7PZ51_ANOGA|Anopheles            QYGAIARVKELIE-AGWDVNQPDSETVTLLHWAAINNRKDIIKYFLDKGAIVDAVGGELN
A7RWD7_NEMVE|Nematostella         ------------------------------------------------------------
C3ZCK2_BRAFL|Branchiostoma        ------------------------------------------------------------
H0W5P5_CAVPO|Cavia                ------------------------------------------------------------
G5ASE1_HETGA|Heterocephalus       ------------------------------------------------------------
ZDH12_MOUSE|Mus                   ------------------------------------------------------------
ZDH12_RAT|Rattus                  ------------------------------------------------------------
H0XYF8_OTOGA|Otolemur             ------------------------------------------------------------
G3U2Z9_LOXAF|Loxodonta            ------------------------------------------------------------
I3MFR4_SPETR|Spermophilus         ------------------------------------------------------------
G1PPR6_MYOLU|Myotis               ------------------------------------------------------------
L5K9R0_PTEAL|Pteropus             ------------------------------------------------------------
E2RQ98_CANFA|Canis                ------------------------------------------------------------
G1MB86_AILME|Ailuropoda           ------------------------------------------------------------
G9KYS3_MUSPF|Mustela              ------------------------------------------------------------
F6RCU4_HORSE|Equus                ------------------------------------------------------------
F6XST1_CALJA|Callithrix           ------------------------------------------------------------
G1S775_NOMLE|Nomascus             ------------------------------------------------------------
K7DHV8_PANTR|Pan                  ------------------------------------------------------------
G7PRE9_MACFA|Macaca               ------------------------------------------------------------
I0FVS9_MACMU|Macaca               ------------------------------------------------------------
ZDH12_HUMAN|Homo                  ------------------------------------------------------------
G3R6W9_GORGO|Gorilla              ------------------------------------------------------------
K7ETB9_PONAB|Pongo                ------------------------------------------------------------
E1B6X9_BOVIN|Bos                  ------------------------------------------------------------
F1RR67_PIG|Sus                    ------------------------------------------------------------
F7G3P7_ORNAN|Ornithorhynchus      ------------------------------------------------------------
F6TT20_MONDO|Monodelphis          ------------------------------------------------------------
G3X3J6_SARHA|Sarcophilus          ------------------------------------------------------------
H2SLY9_TAKRU|Takifugu             ------------------------------------------------------------
H2MTW9_ORYLA|Oryzias              ------------------------------------------------------------
G3PPJ8_GASAC|Gasterosteus         ------------------------------------------------------------
H3C8P8_TETNG|Tetraodon            ------------------------------------------------------------
E7F021_DANRE|Danio                ------------------------------------------------------------
I3JZC4_ORENI|Oreochromis          ------------------------------------------------------------
Q28DG2_XENTR|Xenopus              ------------------------------------------------------------
H3B581_LATCH|Latimeria            ------------------------------------------------------------
K7GJG6_PELSI|Pelodiscus           ------------------------------------------------------------
H0Z129_TAEGU|Taeniopygia          ------------------------------------------------------------
F1NH43_CHICK|Gallus               ------------------------------------------------------------
G1MZA7_MELGA|Meleagris            ------------------------------------------------------------
                                                                                              

L7M222_9ACAR|Rhipicephalus        STPLHWATRQGHLGMVVLLMRHGADASLVDGEGCSCIHLAAQSGHTAIVAYLVAKGQPVN
E2AAK6_CAMFO|Camponotus           STPLHWATRQGHLSTVVILMRAGADPTLRDSEGFSCIHLAAQFGHTAIVAYLVAKGVNPN
K7J8F5_NASVI|Nasonia              ------------------------------------------------------------
G6DPC9_DANPL|Danaus               ------------------------------------------------------------
B4J3N8_DROGR|Drosophila           ATPLHWATRQGHLSAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B4KYH8_DROMO|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B4LDZ7_DROVI|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B4N727_DROWI|Drosophila           ATPLHWATRQGHLGAVVLLIAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B4H7T3_DROPE|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
Q29D93_DROPS|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B3M9T9_DROAN|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
Q9VUW9_DROME|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B3NDQ1_DROER|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B4ITV5_DROYA|Drosophila           ATPLHWATRQGHLGAVVLLMAAGADPRIRDAEGCSCIHIAAQFAHTALVAYFIAKGVDPD
B0W2T5_CULQU|Culex                ------------------------------------------------------------
Q7PZ51_ANOGA|Anopheles            ATPLHWATRQGHLGAVVLLLAAGADPSLRDAEGCSCIHLAAQFGHTALVAYFIARGVNPD
A7RWD7_NEMVE|Nematostella         ------------------------------------------------------------
C3ZCK2_BRAFL|Branchiostoma        ------------------------------------------------------------
H0W5P5_CAVPO|Cavia                ------------------------------------------------------------
G5ASE1_HETGA|Heterocephalus       ------------------------------------------------------------
ZDH12_MOUSE|Mus                   ------------------------------------------------------------
ZDH12_RAT|Rattus                  ------------------------------------------------------------
H0XYF8_OTOGA|Otolemur             ------------------------------------------------------------
G3U2Z9_LOXAF|Loxodonta            ------------------------------------------------------------
I3MFR4_SPETR|Spermophilus         ------------------------------------------------------------
G1PPR6_MYOLU|Myotis               ------------------------------------------------------------
L5K9R0_PTEAL|Pteropus             ------------------------------------------------------------
E2RQ98_CANFA|Canis                ------------------------------------------------------------
G1MB86_AILME|Ailuropoda           ------------------------------------------------------------
G9KYS3_MUSPF|Mustela              ------------------------------------------------------------
F6RCU4_HORSE|Equus                ------------------------------------------------------------
F6XST1_CALJA|Callithrix           ------------------------------------------------------------
G1S775_NOMLE|Nomascus             ------------------------------------------------------------
K7DHV8_PANTR|Pan                  ------------------------------------------------------------
G7PRE9_MACFA|Macaca               ------------------------------------------------------------
I0FVS9_MACMU|Macaca               ------------------------------------------------------------
ZDH12_HUMAN|Homo                  ------------------------------------------------------------
G3R6W9_GORGO|Gorilla              ------------------------------------------------------------
K7ETB9_PONAB|Pongo                ------------------------------------------------------------
E1B6X9_BOVIN|Bos                  ------------------------------------------------------------
F1RR67_PIG|Sus                    ------------------------------------------------------------
F7G3P7_ORNAN|Ornithorhynchus      ------------------------------------------------------------
F6TT20_MONDO|Monodelphis          ------------------------------------------------------------
G3X3J6_SARHA|Sarcophilus          ------------------------------------------------------------
H2SLY9_TAKRU|Takifugu             ------------------------------------------------------------
H2MTW9_ORYLA|Oryzias              ------------------------------------------------------------
G3PPJ8_GASAC|Gasterosteus         ------------------------------------------------------------
H3C8P8_TETNG|Tetraodon            ------------------------------------------------------------
E7F021_DANRE|Danio                ------------------------------------------------------------
I3JZC4_ORENI|Oreochromis          ------------------------------------------------------------
Q28DG2_XENTR|Xenopus              ------------------------------------------------------------
H3B581_LATCH|Latimeria            ------------------------------------------------------------
K7GJG6_PELSI|Pelodiscus           ------------------------------------------------------------
H0Z129_TAEGU|Taeniopygia          ------------------------------------------------------------
F1NH43_CHICK|Gallus               ------------------------------------------------------------
G1MZA7_MELGA|Meleagris            ------------------------------------------------------------
                                                                                              

L7M222_9ACAR|Rhipicephalus        QADSNGMTPLMWAAYRVMTNDPCRLLITLGASLTMCDTYHRNTPLHWAVYVRNSSAV-SL
E2AAK6_CAMFO|Camponotus           MPDRSAMTPLMWSAYKVNSLDPTRLLLTLGASHSLTDNLHGNTALHWAIIAKNNTAISIL
K7J8F5_NASVI|Nasonia              ----------------LASLDPTRLLLTLGASHSLTDNLHGNTALHWAIIAKNNTAIKTL
G6DPC9_DANPL|Danaus               ------MTPLMWASWKVCAVDPTRLLLTLGASPQPADHAHGNTALHWAILARNATAISTL
B4J3N8_DROGR|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
B4KYH8_DROMO|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNSTAISTL
B4LDZ7_DROVI|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNSTAISTL
B4N727_DROWI|Drosophila           LQDRGGMTALMWSAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
B4H7T3_DROPE|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
Q29D93_DROPS|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
B3M9T9_DROAN|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
Q9VUW9_DROME|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
B3NDQ1_DROER|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
B4ITV5_DROYA|Drosophila           LQDRGGMTALMWAAWKVCALDPVRLLLTLGANPAMVDYTHGNTALHWAILARNATAISTL
B0W2T5_CULQU|Culex                -----------MDHHSVDELHRLGTLTA--------------------------------
Q7PZ51_ANOGA|Anopheles            LQDRGGMTALMWAAWKISALDPVRLLLTLGANPSLADHTHGNTALHWAILARNATAISTL
A7RWD7_NEMVE|Nematostella         ---------MAAKHWKERVLSRIF-----------------HIFITTAVVL-------SL
C3ZCK2_BRAFL|Branchiostoma        -----MAGVWQKPCWRL-VFSTAVLVRS------------FHVCITTGVVS-------LL
H0W5P5_CAVPO|Cavia                -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
G5ASE1_HETGA|Heterocephalus       -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
ZDH12_MOUSE|Mus                   -----------MALWPP--LNSGMLVRT------------GHTVLTWGITL-------VL
ZDH12_RAT|Rattus                  -----------MALWPL--LNSGMLVRT------------GHTVLTWGITL-------VL
H0XYF8_OTOGA|Otolemur             -----------MAPWAL--LSSGVLVRT------------GHTVLTWGITL-------VL
G3U2Z9_LOXAF|Loxodonta            -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
I3MFR4_SPETR|Spermophilus         -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
G1PPR6_MYOLU|Myotis               -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
L5K9R0_PTEAL|Pteropus             -----------MAPWAL--FNPGVLVRT------------GHTVLTWGITL-------VL
E2RQ98_CANFA|Canis                -----------MAPWAL--LSPGVLVRT------------GHTVLTWGIPL-------VL
G1MB86_AILME|Ailuropoda           -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
G9KYS3_MUSPF|Mustela              ------------------------------------------------------------
F6RCU4_HORSE|Equus                -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
F6XST1_CALJA|Callithrix           -----------MAPWAL--LSPGILVRT------------RHTVLTWGITL-------VL
G1S775_NOMLE|Nomascus             -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
K7DHV8_PANTR|Pan                  -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
G7PRE9_MACFA|Macaca               -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
I0FVS9_MACMU|Macaca               -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
ZDH12_HUMAN|Homo                  -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
G3R6W9_GORGO|Gorilla              -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
K7ETB9_PONAB|Pongo                -----------MAPWAL--LSPGVLVRT------------GHTVLTWGITL-------VL
E1B6X9_BOVIN|Bos                  -----------MAPWAL--LTPGVLVRT------------GHTVLTWGITL-------VL
F1RR67_PIG|Sus                    ------------------------------------------------------------
F7G3P7_ORNAN|Ornithorhynchus      ------------------------------------------------------------
F6TT20_MONDO|Monodelphis          -----------MGPRAL--LSPGVLVRT------------GHTVLTWGITL-------VL
G3X3J6_SARHA|Sarcophilus          -----------MGPRAL--LSPGVLVRT------------GHTVLTWGITL-------VL
H2SLY9_TAKRU|Takifugu             --------------MAQNMFRSGFLVRT------------THTLITWAITL-------TL
H2MTW9_ORYLA|Oryzias              -----------EMVPNM--FRTGFAVRA------------AHTLLTWVITV-------TL
G3PPJ8_GASAC|Gasterosteus         -----------KMVQNM--FRSGFLVRA------------SHTLLTWVITL-------IL
H3C8P8_TETNG|Tetraodon            -----------NMLRSV--FGSGFAVRT------------AHVVLTWLITL-------IL
E7F021_DANRE|Danio                ------------MFKNV--FGSGFLVRT------------AHVILTWVITL-------IL
I3JZC4_ORENI|Oreochromis          ------------MFKNV--FGSGFLVRT------------SHVILTWVITL-------IL
Q28DG2_XENTR|Xenopus              --------------MFRCVLSAGFLVRT------------VHTVLTWGVTL-------VL
H3B581_LATCH|Latimeria            ------------MFRNV--FAAGFLVRT------------AHTVLTWAVTL-------VL
K7GJG6_PELSI|Pelodiscus           --------MLQAAPWGR-----SSLVRA------------AHAGLSCGVTL-------AL
H0Z129_TAEGU|Taeniopygia          ------------------------------------------------------------
F1NH43_CHICK|Gallus               -----------RARGAM--GAGGLWVRT------------AHTALSGGLTL-------GL
G1MZA7_MELGA|Meleagris            ------------------------------------------------------------
                                                                                              

L7M222_9ACAR|Rhipicephalus        LIKAGSDLSARNAQGDTP-RMMAEKLKSIWIEERLLE-----AEAAQAQGHFLVRIVRDK
E2AAK6_CAMFO|Camponotus           VQHGA-SLDLPNFQNETAMTLLGPHIGAAWLGHKISQEIKE-------KQGRTRTWCRDK
K7J8F5_NASVI|Nasonia              VHYGA-SLDVPNFKNETPMMLLGPHIGAAWLGHKFSHEIR-------QKQGRTRVWCRDK
G6DPC9_DANPL|Danaus               ILYGNASLDVPNLRGVTPLTMLKSNTDSLWVGAKVADKIKEQTAASSKRNIFR-RLAYDK
B4J3N8_DROGR|Drosophila           VLKSKASLDVPNLRAETPLSMLEAQTGAIWIGAKVMDRVREASLTSQQRRSLLSKLRHDK
B4KYH8_DROMO|Drosophila           VLKSKASLDVPNLRAETPLSMLEAQAGAIWIGAKVMDRVKEAALTSQQRRSLVSKLRHDK
B4LDZ7_DROVI|Drosophila           VLKSKASLDVPNLRAETPLSMLETQAGAIWIGAKVLDRIRDASLTSQQRRSLVSKLRHDK
B4N727_DROWI|Drosophila           VLKSKASLDVPNLRGETPLSMLESQTGAIWIGAKVMERVKEAALTSQQRRSLISKLRHDK
B4H7T3_DROPE|Drosophila           VLKSKASLDVPNMRGETPLTMLESQTGAIWIGAKVMDRVREAALTSQQRRSLVSKLRHDK
Q29D93_DROPS|Drosophila           VLKSKASLDVPNMRGETPLTMLESQTGAIWIGAKVMDRVREAALTSQQRRSLVSKLRHDK
B3M9T9_DROAN|Drosophila           VLKSKASLDVPNLRGETPLTMLESQTGAIWIGAKVMDRVKEAALTSQQRRSLVSKLRHDK
Q9VUW9_DROME|Drosophila           VLKSKASLDVPNLRGETPLSMLESQTGAIWIGAKVMDRVKEAALTSQQRRSLLSKLRHDK
B3NDQ1_DROER|Drosophila           VLKSKASLDVPNLRGETPLTMLESQTGAIWIGAKVMDRVKEAALTSQQRRSLLSKLRHDK
B4ITV5_DROYA|Drosophila           VLKSKASLDVPNLRGETPLSMLESQTGAIWIGAKVMDRVKEAALTSQQRRSLLSKLRHDK
B0W2T5_CULQU|Culex                ------------------------------------------------------------
Q7PZ51_ANOGA|Anopheles            VLKGKANMEVPNLRGDTPLTMLQPHLGSIWIGTKVSDRIREATQQSHRRNPLV-RMTLDK
A7RWD7_NEMVE|Nematostella         FLTNT----------------------------------------------ELKRSIFDG
C3ZCK2_BRAFL|Branchiostoma        FFKDT-------------------------------------------------------
H0W5P5_CAVPO|Cavia                FLHDT-------------------------------------------------------
G5ASE1_HETGA|Heterocephalus       FLHDT-------------------------------------------------------
ZDH12_MOUSE|Mus                   FLHDT-------------------------------------------------------
ZDH12_RAT|Rattus                  FLHDT-------------------------------------------------------
H0XYF8_OTOGA|Otolemur             FLHDTGETD-----------------------------------------PTRSWTHPIP
G3U2Z9_LOXAF|Loxodonta            FLHDTGE-----------------------------------------PDPARPRTHPTP
I3MFR4_SPETR|Spermophilus         FLHDTGEPD------------------------------------PERPGPIRS------
G1PPR6_MYOLU|Myotis               FLHDT-------------------------------------------------------
L5K9R0_PTEAL|Pteropus             FLHDT-------------------------------------------------------
E2RQ98_CANFA|Canis                FLHDTGE-----------------------------------------PDPARPRTHPIP
G1MB86_AILME|Ailuropoda           FLHDTGEPD-----------------------------------------PARPQTHPIP
G9KYS3_MUSPF|Mustela              ------------------------------------------------------------
F6RCU4_HORSE|Equus                FLHDT-------------------------------------------------------
F6XST1_CALJA|Callithrix           FLHDTGESADELLATHSHSWNQPLQAFAQPGTHFPTSSCTPAPSTPVLPSPASLCSLASP
G1S775_NOMLE|Nomascus             FLHDTGEPD-----------------------------------------PERPRTHPIP
K7DHV8_PANTR|Pan                  FLHDT-------------------------------------------------------
G7PRE9_MACFA|Macaca               FLHDTGEPD-----------------------------------------PERPRTHPIP
I0FVS9_MACMU|Macaca               FLHDT-------------------------------------------------------
ZDH12_HUMAN|Homo                  FLHDT-------------------------------------------------------
G3R6W9_GORGO|Gorilla              FLHDTGEPD-----------------------------------------PERPRTHPIP
K7ETB9_PONAB|Pongo                FLHDT-------------------------------------------------------
E1B6X9_BOVIN|Bos                  FLHDT-------------------------------------------------------
F1RR67_PIG|Sus                    -----------------------------------------------------------P
F7G3P7_ORNAN|Ornithorhynchus      ---------------------------------------------------------PFS
F6TT20_MONDO|Monodelphis          FLHET-------------------------------------------------------
G3X3J6_SARHA|Sarcophilus          FLHET-------------------------------------------------------
H2SLY9_TAKRU|Takifugu             FLHNT--------------------------------------VNDEKESIQMLIHCAFP
H2MTW9_ORYLA|Oryzias              FLHNT-------------------------------------------------------
G3PPJ8_GASAC|Gasterosteus         FLHDT-------------------------------------------------------
H3C8P8_TETNG|Tetraodon            FLHDT-------------------------------------------------------
E7F021_DANRE|Danio                FLHDT-------------------------------------------------------
I3JZC4_ORENI|Oreochromis          FLHDT-------------------------------------------------------
Q28DG2_XENTR|Xenopus              FLHDT-------------------------------------------------------
H3B581_LATCH|Latimeria            FLHET-------------------------------------------------------
K7GJG6_PELSI|Pelodiscus           FLHRT-------------------------------------------------------
H0Z129_TAEGU|Taeniopygia          -----------------------------------------------------------S
F1NH43_CHICK|Gallus               FLHRT-------------------------------------------------------
G1MZA7_MELGA|Meleagris            -----------------------------------------------------------S
                                                                                              

L7M222_9ACAR|Rhipicephalus        TLK-YWAMFSSPFVAFYAIGLVLDSQETYLVKFGLLFIMGLATMFLSKCLFDERTMNILP
E2AAK6_CAMFO|Camponotus           RIR-WYCMVSTPFIAFYVIGMILQIGWDYLLKLGAFITLYVAVYLMNHFVFDERLFHILP
K7J8F5_NASVI|Nasonia              RIR-WYCMISTPFIIFYAIGMIFQSGLDYLIKLVAFVALYIAIHTASNYIYDERLYYVLP
G6DPC9_DANPL|Danaus               KFR-WWCVISIPFLAFYATGLVLEMDALYLLKGFLLVCFYALLHFFTNALFDDDLKNIFP
B4J3N8_DROGR|Drosophila           RLR-WWSMAASPFTAFYLAGIVFTLNTLYIIKFFLLGCLYAIFHTIGKTLFDEHLMALLP
B4KYH8_DROMO|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTINTLYIIKFFLLGCLYAIFHTIGKTLFDEHLMALLP
B4LDZ7_DROVI|Drosophila           RLR-WWAMVACPFTAFYLAGIVFTLNTLYIIKFFLLGCLYAIFHTIGKTLFDEHLMALLP
B4N727_DROWI|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTLNTLYIIKFFLLGCLYAIFHAIGKTLFDDHLMALLP
B4H7T3_DROPE|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTLNTLYIIKFFLLGCLYGIFHTIGKTLFDEHLMALLP
Q29D93_DROPS|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTLNTLYIIKFFLLGCLYGIFHTIGKTLFDEHLMALLP
B3M9T9_DROAN|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTVNTLYIIKFFLLGCLYAIFHTIGKALFDEHLMALLP
Q9VUW9_DROME|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTVNTLYIIKFFLLGCLYSIFHTIGKALFDEHLMALLP
B3NDQ1_DROER|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTVNTLYIIKFFLLGCLYAIFHTIGKALFDEHLMALLP
B4ITV5_DROYA|Drosophila           RLR-WWSMVACPFTAFYLAGIVFTVNTLYIIKFFLLGCLYAIFHTIGKALFDEHLMALLP
B0W2T5_CULQU|Culex                QLS-GY----------------------------------------------DHL-----
Q7PZ51_ANOGA|Anopheles            RFR-WWSMIATPFLVFYLVGLVFCADTQIIIKIFLLACLYSVAYTIGQHLFDENLMALLP
A7RWD7_NEMVE|Nematostella         RWY-YW------------------------------------------------------
C3ZCK2_BRAFL|Branchiostoma        ALRQQW----------------------------------------------LSGEYLVP
H0W5P5_CAVPO|Cavia                ELR-QW---------------------------------------------EEQGELLLP
G5ASE1_HETGA|Heterocephalus       ELR-QW---------------------------------------------EEQGELLLP
ZDH12_MOUSE|Mus                   ELR-QW---------------------------------------------EEQGELLLP
ZDH12_RAT|Rattus                  ELR-QW---------------------------------------------EEQGELFLP
H0XYF8_OTOGA|Otolemur             QLR-QW---------------------------------------------EEQGELLLP
G3U2Z9_LOXAF|Loxodonta            QLR-QW---------------------------------------------EEQGELLLP
I3MFR4_SPETR|Spermophilus         QLR-QW---------------------------------------------EEQGELLLP
G1PPR6_MYOLU|Myotis               ALR-QW---------------------------------------------EEQGELFLP
L5K9R0_PTEAL|Pteropus             ALR-QW---------------------------------------------EEQGELLLP
E2RQ98_CANFA|Canis                PLR-QW---------------------------------------------EEQGELLLP
G1MB86_AILME|Ailuropoda           PLR-QW---------------------------------------------EEQGELLPP
G9KYS3_MUSPF|Mustela              -LR-QW---------------------------------------------EEQGELLLP
F6RCU4_HORSE|Equus                ALR-QW---------------------------------------------EEQGELLLP
F6XST1_CALJA|Callithrix           ELR-QW---------------------------------------------EEQGELLLP
G1S775_NOMLE|Nomascus             QLR-QW---------------------------------------------EEQGQLLLP
K7DHV8_PANTR|Pan                  ELR-QW---------------------------------------------EEQGELLLP
G7PRE9_MACFA|Macaca               QLR-QW---------------------------------------------EEQGELLLP
I0FVS9_MACMU|Macaca               ELR-QW---------------------------------------------EEQGELLLP
ZDH12_HUMAN|Homo                  ELR-QW---------------------------------------------EEQGELLLP
G3R6W9_GORGO|Gorilla              QLR-QW---------------------------------------------EEQGELLLP
K7ETB9_PONAB|Pongo                ELR-QW---------------------------------------------EEQGELLLP
E1B6X9_BOVIN|Bos                  ALR-QW---------------------------------------------EEQGELLLP
F1RR67_PIG|Sus                    ALR-QW---------------------------------------------EEQGELLLP
F7G3P7_ORNAN|Ornithorhynchus      ELR-QQ---------------------------------------------EAHGELLQP
F6TT20_MONDO|Monodelphis          ELK-QQ---------------------------------------------EARGELLQP
G3X3J6_SARHA|Sarcophilus          ELK-QQ---------------------------------------------EARGELLQP
H2SLY9_TAKRU|Takifugu             DLR-KC---------------------------------------------EELGELLMP
H2MTW9_ORYLA|Oryzias              DLR-RC---------------------------------------------EERGELLPP
G3PPJ8_GASAC|Gasterosteus         DLR-RC---------------------------------------------EERGELLLP
H3C8P8_TETNG|Tetraodon            ELR-RQ---------------------------------------------EQPGQPGQP
E7F021_DANRE|Danio                DLR-RQ---------------------------------------------EETGELTLP
I3JZC4_ORENI|Oreochromis          ELR-KQ---------------------------------------------EETGQLVQP
Q28DG2_XENTR|Xenopus              DLY-HQ---------------------------------------------ENQWKLLQP
H3B581_LATCH|Latimeria            DLR-KL---------------------------------------------EERGELLQP
K7GJG6_PELSI|Pelodiscus           DLQ-KQ---------------------------------------------EEHGELLQP
H0Z129_TAEGU|Taeniopygia          DLQ-KQ---------------------------------------------EERGELLQP
F1NH43_CHICK|Gallus               DLQ-KE---------------------------------------------AERGAALQP
G1MZA7_MELGA|Meleagris            DLQ-KE---------------------------------------------AERGAVLQP
                                                                                              

L7M222_9ACAR|Rhipicephalus        MAVYLATKFWMYITWVTDLWPYVGTFWVNVGFVISSVPLFYSFYKSWRADPGIISAN---
E2AAK6_CAMFO|Camponotus           MSIYLATKMWIYVTWIFWLGVHA-AWYLWLLLVGGSVPLWICFLQSWRGDPGIITAT---
K7J8F5_NASVI|Nasonia              MSIYLATKMWIYVTWVFWLGIHA-AWYLWLLLVGGSVPLWICFLQSWRGDPGVIKAS---
G6DPC9_DANPL|Danaus               LSVYLATKVWFYITWVVLIAPVV-GGGETVAFLLCSMSLWYTFLRSWRSDPGVICAS---
B4J3N8_DROGR|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-TFATTVCFLICSLGLWVCFLKSWKGDPGIIRPT---
B4KYH8_DROMO|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SLANTVCFLISSLALWVCFLKSWKGDPGIIRPT---
B4LDZ7_DROVI|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SLATTVCFLISSLGLWVCFLKSWKGDPGIIRPT---
B4N727_DROWI|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SLTATICFLACSLVLWVCFLKSWKGDPGIIKPT---
B4H7T3_DROPE|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SLTATVCFLICSLILWVCFLKSWKGDPGIIRPT---
Q29D93_DROPS|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SLTATVCFLICSLILWVCFLKSWKGDPGIIRPT---
B3M9T9_DROAN|Drosophila           LSVYLATKAWFYITWLMFIDDAV-SFTATICFLISSLALWVCFLKSWKGDPGIIRPT---
Q9VUW9_DROME|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SFTATVCFLISSLLLWVCFLKSWKGDPGIIRPT---
B3NDQ1_DROER|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SITATICFLISSLLLWVCFLKSWKGDPGIIRPT---
B4ITV5_DROYA|Drosophila           LSVYLATKAWFYVTWLMYIDDAV-SLTATVCFLISSLLLWVCFLKSWKGDPGIIRPT---
B0W2T5_CULQU|Culex                -------------------------------LTLGGGLHDEAQHTV----AGTMHG----
Q7PZ51_ANOGA|Anopheles            LSVYMATKLWFYVTWLTYIAPTV-SFLASLAFLACSAGLWVCFLKSWRGNPGVIQPT---
A7RWD7_NEMVE|Nematostella         SSFLI--------------------------LCVLGLVFYFIAGIM---DPGYVETQEHN
C3ZCK2_BRAFL|Branchiostoma        CVYLA--------------------------LVFLSLVLYAAVCSM---DPGFVKDD---
H0W5P5_CAVPO|Cavia                LTFLF--------------------------LVLGSLLLYLAVSLM---DPGYVNTQ---
G5ASE1_HETGA|Heterocephalus       LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNTQ---
ZDH12_MOUSE|Mus                   LTFLL--------------------------LVLSSLLLYLAVSLM---DPGYVTTQ---
ZDH12_RAT|Rattus                  LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVTAQ---
H0XYF8_OTOGA|Otolemur             LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
G3U2Z9_LOXAF|Loxodonta            LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
I3MFR4_SPETR|Spermophilus         LTFLF--------------------------LVLGSLLLYLAVSLM---DPGYVNTQ---
G1PPR6_MYOLU|Myotis               LTFLL--------------------------LVLGSLLLYLAVSLM---DP-YVNIQ---
L5K9R0_PTEAL|Pteropus             LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNIQ---
E2RQ98_CANFA|Canis                LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
G1MB86_AILME|Ailuropoda           LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
G9KYS3_MUSPF|Mustela              LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
F6RCU4_HORSE|Equus                LIFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
F6XST1_CALJA|Callithrix           LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
G1S775_NOMLE|Nomascus             LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
K7DHV8_PANTR|Pan                  LTFLL--------------------------LVLGSLLLYFAVSLM---DPGYVNVQ---
G7PRE9_MACFA|Macaca               LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNAQ---
I0FVS9_MACMU|Macaca               LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNAQ---
ZDH12_HUMAN|Homo                  LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
G3R6W9_GORGO|Gorilla              LTFLL--------------------------LVLGSLLLYLTVSLM---DPGYVNVQ---
K7ETB9_PONAB|Pongo                LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVQ---
E1B6X9_BOVIN|Bos                  LTFLL--------------------------LVLASLLLYLTVSLM---DPGYVNVL---
F1RR67_PIG|Sus                    LTFLL--------------------------LVLGSLLLYLAVSLM---DPGYVNVL---
F7G3P7_ORNAN|Ornithorhynchus      LLFVL--------------------------LVLCSVLLYFAVSLM---DPGYVGPE---
F6TT20_MONDO|Monodelphis          LLFIL--------------------------LVLCSLLLYLAVSLM---DPGYVGPDPEA
G3X3J6_SARHA|Sarcophilus          LLFIL--------------------------LVLCSLLLYLAVSLM---DPGYVGPD---
H2SLY9_TAKRU|Takifugu             VVFIL--------------------------LVVLSVLLYFAVSLM---DPGFVLSD---
H2MTW9_ORYLA|Oryzias              ALFFL--------------------------LVVVSVILYFTVSLM---DPGFVPGD---
G3PPJ8_GASAC|Gasterosteus         VLFFL--------------------------LVMLSVLFYFAVSLM---DPGFVLSD---
H3C8P8_TETNG|Tetraodon            VLFVL--------------------------LVLVSVLLYLAVSLM---DPGFILAE--D
E7F021_DANRE|Danio                VLFVL--------------------------LVLVSVLLYFAVSLM---DPGFVLTD--D
I3JZC4_ORENI|Oreochromis          VLFVL--------------------------LVLLSVLLYFAVSLM---DPGFILSD--D
Q28DG2_XENTR|Xenopus              LSFGL--------------------------LVLCSVLLYFAVSLM---DPGYVLSD---
H3B581_LATCH|Latimeria            VVFVL--------------------------LILCSVLLYFIVSLM---DPGYIRSD---
K7GJG6_PELSI|Pelodiscus           LIFIL--------------------------LVLCSVLLYFAVSFM---DPGFVESD---
H0Z129_TAEGU|Taeniopygia          LIFVL--------------------------LVLCSILLYFKVSLM---DPGFVKPE---
F1NH43_CHICK|Gallus               TLFVA--------------------------LLGCSVLLYFRVSLM---DPGFVRAE---
G1MZA7_MELGA|Meleagris            ALFVA--------------------------LLGCSVLLYFRVSLM---DPGFVRAE---
                                                                 :   .              .  :      

L7M222_9ACAR|Rhipicephalus        ---------TE----QKYRTIVELAEQ---DGFDP-----AVFCSTCLVRRPLRSKHCSV
E2AAK6_CAMFO|Camponotus           ---------HE----DKLNTIIELAES---GGFEP-----QWFCSSCLVRRPMRSKHCST
K7J8F5_NASVI|Nasonia              ---------HE----DKLNCIIELAEN---GGFEP-----QLFCHTCLVRKPIRSKHCSV
G6DPC9_DANPL|Danaus               ---------RA----EKMRTIIELSERGGGGGFEP-----ARFCSACLLRRPLRSKHCSV
B4J3N8_DROGR|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B4KYH8_DROMO|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B4LDZ7_DROVI|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B4N727_DROWI|Drosophila           ---------RE----QRFKTIVELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B4H7T3_DROPE|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
Q29D93_DROPS|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B3M9T9_DROAN|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
Q9VUW9_DROME|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B3NDQ1_DROER|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B4ITV5_DROYA|Drosophila           ---------RE----QRFKTIIELSER-GGIGFEP-----ASFCSGCLVRRPIRSKHCSV
B0W2T5_CULQU|Culex                ---------QT----SDQLTIVELSER-GGGGFEP-----SAFCSACLVRRPVRSKHCSV
Q7PZ51_ANOGA|Anopheles            ---------QE----QRFRTIIELSER-GASGFEP-----SAFCSACLVRRPVRSKHCSV
A7RWD7_NEMVE|Nematostella         NILISYEK-AEVDIESQSENESDNAEETCKILATPPFGSRLRRCGYCAIMQPLRTKHCED
C3ZCK2_BRAFL|Branchiostoma        ---------ST----SATETSVMIEPDIGVKPRVK-----LRNCGFCGIQQPIRAKHCEQ
H0W5P5_CAVPO|Cavia                --PQP----QE----EAKEEQTAMVPP-----AIA-----LRRCRFCLVLQPLRARHCRD
G5ASE1_HETGA|Heterocephalus       --PQP----QE----EPKEEQTAMVPQ-----PVA-----LRRCRYCLVLQPLRARHCCA
ZDH12_MOUSE|Mus                   --PQP----QG----EPKEEQAAMVPQ-----AVP-----LRRCRHCLVLQPLRARHCRD
ZDH12_RAT|Rattus                  --PQP----QE----EPKEEQTAMVPQ-----AIP-----LRRCRYCLVLQPLRARHCRE
H0XYF8_OTOGA|Otolemur             --PQP----QE----DPKEEQMAMVPQ-----AIP-----LRRCRYCLVLQPLRARHCRE
G3U2Z9_LOXAF|Loxodonta            --PQF----QE----ELKEEQTAMVPQ-----AIP-----LRRCRYCLMLHPLRARHCHE
I3MFR4_SPETR|Spermophilus         --PQP----QK----EPKEEQTAMVPQ-----GIA-----LRRCRYCLVLQPLRARHCRD
G1PPR6_MYOLU|Myotis               --PQPGPHFQE----EAKEEQTAMVPP-----AIA-----LRRCRHCMVLQPLRARHCSE
L5K9R0_PTEAL|Pteropus             --PQP----QE----EVKEEQTAMVPP-----AIP-----LRRCRYCMVLQPLRARHCRE
E2RQ98_CANFA|Canis                --PQP----QE----EAKEEQTAMVPQ-----AIP-----LRRCRYCLVLQPLRARHCRE
G1MB86_AILME|Ailuropoda           --PQP----QE----EAKEEQTAMVPQ-----AIP-----LRRCRYCLVLQPLRARHCRE
G9KYS3_MUSPF|Mustela              --PQP----QE----EVKEEQTAMVPQ-----AIP-----LRRCRYCLVLQPLRARHCRE
F6RCU4_HORSE|Equus                --PQP----QE----EAKEEQTAMVPQ-----TIP-----LRRCRYCLVLQPLRARHCRE
F6XST1_CALJA|Callithrix           --PQP----QE----EIKEEQTAMVSP-----AIP-----LRRCRYCLVLQPLRARHCRE
G1S775_NOMLE|Nomascus             --PQP----QE----ALKEEQTAMVPP-----AIP-----LRRCRYCLVLQPLRARHCRE
K7DHV8_PANTR|Pan                  --PQP----QE----ELKEEQTAMVPP-----AIP-----LRRCRYCLVLQPLRARHCRE
G7PRE9_MACFA|Macaca               --PQP----QE----ELKEEQTAMVPP-----AIP-----LRRCRYCLVLQPLRARHCRE
I0FVS9_MACMU|Macaca               --PQP----QE----ELKEEQTAMVPP-----AIP-----LRRCRYCLVLQPLRARHCRE
ZDH12_HUMAN|Homo                  --PQP----QE----ELKEEQTAMVPP-----AIP-----LRRCRYCLVLQPLRARHCRE
G3R6W9_GORGO|Gorilla              --PQP----QE----ELKEEQTAMVPP-----AIP-----LRRCRYCLVLQPLRARHCRE
K7ETB9_PONAB|Pongo                --PQP----QE----ELKEEQTAMVPP-----AIP-----LRRCRYCLVLQPLRARHCRE
E1B6X9_BOVIN|Bos                  --PQP----QE----EAKEEQTAMVPQ-----AIP-----LRRCRYCMVLQPLRARHCRE
F1RR67_PIG|Sus                    --PQP----QE----EAKEEQTAMVPQ-----AIP-----LRRCRFCMVLQPLRARHCRE
F7G3P7_ORNAN|Ornithorhynchus      --PAPHA--QA----STSEELKAMVPQ--KPPTIH-----LRRCGYCLLKQPLRARHCRS
F6TT20_MONDO|Monodelphis          PSPPP----QK----EPKEEQTAMIPE----KTFR-----LRRCGYCLLQQPLRSKHCRS
G3X3J6_SARHA|Sarcophilus          -LEPPLSQLQK----EPKEEQTAMIPS----RTLR-----LRRCGYCLLQQPLRSKHCRS
H2SLY9_TAKRU|Takifugu             ---------TEKGSQDLTEEMESMMES-----SAP----WLRRCGYCLLQQPMRAKHCQI
H2MTW9_ORYLA|Oryzias              -SEKG----SE----ASDEESEAMIPR---PLAPQ-----LRRCGFCRLQQPMRAKHCRT
G3PPJ8_GASAC|Gasterosteus         ---------ST----KASGEEESMIPQ---SSTPR-----PRRCGYCLLQQPMRAKHCQT
H3C8P8_TETNG|Tetraodon            AGLQV----PL----GVTEEQQDMIPP--SAASQR-----RRRCAHCLVQQPMRSKHCQA
E7F021_DANRE|Danio                CDLQF----TL----GIAEETQDMIPQ--TTKSIR-----LRRCGHCLVQQPMRSKHCQT
I3JZC4_ORENI|Oreochromis          TDLQF----ML----GVTEEQQDMIPP--ATKSLR-----QRRCGHCLLQQPMRSKHCQT
Q28DG2_XENTR|Xenopus              ---------CNKKPLPTYLEQGVMIPE--APSGMR-----LRRCGYCLLQQPIRARHCKT
H3B581_LATCH|Latimeria            ---------SKVKLVAVSEEQEEMIPQ--VPKAMR-----LRRCGHCKLQQPMRAKHCES
K7GJG6_PELSI|Pelodiscus           ---------EE-EKVGVNEEQSVMMPQ--LPSNVR-----LRRCGYCMLKQPMRAKHCQL
H0Z129_TAEGU|Taeniopygia          ---------EE----EGEDKGQGVVIP-LIPGDIK-----LRRCGYCLVKQPMRAKHCRL
F1NH43_CHICK|Gallus               ---------EE-AEADKSEEQCTLVPQ--VSSSVK-----MRRCGYCMVKQPMRAKHCQL
G1MZA7_MELGA|Meleagris            ---------EE-AEADKSEEQCMVIPQ--VSSSVK-----MRRCGYCMVKQPMRAKHCQL
                                                                             *  * : .*:*:.**  

L7M222_9ACAR|Rhipicephalus        CNHCVARFDHHCPWVNNCVGAGNHVYFVNYLIFLLAMLGWSWY---GCFAFWKE------
E2AAK6_CAMFO|Camponotus           CDRCVARFDHHCPWVNNCIGAHNHKYFLGFLASLLGLCIVILT---ASVQYWKFEC----
K7J8F5_NASVI|Nasonia              CDVCVARYDHHCPWVNNCIGARNHKYFLGFLMSLLGLCIVVLT---ASIQYWQFEC----
G6DPC9_DANPL|Danaus               CNRCVAKFDHHCPWVANCIGAKNHHYFIGFLASLLVMCAWML---WGAAQYFTSVCGAAS
B4J3N8_DROGR|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCAWMLY---GGSKYYVNECNVRF
B4KYH8_DROMO|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCGWMLY---GGSKFYVNECNVHF
B4LDZ7_DROVI|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCVWMLY---GGSKFYVNECNVHF
B4N727_DROWI|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCAWMLY---GGSKYYVNQCNVHF
B4H7T3_DROPE|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCVWMLY---GGSKYYVNQCNVHF
Q29D93_DROPS|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCVWMLY---GGSKYYVNQCNVHF
B3M9T9_DROAN|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCAWMLY---GGSKFYVNQCNVRF
Q9VUW9_DROME|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCAWMLY---GGSKYYVNQCNVRF
B3NDQ1_DROER|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCAWMLY---GGSKYYVNQCNVRF
B4ITV5_DROYA|Drosophila           CDRCVARFDHHCPWVGNCIGLKNHSYFMGFLWMLLIMCAWMLY---GGSKYYVNQCNVRF
B0W2T5_CULQU|Culex                CDRCVARFDHHCPWVGNCIGSKNHKYFMGFLWMLLTMCCWMLY---GGANFYVQACNVNM
Q7PZ51_ANOGA|Anopheles            CDRCVARFDHHCPWVGNCIGAKNHKYFMGFLWMLLIMCGWMLY---GGSNFYVQTCSINM
A7RWD7_NEMVE|Nematostella         CGRCVRKYDHHCPWLGTCVGERNHRFFWCFLVSQNALVAWAIEIAWHGFVYKDS------
C3ZCK2_BRAFL|Branchiostoma        CGFCIHRFDHHCPWFETCIGERNHRFFWTFLLVETSLVGWTVHLVWTAFVYEAS------
H0W5P5_CAVPO|Cavia                CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLAVLLWGLHLAWSGLHFFQP------
G5ASE1_HETGA|Heterocephalus       CRRCVRRYDHHCPWMENCVGERNHPLFVAYLVVQLAVLLWGLHLAWSGLHFFQP------
ZDH12_MOUSE|Mus                   CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLCLAWSGLQFFQP------
ZDH12_RAT|Rattus                  CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLQFFQP------
H0XYF8_OTOGA|Otolemur             CRRCVRRYDHHCPWMENCVGERNHPFFVVYLALQLVVLLWGLYLAWSGLRFFQP------
G3U2Z9_LOXAF|Loxodonta            CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWALCLAWSGLRFFQP------
I3MFR4_SPETR|Spermophilus         CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLQFFQP------
G1PPR6_MYOLU|Myotis               CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLRFFQP------
L5K9R0_PTEAL|Pteropus             CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLRFFQP------
E2RQ98_CANFA|Canis                CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLHFFQP------
G1MB86_AILME|Ailuropoda           CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLHFFQP------
G9KYS3_MUSPF|Mustela              CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWSLYLAWSGLHFFQP------
F6RCU4_HORSE|Equus                CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLRFFQP------
F6XST1_CALJA|Callithrix           CRRCVRRYDHHCPWMENCVGERNHPLFVVYLVLQLLVLLWGLYLAWSGLRFFQP------
G1S775_NOMLE|Nomascus             CRRCVRRYDHHCPWMDNCVGERNHPLFVVYLALHLVVLLWGLYLAWSGLRFFQP------
K7DHV8_PANTR|Pan                  CRRCVRRYDHHCPWMENCVGERNHPLFVVYLALQLVVLLWGLYLAWSGLRFFQP------
G7PRE9_MACFA|Macaca               CRRCVRRYDHHCPWMENCVGERNHPLFVVYLALQLVVLLWGLYLAWSGLQFFQP------
I0FVS9_MACMU|Macaca               CRRCVRRYDHHCPWMENCVGERNHPLFVVYLALQLVVLLWGLYLAWSGLQFFQP------
ZDH12_HUMAN|Homo                  CRRCVRRYDHHCPWMENCVGERNHPLFVVYLALQLVVLLWGLYLAWSGLRFFQP------
G3R6W9_GORGO|Gorilla              CRRCVRRYDHHCPWMENCVGERNHPLFVVYLALQLVVLLWGLYLAWSGLRFFQP------
K7ETB9_PONAB|Pongo                CRRCVRRYDHHCPWMENCVGERNHPLFVVYLALQLVVLLWGLYLAWSGLRFFQP------
E1B6X9_BOVIN|Bos                  CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWALYLAWSGLRFFQP------
F1RR67_PIG|Sus                    CRRCVRRYDHHCPWMENCVGERNHPLFVAYLALQLVVLLWGLYLAWSGLRFFQP------
F7G3P7_ORNAN|Ornithorhynchus      CKRCVRRYDHHCPWIENCVGERNHPLFVAYLALQLVVLVWALRLAWSGISFEQP------
F6TT20_MONDO|Monodelphis          CKRCVRRFDHHCPWIENCVGERNHPLFLAYLAVQLVVLLWGLHLAWSGLHFRES------
G3X3J6_SARHA|Sarcophilus          CKRCVRRFDHHCPWIENCVGERNHPLFLAYLAVQLVVLLWGLHLAWSGLHFQEP------
H2SLY9_TAKRU|Takifugu             CKRCVRRYDHHCPWIENCVGERNHRWFVIYLLVQLLALLWAFHIALSGLSPSVT------
H2MTW9_ORYLA|Oryzias              CRRCVRRFDHHCPWLENCVGERNHRWFVVYLLVQLLALLWALRTALSGLSPGPT------
G3PPJ8_GASAC|Gasterosteus         CQRCVRRFDHHCPWMENCVGERNHRWFLVYLLVQLLALLWALRVALSGLAPGAS------
H3C8P8_TETNG|Tetraodon            CRRCVRRYDHHCPWMENCVGERNHRWFMLYLLVQLLVLLWGLHIASTGFQAGGA------
E7F021_DANRE|Danio                CQHCVRRYDHHCPWIENCVGERNHRWFVLYLAVQFVVLLWGLYMAWSGFSHAST------
I3JZC4_ORENI|Oreochromis          CQHCVRRYDHHCPWIENCVGERNHRWFVLYLAFQLLVLLWGLRIAWTGFTYVPI------
Q28DG2_XENTR|Xenopus              CHHCVRRFDHHCPWIENCVGERNHPLFMLYLGVQFLVLLWAFRLTWSGFQFEAS------
H3B581_LATCH|Latimeria            CRYCVRRYDHHCPWIENCVGERNHPFFISYLAVQLIVLFWGFHFAWSGFHSEPS------
K7GJG6_PELSI|Pelodiscus           CRHCVRRYDHHCPMIENCIGERNHPFFIAYLAVQLVVLLWAFHIAWSGLYFEQS------
H0Z129_TAEGU|Taeniopygia          CQHCVRRYDHHCPWLENCVGERNHPLFIVYLSVQLVVLLWGGHVAWSGLYFEQS------
F1NH43_CHICK|Gallus               CQHCVRRYDHHCPWIENCVGEKNHPLFIVYLSVQLVVLLWGGHIAWSGLYFKQS------
G1MZA7_MELGA|Meleagris            CQHCVRRFDHHCPWIENCVGEKNHPLFVVYLSVQLVVLLWGGHIAWSGLYFKQS------
                                  *  *: .:***** . .*:*  **  *  :*                             

L7M222_9ACAR|Rhipicephalus        -HTLWA--------------ALSQSG-WVAWVAFNTLLHSAWVSCLLLCQLYQMVWLAMT
E2AAK6_CAMFO|Camponotus           ----WSNLTNGHSADNYLVAAATCDA-WVMWVAANTSLHSFWVGTLLACQCYQIMVLGMT
K7J8F5_NASVI|Nasonia              ----WTNLTDGHTADNYLIAAATCDA-WIMWVTTNTALHSFWVGTLLACQCYQIMILGMT
G6DPC9_DANPL|Danaus               GGTVVLV-------------WLQCSP-WLAWVSLNAAFHLFWVTVLSCCQLYLVVCLGMT
B4J3N8_DROGR|Drosophila           DD-FLTAMRA----------IGNCNA-WVGWVMGNALLHMSWVILLTVCQTYQVICLGMT
B4KYH8_DROMO|Drosophila           DD-FLAAMRA----------IGNCNA-WVGWVMGNALLHMSWVILLTVCQTYQVVCLGMT
B4LDZ7_DROVI|Drosophila           DD-FLTAMRA----------IGNCNA-WVGWVMGNALLHMSWVILLTVCQTYQVICLGMT
B4N727_DROWI|Drosophila           DD-FLTAMRA----------IGNCNA-WVGWVMGNALLHMSWVILLTICQTYQVICLGMT
B4H7T3_DROPE|Drosophila           DD-FLGAMRA----------IGNCNA-WVGWVMGNALLHMSWVILLTICQTYQVICLGMT
Q29D93_DROPS|Drosophila           DD-FLGAMRA----------IGNCNA-WVGWVMGNALLHMSWVILLTICQTYQVICLGMT
B3M9T9_DROAN|Drosophila           DD-FLGAMRA----------IGNCNA-WVGWVMGNALLHMSWVILLTICQTYQVICLGMT
Q9VUW9_DROME|Drosophila           DD-FLGAMRA----------IGNCDA-WVGWVMGNALLHMSWVILLTICQTYQVICLGMT
B3NDQ1_DROER|Drosophila           DD-FLGAMRA----------IGNCDA-WVGWVMGNAMLHMSWVILLTICQTYQVICLGMT
B4ITV5_DROYA|Drosophila           DD-FLGAMRA----------IGNCDA-WVGWVMGNAMLHMSWVILLTICQTYQVICLGMT
B0W2T5_CULQU|Culex                DEGLWSAMVA----------IGSCNP-WVGWVMANALLHMSWVTVLTICQTYQVVCLGMT
Q7PZ51_ANOGA|Anopheles            DEGLWSALQA----------IGSCNP-WVGWVMGNALLHMSWVTVLTICQSYQVVCLGMT
A7RWD7_NEMVE|Nematostella         ----WWD-------------WVVANA-FLLISMFILIFGMITVFLLLCCHTYLMVT-AQT
C3ZCK2_BRAFL|Branchiostoma        ----WSS-------------WFVSNG-LYLVAMFVLVLGGTATFLLVASHTYLIGI-NLT
H0W5P5_CAVPO|Cavia                ----WGV-------------WLRSSG-LLFATFLLLFLFSLVVGLLLASHLYLVAS-NTT
G5ASE1_HETGA|Heterocephalus       ----WGL-------------WLRSSG-LLFATFLLLSLFSLVASLLLASHLYLVAS-NTT
ZDH12_MOUSE|Mus                   ----WGL-------------WLRSTG-LLFTTFLLLSFFALVVALLLASHLYLVAR-NTT
ZDH12_RAT|Rattus                  ----WGL-------------WLRSTG-LLFTTFLLLSFFALVVSLLLASHLYLVAR-NTT
H0XYF8_OTOGA|Otolemur             ----WGL-------------WLRSSG-LLFITFLLLSFFALIAGLLLASHLYLVAS-NTT
G3U2Z9_LOXAF|Loxodonta            ----WGL-------------WLRSNG-LLFATFLLLSLFSSVASLLLASHLYLVAS-NTT
I3MFR4_SPETR|Spermophilus         ----WGL-------------WLRSRG-LLFATFLLLSFFSLVAGLLLASHLYLVAS-NTT
G1PPR6_MYOLU|Myotis               ----WGL-------------WLRSSG-LLFATFLLLSLFSMVAGLLLASHIYLVAS-NTT
L5K9R0_PTEAL|Pteropus             ----WGL-------------WLRSSG-LLFATFLLLSLFSLAASLLLASHLYLVAS-NTT
E2RQ98_CANFA|Canis                ----WGL-------------WLRSSG-LLFATFLLLSVFSLVASLLLASHLYLVAS-NTT
G1MB86_AILME|Ailuropoda           ----WGL-------------WLRSSG-LLFATFLLLSFFSLGASLLLASHLYLVAS-NTT
G9KYS3_MUSPF|Mustela              ----WGL-------------WLRSSG-LLFATFLLLSLFSLVASLLLASHLYLVAS-NTT
F6RCU4_HORSE|Equus                ----WGL-------------WLRSSG-LLFATFLLLSLFSLVAGLLLASHLYLVAS-NTT
F6XST1_CALJA|Callithrix           ----WGL-------------WLRSSG-LLFATFLLLSLFSLVASLLLASHLYLVAS-NTT
G1S775_NOMLE|Nomascus             ----WGL-------------WLRSSG-LLFATFLLLSLFSLVASLLLASHLYLVAS-NTT
K7DHV8_PANTR|Pan                  ----WGL-------------WLRSSG-LLFATFLLLSFFSLVASLLLALHLYLVAS-NTT
G7PRE9_MACFA|Macaca               ----WGL-------------WLRSSG-LLFATFLLLSLLSLVASLLLASHLYLVAS-NTT
I0FVS9_MACMU|Macaca               ----WGL-------------WLRSSG-LLFATFLLLSLLSLVASLLLASHLYLVAS-NTT
ZDH12_HUMAN|Homo                  ----WGQ-------------WLRSSG-LLFATFLLLSLFSLVASLLLVSHLYLVAS-NTT
G3R6W9_GORGO|Gorilla              ----WGL-------------WLRSSG-LLFATFLLLSLFSLVASLLLASHLYLVAS-NTT
K7ETB9_PONAB|Pongo                ----WGL-------------WLRSSG-LLFATFLLLSLFSLVASLLLASHLYLVAS-NTT
E1B6X9_BOVIN|Bos                  ----WGL-------------WLRSSG-LLFATFLLLSLFSLVAGLLLASHLYLVAS-NTT
F1RR67_PIG|Sus                    ----WGL-------------WLRSSG-LLLATFLLLSLFSLVAGLLLASHLYLVAS-NTT
F7G3P7_ORNAN|Ornithorhynchus      ----WGA-------------WLRHTG-LLFAAFLLLAVFSAVVALLLASHLYLVSC-DTT
F6TT20_MONDO|Monodelphis          ----WQS-------------WLPHNG-LLFLTFLLLSIFSTVVTLLLASHLYLVAS-DTT
G3X3J6_SARHA|Sarcophilus          ----WQS-------------WLQHNG-LLFATFLLLGIFSTVVTLLLASHLYLVAS-DMT
H2SLY9_TAKRU|Takifugu             ----WDL-------------WFRSNG-FLLASLVIVGIFSVAVVLLLGCHLYLVSI-NCT
H2MTW9_ORYLA|Oryzias              ----WQQ-------------WLWVNG-FLLAALAVVGVFSVVVGLLLGCHLYLVSI-NST
G3PPJ8_GASAC|Gasterosteus         ----WDL-------------WLRANC-FLLAALAVLGVFSAVVLLLLGVHLYLASV-NCT
H3C8P8_TETNG|Tetraodon            ----WRP-------------WLRANDRWFMLYLLVQLLVLLWGLHIGSSHLYLISL-NTT
E7F021_DANRE|Danio                ----WQQ-------------WLRTNG-VLLGAAAVVAILALTVLLLLGSHLYLVSL-NTT
I3JZC4_ORENI|Oreochromis          ----WHQ-------------WLRTNG-VLTAVTMLLALLSLIVLLLLGSHLYLVSL-NTT
Q28DG2_XENTR|Xenopus              ----WTE-------------WLKVNI-FLLLAFILTGIFTFVVALLLGCHCYLISC-NVT
H3B581_LATCH|Latimeria            ----MKE-------------WLQHNC-FLLLAFVIIAIFTVVVILLLVSHLYLVSC-NTT
K7GJG6_PELSI|Pelodiscus           ----WE--------------WLKHNI-FLLLSFLLIVIFTIVVMLLLVSHLYLVSC-NTT
H0Z129_TAEGU|Taeniopygia          -----QE-------------WLQDNI-FLLVSFLLIFIFTIVVLLLLVSHLYLISC-NTT
F1NH43_CHICK|Gallus               ----WE--------------WLRHNI-FLLISFLLIVIFTIVVLLLLISHLYLISC-NTT
G1MZA7_MELGA|Meleagris            ----WE--------------WLRHNI-FLLISFLLIVIFTIVVLLLLISHLYLISC-NTT
                                                                       .       :   : *       *

L7M222_9ACAR|Rhipicephalus        TNERMNCNRYPHFRRASSGRVISPFNMGPLKNLADF--CEWRCLGANPR-DWRHVYNAND
E2AAK6_CAMFO|Camponotus           TNERMNAGRYKHFKQG------NPFHRGALQNAADFCNFSFCGVKAKPSSDWLHSFDLKQ
K7J8F5_NASVI|Nasonia              TNERINAGRYKHF--SKG----NPFHRGALQNAADFCDCSFCGLKAKPSTDWLHSYDLKQ
G6DPC9_DANPL|Danaus               TNEQLNRGRYRHFQARGGR---SPFTRGPLNNLADFFQCRLCGLLAPRPRDWSAAGL-DD
B4J3N8_DROGR|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPLLNLIDFLECSCFGMMQPRHVDWMSYYDYDA
B4KYH8_DROMO|Drosophila           TNERMNRGRYRHFQAKGGQ---SPFTRGPLLNLIDFLECSCFGLVQPRRIDWMNYYDYDA
B4LDZ7_DROVI|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPLLNLVDFLDCNCFGLVQPRRVDWMNYYDYDA
B4N727_DROWI|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPWQNLIDFLECNCFGLVQPKRVDWMNYYEYDE
B4H7T3_DROPE|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPIQNLIDFLECSCFGLVQPKRVDWMNYYDYDA
Q29D93_DROPS|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPIQNLIDFLECSCFGLVQPKRVDWMNYYDYDA
B3M9T9_DROAN|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPFQNLVDFLECSCFGLVQPKRVDWMNYYDYDA
Q9VUW9_DROME|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPIQNLVDFLECSCFGLVQPKRVDWMNYYDYDA
B3NDQ1_DROER|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPIQNLVDFLECSCFGLVQPKRVDWMNYYDYDA
B4ITV5_DROYA|Drosophila           TNERMNRGRYRHFQAKGGH---SPFTRGPIQNLVDFLECSCFGLVQPKRVDWMNYYDYDA
B0W2T5_CULQU|Culex                TNERMNRGRYRHFQAKGGK---SPFTRGPVRNLFDFLECSCFGLVQPLQTDWMQYFDFDK
Q7PZ51_ANOGA|Anopheles            TNERLNRGRYRHFQAKGGK---SPFNRGPVKNLFDFLECSCFGLVQPQRTDWMQFFEFDK
A7RWD7_NEMVE|Nematostella         TWEYMSRSRISYLKTLSEDI--NPFDQGYLCNVYGFL-CQC------RIQKWEAMLR---
C3ZCK2_BRAFL|Branchiostoma        TWEFMSRHRITYLKDYHGDE--NPFDEGLLKNLWKFF-LHL------RLKDWGMYLM-NR
H0W5P5_CAVPO|Cavia                TWEFISSHRIAYLRQRPG----NPFDHGLTRNLAHFF-CGW------PLRSWDILRA-EE
G5ASE1_HETGA|Heterocephalus       TWEFISPHRIAYLRQRSR----NPFDRGLTHNLAHFF-CGW------PSGSWDTLWA-EG
ZDH12_MOUSE|Mus                   TWEFISSHRIAYLRQRTS----NPFDRGPTRNLAHFF-CGW------PSGPWETLSA-EE
ZDH12_RAT|Rattus                  TWEFISSHRIAYLRQRTS----NPFDRGPTRNLAHFF-CGW------PSGPWETLWA-EE
H0XYF8_OTOGA|Otolemur             TWEFISSHRIAYLRQRSS----NPFDRGLIRNLARFF-CGW------PSGSWETLWA-ED
G3U2Z9_LOXAF|Loxodonta            TWEFISSHRIAYLRQRSS----NPFDRGLIRNLAHFF-CGW------PSGSWETLWA-EE
I3MFR4_SPETR|Spermophilus         TWEFISSHRIAYLRQRPS----NPFNRGLTRNLAHFF-CGW------PSGSWETLWA-EE
G1PPR6_MYOLU|Myotis               TWEFLSSHRIAYLRQRPG----NPFDRGLIRNLAHFF-CGW------PSGPWETLLA-EE
L5K9R0_PTEAL|Pteropus             TWEFISSHRIAYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWETLWAGED
E2RQ98_CANFA|Canis                TWEFISSHRIAYLRQRPS----NPFDRGLTRNLAHFF-CGW------PSGSWEALWA-EG
G1MB86_AILME|Ailuropoda           TWEFISSHRIAYLRQRTS----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EG
G9KYS3_MUSPF|Mustela              TWEFISSHRIAYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EG
F6RCU4_HORSE|Equus                TWEFISSHRIAYLRQRPG----NPFDRGLIRNLAHFF-CGW------PSGSWETLWA--E
F6XST1_CALJA|Callithrix           TWEFMSSHRITYLRQRPD----NPFDQGLTRNLAHFF-CGW------PSGSWETLWA-EE
G1S775_NOMLE|Nomascus             TWEFISSHRIAYLRQRPS----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
K7DHV8_PANTR|Pan                  TWEFISSHRIAYLRQRPS----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
G7PRE9_MACFA|Macaca               TWEFISSHRIAYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
I0FVS9_MACMU|Macaca               TWEFISSHRIAYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
ZDH12_HUMAN|Homo                  TWEFISSHRIAYLRQRPS----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
G3R6W9_GORGO|Gorilla              TWEFISSHRIAYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
K7ETB9_PONAB|Pongo                TWEFISSHRITYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
E1B6X9_BOVIN|Bos                  TWEFISSHRIAYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWEALWA-ED
F1RR67_PIG|Sus                    TWEFISSHRIAYLRQRPG----NPFDRGLTRNLAHFF-CGW------PSGSWETLWA-EE
F7G3P7_ORNAN|Ornithorhynchus      TWEFMSPHRISYLRRRSS----SPFDRGLLRNLGRFF-CGC------EAVAWEMLYTPED
F6TT20_MONDO|Monodelphis          TWEFISPHRIAYLRHRPD----SPFDQGFARNLARFF-CGY------GAVPWEVLYAQEE
G3X3J6_SARHA|Sarcophilus          TWEFISPHRIAYLRHRSD----SPFDRGLARNLARFF-CGY------GAVPWEVLYA-QE
H2SLY9_TAKRU|Takifugu             TWEFMSQHRISYLKNCDSEY--SPFDRGVFCNLWDFF-CTC------RTVMWEQTFL---
H2MTW9_ORYLA|Oryzias              TWEFMSRHRILYLKDCREED--NPFDRGSVCNLWDFF-CSC------RTVMWEQVYQ---
G3PPJ8_GASAC|Gasterosteus         TWEFVSRHRVSYLKNRADER--SPFDRGLLCNLWDFF-C---------------------
H3C8P8_TETNG|Tetraodon            TWEFMCRHRISYLRHCGADQ--NPFDRGPAHNLWGFF-CVW------GTVVWEQVYF-QE
E7F021_DANRE|Danio                TWEFMSRHRISYLKHCGADE--NPFDKGILRNLWGFF-CAW------EPVVWEHVYF-KQ
I3JZC4_ORENI|Oreochromis          TWEFMSRHRISYLKHCGADE--NPFDRGTFQNLWGFF-CVW------GTVVWEQVYF-KE
Q28DG2_XENTR|Xenopus              TWEFMSHHRISYLKHYDSDT--NPFDKGIARNLWDFF-CKC------NRVAWEQVYF---
H3B581_LATCH|Latimeria            TWEFMSRHRISYLKHCGAEE--NPFDQGIIRNLWTFF-CVC------QTINWEKIYFQEE
K7GJG6_PELSI|Pelodiscus           TWEFMSRHRISYLRHSESE---NPFDQGVILNLWRFF-CAC------HLITWEKIYF---
H0Z129_TAEGU|Taeniopygia          TWEFMSHHRISYLRHSELE---NPFDQGIILNLWGFF-C---------------------
F1NH43_CHICK|Gallus               TWEFMSYHRISYLRHSELE---NPFDQGVIRNLWMFF-CSC------HLTAWEKIYF---
G1MZA7_MELGA|Meleagris            TWEFMSYHRISYLRHSELE---NPFDQGVIRNLWRFF-CSC------HLTAWEKIYF---
                                  *.* :   *  ::         .**  *   *   *                        

L7M222_9ACAR|Rhipicephalus        D---------------------------------DEEKQTLLHYV---------------
E2AAK6_CAMFO|Camponotus           SI----EKLPLL------------------------AQKDNFQYV---------------
K7J8F5_NASVI|Nasonia              S----VEKLPLLSQK------------------------DNYQYV---------------
G6DPC9_DANPL|Danaus               T---------------------------------EPMLPRDTHYV---------------
B4J3N8_DROGR|Drosophila           QVHQTIEKEPLLRVD----------------CADADGLAGDHQYV---------------
B4KYH8_DROMO|Drosophila           QVHQTIEKEPLLRAE----------------GADADGLIGDHQYV---------------
B4LDZ7_DROVI|Drosophila           QVHQTIEKEPLLRTD----------------CADADGLAGDHQYV---------------
B4N727_DROWI|Drosophila           QVHQTIEKEPLLRID----------------S--AAGAADDHQYV---------------
B4H7T3_DROPE|Drosophila           HVHQTIEKEPLLSVD----------------C--PDGMGGDHQYV---------------
Q29D93_DROPS|Drosophila           HVHQTIEKEPLLSVD----------------C--PDGMGGDHQYV---------------
B3M9T9_DROAN|Drosophila           QTHQTIEKEPLLSVD----------------C--PDGMGGDHQYV---------------
Q9VUW9_DROME|Drosophila           QTHQTIEKEPLLSVD----------------C--PDGMAGDHQYV---------------
B3NDQ1_DROER|Drosophila           QTHQTIEKEPLLSVD----------------C--PDGMAGDHQYV---------------
B4ITV5_DROYA|Drosophila           QTHQTIEKEPLLSVD----------------C--PDGMAGDHQYV---------------
B0W2T5_CULQU|Culex                S----VEHEPLLRPDNFQYAQGKAGESMPAAGGRDEAAGGAGDAANRGEEQADLRTVTTT
Q7PZ51_ANOGA|Anopheles            H----VEHEPLLRPD----------------N---------FQYV---------------
A7RWD7_NEMVE|Nematostella         ---------------------------------------AHERWA---------------
C3ZCK2_BRAFL|Branchiostoma        P---------------------------------AK---TLGRA----------------
H0W5P5_CAVPO|Cavia                V---------------------------------EEG--GSSQDI---------------
G5ASE1_HETGA|Heterocephalus       E---------------------------------AEG--GSSQDV---------------
ZDH12_MOUSE|Mus                   E---------------------------------EE---GSSQVV---------------
ZDH12_RAT|Rattus                  E---------------------------------EE---GSSQVV---------------
H0XYF8_OTOGA|Otolemur             E---------------------------------EE---SSSQVV---------------
G3U2Z9_LOXAF|Loxodonta            E---------------------------------ED---SS-------------------
I3MFR4_SPETR|Spermophilus         E---------------------------------VEE--GNSQAV---------------
G1PPR6_MYOLU|Myotis               E---------------------------------EEEGEGSSQAV---------------
L5K9R0_PTEAL|Pteropus             E---------------------------------EE---SSSQAA---------------
E2RQ98_CANFA|Canis                E---------------------------------EEEEGGSQAV----------------
G1MB86_AILME|Ailuropoda           E---------------------------------DEEEEGRSQAV---------------
G9KYS3_MUSPF|Mustela              E---------------------------------EEEEEGRSQA----------------
F6RCU4_HORSE|Equus                E---------------------------------EEEEEGSSQAV---------------
F6XST1_CALJA|Callithrix           E---------------------------------EE---GSSPAV---------------
G1S775_NOMLE|Nomascus             E---------------------------------EE---GSSPAV---------------
K7DHV8_PANTR|Pan                  E---------------------------------EE---GSSPAV---------------
G7PRE9_MACFA|Macaca               E---------------------------------EE---GSSPTV---------------
I0FVS9_MACMU|Macaca               E---------------------------------EE---GSSPAV---------------
ZDH12_HUMAN|Homo                  E---------------------------------EE---GSSPAV---------------
G3R6W9_GORGO|Gorilla              E---------------------------------EE---GSSPAV---------------
K7ETB9_PONAB|Pongo                E---------------------------------EE---GSSPAV---------------
E1B6X9_BOVIN|Bos                  E---------------------------------EEE--GSSQAV---------------
F1RR67_PIG|Sus                    E---------------------------------EEERDGSSQAV---------------
F7G3P7_ORNAN|Ornithorhynchus      ---------------------------------------GE-------------------
F6TT20_MONDO|Monodelphis          K----------------------------------------GEAV---------------
G3X3J6_SARHA|Sarcophilus          E---------------------------------EGE--GDSRRQ---------------
H2SLY9_TAKRU|Takifugu             --------------------------------------RKSTSSI---------------
H2MTW9_ORYLA|Oryzias              --------------------------------------RSTADPV---------------
G3PPJ8_GASAC|Gasterosteus         ------------------------------------------------------------
H3C8P8_TETNG|Tetraodon            ---------------------------------------GSDQLV---------------
E7F021_DANRE|Danio                ---------------------------------------GNDPI----------------
I3JZC4_ORENI|Oreochromis          ---------------------------------------GSDQV----------------
Q28DG2_XENTR|Xenopus              --------------------------------------RGTYNIV---------------
H3B581_LATCH|Latimeria            N-----------------------------------------NPV---------------
K7GJG6_PELSI|Pelodiscus           --------------------------------------QEDSGPV---------------
H0Z129_TAEGU|Taeniopygia          ------------------------------------------------------------
F1NH43_CHICK|Gallus               --------------------------------------HRNNEPV---------------
G1MZA7_MELGA|Meleagris            --------------------------------------HRNNEPV---------------
                                                                                              

L7M222_9ACAR|Rhipicephalus        ------------------------------------------------------------
E2AAK6_CAMFO|Camponotus           ------------------------------------------------------------
K7J8F5_NASVI|Nasonia              ------------------------------------------------------------
G6DPC9_DANPL|Danaus               ------------------------------------------------------------
B4J3N8_DROGR|Drosophila           ------------------------------------------------------------
B4KYH8_DROMO|Drosophila           ------------------------------------------------------------
B4LDZ7_DROVI|Drosophila           ------------------------------------------------------------
B4N727_DROWI|Drosophila           ------------------------------------------------------------
B4H7T3_DROPE|Drosophila           ------------------------------------------------------------
Q29D93_DROPS|Drosophila           ------------------------------------------------------------
B3M9T9_DROAN|Drosophila           ------------------------------------------------------------
Q9VUW9_DROME|Drosophila           ------------------------------------------------------------
B3NDQ1_DROER|Drosophila           ------------------------------------------------------------
B4ITV5_DROYA|Drosophila           ------------------------------------------------------------
B0W2T5_CULQU|Culex                TTTTVDVLVRAQKPNKAGAKQNRVNRTVGSLPFSVYEKQKKPKSYDILHVEGNIGRQAQC
Q7PZ51_ANOGA|Anopheles            ------------------------------------------------------------
A7RWD7_NEMVE|Nematostella         ------------------------------------------------------------
C3ZCK2_BRAFL|Branchiostoma        ------------------------------------------------------------
H0W5P5_CAVPO|Cavia                ------------------------------------------------------------
G5ASE1_HETGA|Heterocephalus       ------------------------------------------------------------
ZDH12_MOUSE|Mus                   ------------------------------------------------------------
ZDH12_RAT|Rattus                  ------------------------------------------------------------
H0XYF8_OTOGA|Otolemur             ------------------------------------------------------------
G3U2Z9_LOXAF|Loxodonta            ------------------------------------------------------------
I3MFR4_SPETR|Spermophilus         ------------------------------------------------------------
G1PPR6_MYOLU|Myotis               ------------------------------------------------------------
L5K9R0_PTEAL|Pteropus             ------------------------------------------------------------
E2RQ98_CANFA|Canis                ------------------------------------------------------------
G1MB86_AILME|Ailuropoda           ------------------------------------------------------------
G9KYS3_MUSPF|Mustela              ------------------------------------------------------------
F6RCU4_HORSE|Equus                ------------------------------------------------------------
F6XST1_CALJA|Callithrix           ------------------------------------------------------------
G1S775_NOMLE|Nomascus             ------------------------------------------------------------
K7DHV8_PANTR|Pan                  ------------------------------------------------------------
G7PRE9_MACFA|Macaca               ------------------------------------------------------------
I0FVS9_MACMU|Macaca               ------------------------------------------------------------
ZDH12_HUMAN|Homo                  ------------------------------------------------------------
G3R6W9_GORGO|Gorilla              ------------------------------------------------------------
K7ETB9_PONAB|Pongo                ------------------------------------------------------------
E1B6X9_BOVIN|Bos                  ------------------------------------------------------------
F1RR67_PIG|Sus                    ------------------------------------------------------------
F7G3P7_ORNAN|Ornithorhynchus      ------------------------------------------------------------
F6TT20_MONDO|Monodelphis          ------------------------------------------------------------
G3X3J6_SARHA|Sarcophilus          ------------------------------------------------------------
H2SLY9_TAKRU|Takifugu             ------------------------------------------------------------
H2MTW9_ORYLA|Oryzias              ------------------------------------------------------------
G3PPJ8_GASAC|Gasterosteus         ------------------------------------------------------------
H3C8P8_TETNG|Tetraodon            ------------------------------------------------------------
E7F021_DANRE|Danio                ------------------------------------------------------------
I3JZC4_ORENI|Oreochromis          ------------------------------------------------------------
Q28DG2_XENTR|Xenopus              ------------------------------------------------------------
H3B581_LATCH|Latimeria            ------------------------------------------------------------
K7GJG6_PELSI|Pelodiscus           ------------------------------------------------------------
H0Z129_TAEGU|Taeniopygia          ------------------------------------------------------------
F1NH43_CHICK|Gallus               ------------------------------------------------------------
G1MZA7_MELGA|Meleagris            ------------------------------------------------------------
                                                                                              

L7M222_9ACAR|Rhipicephalus        -----------------------------------------------------
E2AAK6_CAMFO|Camponotus           -----------------------------------------------------
K7J8F5_NASVI|Nasonia              -----------------------------------------------------
G6DPC9_DANPL|Danaus               -----------------------------------------------------
B4J3N8_DROGR|Drosophila           -----------------------------------------------------
B4KYH8_DROMO|Drosophila           -----------------------------------------------------
B4LDZ7_DROVI|Drosophila           -----------------------------------------------------
B4N727_DROWI|Drosophila           -----------------------------------------------------
B4H7T3_DROPE|Drosophila           -----------------------------------------------------
Q29D93_DROPS|Drosophila           -----------------------------------------------------
B3M9T9_DROAN|Drosophila           -----------------------------------------------------
Q9VUW9_DROME|Drosophila           -----------------------------------------------------
B3NDQ1_DROER|Drosophila           -----------------------------------------------------
B4ITV5_DROYA|Drosophila           -----------------------------------------------------
B0W2T5_CULQU|Culex                SHEPKPSARLGSFFWFRFTPHVGKHRRLRLTECREPWFIWFKPGEASQNESLA
Q7PZ51_ANOGA|Anopheles            -----------------------------------------------------
A7RWD7_NEMVE|Nematostella         -----------------------------------------------------
C3ZCK2_BRAFL|Branchiostoma        -----------------------------------------------------
H0W5P5_CAVPO|Cavia                -----------------------------------------------------
G5ASE1_HETGA|Heterocephalus       -----------------------------------------------------
ZDH12_MOUSE|Mus                   -----------------------------------------------------
ZDH12_RAT|Rattus                  -----------------------------------------------------
H0XYF8_OTOGA|Otolemur             -----------------------------------------------------
G3U2Z9_LOXAF|Loxodonta            -----------------------------------------------------
I3MFR4_SPETR|Spermophilus         -----------------------------------------------------
G1PPR6_MYOLU|Myotis               -----------------------------------------------------
L5K9R0_PTEAL|Pteropus             -----------------------------------------------------
E2RQ98_CANFA|Canis                -----------------------------------------------------
G1MB86_AILME|Ailuropoda           -----------------------------------------------------
G9KYS3_MUSPF|Mustela              -----------------------------------------------------
F6RCU4_HORSE|Equus                -----------------------------------------------------
F6XST1_CALJA|Callithrix           -----------------------------------------------------
G1S775_NOMLE|Nomascus             -----------------------------------------------------
K7DHV8_PANTR|Pan                  -----------------------------------------------------
G7PRE9_MACFA|Macaca               -----------------------------------------------------
I0FVS9_MACMU|Macaca               -----------------------------------------------------
ZDH12_HUMAN|Homo                  -----------------------------------------------------
G3R6W9_GORGO|Gorilla              -----------------------------------------------------
K7ETB9_PONAB|Pongo                -----------------------------------------------------
E1B6X9_BOVIN|Bos                  -----------------------------------------------------
F1RR67_PIG|Sus                    -----------------------------------------------------
F7G3P7_ORNAN|Ornithorhynchus      -----------------------------------------------------
F6TT20_MONDO|Monodelphis          -----------------------------------------------------
G3X3J6_SARHA|Sarcophilus          -----------------------------------------------------
H2SLY9_TAKRU|Takifugu             -----------------------------------------------------
H2MTW9_ORYLA|Oryzias              -----------------------------------------------------
G3PPJ8_GASAC|Gasterosteus         -----------------------------------------------------
H3C8P8_TETNG|Tetraodon            -----------------------------------------------------
E7F021_DANRE|Danio                -----------------------------------------------------
I3JZC4_ORENI|Oreochromis          -----------------------------------------------------
Q28DG2_XENTR|Xenopus              -----------------------------------------------------
H3B581_LATCH|Latimeria            -----------------------------------------------------
K7GJG6_PELSI|Pelodiscus           -----------------------------------------------------
H0Z129_TAEGU|Taeniopygia          -----------------------------------------------------
F1NH43_CHICK|Gallus               -----------------------------------------------------
G1MZA7_MELGA|Meleagris            -----------------------------------------------------
                                                                                       
