MUSCLE (3.8) multiple sequence alignment


B4GIR9_DROPE|Drosophila           -------------------------------MISNRSQSIPISTVPAVTQLAIECLTEDR
B5E105_DROPS|Drosophila           -------------------------------MISNRSQSIPIDTVPVVTQLAIECLTEDR
B4JHI4_DROGR|Drosophila           ----------MARIKWRLGANQNIFSTFRLRWSYMKHCWHSLTINSHMN-----------
B4K9M3_DROMO|Drosophila           ----------MARITWRTSSTQNLVSKFRLRWSYMKHCWHSLTFNAHMN-----------
B4M137_DROVI|Drosophila           ----------MVRITWRTNSTQSLVSTFRLRWSYMNHCWHSLTFNAHMN-----------
C3Z5I5_BRAFL|Branchiostoma        -----------------MHRITMDMDISDMHWKIKGTSKFTRKGASILG-----------
G9KYT5_MUSPF|Mustela              ---------------------------MGQPWAVGTGEGAPARLPLVLT-----------
G6DDL9_DANPL|Danaus               ------------------------------------------------------------
F7DR35_XENTR|Xenopus              ------------------------------------------------------------
F6SE12_ORNAN|Ornithorhynchus      PGGGGQGGLGPVGLRARPRRDRPGGGAERTAEERGGGCALNHSIVSTAP-----------
G1KTK1_ANOCA|Anolis               --------------------------------------MLVLRFLNVVA-----------
H0ZPV6_TAEGU|Taeniopygia          --------------------------------------MLVLRLLNVVA-----------
K7GJD6_PELSI|Pelodiscus           --------------------------------------MLVLRVLNVVA-----------
E1C5D7_CHICK|Gallus               --------------------------------------MLVLRLLNVVA-----------
G1NJK6_MELGA|Meleagris            --------------------------------------MLVLRLLNVVA-----------
F7G5M0_MONDO|Monodelphis          --------------------------------------MLILRLLNVVA-----------
G3W6V0_SARHA|Sarcophilus          --------------------------------------MLILRLLNVVA-----------
ZDH22_MOUSE|Mus                   --------------------------------------MLALRLLNVVA-----------
ZDH22_RAT|Rattus                  --------------------------------------MLALRLLNVVA-----------
G1SNL9_RABIT|Oryctolagus          --------------------------------------MLALRLLNVVA-----------
G1MJ71_AILME|Ailuropoda           --------------------------------------MLALRLLNVVA-----------
J9NZC5_CANFA|Canis                --------------------------------------MLALRLLNVVA-----------
G5B683_HETGA|Heterocephalus       --------------------------------------MLALRLLNVVA-----------
H0W7M0_CAVPO|Cavia                --------------------------------------MLALRLLNVVA-----------
E1B987_BOVIN|Bos                  --------------------------------------MLALRLLNVVA-----------
G3UIR0_LOXAF|Loxodonta            --------------------------------------MLALRLLNVVA-----------
H0XYR4_OTOGA|Otolemur             --------------------------------------MLALRLLNVVA-----------
F6Y2X5_CALJA|Callithrix           --------------------------------------MLALRLLNVVA-----------
G7PB25_MACFA|Macaca               --------------------------------------MLALRLLNVVA-----------
G7MYW0_MACMU|Macaca               --------------------------------------MLALRLLNVVA-----------
H2RG61_PANTR|Pan                  --------------------------------------MLALRLLNVVA-----------
G1S3X2_NOMLE|Nomascus             --------------------------------------MLALRLLNVVA-----------
ZDH22_HUMAN|Homo                  --------------------------------------MLALRLLNVVA-----------
H2NLW0_PONAB|Pongo                --------------------------------------MLALRLLNVVA-----------
G3R3R5_GORGO|Gorilla              --------------------------------------MLALRLLNVVA-----------
G1PX45_MYOLU|Myotis               --------------------------------------MLALRLLNVVA-----------
F1S2N2_PIG|Sus                    --------------------------------------MLALRLLNVVA-----------
I3LX43_SPETR|Spermophilus         --------------------------------------MLALRLLNVVA-----------
L5JNU0_PTEAL|Pteropus             --------------------------------------MLALRLLNVVA-----------
F6SFZ8_HORSE|Equus                --------------------------------------MLALRLLNVVA-----------
H3AW31_LATCH|Latimeria            ----------------------------------MLPKMFKLRLLNFIA-----------
E7EY29_DANRE|Danio                ----------------------------------MLFKMGKLKLLNTIA-----------
H2VBD4_TAKRU|Takifugu             --------------------------------------MLKLRLLNVVA-----------
H3DJ29_TETNG|Tetraodon            --------------------------------------MLKLRLLNVVA-----------
H2MNL7_ORYLA|Oryzias              ----------------------------------MFTRMLKLRLLNAVA-----------
G3NYI0_GASAC|Gasterosteus         --------------------------------------MLKLRLLNAVA-----------
I3KWA6_ORENI|Oreochromis          --------------------------------MF--TRMLKLRLLNAVA-----------
B4NJC4_DROWI|Drosophila           ---------------------------------MKNHGDGIVHIFHVIS-----------
Q9I7L7_DROME|Drosophila           ------------------------------MRFRSLKNIWPKEKLEQFL-----------
B3MEE9_DROAN|Drosophila           ------------------------------MRIR--RNPLPRRLVDILC-----------
B4P7Y0_DROYA|Drosophila           ------------------------------MRIR--SNPLPRRLVDTTC-----------
Q7PVS0_ANOGA|Anopheles            -------------------------------TMRIRKHVLPRTLQDAVA-----------
B0WDA3_CULQU|Culex                --------------------------------MKIRKRFLPRCVQDGVA-----------
E2AAM9_CAMFO|Camponotus           --------------------------------MIIRKKIWPRTIGDLLS-----------
K7IP65_NASVI|Nasonia              ------------------------------MLIR--RKILPRTASDILS-----------
L7M074_9ACAR|Rhipicephalus        --------------------------------MAARKSIIPGGYRDRVL-----------
A7SWQ7_NEMVE|Nematostella         ----------------------MFSQDPQYEKLSLAKRVIPKKGSDAAA-----------
                                                                                              

B4GIR9_DROPE|Drosophila           GDDRRQRRTCCGCLESIFNWMPVIF--IVGLIVYSYYVYVWHLCLQNMRNHSAIVLGVV-
B5E105_DROPS|Drosophila           GDDRRQRRTCCGCLESIFNWIPVIF--IVCLIVYSYYVYVWHLCLQNMRNHSAIVLGVV-
B4JHI4_DROGR|Drosophila           ---------------------SSYAIDV-CMTPIFWIVDNYTHCLGPFFVVGVAVLTTVV
B4K9M3_DROMO|Drosophila           ---------------------SSYATDV-CMTPIFWIVDNYTHCLGPFFVVGTAILTTAV
B4M137_DROVI|Drosophila           ---------------------SSYATDV-CMTPIFWVVDNYTHCLGPFFVVGVAILTTAV
C3Z5I5_BRAFL|Branchiostoma        ---------------------VIYF--F-LFAGTIMWTTV-VHALPSLYPE----STEG-
G9KYT5_MUSPF|Mustela              ---------------------ALWA--A------AVGLELAYVLILGPGP-----PPLG-
G6DDL9_DANPL|Danaus               ------------------------------------------------------------
F7DR35_XENTR|Xenopus              ------------------------------------------------------------
F6SE12_ORNAN|Ornithorhynchus      ---------------------SAYS--VRSAALSAWNGQVGNRWRPSLPNNGLTVPSAA-
G1KTK1_ANOCA|Anolis               ---------------------PAYF--L-CISIVTFGLQL-FLFIPSMFQD----PSAN-
H0ZPV6_TAEGU|Taeniopygia          ---------------------PAYF--L-CISLVTFVLQI-FVFIPSMFRD----PSTT-
K7GJD6_PELSI|Pelodiscus           ---------------------PTYF--L-CISLVTFVLQL-FLFIPSMFKD----PSTT-
E1C5D7_CHICK|Gallus               ---------------------PAYF--L-CISLVTFVLQI-FLFIPSMFRD----PSTT-
G1NJK6_MELGA|Meleagris            ---------------------PAYF--L-CISLVTFVLQI-FLFIPSMFRD----PSTT-
F7G5M0_MONDO|Monodelphis          ---------------------PVYF--L-CISLVTFILQL-FLFLPNMFKD----PTIT-
G3W6V0_SARHA|Sarcophilus          ---------------------PVYF--L-CISLVTFILQL-FLFLPNMFKD----PTIT-
ZDH22_MOUSE|Mus                   ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PTAT-
ZDH22_RAT|Rattus                  ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PTAT-
G1SNL9_RABIT|Oryctolagus          ---------------------PAYF--L-CLSLVTFALQL-FLFLPSMRED----PAAA-
G1MJ71_AILME|Ailuropoda           ---------------------PAYF--L-CISLVTFALQL-FLFLPSMRQD----PAAT-
J9NZC5_CANFA|Canis                ---------------------PAYF--L-CISLVTLALQL-FLFLPSMRQD----PAAA-
G5B683_HETGA|Heterocephalus       ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAT-
H0W7M0_CAVPO|Cavia                ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAT-
E1B987_BOVIN|Bos                  ---------------------PAYF--L-CIALVTLVLQL-FLFLPRMRED----PTAA-
G3UIR0_LOXAF|Loxodonta            ---------------------PAYF--L-CIALVTFVLQL-FLFLPSMRED----PAAA-
H0XYR4_OTOGA|Otolemur             ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
F6Y2X5_CALJA|Callithrix           ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
G7PB25_MACFA|Macaca               ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
G7MYW0_MACMU|Macaca               ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
H2RG61_PANTR|Pan                  ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
G1S3X2_NOMLE|Nomascus             ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
ZDH22_HUMAN|Homo                  ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
H2NLW0_PONAB|Pongo                ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
G3R3R5_GORGO|Gorilla              ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
G1PX45_MYOLU|Myotis               ---------------------PAYF--L-CISLVTFALQL-FLFLPSMRED----PAA--
F1S2N2_PIG|Sus                    ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRQD----PAAA-
I3LX43_SPETR|Spermophilus         ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
L5JNU0_PTEAL|Pteropus             ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
F6SFZ8_HORSE|Equus                ---------------------PAYF--L-CISLVTFVLQL-FLFLPSMRED----PAAA-
H3AW31_LATCH|Latimeria            ---------------------STYF--L-SASVVTFALQL-FVFIPTVFGS----PSI--
E7EY29_DANRE|Danio                ---------------------PAYF--Y-AATVVTFALHF-LLFTPTIFQS----SDVT-
H2VBD4_TAKRU|Takifugu             ---------------------PVYF--F-TATAVTFVFHF-CFFVPTIFPV----PDA--
H3DJ29_TETNG|Tetraodon            ---------------------PVYF--F-TATAVTFVFHF-CFFLPTIFPV----PDA--
H2MNL7_ORYLA|Oryzias              ---------------------PVYF--F-MATAVTNILHF-FFFIPTIFPY----PET--
G3NYI0_GASAC|Gasterosteus         ---------------------PAYF--F-VATAVTFILHF-CFFIPTIFSN----PHA--
I3KWA6_ORENI|Oreochromis          ---------------------PAYF--F-TATAVTFILHF-GFFIPTIFPS----QGT--
B4NJC4_DROWI|Drosophila           ---------------------FSLL--M-GITLFFFIYEV-WFILPILCDT---------
Q9I7L7_DROME|Drosophila           ---------------------FLFI--L-CGLPAIYYVLM-EIILPELSDY---------
B3MEE9_DROAN|Drosophila           ---------------------FLLI--G-IFLPVVFMFEI-VVVLPNFHD-----PGSF-
B4P7Y0_DROYA|Drosophila           ---------------------FLII--G-IFLPVVFMFEI-VVVLPAFHE-----PGGF-
Q7PVS0_ANOGA|Anopheles            ---------------------TAFM--A-GIIPITFWFEV-YVVIPGIHG-----PDSV-
B0WDA3_CULQU|Culex                ---------------------TLFM--I-GIIPVTFWFEV-SVVIPGIHG-----TNSG-
E2AAM9_CAMFO|Camponotus           ---------------------MIFV--L-VIVPLMYWFGL-WIVLPALYKD---------
K7IP65_NASVI|Nasonia              ---------------------TTFL--L-IIVPLLYWFEL-WVVLPNLYE-----PGSA-
L7M074_9ACAR|Rhipicephalus        ---------------------FLLM--M-CGIPVIVFFDF-CFVAPRYHDT----FDK--
A7SWQ7_NEMVE|Nematostella         ---------------------FVFM--F-VMLWVISLFEL-LVVLPIYHE----------
                                                                                              

B4GIR9_DROPE|Drosophila           ---------LFWY-------HLLLLMFLWS-----------YWSSMWAKVMPIP----AE
B5E105_DROPS|Drosophila           ---------LFWY-------HLLLLMFLWS-----------YWSSMWAKVMPIP----AE
B4JHI4_DROGR|Drosophila           VSIAYWIGLPFWWAKSQ---LATILLLIFG------NWVLLNIIFHYVMAVITP----PG
B4K9M3_DROMO|Drosophila           VSIAYWIGLPFWWAKSQ---AATIVLLIIG------NWLLLNIIFHYVMGVITPAGQPPE
B4M137_DROVI|Drosophila           VGIAYWIGLPFWWAKSQ---VATILLLIVG------NWLLLNIIFHYVMAVITPAGQPPE
C3Z5I5_BRAFL|Branchiostoma        --------------GKI---HYFLIVFLWG-----------NMLANYCLCCTTK----SF
G9KYT5_MUSPF|Mustela              ---------PLARALQL-----VLAAFQLL-----------NLLGNVGLFLRSD----PS
G6DDL9_DANPL|Danaus               -----------------------------------------MILGIFTDTTIKM----RA
F7DR35_XENTR|Xenopus              ----------------------SLFVVLLV-----------NVLGNYILTIWKS----PH
F6SE12_ORNAN|Ornithorhynchus      ---------PAPSPTPAGTDQGDLKVIRRALRPASRREGRSAGSGSSAPTLSHP----PD
G1KTK1_ANOCA|Anolis               ---------PLFSSALL---HGVLFLFLSA-----------NALGNYILVIQNT----PE
H0ZPV6_TAEGU|Taeniopygia          ---------SLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PE
K7GJD6_PELSI|Pelodiscus           ---------PLFSPALL---HGALFLFLSA-----------NALGNYILVIQSS----PE
E1C5D7_CHICK|Gallus               ---------PLFSPALL---HGALFLFLSA-----------NALGNYILVIQSS----PE
G1NJK6_MELGA|Meleagris            ---------PLFSPALL---HGALFLFLSA-----------NALGNYILVIQSS----PE
F7G5M0_MONDO|Monodelphis          ---------PLFSPALL---HGALFLFLSA-----------NALGNYILVIQNS----PE
G3W6V0_SARHA|Sarcophilus          ---------PLFSPALL---HGALFLFLSA-----------NALGNYILVIQNS----PE
ZDH22_MOUSE|Mus                   ---------PLFSPAVL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
ZDH22_RAT|Rattus                  ---------PLFSPAVL---HGALFLFLSA-----------NALGNYILVVQNS----PD
G1SNL9_RABIT|Oryctolagus          ---------PLFPPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
G1MJ71_AILME|Ailuropoda           ---------RLFPPALL---HGALFLFLST-----------NALGNYVLVIQNS----PD
J9NZC5_CANFA|Canis                ---------RLFPPALL---HGALFLFLST-----------NALGNYVLVIQNS----PE
G5B683_HETGA|Heterocephalus       ---------PLLSPALL---HGALFLFLSA-----------NALGNYVLVVQNS----PD
H0W7M0_CAVPO|Cavia                ---------RLLSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
E1B987_BOVIN|Bos                  ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
G3UIR0_LOXAF|Loxodonta            ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
H0XYR4_OTOGA|Otolemur             ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
F6Y2X5_CALJA|Callithrix           ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
G7PB25_MACFA|Macaca               ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
G7MYW0_MACMU|Macaca               ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
H2RG61_PANTR|Pan                  ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
G1S3X2_NOMLE|Nomascus             ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
ZDH22_HUMAN|Homo                  ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
H2NLW0_PONAB|Pongo                ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
G3R3R5_GORGO|Gorilla              ---------RLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
G1PX45_MYOLU|Myotis               ---------RLCSPALL---HGALFLFLST-----------NALGNYVLVIQNS----PD
F1S2N2_PIG|Sus                    ---------RIFSPALL---HGALFLFLST-----------NALGNYVLVIQNS----PD
I3LX43_SPETR|Spermophilus         ---------PLFSPALL---HGALFLFLSA-----------NALGNYVLVIQNS----PD
L5JNU0_PTEAL|Pteropus             ---------PLFSPALL---HGALFLFLST-----------NALGNYVLVIQNS----PD
F6SFZ8_HORSE|Equus                ---------PLFSPALL---HGALFLFLST-----------NALGNYVLVIQNS----PD
H3AW31_LATCH|Latimeria            ---------RLSPSVLL---HWGLFLSLSA-----------NVLGNYALIILNP----SE
E7EY29_DANRE|Danio                -----------INPAMLA--HISIFLFLMG-----------NALGNYIMTIRNP----SE
H2VBD4_TAKRU|Takifugu             ---------PLWASTTL---HTALFLFSMF-----------NALGNYIMTIRYP----AA
H3DJ29_TETNG|Tetraodon            ---------SLWASTSL---HTALFLFSMF-----------NALGNYIMTIRYP----AA
H2MNL7_ORYLA|Oryzias              ---------SLMVSSTL---HTVLVLFLMF-----------NALGNYIMTIIYP----AE
G3NYI0_GASAC|Gasterosteus         ---------SLSSSTAL---HTLVFLFLMF-----------NALGNYIMTIKYP----AE
I3KWA6_ORENI|Oreochromis          ---------SLEGSKVL---HTVIFLFLMF-----------NALGNYIMTIKYP----AE
B4NJC4_DROWI|Drosophila           ---------RSWSYTF----NCMLCIYTLH-----------NIIGNFLMCWLTD----NS
Q9I7L7_DROME|Drosophila           -----------WSPGYVF--QLLLGLFLFS-----------NVMSNYVMCILVD----PS
B3MEE9_DROAN|Drosophila           ---------FHTL-------HFLMAMFLVF-----------NIKSNMIACMMID----TS
B4P7Y0_DROYA|Drosophila           ---------FHTF-------TFLMAMFLVF-----------NIKGNMIACIMID----SS
Q7PVS0_ANOGA|Anopheles            ---------YNWV-------HFVPAVLLLF-----------NVTAHMLATMLCD----TS
B0WDA3_CULQU|Culex                ---------WNWI-------HLVPALFLLY-----------NISTNMLATILCD----TS
E2AAM9_CAMFO|Camponotus           ----------DILPYTL---HFVLGNFIMF-----------NIVGNFTYTVLCD----TS
K7IP65_NASVI|Nasonia              ---------MYIF-------HFCLGSFIMI-----------NIVGNFTYTVLSD----TS
L7M074_9ACAR|Rhipicephalus        ---------FMWV-------HSASAAFILF-----------NIYANLFKLLLTD----TS
A7SWQ7_NEMVE|Nematostella         ---------FLSTWYLI---HVFCGLFMFL-----------NVFANLYKVITTD------
                                                                                              

B4GIR9_DROPE|Drosophila           WSIPDADWTRLIRANGLEERRHILSHVARRLPITMCDQNGVVRYCGQCR--LIKPDR---
B5E105_DROPS|Drosophila           WSIPDADWTRLIRANGLEERRHILSHVARRLPITMCDQNGVVRYCGQCR--LIKPDR---
B4JHI4_DROGR|Drosophila           ---------------HPPEGVSQVEAVS---------------MCSKCI--TPKPPR---
B4K9M3_DROMO|Drosophila           ---------------GISHVEAVS-------------------MCSKCI--SPKPPR---
B4M137_DROVI|Drosophila           ---------------GVSHVEAVS-------------------MCTKCI--SPKPPR---
C3Z5I5_BRAFL|Branchiostoma        ---------------YKDHEPKHVP--------------EHWNYCLPCG--KHLPPR---
G9KYT5_MUSPF|Mustela              ---------------IRGVMLAGRGL------------GQGWAYCYQCQ--SQVPPR---
G6DDL9_DANPL|Danaus               ---------------RSHNCEE---------------------FCESCQ--MYRPAK---
F7DR35_XENTR|Xenopus              ---------------GNAMYAETE------------------------------LSG---
F6SE12_ORNAN|Ornithorhynchus      ---------------PQNFLPE---------------------HRARPP-----PPQKKL
G1KTK1_ANOCA|Anolis               ---------------DLRAQEDLGL------------------TKLVAPESEEVLPG---
H0ZPV6_TAEGU|Taeniopygia          ---------------DLGKDLNLGK----------GAEVADWLDGSRSP--GSALPG---
K7GJD6_PELSI|Pelodiscus           ---------------DLGKCLNSGGGAEAVAARP---------DGSRSP--GSALPS---
E1C5D7_CHICK|Gallus               ---------------ELGKGLNLGE---------GAEMVADWLDGSRSP--GSALPS---
G1NJK6_MELGA|Meleagris            ---------------ELGKGLNLGEGAEM---------MADWLDGSRSP--GSALPS---
F7G5M0_MONDO|Monodelphis          ---------------DMGTCKNAGA------------------RGVGTP--SEWPEAGRK
G3W6V0_SARHA|Sarcophilus          ---------------DLGTRKNVGT------------------KGAGSP--SEWPES---
ZDH22_MOUSE|Mus                   ---------------DLGTCQGTMS------------------QRPQCP-----PPS---
ZDH22_RAT|Rattus                  ---------------DLGACQGTSS------------------QRPQRP-----PPS---
G1SNL9_RABIT|Oryctolagus          ---------------DLGACQGTPA------------------RRAPCP-----PPS---
G1MJ71_AILME|Ailuropoda           ---------------DLDACQGPSA------------------RRAPCP-----PPS---
J9NZC5_CANFA|Canis                ---------------DLDACQGPPA------------------RRAPCP-----PPS---
G5B683_HETGA|Heterocephalus       ---------------DLGAYQGSSA------------------RRAQCP-----TPS---
H0W7M0_CAVPO|Cavia                ---------------DLGACQGSSA------------------RRALCP-----PPS---
E1B987_BOVIN|Bos                  ---------------DLDACQGAEA------------------RRALCP-----PPS---
G3UIR0_LOXAF|Loxodonta            ---------------DLGACQGTSA------------------RRAACP-----PPS---
H0XYR4_OTOGA|Otolemur             ---------------DLGACQGTSA------------------RRASCP-----SPS---
F6Y2X5_CALJA|Callithrix           ---------------DLGACQGASA------------------TKAPCP-----SPS---
G7PB25_MACFA|Macaca               ---------------DLGACQGAST------------------RKVPCP-----SPS---
G7MYW0_MACMU|Macaca               ---------------DLGACQGAST------------------RKVPCP-----SPS---
H2RG61_PANTR|Pan                  ---------------DLGACQGASA------------------RKTPCP-----SPS---
G1S3X2_NOMLE|Nomascus             ---------------DLGACQGASA------------------RKTPCP-----SPS---
ZDH22_HUMAN|Homo                  ---------------DLGACQGASA------------------RKTPCP-----SPS---
H2NLW0_PONAB|Pongo                ---------------DLGACQGASA------------------RKTPCP-----SPS---
G3R3R5_GORGO|Gorilla              ---------------DLGACQGASA------------------RKTPCP-----SPS---
G1PX45_MYOLU|Myotis               ---------------DLDACQGASA------------------RKALCP-----PPS---
F1S2N2_PIG|Sus                    ---------------DLDACQGAAA------------------RRAPCP-----PPS---
I3LX43_SPETR|Spermophilus         ---------------DLDACQGTSS------------------KRALCP-----PPS---
L5JNU0_PTEAL|Pteropus             ---------------DMDACQGTSA------------------RKALCP-----PPS---
F6SFZ8_HORSE|Equus                ---------------DLDACQGASA------------------KRAPCP-----PPS---
H3AW31_LATCH|Latimeria            ---------------CLRNAMGP--------------------HQAGDSADALPVPG---
E7EY29_DANRE|Danio                ---------------SANETVIPVCSP----------------DCPDRIDAHYLLNG---
H2VBD4_TAKRU|Takifugu             ---------------SAGDSTVPVCSP----------------HCSDKVDAHYLLND---
H3DJ29_TETNG|Tetraodon            ---------------SAGDSAVPVCSP----------------HCSDKVDAHYLLND---
H2MNL7_ORYLA|Oryzias              ---------------SANETLIPVCSP----------------HCSDKVDAHYLLNG---
G3NYI0_GASAC|Gasterosteus         ---------------SANETVVPVCSA----------------HCSDKVDAHYLLNG---
I3KWA6_ORENI|Oreochromis          ---------------SANETVIPVCSP----------------HCSDKVDAHYLLNG---
B4NJC4_DROWI|Drosophila           -------------MKSLPNYRQHPP----------PTEARFWHLCTQCQ--MMVPPR---
Q9I7L7_DROME|Drosophila           ---------------IDPKLMKNQLVRGQH--------SEDWHECDKCG--ILAPPR---
B3MEE9_DROAN|Drosophila           ---------------CDVKKIEPPED------------HSDWRECDICQ--KLAPPR---
B4P7Y0_DROYA|Drosophila           ---------------VDVKKIDPPGD------------QENWRECGECQ--KLAPPR---
Q7PVS0_ANOGA|Anopheles            ---------------CSTELIQLPPAGVSTAGAGTGLSSKSWHLCATCE--FIAPPR---
B0WDA3_CULQU|Culex                ---------------CGTEVISVPPDVAVASGQG----SRSWHLCSTCE--AVAPPR---
E2AAM9_CAMFO|Camponotus           ---------------TKRRIVPVSTATV----------ADGWRLCATCE--CLSPPR---
K7IP65_NASVI|Nasonia              ---------------TQRVVVPTSKMNI----------KEGWRLCAVCT--SIAPPR---
L7M074_9ACAR|Rhipicephalus        ---------------AHHTADDVLL--------------PGWRYCPVCA--MNVPPR---
A7SWQ7_NEMVE|Nematostella         ---------------TTGAKLGMPS-----------VLKPGWAYCPFCQ--LNSPPR---
                                                                                              

B4GIR9_DROPE|Drosophila           -------AHHCRICQRCILKMDHHCPWVNNCVHFHNYKFFLLFLIYASLYCLYVLVTLLL
B5E105_DROPS|Drosophila           -------AHHCRICQRCILKMDHHCPWVNNCVHFHNYKFFLLFLIYASVYCLYVLVTLLL
B4JHI4_DROGR|Drosophila           -------THHCSVCNRCILKMDHHCPWLNNCVGYANHRYFFLYMLYTTMGCLLLIVAGVE
B4K9M3_DROMO|Drosophila           -------THHCSVCNRCILKMDHHCPWLNNCVGYANHRYFFLYMVYTTLGCLFLIVAGVE
B4M137_DROVI|Drosophila           -------THHCSVCNRCILKMDHHCPWLNNCVGYANHRYFFLYMLYTTLGCLFLIVCGLE
C3Z5I5_BRAFL|Branchiostoma        -------AHHCLYCDRCVLKRDHHCFFTGSCVGYFNQRRFVIFNLYTCLSAVHVLGLLLQ
G9KYT5_MUSPF|Mustela              -------SGHCSACRVCVLRRDHHCRLLGRCVGFRNYRPFLCLLLHAAGVLLHVSVLLGP
G6DDL9_DANPL|Danaus               -------AWHCKKCNACILKRDHHCFFFSRCIGLRNQRYYVTYLTYIFISMVYSTYFNFY
F7DR35_XENTR|Xenopus              -------KPFCHLCARVMGEQEHHCFFTGTCIGRSNLRSFVLFCLHASCSCFHAMVVGVG
F6SE12_ORNAN|Ornithorhynchus      LQEARALLPFHSSRPPGENREKISLTSAGNCIGSRNMRNFIMFCLYTSLACLYSTVAGAA
G1KTK1_ANOCA|Anolis               -------THFCRLCARVTQRHDHHCFFTGNCIGSRNMRNFVMFCLHTSLACLDSMVAGVA
H0ZPV6_TAEGU|Taeniopygia          -------THFCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLYTSLACLHSLVAGMA
K7GJD6_PELSI|Pelodiscus           -------THFCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLYTSLACLDSLVAGVA
E1C5D7_CHICK|Gallus               -------THYCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLYTSLACLDSLVAGMA
G1NJK6_MELGA|Meleagris            -------THYCRLCARVTQRHDHHCFFTGNCIGSRNMRNFIMFCLYTSLACLDSLVAGMA
F7G5M0_MONDO|Monodelphis          ASSSSQNTHFCRLCARVTLRHDHHCFFTGNCIGSRNMRNFIMFCLYTSLACLYSMVAGVA
G3W6V0_SARHA|Sarcophilus          -------THFCRLCARVTLRHDHHCFFTGNCIGSRNMRNFIMFCLYTSLACLYSMVAGVA
ZDH22_MOUSE|Mus                   -------THFCRVCSRVTLRHDHHCFFTGNCIGSRNMRNFILFCLYTSLACLYSMVAGVA
ZDH22_RAT|Rattus                  -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFILFCLYTSLACLYSMVAGVA
G1SNL9_RABIT|Oryctolagus          -------THFCRVCARVTLRHDHHCFFTGNCIGGRNMRNFVLFCLYTSLACLYSMVAGVA
G1MJ71_AILME|Ailuropoda           -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSTVAGLA
J9NZC5_CANFA|Canis                -------THFCRVCARVTLRHDHHCFFTGNCIGGRNMRNFVLFCLYTSLACLYSMVAGVA
G5B683_HETGA|Heterocephalus       -------THFCRVCARVTLRHDHHCFFTGNCIGRRNMRNFVLFCLYTSLACLYSMVAGVA
H0W7M0_CAVPO|Cavia                -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
E1B987_BOVIN|Bos                  -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFILFCLYTSLACLYSMVAGVA
G3UIR0_LOXAF|Loxodonta            -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
H0XYR4_OTOGA|Otolemur             -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
F6Y2X5_CALJA|Callithrix           -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
G7PB25_MACFA|Macaca               -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
G7MYW0_MACMU|Macaca               -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
H2RG61_PANTR|Pan                  -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
G1S3X2_NOMLE|Nomascus             -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
ZDH22_HUMAN|Homo                  -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
H2NLW0_PONAB|Pongo                -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLA----------
G3R3R5_GORGO|Gorilla              -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
G1PX45_MYOLU|Myotis               -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
F1S2N2_PIG|Sus                    -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
I3LX43_SPETR|Spermophilus         -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
L5JNU0_PTEAL|Pteropus             -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
F6SFZ8_HORSE|Equus                -------THFCRVCARVTLRHDHHCFFTGNCIGSRNMRNFVLFCLYTSLACLYSMVAGVA
H3AW31_LATCH|Latimeria            -------SHFCKLCKKVILRRDHHCFFTGCCIGKKNMRYFIMFCLYTSVSSLYSLVLGVA
E7EY29_DANRE|Danio                -------RHFCKVCKKVILKRDHHCFFTGNCIGNRNMRYFIMFSIYTSSSCLYSLVIGVA
H2VBD4_TAKRU|Takifugu             -------RHFCKLCRKVILKRDHHCFFTGNCIGQKNMRYFIMFCIHTSCTCMYSLVLGVA
H3DJ29_TETNG|Tetraodon            -------RHFCKLCRKVILKRDHHCFFTGNCIGKKNMRYFIMFCIHTSCTCMYSLVLGVA
H2MNL7_ORYLA|Oryzias              -------RHFCKLCKKIILKRDHHCFFTGNCIGNKNMRYFLMFCIYTS------------
G3NYI0_GASAC|Gasterosteus         -------RHFCKLCKKVILKRDHHCFFTGNCIGNKNMRYFIMFCIYTSCTCLYSLVLGVA
I3KWA6_ORENI|Oreochromis          -------RHFCKLCKKVILKRDHHCFFTGNCIGNKNMRYFIMFCIYTSCTCLYSLVLGVA
B4NJC4_DROWI|Drosophila           -------SWHCQSCRRCTLKRDHHCTFTANCIGHNNHRYFICMLFHLSVGCGICLVFNTI
Q9I7L7_DROME|Drosophila           -------SRHCRKCGVCVLMRDHHCFFTGCCIGHENYRYFFYFLIYFFLSCMISLTSSSI
B3MEE9_DROAN|Drosophila           -------SWHCKICGVCVLKRDHHCIYTGCCIGHRNHRFFMGFIFYLFVGSVYALVYNSI
B4P7Y0_DROYA|Drosophila           -------SWHCKICKVCILKRDHHCIYTGCCIGLRNHRFFMGFIFYLFVGSVYALVYNSI
Q7PVS0_ANOGA|Anopheles            -------SWHCASCRTCILKRDHHCVFTGCCIGHKNHRYFILFVVYLFISTLYASVLNNY
B0WDA3_CULQU|Culex                -------SWHCNACRTCVLKRDHHCVFTGCCIGHKNHRYFIMFVFHLFVATLYSSALNNY
E2AAM9_CAMFO|Camponotus           -------SWHCNTCDTCILKRDHHCVFTGCCVGHHNHRYFVMFLWYLFLGAAYAFSYGSF
K7IP65_NASVI|Nasonia              -------SWHCTTCDTCILKRDHHCIFTACCVGHYNHRYFLMFIFYLFVATVYSFAYNNF
L7M074_9ACAR|Rhipicephalus        -------SHHCSVCNECILKHDHHCMFTGRCIGFYNQRYFVVALFYMTAGLLYSLWYKCP
A7SWQ7_NEMVE|Nematostella         -------AYHCHVCDICVLRRDHHCIFAGKCVGHSNYRYYLFLAFYLWLGALYANLFHWE
                                           .           .        *:   * . :.    :              

B4GIR9_DROPE|Drosophila           ----ELHHAWGFDFDNV-------DLNSL--------QT--------MIPIVLAMIFT--
B5E105_DROPS|Drosophila           ----ELHHAWGFDFDNV-------DLNSV--------QT--------MIPIVLAMIFT--
B4JHI4_DROGR|Drosophila           IGHKYLWLDHSEPW--TELEPLEGHPVQYNLSGHIIPVTHPHEYDDILLPAAVHNLPT--
B4K9M3_DROMO|Drosophila           IGYKYLWLDHSEHW--TELEPLEGHPVKFNQSGHVIAVTHPNEYDDILLPPAVHHLPT--
B4M137_DROVI|Drosophila           IGYKYLWLDHSEHW--TELEPLEGHPVKFNLSGHAILVTHPHEYDDILLPAAVHHLPT--
C3Z5I5_BRAFL|Branchiostoma        ----YLEILNGPTM--E-------RLLTY------------------IFPVTVYEWYV--
G9KYT5_MUSPF|Mustela              ----ALSALLRAH-----------APLHT--------AA--------LLLLPWLMLLT--
G6DDL9_DANPL|Danaus               ----YVVSKYD-EY--E-------IYVSV--------CR--------IVNPFL-RYLI--
F7DR35_XENTR|Xenopus              ----YISESISLSL--Y-------DPMTF--------LR--------LLPLSITRFFS--
F6SE12_ORNAN|Ornithorhynchus      ----YISTVLSVSF--A-------HPLAF--------LT--------LLPHSISQFFS--
G1KTK1_ANOCA|Anolis               ----YISSVLSTSF--A-------SPMAF--------LT--------LLPNSISQFFS--
H0ZPV6_TAEGU|Taeniopygia          ----YISATLSMSF--V-------DPLAF--------LT--------LLPHSISQFFS--
K7GJD6_PELSI|Pelodiscus           ----YISAVLSVSF--A-------SPLAF--------LT--------LLPHSISQFFS--
E1C5D7_CHICK|Gallus               ----YISASLSMSF--A-------NPLAF--------LT--------LLPHSISQFFS--
G1NJK6_MELGA|Meleagris            ----YISASLSMSF--A-------NPLAF--------LT--------LLPHSISQFFS--
F7G5M0_MONDO|Monodelphis          ----YISTVLSISF--A-------HPLAF--------LT--------LLPHSISQFFS--
G3W6V0_SARHA|Sarcophilus          ----YISAVLSISF--A-------HPLAF--------LT--------LLPHSISQFFS--
ZDH22_MOUSE|Mus                   ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
ZDH22_RAT|Rattus                  ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
G1SNL9_RABIT|Oryctolagus          ----YISAVLSVSF--A-------HPLAF--------LT--------LLPTAISQFFA--
G1MJ71_AILME|Ailuropoda           ----YISAALSTSF--A-------HPLAF--------LT--------LLPTSISRFFS--
J9NZC5_CANFA|Canis                ----YISAALSTSF--A-------HPLAF--------LT--------LLPTSISQFFS--
G5B683_HETGA|Heterocephalus       ----YISAVLSVSF--A-------HPLAF--------LT--------LLPTSISQFFS--
H0W7M0_CAVPO|Cavia                ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
E1B987_BOVIN|Bos                  ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
G3UIR0_LOXAF|Loxodonta            ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
H0XYR4_OTOGA|Otolemur             ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
F6Y2X5_CALJA|Callithrix           ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
G7PB25_MACFA|Macaca               ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
G7MYW0_MACMU|Macaca               ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
H2RG61_PANTR|Pan                  ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
G1S3X2_NOMLE|Nomascus             ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
ZDH22_HUMAN|Homo                  ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
H2NLW0_PONAB|Pongo                -------QELTRSL--R-------KEVAA-------------------------------
G3R3R5_GORGO|Gorilla              ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
G1PX45_MYOLU|Myotis               ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
F1S2N2_PIG|Sus                    ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
I3LX43_SPETR|Spermophilus         ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
L5JNU0_PTEAL|Pteropus             ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFSAV
F6SFZ8_HORSE|Equus                ----YISAVLSISF--A-------HPLAF--------LT--------LLPTSISQFFS--
H3AW31_LATCH|Latimeria            ----YITVKYSLSF--E-------NPLAF--------LT--------LLPLALSYFIL--
E7EY29_DANRE|Danio                ----YLTIEYSISF--E-------NPLTF--------LT--------LLPLSTGYFFL--
H2VBD4_TAKRU|Takifugu             ----FLTMEYSISF--E-------DPLTF--------LT--------LLPLSTGYFFM--
H3DJ29_TETNG|Tetraodon            ----FLTVEYSISF--E-------DPLTF--------LT--------LLPLSTGYFFM--
H2MNL7_ORYLA|Oryzias              ------------------------------------------------------------
G3NYI0_GASAC|Gasterosteus         ----FLTVEYSLSF--E-------NPLTF--------LT--------LLPLSTGYFFT--
I3KWA6_ORENI|Oreochromis          ----FLTVEYSISF--E-------NPLTF--------LT--------LLPFSTGYFFM--
B4NJC4_DROWI|Drosophila           ----ESYYAKSLFF--A-------DSLIL--------FS--------IWGLIRQEIVD--
Q9I7L7_DROME|Drosophila           ----FIYVLHGGRY----------QLFML------------------THPAPNSAYFN--
B3MEE9_DROAN|Drosophila           ----YLWVFQAHIY--C-------HWFTL--------FK--------LLNP-LFLLFT--
B4P7Y0_DROYA|Drosophila           ----YLWVIHGHIY--N-------NWLTL--------LKLFCP----MLHTVTGSFWS--
Q7PVS0_ANOGA|Anopheles            ----FLWFVRGEEF--R-------NWTSL--------VK--------IVFP-LAMLL---
B0WDA3_CULQU|Culex                ----FIWYIHGEEF--R-------NWTSF--------IK--------MVFP-LAMLV---
E2AAM9_CAMFO|Camponotus           ----FIWTRTSFEF-----------PMSV--------IK--------MVFPVAIFFF---
K7IP65_NASVI|Nasonia              ----FIWSRIHFEF-----------PMTI--------VK--------LVFPVAIFIFG--
L7M074_9ACAR|Rhipicephalus        ----YVLEMLG-GL----------NLVTV--------LH--------MVAPHFGLLL---
A7SWQ7_NEMVE|Nematostella         ----YVTSVMD-NF--T-------LWTMF------------------TMFMPMLSWML--
                                                                                              

B4GIR9_DROPE|Drosophila           ------------------------------------------------------------
B5E105_DROPS|Drosophila           ------------------------------------------------------------
B4JHI4_DROGR|Drosophila           ------------------------------------------------------------
B4K9M3_DROMO|Drosophila           ------------------------------------------------------------
B4M137_DROVI|Drosophila           ------------------------------------------------------------
C3Z5I5_BRAFL|Branchiostoma        ------------------------------------------------------------
G9KYT5_MUSPF|Mustela              ------------------------------------------------------------
G6DDL9_DANPL|Danaus               ------------------------------------------------------------
F7DR35_XENTR|Xenopus              ------------------------------------------------------------
F6SE12_ORNAN|Ornithorhynchus      ------------------------------------------------------------
G1KTK1_ANOCA|Anolis               ------------------------------------------------------------
H0ZPV6_TAEGU|Taeniopygia          ------------------------------------------------------------
K7GJD6_PELSI|Pelodiscus           ------------------------------------------------------------
E1C5D7_CHICK|Gallus               ------------------------------------------------------------
G1NJK6_MELGA|Meleagris            ------------------------------------------------------------
F7G5M0_MONDO|Monodelphis          ------------------------------------------------------------
G3W6V0_SARHA|Sarcophilus          ------------------------------------------------------------
ZDH22_MOUSE|Mus                   ------------------------------------------------------------
ZDH22_RAT|Rattus                  ------------------------------------------------------------
G1SNL9_RABIT|Oryctolagus          ------------------------------------------------------------
G1MJ71_AILME|Ailuropoda           ------------------------------------------------------------
J9NZC5_CANFA|Canis                ------------------------------------------------------------
G5B683_HETGA|Heterocephalus       ------------------------------------------------------------
H0W7M0_CAVPO|Cavia                ------------------------------------------------------------
E1B987_BOVIN|Bos                  ------------------------------------------------------------
G3UIR0_LOXAF|Loxodonta            ------------------------------------------------------------
H0XYR4_OTOGA|Otolemur             ------------------------------------------------------------
F6Y2X5_CALJA|Callithrix           ------------------------------------------------------------
G7PB25_MACFA|Macaca               ------------------------------------------------------------
G7MYW0_MACMU|Macaca               ------------------------------------------------------------
H2RG61_PANTR|Pan                  ------------------------------------------------------------
G1S3X2_NOMLE|Nomascus             ------------------------------------------------------------
ZDH22_HUMAN|Homo                  ------------------------------------------------------------
H2NLW0_PONAB|Pongo                ------------------------------------------------------------
G3R3R5_GORGO|Gorilla              ------------------------------------------------------------
G1PX45_MYOLU|Myotis               ------------------------------------------------------------
F1S2N2_PIG|Sus                    ------------------------------------------------------------
I3LX43_SPETR|Spermophilus         ------------------------------------------------------------
L5JNU0_PTEAL|Pteropus             VLPLSQICHQNMDWLAEIAAKCSFDIINLLLFLAESAYRDGSSVRGLSVKRFWCFPAPPA
F6SFZ8_HORSE|Equus                ------------------------------------------------------------
H3AW31_LATCH|Latimeria            ------------------------------------------------------------
E7EY29_DANRE|Danio                ------------------------------------------------------------
H2VBD4_TAKRU|Takifugu             ------------------------------------------------------------
H3DJ29_TETNG|Tetraodon            ------------------------------------------------------------
H2MNL7_ORYLA|Oryzias              ------------------------------------------------------------
G3NYI0_GASAC|Gasterosteus         ------------------------------------------------------------
I3KWA6_ORENI|Oreochromis          ------------------------------------------------------------
B4NJC4_DROWI|Drosophila           ------------------------------------------------------------
Q9I7L7_DROME|Drosophila           ------------------------------------------------------------
B3MEE9_DROAN|Drosophila           ------------------------------------------------------------
B4P7Y0_DROYA|Drosophila           ------------------------------------------------------------
Q7PVS0_ANOGA|Anopheles            ------------------------------------------------------------
B0WDA3_CULQU|Culex                ------------------------------------------------------------
E2AAM9_CAMFO|Camponotus           ------------------------------------------------------------
K7IP65_NASVI|Nasonia              ------------------------------------------------------------
L7M074_9ACAR|Rhipicephalus        ------------------------------------------------------------
A7SWQ7_NEMVE|Nematostella         ------------------------------------------------------------
                                                                                              

B4GIR9_DROPE|Drosophila           GATM---------------IMLGLHIYLLLLNR--------TT-----M-ESAHAPMFCV
B5E105_DROPS|Drosophila           GATV---------------IMLGLHIYLLLLNR--------TT-----M-ESAHAPMFCV
B4JHI4_DROGR|Drosophila           PAVHT-DES---------SPARRRILWFMAVTN--------VAVVIALGSLCTWHAKLIT
B4K9M3_DROMO|Drosophila           PMADS-PDA---------TPTRRRVLWFMAVVN--------VAVVIALGSLSIWHAKLIT
B4M137_DROVI|Drosophila           PIADTLADS---------TPTRRRILWFMAVTN--------VAVVIALGTLCTWHAKLIT
C3Z5I5_BRAFL|Branchiostoma        GYMPT-STV---------LVVLEVYVCAVACIG--------CG-----G-LFGWQIMIIR
G9KYT5_MUSPF|Mustela              GRVSL-AQF---------ALAFVTDTCVAGALL--------CG-----A-GLLFHGMLLL
G6DDL9_DANPL|Danaus               PEPMG-MKD---------LYVFFLFLNVGLVIW--------SG-----G-LFVFHTRNVL
F7DR35_XENTR|Xenopus              GTLLS-SEM---------LVVLMIYLWFGVGVA--------CA-----A-FCCHHLILIC
F6SE12_ORNAN|Ornithorhynchus      GAVLG-SEM---------FVILMLYLWFGIGLA--------CA-----G-FCCHQLLLIL
G1KTK1_ANOCA|Anolis               GALPS-LEM---------FVILMLYLWLGIGLA--------CA-----G-FCCHQILLIL
H0ZPV6_TAEGU|Taeniopygia          GALLS-SEM---------FIILMLYLWLGIGLA--------CA-----G-FCFHQMLLIL
K7GJD6_PELSI|Pelodiscus           GALLS-SEM---------FVILMLYLWLGIGLA--------CA-----G-FCSHQILLIL
E1C5D7_CHICK|Gallus               GALLS-SEM---------FVILMLYLWLGIGLA--------CA-----G-FCCHQLLLIL
G1NJK6_MELGA|Meleagris            GALLS-SEM---------FVILMLYLWLGIGLA--------CA-----G-FCCHQLLLIL
F7G5M0_MONDO|Monodelphis          GAVLG-SEM---------FVILMLYLWFGIGLA--------CA-----G-FCCHQLLLVL
G3W6V0_SARHA|Sarcophilus          GAVLG-SEM---------FVILMLYLWFGIGLA--------CA-----G-FCCHQLLLVL
ZDH22_MOUSE|Mus                   GAVLG-SDM---------FVILMLYLWFAVGLA--------CA-----G-FCCHQLLLIL
ZDH22_RAT|Rattus                  GAVLG-SDM---------FVILMLYLWFAVGLA--------CA-----G-FCCHQLLLIL
G1SNL9_RABIT|Oryctolagus          GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
G1MJ71_AILME|Ailuropoda           GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
J9NZC5_CANFA|Canis                GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
G5B683_HETGA|Heterocephalus       GAVLG-SEM---------FVILMLYLWFAVGLA--------CA-----G-FCCHQLLLIL
H0W7M0_CAVPO|Cavia                GAVLG-SDM---------FVILMLYLWFAVGLA--------CA-----G-FCCHQLLLIL
E1B987_BOVIN|Bos                  GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
G3UIR0_LOXAF|Loxodonta            GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
H0XYR4_OTOGA|Otolemur             GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
F6Y2X5_CALJA|Callithrix           GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
G7PB25_MACFA|Macaca               GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
G7MYW0_MACMU|Macaca               GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
H2RG61_PANTR|Pan                  GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
G1S3X2_NOMLE|Nomascus             GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
ZDH22_HUMAN|Homo                  GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
H2NLW0_PONAB|Pongo                GPA-------------------------GPHVQ--------CR-----K-----------
G3R3R5_GORGO|Gorilla              ------------------------------------------------------------
G1PX45_MYOLU|Myotis               GAVLG-SEM---------FVILMLYLWFAVGLA--------CA-----G-FCCHQLLLIL
F1S2N2_PIG|Sus                    GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
I3LX43_SPETR|Spermophilus         GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
L5JNU0_PTEAL|Pteropus             GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
F6SFZ8_HORSE|Equus                GAVLG-SEM---------FVILMLYLWFAIGLA--------CA-----G-FCCHQLLLIL
H3AW31_LATCH|Latimeria            GAISG-LEL---------FLILLLYVWLGIGLT--------CA-----G-FCCQQILLVS
E7EY29_DANRE|Danio                GLISG-LQF---------FLVIMLYIWLGIGLV--------SV-----G-FCCQQLLLVA
H2VBD4_TAKRU|Takifugu             GTISG-LQL---------FLVLMLYVWLGIGLV--------CA-----G-FCCQQVLLVA
H3DJ29_TETNG|Tetraodon            GTVSG-LQL---------FLVLMLYVWLGIGLV--------CA-----G-FCCQQVLLVA
H2MNL7_ORYLA|Oryzias              ------------------------------------------------------------
G3NYI0_GASAC|Gasterosteus         GTISG-LQL---------FLVLMLYVWLGIGLV--------CA-----G-FCCQQVLLVA
I3KWA6_ORENI|Oreochromis          GTISG-LQL---------FLVLMLYVWLGIGLV--------CA-----G-FCCQQVLLVA
B4NJC4_DROWI|Drosophila           EHFWH-IVS---------SCIIKLNFFLTV-LA--------IA-------QLVYQLIMLS
Q9I7L7_DROME|Drosophila           SLIIRIIYFKLPDIYELVFTLVFVLLWIGVCVATYVAYDQWSR-----G-YFCYD-----
B3MEE9_DROAN|Drosophila           GNFWS-------------NMYLIFYGLNILAFL--------YG-----VLLLAYHVPIIL
B4P7Y0_DROYA|Drosophila           NMYLG-FYS---------LNVLAL----AYGVI--------LL-----G----YHVPIVL
Q7PVS0_ANOGA|Anopheles            --IDT-STK---------QYYLVIYLINMVGVM--------FT-----GVLLIYHGRLIL
B0WDA3_CULQU|Culex                --IDA-STK---------QYYLVIYLINMIGML--------FT-----GVLLIYHGRLIL
E2AAM9_CAMFO|Camponotus           GFDSS-IDQ----------FYLLLYVVSAVGTL--------YT-----AVLCIYHFNLIL
K7IP65_NASVI|Nasonia              --FDG-SME---------QFYLMLYIVTVIGML--------FT-----GALCVYHFNLLF
L7M074_9ACAR|Rhipicephalus        GLVDG-WLF---------VCTLLNLVELVVFFL--------CA-----Y-LLAVELICVA
A7SWQ7_NEMVE|Nematostella         GYTTI-YQT---------FVTFITAISLFAFVM--------FS-----G-LLFFQLNIIA
                                                                                              

B4GIR9_DROPE|Drosophila           GGRTR-------------KAFN---LGCCA--------NLCEVFG-----DRWYL-WPLP
B5E105_DROPS|Drosophila           GGRTR-------------KAFN---LGCCT--------NLCEVFG-----NRWYL-WPLP
B4JHI4_DROGR|Drosophila           RGETSVESHINEAETKRFLQVN---RIYINPYNFGSKKNWKLFLGLVRGRSFWRTVLLPS
B4K9M3_DROMO|Drosophila           RGETSIEAHINEAERKRLLQLK---RVYINPYNFGTKKNWKLFLGLVRGRSFWRTVLLPS
B4M137_DROVI|Drosophila           RGETSVEAHINEAERKRFLQLK---RIYINPYNFGTKKNWKLFLGLVRGRSFWRTVLLPS
C3Z5I5_BRAFL|Branchiostoma        DGQTS-------------YEAV---------------KNIK-------------------
G9KYT5_MUSPF|Mustela              RGQTT-------------WEWA---RG-QHSYDLGPCHNLQAALG-----PRWVLVWLWP
G6DDL9_DANPL|Danaus               RGETS-------------HEYKENTRSTFRNNLSAMKRNFINVFG-----EKWYIALVWP
F7DR35_XENTR|Xenopus              RGSNG-------------QQFH---TAEI--RITNGKENLQRVFG-----KKWLFAIFVP
F6SE12_ORNAN|Ornithorhynchus      RGQTR-------------HQVR---KG-VIVRARPWRRNLQEVFG-----KRWLLGLLIP
G1KTK1_ANOCA|Anolis               RGQTR-------------YQVR---KG-MAARARPWKKNLEEVFG-----KRWLLGLLIP
H0ZPV6_TAEGU|Taeniopygia          RGQTR-------------YQVR---KG-VLVRARPWRENLQEVFG-----KKWLLGLFIP
K7GJD6_PELSI|Pelodiscus           RGQTR-------------YQVR---KG-MVVRARPWRKNLQDVFG-----KRWLIGLLIP
E1C5D7_CHICK|Gallus               RGQTQ-------------YQVR---KG-MVVRARPWRENLREVFG-----KRWLLGLLIP
G1NJK6_MELGA|Meleagris            RGQTR-------------YQVR---KG-MVVKARPWRENLREVFG-----KRWLLGLLIP
F7G5M0_MONDO|Monodelphis          RGQTR-------------HQVR---KG-MVVRARPWRKNLQEVFG-----KRWLLGLLIP
G3W6V0_SARHA|Sarcophilus          RGQTR-------------HQVR---KG-MVVRARPWRKNLQEVFG-----KRWLLGLLIP
ZDH22_MOUSE|Mus                   RGQTR-------------YQVR---KG-MAVRARPWRKNLQEVFG-----KRWLLGLLVP
ZDH22_RAT|Rattus                  RGQTR-------------YQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
G1SNL9_RABIT|Oryctolagus          RGQTR-------------HQLR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
G1MJ71_AILME|Ailuropoda           RGQTR-------------HQVR---KG-VAMRARPWRKNLQEVFG-----KRWLLGLLVP
J9NZC5_CANFA|Canis                RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
G5B683_HETGA|Heterocephalus       RGQTR-------------YQVR---KG-VAVRAQPWRKNLQEVFG-----KRWLLGLLVP
H0W7M0_CAVPO|Cavia                RGQTR-------------HQVR---KG-VAVRAQPWRKNLQEVFG-----KRWLLGLLVP
E1B987_BOVIN|Bos                  RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
G3UIR0_LOXAF|Loxodonta            RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
H0XYR4_OTOGA|Otolemur             RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
F6Y2X5_CALJA|Callithrix           RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
G7PB25_MACFA|Macaca               RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
G7MYW0_MACMU|Macaca               RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
H2RG61_PANTR|Pan                  RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
G1S3X2_NOMLE|Nomascus             RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
ZDH22_HUMAN|Homo                  RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
H2NLW0_PONAB|Pongo                ------------------------------------------------------------
G3R3R5_GORGO|Gorilla              ------------------------------------------------------------
G1PX45_MYOLU|Myotis               RGQTR-------------HQVR---KG-VAVRAGPWRKNLQEVFG-----KRWLLGLLVP
F1S2N2_PIG|Sus                    RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLIP
I3LX43_SPETR|Spermophilus         RGQTR-------------HQAR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
L5JNU0_PTEAL|Pteropus             RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
F6SFZ8_HORSE|Equus                RGQTR-------------HQVR---KG-VAVRARPWRKNLQEVFG-----KRWLLGLLVP
H3AW31_LATCH|Latimeria            RGQTW-------------HQVR---KG-LSMRHGHWGENLQQVFG-----KRWLLGLFIP
E7EY29_DANRE|Danio                RGQTW-------------CELQ---KGQLSECRGTWRANLTDVFG-----SHWVLGLFVP
H2VBD4_TAKRU|Takifugu             RGQTW-------------CQMQ---QGRLQEIQSPWQNNLKDVFG-----TRWILGLILP
H3DJ29_TETNG|Tetraodon            RGQTW-------------CQMQ---RGRLQGVQSPWQNNLKDVFG-----TRWILGLILP
H2MNL7_ORYLA|Oryzias              ------------------------------------------------------------
G3NYI0_GASAC|Gasterosteus         RGRTW-------------CQMQ---RGQLVDNRSPWRSNLKDVFG-----TRWILGLILP
I3KWA6_ORENI|Oreochromis          RGQTW-------------CQMQ---RGQLAENRNPWRANLKDVFG-----TRWILGLILP
B4NJC4_DROWI|Drosophila           RNSTC-------------HRFK------DCIYDQGFKKNVELIMG-----RRKFWVLLSP
Q9I7L7_DROME|Drosophila           ------------------FELQ------NIPFDRKLRRNFKTFLG-----RRMKWTWISG
B3MEE9_DROAN|Drosophila           RGGVS-------------ADRT---LASKHRYDRGVRQNLRSVFG-----NRMHLAWISP
B4P7Y0_DROYA|Drosophila           RGGVS-------------ADIT---KESKEKYDRGVYQNLRSVFG-----IRMHLAWLSP
Q7PVS0_ANOGA|Anopheles            SGAVV-------------HERK---AP---EYDMGRAENLRMVLG-----NRWYIAWLSP
B0WDA3_CULQU|Culex                SGSVV-------------HEQN---GR---DFDLGRMENLRMVLG-----ERWHLAWLSP
E2AAM9_CAMFO|Camponotus           RGVVG-------------NESN---KK-DFTYDMGWKDNVREVFG-----ERWYLAWLLP
K7IP65_NASVI|Nasonia              NGCTS-------------DERN---KKNYS-YSLGWKQNIKEVFG-----DKWYLVWLIP
L7M074_9ACAR|Rhipicephalus        RNQTT-------------YEKS---HG-IRTYGRGLRRNLKEALG-----AAWFLVWLSP
A7SWQ7_NEMVE|Nematostella         RGQTS-------------YERK---RK-RRIYDKGWLRNFIEVLG-----ENWFLSWIWP
                                                                                              

B4GIR9_DROPE|Drosophila           VYSSRGDGLTFPLREGS-ISSASSADF------------
B5E105_DROPS|Drosophila           VYSSRGDGLT-----------FPLREGSISS--ASSADF
B4JHI4_DROGR|Drosophila           WHRPEGNGLTFHTVHDAPFEDEWP---------------
B4K9M3_DROMO|Drosophila           WHKPEGNGLSFHTVHDAPFEDEWP---------------
B4M137_DROVI|Drosophila           WHRPEGNGLSFHTVHDAIFEDEWP---------------
C3Z5I5_BRAFL|Branchiostoma        ---------------------------------------
G9KYT5_MUSPF|Mustela              FLASPLPGDGVTFQTAA----DMGL--------------
G6DDL9_DANPL|Danaus               LANSPLPET------------TEDRGDEY----------
F7DR35_XENTR|Xenopus              Q--------------------------------------
F6SE12_ORNAN|Ornithorhynchus      VLNVGSEYHQ-----------QKDK--------------
G1KTK1_ANOCA|Anolis               MLNVGSDYHR-----------QKEK--------------
H0ZPV6_TAEGU|Taeniopygia          VQNTESSYRR-----------QKEK--------------
K7GJD6_PELSI|Pelodiscus           VLNVGSDCHR-----------PKDK--------------
E1C5D7_CHICK|Gallus               MLNVGSDCRR-----------QKVK--------------
G1NJK6_MELGA|Meleagris            MLNVGSDCRR-----------QKVK--------------
F7G5M0_MONDO|Monodelphis          MLNVGSDYPR-----------HKGK--------------
G3W6V0_SARHA|Sarcophilus          MLNVGSEYPR-----------HKGK--------------
ZDH22_MOUSE|Mus                   MFNVGTESSK-----------QQDK--------------
ZDH22_RAT|Rattus                  MFNVGTESSK-----------QQDK--------------
G1SNL9_RABIT|Oryctolagus          MFNVGSESSK-----------QWDK--------------
G1MJ71_AILME|Ailuropoda           MFNVGGESSK-----------QHDK--------------
J9NZC5_CANFA|Canis                MFNVGGESSK-----------QRDK--------------
G5B683_HETGA|Heterocephalus       MFNVGSESSK-----------LKDK--------------
H0W7M0_CAVPO|Cavia                MFNVGSEGSK-----------PQDK--------------
E1B987_BOVIN|Bos                  MFNVGSESCK-----------QRDK--------------
G3UIR0_LOXAF|Loxodonta            MFNVGSESAK-----------QRDK--------------
H0XYR4_OTOGA|Otolemur             TLNVGSESSK-----------QWDK--------------
F6Y2X5_CALJA|Callithrix           MFNVGSESSK-----------QQDK--------------
G7PB25_MACFA|Macaca               MFNVGSESSK-----------QQDK--------------
G7MYW0_MACMU|Macaca               MFNVGSESSK-----------QQDK--------------
H2RG61_PANTR|Pan                  MFNVGSESSK-----------QQDK--------------
G1S3X2_NOMLE|Nomascus             MFNVGSESSK-----------QQDK--------------
ZDH22_HUMAN|Homo                  MFNVGSESSK-----------QQDK--------------
H2NLW0_PONAB|Pongo                ---------------------------------------
G3R3R5_GORGO|Gorilla              ---------------------------------------
G1PX45_MYOLU|Myotis               MFNVGGESSK-----------QRDK--------------
F1S2N2_PIG|Sus                    MFNVGSESSK-----------QRDK--------------
I3LX43_SPETR|Spermophilus         MFNVGSESSK-----------QQDK--------------
L5JNU0_PTEAL|Pteropus             MLNVGGESSK-----------QRDK--------------
F6SFZ8_HORSE|Equus                MFNVGGESSK-----------QRDK--------------
H3AW31_LATCH|Latimeria            MATVEYKQSA---------KTQEDKRN------------
E7EY29_DANRE|Danio                VPTVETVPGNWQVY-----HDHKHD--------------
H2VBD4_TAKRU|Takifugu             VQTVETCSEE-----------KQD---------------
H3DJ29_TETNG|Tetraodon            VQTVETSLEE-----------KQE---------------
H2MNL7_ORYLA|Oryzias              ---------------------------------------
G3NYI0_GASAC|Gasterosteus         VQTAETGSEDPDA--------HKQD--------------
I3KWA6_ORENI|Oreochromis          VQTVETCSEDADV--------HKQD--------------
B4NJC4_DROWI|Drosophila           FMDSPLPHDGT----------QWQLAKHYL---------
Q9I7L7_DROME|Drosophila           FVPSQLDHDGFDLDPDNERVADWCSETTIKDG-------
B3MEE9_DROAN|Drosophila           LIRSDLPDDGYHWKPTIDE--QEKD--------------
B4P7Y0_DROYA|Drosophila           LIRSDLPDDGYHWSVST----NKQD--------------
Q7PVS0_ANOGA|Anopheles            FVASELPHNGVNWE-----TLQKQT----LKSK------
B0WDA3_CULQU|Culex                FVRSDLPHNGVDWD-----RVQREA----AKSK------
E2AAM9_CAMFO|Camponotus           YIKSQLPHDGISWHYLC----SKKD--------------
K7IP65_NASVI|Nasonia              YVPSKLPQDGVSWHRSSKWNMNNSKCK------------
L7M074_9ACAR|Rhipicephalus        WVHSPVPGDF---DGRVVCVEKKVL--------------
A7SWQ7_NEMVE|Nematostella         KITSPLPHNGTDYTQACNEELPKDM--------------
                                                                         
