MUSCLE (3.8) multiple sequence alignment


A7SWQ7_NEMVE|Nematostella        -----MFSQDPQYEKLS--LAKRVIPKKGS-DAAAFVFMFVMLWVISLFELLVVL-----
B4KT36_DROMO|Drosophila          -----------------------------M-DIFCHLILVICLPVSLLYEFIAVI-----
G3MTJ6_9ACAR|Amblyomma           MEPTLPTTAVNVFAAPA--SRRSIMPTGFR-DRVLFLLMVLGIPLIVFFDFYFVA-----
C3Z4Y6_BRAFL|Branchiostoma       ------METALDGGFAR--RARQFLPKSRG-DKVAFAFLVVIIHLIFYFEQFRVL-----
B3MMJ1_DROAN|Drosophila          ------------MAIRS--LKRIVPPNALE-GFFLVVLVAGMTVVLAIL-LNMMM-----
B4NLE0_DROWI|Drosophila          ------------MILRS--FKR-VRPRCLA-DLACFLLVAVFVPVTFIFQVTVVL-----
B4GD12_DROPE|Drosophila          --------------------------------------------------MTLVL-----
Q292N6_DROPS|Drosophila          --------------------------------------------------MTLVL-----
B3NRN6_DROER|Drosophila          ------------MILRS--WDR-VKPHSIS-DFACFLLVAVFVPVTYIFQVTVVM-----
Q0IGS7_DROME|Drosophila          -----------MMILRS--WDR-VKPRSIS-DFACFLLVAVFVPVTYIFHVTIVM-----
B4P4K3_DROYA|Drosophila          ------------MILRS--WDR-IKPRSIS-DFACFLLVAVFVPVTYIFHVTVVM-----
B4J5B6_DROGR|Drosophila          ------------MILRP--LGRAFRPRSIA-DGACFMLIAVFVPITYIFQVTVIM-----
B4LLZ9_DROVI|Drosophila          -----------------------------------------------MFQVTVIM-----
Q7PVS0_ANOGA|Anopheles           --------------TMR--IRKHVLPRTLQ-DAVATAFMAGIIPITFWFEVYVVI-----
B0WDA3_CULQU|Culex               ---------------MK--IRKRFLPRCVQ-DGVATLFMIGIIPVTFWFEVSVVI-----
E2AAM9_CAMFO|Camponotus          ------------MIIRKKIW-----PRTIG-DLLSMIFVLVIVPLMYWFGLWIVL-----
K7IP65_NASVI|Nasonia             -----------------MLIRRKILPRTAS-DILSTTFLLIIVPLLYWFELWVVL-----
G6CN66_DANPL|Danaus              MASRRVTRKWEVFAGRNRFWCDGRLMTAPHPGVFALTLALICGTCVLHFAFDCPFLAARV
H9GE24_ANOCA|Anolis              -----------AMAGPE--WKK-------R-ALPVLAGAALGSALAAEVLALLLLR----
F7E5D5_MONDO|Monodelphis         -------------MGGL--WPAGGGRGLQL-PLPLLLTSLWAVAVALELAYVLVHG----
G3W4T3_SARHA|Sarcophilus         ------------NEGEQ--WES--------------------------------------
ZDH24_MOUSE|Mus                  -------------MGES--WAARGAEGAPA-RMPLVLTALWAAVVVLELAYVMVLG----
ZDH24_RAT|Rattus                 -------------MGEP--WAARGTEGAPA-RMPVVFTALWAAVVVLELTYVMVLG----
G1SD06_RABIT|Oryctolagus         -----------------------------------------------------LMG----
G5BWY5_HETGA|Heterocephalus      -------------MGQP---------GTPT-QLPLVLTTLWAAAVVLELVYVLVLG----
L5KQT9_PTEAL|Pteropus            -------------MEQP--WAAGSAEGTPT-RLPLVLTALWAAAVGLELAYVLVLG----
G1QBQ1_MYOLU|Myotis              -------------MGQP--RAVGSADGPPT-RLPLVLTALWATAVGLELAYVLVLG----
H0VVK0_CAVPO|Cavia               -------------MGQP--WASGNAERSPA-RLPLVFTTLWVAAVVLELAYVLVLG----
H0Y068_OTOGA|Otolemur            -------------MGQP--WAATSTEGAPA-RLPLVLTLLWAVAVGLELAYVLVLG----
I3ME48_SPETR|Spermophilus        -------------MGQP--WAAGSAEGAPA-RLPLVLTALWAAVVSLELAYVLVLG----
G3U2N9_LOXAF|Loxodonta           -------------MGQP--WAVGSAEGAPA-RLPLVITALWAAAVGLELAYVLVLG----
E1BPA5_BOVIN|Bos                 -------------MGQP--WAVGTAEASPA-RLPLVLTALWAAAVGLELAYVLVLG----
F1RU50_PIG|Sus                   -------------MGQP--WAVGSAEGAHA-RLPLVLTALWAAAVGLEVAYVLVLG----
F6ZZE9_HORSE|Equus               -------------MGQP--WAAGSAEWAPA-RLPLVLTALWAAAVGLELAYVLVLG----
G9KYT5_MUSPF|Mustela             -------------MGQP--WAVGTGEGAPA-RLPLVLTALWAAAVGLELAYVLILG----
E2RIK9_CANFA|Canis               -------------MGQP--WAVGSAEGAPA-RLPLVLTALWAAAVGLELAYVLVLG----
D2HYA8_AILME|Ailuropoda          -------------MGQP--WAVGSAEGAPA-RLPLVLTALWAAAVGLELAYVLVLG----
F7I2B0_CALJA|Callithrix          ----------------------------------------XSTAVGLELAYVLMVR----
G1R2S0_NOMLE|Nomascus            -------------MGQP--WAAGSADGAPA-RLPLVLTALWAAAVGLELAYVLVLG----
ZDH24_HUMAN|Homo                 -------------MGQP--WAAGSTDGAPA-QLPLVLTALWAAAVGLELAYVLVLG----
G3RIT0_GORGO|Gorilla             -------------MGQP--WAAGSTDGAPA-RLPLVLTALWAAAVGLELAYVLVLG----
K7CBF0_PANTR|Pan                 -------------MGQH--WASGSTDGAPA-QLPLVLTALWAAAVGLELAYVLVLG----
G7PP90_MACFA|Macaca              ------------------------------------------------------------
F7GVE4_MACMU|Macaca              -------------MGQP--WAAGSADGAPA-RLPLVLTALWAAAVGLELAYVLVLG----
H3BDY5_LATCH|Latimeria           ------------MKGFV--TRHRFDPALL---MPLWVTSGLMFVVAAEVLYLVLTEGLGA
Q6DG77_DANRE|Danio               ---------MTSFMSRV--WCK--VESTGR-QLPIVLNAVLVFSITAEVSYLVLVEAPFE
B3DLR2_XENTR|Xenopus             ---------MTSFMSRV--WCK--VESTGR-QLPIVLNAVLVFSITAEVSYLVLVEAPFE
H2LCC6_ORYLA|Oryzias             -----------MTSLRS--KVLCQAERICN-HLPVFLNTFLVFSITGEVSYLVLVEAPLE
G3Q0C2_GASAC|Gasterosteus        ---------MSSFASQV--FGR--VDRLCR-PLPMVLNTFLVFSITGEVSYLVLLEAPLQ
I3JCL8_ORENI|Oreochromis         ---------MTSLASKV--FCR--VEKMCH-HLPVVLNTFLVFSITGEVSYLVSVEAPLE
H2ULS9_TAKRU|Takifugu            ---------MTSFASKT--FCR--VEKLCH-HLPVVLNTFLVFSITGEVSYLVMVEAPLE
H3DHA6_TETNG|Tetraodon           ---------MTSFASKT--FCR--VEKLCH-YLPVVLNTFLVFSITGEVSYLVMVEAPLE
                                                                                             

A7SWQ7_NEMVE|Nematostella        P--IYHEFLSTWYLI---HVFCGLFM-------------------FLNVFANLYKVITTD
B4KT36_DROMO|Drosophila          P--KYHSPGGYAYAL---IVICVILL-------------------YINVMANMIACMMVD
G3MTJ6_9ACAR|Amblyomma           P--RYHETFDNVMCI---HTALATFL-------------------VFNIYGNLFKLLRIG
C3Z4Y6_BRAFL|Branchiostoma       P--EIYHEPCLASYI---HTAFMVFV-------------------YINTVGNLFMMMNVD
B3MMJ1_DROAN|Drosophila          P--QMVAQGTAAVTL---YTLLGFFL-------------------YTNIITNMAMCILVD
B4NLE0_DROWI|Drosophila          P--ELMELFGFGYYLLFFIFFIGVFI-------------------LFNLISNMMACMLVD
B4GD12_DROPE|Drosophila          P--ELFGVGSFWYTV---IWVAAQFL-------------------IFNITANLLACMLVD
Q292N6_DROPS|Drosophila          P--ELFGVGSFWYTV---IWVAAQFL-------------------IFNITANLLACMLVD
B3NRN6_DROER|Drosophila          P--ELFAIGGVWYTL---FWLASLFL-------------------IFNITSNMLACMLVD
Q0IGS7_DROME|Drosophila          P--ELFAIGGIWYTL---LWLASLFL-------------------IFNITSNMLACMLVD
B4P4K3_DROYA|Drosophila          P--ELFAIGGFWYTL---FWVASLFV-------------------IFNITSNMLACMLVD
B4J5B6_DROGR|Drosophila          P--ELHNVGSFWYTV---IWLAGLFL-------------------VFNLTSNMLACMLVD
B4LLZ9_DROVI|Drosophila          P--ELHDVGSFWYTA---VWLAGIFL-------------------VFNITSNMLACMLVD
Q7PVS0_ANOGA|Anopheles           P--GIHGPDSVYNWV---HFVPAVLL-------------------LFNVTAHMLATMLCD
B0WDA3_CULQU|Culex               P--GIHGTNSGWNWI---HLVPALFL-------------------LYNISTNMLATILCD
E2AAM9_CAMFO|Camponotus          P--ALYKDDILPYTL---HFVLGNFI-------------------MFNIVGNFTYTVLCD
K7IP65_NASVI|Nasonia             P--NLYEPGSAMYIF---HFCLGSFI-------------------MINIVGNFTYTVLSD
G6CN66_DANPL|Danaus              S--GAVPAAGAALCG---VTLAALLRTALSDPGIIPRAAPHEAAALGALEAADGAAGRPP
H9GE24_ANOCA|Anolis              RRGEPFPLPTLAALL---------AL-------------------LGNALESARRFVTAS
F7E5D5_MONDO|Monodelphis         P--GLPAAGPLARTL---HMLLAAFQ-------------------LLNLLGNAVLFLSRN
G3W4T3_SARHA|Sarcophilus         P--------DRWQPP--------------------------------------------A
ZDH24_MOUSE|Mus                  P--GPPPLGPLARAL---QLALAAYQ-------------------LLNLLGNVVLFLRSD
ZDH24_RAT|Rattus                 P--GPPPLEPLARAL---QLALAAYQ-------------------LLNLLGNMGLFLRSD
G1SD06_RABIT|Oryctolagus         P--GLRA-GTLARAL---QLALAALQ-------------------LLNLLGNVGLFLRSD
G5BWY5_HETGA|Heterocephalus      P--GPPPLGPLAQAL---QLALAVFQ-------------------LLNLLGNVGLFLRSD
L5KQT9_PTEAL|Pteropus            P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
G1QBQ1_MYOLU|Myotis              P--GPPPLGPLARAF---QLALAAFQ-------------------LLNLLGNVGLFLCSD
H0VVK0_CAVPO|Cavia               P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
H0Y068_OTOGA|Otolemur            P--GPPPLGPLARAL---QLALATFQ-------------------LLNLLGNVGLFLRSD
I3ME48_SPETR|Spermophilus        P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
G3U2N9_LOXAF|Loxodonta           P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
E1BPA5_BOVIN|Bos                 P--GPPPLGPLARTL---QVALAAFQ-------------------LLNLLGNVGLFLRSD
F1RU50_PIG|Sus                   P--GPPPLGPLARTL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
F6ZZE9_HORSE|Equus               P--GPPPLGPLARTL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
G9KYT5_MUSPF|Mustela             P--GPPPLGPLARAL---QLVLAAFQ-------------------LLNLLGNVGLFLRSD
E2RIK9_CANFA|Canis               P--GPPPLGPLARAL---QLVLAAFQ-------------------LLNLLGNVGLFLRSD
D2HYA8_AILME|Ailuropoda          P--GPPPLGPLARAL---QLVLAAFQ-------------------LLNLLGNVGLFLRSD
F7I2B0_CALJA|Callithrix          S--RTPPDGPLARAF---QLALAAFQ-------------------MLNLLGNVGLFLRSD
G1R2S0_NOMLE|Nomascus            P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
ZDH24_HUMAN|Homo                 P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
G3RIT0_GORGO|Gorilla             P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
K7CBF0_PANTR|Pan                 P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
G7PP90_MACFA|Macaca              --------GPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
F7GVE4_MACMU|Macaca              P--GPPPLGPLARAL---QLALAAFQ-------------------LLNLLGNVGLFLRSD
H3BDY5_LATCH|Latimeria           P---SGSEGGVPKAV---HLCFMTFV-------------------LTNTIGNIIQFIKNS
Q6DG77_DANRE|Danio               PEQKKSDWSTIWTGL---HLFAQYFM-------------------LGNITWNASLFVKTN
B3DLR2_XENTR|Xenopus             PEQKKSDWSTIWTGL---HLFAQYFM-------------------LGNITWNAPLFVKTN
H2LCC6_ORYLA|Oryzias             AEQQKSEWSGWWKAV---HLLSQYFM-------------------LANICWNALLFVKTN
G3Q0C2_GASAC|Gasterosteus        PDQKKTVWSAWWKAV---HLLAQYFM-------------------LGNICWNAALFLRTS
I3JCL8_ORENI|Oreochromis         PDQKKTQWSSRWKLI---HLLAQYFM-------------------LGNICWNALLFMKTS
H2ULS9_TAKRU|Takifugu            PDQKKTIWSSRWKTA---HLISQYFM-------------------LINICWNAMLFIKTS
H3DHA6_TETNG|Tetraodon           ADQKKTVWSTRWKTA---HLISQYSM-------------------LVNICWNALLFVKTS
                                                                                             

A7SWQ7_NEMVE|Nematostella        TT----GAKLGMPSVL---KPG-------WAYCPFCQLNSPPRAYHC----HVCDICVLR
B4KT36_DROMO|Drosophila          IS--VDCDRIKSFDVNDE-CVN-------WRHCKICNALAPPRSWHC----ATCGTCILT
G3MTJ6_9ACAR|Amblyomma           TG--VRDVKTPSVL-----MPG-------WRYCAVCEVNAPPRSHHC----SVCNECILK
C3Z4Y6_BRAFL|Branchiostoma       TT--TGSHVLPSIL-----KPG-------WHFCASCEANAPPRSFHC----WECGTCILK
B3MMJ1_DROAN|Drosophila          PR--ADPKRMALELELAGGGKG-------WHECTECQMWVPPRSRHC----RICAVCVLK
B4NLE0_DROWI|Drosophila          TS--INIELLKPPLDPVQ-RIS-------WHKCDDCQAEVPPRCRHC----DICQICVLK
B4GD12_DROPE|Drosophila          TT--IRMELLKPPLDPDL-RAR-------WHMCNECQALVPPRSWHC----EVCNVCVLK
Q292N6_DROPS|Drosophila          TT--IRMELLKPPLDPDL-RAR-------WHMCNECQALVPPRSWHC----EVCNVCVLK
B3NRN6_DROER|Drosophila          TS--IRKELLKPPMDAEQ-LAR-------WHSCHDCQTLVPPRSWHC----EVCNVCVLK
Q0IGS7_DROME|Drosophila          TS--IRKELLKPPLDAAQ-LAR-------WHSCQDCQTLVPPRSWHC----EVCNVCVLK
B4P4K3_DROYA|Drosophila          TS--IRKELLKPPMDAGQ-LAR-------WHSCHDCQTLVPPRSWHC----EVCNVCVLK
B4J5B6_DROGR|Drosophila          TS--IKMVILKPPLEAHL-LSR-------WHMCDMCQTLVPPRAWHC----EVCNVCVLK
B4LLZ9_DROVI|Drosophila          TS--IKLHILKPPVDSHL-LSR-------WHMCDACQTLVPPRSWHC----EICNVCVLK
Q7PVS0_ANOGA|Anopheles           TSCSTELIQLPPAGVSTA-GAGTGLSSKSWHLCATCEFIAPPRSWHC----ASCRTCILK
B0WDA3_CULQU|Culex               TSCGTEVISVPPDVAVAS-GQG----SRSWHLCSTCEAVAPPRSWHC----NACRTCVLK
E2AAM9_CAMFO|Camponotus          TS--TKRRIVPVSTATV--ADG-------WRLCATCECLSPPRSWHC----NTCDTCILK
K7IP65_NASVI|Nasonia             TS--TQRVVVPTSKMNI--KEG-------WRLCAVCTSIAPPRSWHC----TTCDTCILK
G6CN66_DANPL|Danaus              PR--AREVLVRGR------PVK-------LKYCFTCKMFRPPRASHC----SLCDNCVDR
H9GE24_ANOCA|Anolis              PS--TRGVMLAGA------GQG-------WDYCYSCQTHVPPRCGHC----FSCNVCILR
F7E5D5_MONDO|Monodelphis         PG--IGGVLLAGRAV----GHG-------WDYCYQCQSQVPPRSGHC----PACRVCVLR
G3W4T3_SARHA|Sarcophilus         PS--GRGPSIPRF------CPS--------GYCYQCQSQVPPRSGHC----PACRVCVLR
ZDH24_MOUSE|Mus                  PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
ZDH24_RAT|Rattus                 PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
G1SD06_RABIT|Oryctolagus         PS--IRGVMLAGRGL----GQG-------WAYCHQCQ-QVPPRSGHC----PACRVCVLR
G5BWY5_HETGA|Heterocephalus      PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SVCRVCILR
L5KQT9_PTEAL|Pteropus            PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSRHC----STCRVCILR
G1QBQ1_MYOLU|Myotis              PS--IRGVMLAGHGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
H0VVK0_CAVPO|Cavia               PS--IRGVMLAGRGL----GQG-------WAFCYQCQSQVPPRSGHC----SACRVCILR
H0Y068_OTOGA|Otolemur            PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCVLR
I3ME48_SPETR|Spermophilus        PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRICILR
G3U2N9_LOXAF|Loxodonta           PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCVLR
E1BPA5_BOVIN|Bos                 PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRICILR
F1RU50_PIG|Sus                   PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRICILR
F6ZZE9_HORSE|Equus               PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
G9KYT5_MUSPF|Mustela             PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCVLR
E2RIK9_CANFA|Canis               PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
D2HYA8_AILME|Ailuropoda          PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
F7I2B0_CALJA|Callithrix          PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
G1R2S0_NOMLE|Nomascus            PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILA
ZDH24_HUMAN|Homo                 PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
G3RIT0_GORGO|Gorilla             PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
K7CBF0_PANTR|Pan                 PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
G7PP90_MACFA|Macaca              PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
F7GVE4_MACMU|Macaca              PS--IRGVMLAGRGL----GQG-------WAYCYQCQSQVPPRSGHC----SACRVCILR
H3BDY5_LATCH|Latimeria           PT--ISGVFLSRDGV----GQG-------WMYCYSCETHVPSRCFHC----PDCNVCVLR
Q6DG77_DANRE|Danio               PS--IRGVFLGGDTL----GQG-------WRYCYNCETHTPPRCSHC----YDCNVCVLR
B3DLR2_XENTR|Xenopus             PS--IRGVFLGGDTL----GQG-------WRYCYNCETHTPPRCSHC----YDCNVCVLR
H2LCC6_ORYLA|Oryzias             PS--IKGVFLGGDGL----GQG-------WRFLFSSSAPPPQKTPHTHNTQFQXKVCVLR
G3Q0C2_GASAC|Gasterosteus        PS--IKGVFLGGEGM----GQG-------WRYCYTCETHTPPRCSHC----YDCKVCVLR
I3JCL8_ORENI|Oreochromis         PS--IKGVFLGGEVL----GQG-------WRYCYTCEAHTPPRCSHC----YDCKVCVLR
H2ULS9_TAKRU|Takifugu            PS--IRGVFLGGEGM----GQG-------WRYCYNCETHTPPRCSHC----YDCKVCVLR
H3DHA6_TETNG|Tetraodon           PS--IKGVFLGGENV----GQG-------WRYCYTCETHTPP-CSHC----YDCKVCVLR
                                                                    .    *    *          *:  

A7SWQ7_NEMVE|Nematostella        RDHHCIFAGKCVGHSNYRYYLFLAFYLWLGALYANLFHW-EYVTSVMDNFT--LWTMFTM
B4KT36_DROMO|Drosophila          RDHHCNFTGCCIGHQNYRYFTCFVLYSFVLSSLLMFYNLKYFIWSMGQLTYHTHFSDMTF
G3MTJ6_9ACAR|Amblyomma           HDHHCMFTGRCIGFYNQRYFVVALLYMTVGVLYSLSYKF-PYVFEMLGGLN--VVTMIHM
C3Z4Y6_BRAFL|Branchiostoma       RIHHCTFTGNCAAWANQRYYIVFLLYMSIGAVYTNIMNF-DYVWDVMGGLT--VTSILTM
B3MMJ1_DROAN|Drosophila          RDHHCILTGCCVGHHNYRYFFYFVLYMFLASAISFVVGL-DFVYVHRAGNFE--------
B4NLE0_DROWI|Drosophila          RDHHCRFTGCCIGHYNYRYFFFFLLYLAIGSMISSIMGS-IFI-CLHLDIYWHLSTLLTV
B4GD12_DROPE|Drosophila          RDHHCRFTCCCIGHHNYRYFVYFLLYLMIGSFVAGILGG-IYLWNVHFDFFYRPFTLITV
Q292N6_DROPS|Drosophila          RDHHCRFTCCCIGHHNYRYFVYFLLYLMIGSFVAGILGG-IYLWNVHFDFFYRPFTLITV
B3NRN6_DROER|Drosophila          RDHHCRFTCCCIGHHNYRYFFYYLVYMIIGSLAAAIMES-IYLWHLHLDIYWRWSTLFTI
Q0IGS7_DROME|Drosophila          RDHHCRFTCCCIGHHNYRYFFYYLVYMIIGSLAAAIMES-IYLWHLHLDIYWRWSTLFTI
B4P4K3_DROYA|Drosophila          RDHHCRFTCCCIGHHNYRYFFYYLVYMIIGSLAAAIMES-IYLWHLHLDVYWRWSTLFTI
B4J5B6_DROGR|Drosophila          RDHHCRFTCCCIGHHNYRYFFYYLLYMCIGACYVSINAS-IYLWYLHADYYWRPYTLITI
B4LLZ9_DROVI|Drosophila          RDHHCRFTCCCIGHHNYRYFFYFLLYMGLGALYVSINAS-IYLWYLHADYYWRPYTLLTV
Q7PVS0_ANOGA|Anopheles           RDHHCVFTGCCIGHKNHRYFILFVVYLFISTLYASVLNN-YFLWFVRGEEFRNWTSLVKI
B0WDA3_CULQU|Culex               RDHHCVFTGCCIGHKNHRYFIMFVFHLFVATLYSSALNN-YFIWYIHGEEFRNWTSFIKM
E2AAM9_CAMFO|Camponotus          RDHHCVFTGCCVGHHNHRYFVMFLWYLFLGAAYAFSYGS-FFIWTRTSFEFP--MSVIKM
K7IP65_NASVI|Nasonia             RDHHCIFTACCVGHYNHRYFLMFIFYLFVATVYSFAYNN-FFIWSRIHFEFP--MTIVKL
G6CN66_DANPL|Danaus              FDHHCPWVGNCVGKRNYRYFYLFVVSLSFLAVWVFACAV-THLALLARGAGL-AAALRAT
H9GE24_ANOCA|Anolis              RDHHCTLLGQCLGYQNYRYFLSLLLHGAVLLLCCAVLNA-DVVWTLLQEKPL-AQTVLLL
F7E5D5_MONDO|Monodelphis         RDHHCMLLGRCVGFSNYRPFLCLLLHGLGLLLHVTALLG-PALAAVLRAHSP-PHALTVL
G3W4T3_SARHA|Sarcophilus         RDHHCLLLGRCVGFSNYRPFLCLLLHGAGLLLHVTALLG-PALGLLLRAHSQ-LHAVTLL
ZDH24_MOUSE|Mus                  RDHHCRLLGCCVGFHNYRPFLCLLLHSAGVLLHISVLLG-PALSALLQAHSA-LYTVALL
ZDH24_RAT|Rattus                 RDHHCRLLGRCVGFHNYRPFLCLLLHAAGVLLHISVLLS-PALSALLQAHSA-LYTVALL
G1SD06_RABIT|Oryctolagus         RDHHCRLLDRCVGFHNYRPFLCLLLHAAGVLLHVSVLLG-PALAALLHAQAP-LHTAALL
G5BWY5_HETGA|Heterocephalus      RDHHCRLLGRCVGFHNYRHFLCLLLHATGVLLHVSVLLG-PALSALLQAHAP-LHTAALL
L5KQT9_PTEAL|Pteropus            RDHHCLLLGRCVGFHNYRPFLCLLLHASGVLLHVSVLLG-PALSALLRAHSL-LHTAALL
G1QBQ1_MYOLU|Myotis              RDHHCRLLGRCVGFHNYRPFLCLLLHGAGILLHVSVLLG-PALAALLQAHTP-LHTAALL
H0VVK0_CAVPO|Cavia               RDHHCRLLGRCVGFHNYRHFLCLLLHASGVLLHVSVLLG-PALSALLRAHAP-LHTAALL
H0Y068_OTOGA|Otolemur            RDHHCRLLGRCVGFGNYRPFLCLLLHGAGVLLHISVLLG-PALSALLRAHSP-LHTAALL
I3ME48_SPETR|Spermophilus        RDHHCRLLGRCVGFRNYRPFLCLLLHGAGVLLHISVLLG-PALSALLRAHSL-LHTAALL
G3U2N9_LOXAF|Loxodonta           RDHHCRLLGRCVGFRNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHAP-LHAATLL
E1BPA5_BOVIN|Bos                 RDHHCRLLGRCVGFRNYRPFLCLLLHGAGVLLHASVLLG-PALSALLRAHTP-LHTAALL
F1RU50_PIG|Sus                   RDHHCRLLGRCVGFHNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHTP-LHTAALL
F6ZZE9_HORSE|Equus               RDHHCRLLGRCVGFRNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHAP-LHTAALL
G9KYT5_MUSPF|Mustela             RDHHCRLLGRCVGFRNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHAP-LHTAALL
E2RIK9_CANFA|Canis               RDHHCRLLGRCVGFHNYRPFLCLLLHAAGVLLHISVLLG-PALSALLRAHAP-LHTAALL
D2HYA8_AILME|Ailuropoda          RDHHCRLLGRCVGFRNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHAP-LHTAALL
F7I2B0_CALJA|Callithrix          RDHHCRLLGRCVGFSNYRPFLCLLLHATGVLLHISVLLG-PALSALLRAHTP-LHMAALL
G1R2S0_NOMLE|Nomascus            SDHH--------------------------------------------------------
ZDH24_HUMAN|Homo                 RDHHCRLLGRCVGFGNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHTP-LHMAALL
G3RIT0_GORGO|Gorilla             RDHHCRLLGRCVGFGNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHTP-LHMAALL
K7CBF0_PANTR|Pan                 RDHHCRLLGRCVGFGNYRPFLCLLLHAAGVLLHVSVLLG-PALSALLRAHTP-LHMAALL
G7PP90_MACFA|Macaca              RDHHCRLLGRCVGFGNYRPFLCLLLHAAGVLLHISVLLG-PALSALLRAHTP-LHMAALL
F7GVE4_MACMU|Macaca              RDHHCRLLGRCVGFGNYRPFLCLLLHAAGVLLHISVLLG-PALSALLRAHTP-LHMAALL
H3BDY5_LATCH|Latimeria           RDHHCVFYGQCVGHRNYRYFLCALLYTWVALLYAMVLNMEVFLAIIQEGVT--LRTVLML
Q6DG77_DANRE|Danio               RDHHCVFFGQCVGFHNYRYFLTCLLFMWAGLLYAVVMNAEVFIFILKEGVT--FHSVMLL
B3DLR2_XENTR|Xenopus             RDHHCVFFGQCVGFHNYRYFLTCLLFMWAGLLYAVVMNAEVFIFILKEGVT--FHSVMLL
H2LCC6_ORYLA|Oryzias             RDHHCVFFGQCVGFRNYRYFLSCLLFMWSGLLYAVVMNAEVFMVILKEGVT--LHSILLL
G3Q0C2_GASAC|Gasterosteus        RDHHCVFFGQCVGFRNYRYFLSCLFFMWSGLLYATLMNAEVFIVILKEGVT--MHSVLLM
I3JCL8_ORENI|Oreochromis         RDHHCVFFGQCVGFRNYRYFLSCLFFMWSGLLYATLMNAEVFIVILKEGVT--VHSILLL
H2ULS9_TAKRU|Takifugu            RDHHCVFFGQCVGFRNYRYFLSCLLFMWSGLLYATLMNAEVFLVILKEGVT--VHSVLLL
H3DHA6_TETNG|Tetraodon           RDHHCVFFGQCVGFRNYRYLSC-LLFMWTGLLYATLMNAEVFIVILKEGVT--VHSILLL
                                   **                                                        

A7SWQ7_NEMVE|Nematostella        FMPMLSWMLGYTTIYQTFVTFITAISLFAFVMF-SGLLFFQLNIIARGQTSYERK-RKRR
B4KT36_DROMO|Drosophila          L--------------QILHNSVFTLNLIYQIFS-TGMIILHAPFVLKGELIGERNLKDKH
G3MTJ6_9ACAR|Amblyomma           MAPHFGLLLGLYDFWLFLCTIVNLIELVVLCLC-AYLLTVELTCMARNQTTYEKS-HGIK
C3Z4Y6_BRAFL|Branchiostoma       FAPLVMWIAGQAKAHTFFVSIMSMVCLIGGAFS-LVLFYYHSKLTVMNRTVFEFN-KRIS
B3MMJ1_DROAN|Drosophila          FFPIYVS----------LFVIVIIMSLLFMVMS-GCILYKQWPAIRYGATSLEAE-AHNF
B4NLE0_DROWI|Drosophila          FAPAVSLA--LNANWMSFYLLICELSLLSFCTT-SLLLVYHSDIFKRGTVVKE---RGTS
B4GD12_DROPE|Drosophila          FVPAVSLT--LSPSWESFYLLTYLLTWLAFSISTSLLLVYHWPILKLGSVAKE---RRSR
Q292N6_DROPS|Drosophila          FVPAVSLT--LSPSWESFYLLTYLLTWLAFSISTSLLLVYHWPILKLGSVAKE---RRSR
B3NRN6_DROER|Drosophila          FAPVVSVM--LSPSWEAFYLVIYDLTLLGFGIS-SLLLVFHWSIFKSGSVTRE---RGTR
Q0IGS7_DROME|Drosophila          FAPVVSLM--LSPSWESFYLVIYDLTLLGFAIS-SLLLVFHWSIFKSGSVTRE---RGTR
B4P4K3_DROYA|Drosophila          FAPVVSLL--LSPSWESFYLVIYDLTLLGFAIS-SLLLVFHWSIFKSGAVTRE---RGTR
B4J5B6_DROGR|Drosophila          FVPALSLT--VHASWENFYVVIYELNLLAFGMS-TLLLIYHLPMFKRGAVMKE---RQST
B4LLZ9_DROVI|Drosophila          FVPALSLT--VHASWENFYVVLYELNLLAFCMC-TLLLVYHRPIFQRGAVMKE---RSTS
Q7PVS0_ANOGA|Anopheles           VFPLAMLL--IDTSTKQYYLVIYLINMVGVMFT-GVLLIYHGRLILSGAVVHE---RKAP
B0WDA3_CULQU|Culex               VFPLAMLV--IDASTKQYYLVIYLINMIGMLFT-GVLLIYHGRLILSGSVVHE---QNGR
E2AAM9_CAMFO|Camponotus          VFPVAIFFFGFDSSIDQFYLLLYVVSAVGTLYT-AVLCIYHFNLILRGVVGNESN-KKDF
K7IP65_NASVI|Nasonia             VFPVAIFIFGFDGSMEQFYLMLYIVTVIGMLFT-GALCVYHFNLLFNGCTSDERN-KKNY
G6CN66_DANPL|Danaus              PASAVAAAVCFLSVWSVLGLAGFHTYLASTDQT--TNEDIKGSFSRRGSGG-----AGTN
H9GE24_ANOCA|Anolis              VLPWLMLLTGQVNFTAFFFAVVTDACLAGCLFC-AGFLFFHSLLVLRGQTTKEWF-EGDR
F7E5D5_MONDO|Monodelphis         LLPWLMLVTGGITLGQFALTFVADTCVAGALLC-GAGLLFHGRLLLRGQTTREWA-HDLR
G3W4T3_SARHA|Sarcophilus         LLPWLMLLTGE-GRGGSGAXFIADTCVAGALLC-GAGLLFHGMLLLRGQTTREWA-HGQR
ZDH24_MOUSE|Mus                  LLPWLMLLTGKVSLAQFALAFVVDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGHH
ZDH24_RAT|Rattus                 LLPWLMLLTGKVSLAQFALAFVVDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
G1SD06_RABIT|Oryctolagus         LLPWLMLLTGRVSLAQFALAFVMDTCVAGALLC-AAGLLFHGMLLLRGQTTWEWA-RGQH
G5BWY5_HETGA|Heterocephalus      LLPWLMLLTGRVSLAQFALAFVMDTCVAGALLC-GAGLLFHGTLLLRGQTTWEWA-RGQH
L5KQT9_PTEAL|Pteropus            LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
G1QBQ1_MYOLU|Myotis              LLPWLMLLTGRVSLAQFALAFVTDTCVAGALFC-GAGLLFHGMLLLRGQTTWEWA-RGQH
H0VVK0_CAVPO|Cavia               LLPWLMLLTGRVSLAQFALAFVMDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
H0Y068_OTOGA|Otolemur            LLPWLMLLTGRVSLAQFALAFVMDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
I3ME48_SPETR|Spermophilus        LLPWLMLLTGRVSLAQFTLAFVMDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
G3U2N9_LOXAF|Loxodonta           LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGLLLLRGQTTWEWA-RGQH
E1BPA5_BOVIN|Bos                 LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
F1RU50_PIG|Sus                   LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
F6ZZE9_HORSE|Equus               LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
G9KYT5_MUSPF|Mustela             LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
E2RIK9_CANFA|Canis               LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
D2HYA8_AILME|Ailuropoda          LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
F7I2B0_CALJA|Callithrix          LLPWLMLLTGRVSLAQFALAFVMDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
G1R2S0_NOMLE|Nomascus            ------------------------------------------------------------
ZDH24_HUMAN|Homo                 LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
G3RIT0_GORGO|Gorilla             LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
K7CBF0_PANTR|Pan                 LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
G7PP90_MACFA|Macaca              LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
F7GVE4_MACMU|Macaca              LLPWLMLLTGRVSLAQFALAFVTDTCVAGALLC-GAGLLFHGMLLLRGQTTWEWA-RGQH
H3BDY5_LATCH|Latimeria           IMPWLMFMTGQVSPSAFLFAFVADTCVVGFLFV-STVLALHAYLSSHGQTTREWL-ANNH
Q6DG77_DANRE|Danio               LVPWIMLVSGQVTTRAFAFAFIADTCVVGFLLV-AAFLFFHVALMLRGQTTREWY-STRR
B3DLR2_XENTR|Xenopus             LVPWIMLVSGQVTTRAFAFAFIADTCIVGFLLV-AAFLFFHVALMLRGQTTREWY-STRR
H2LCC6_ORYLA|Oryzias             LVPWIMLVSGQVSARAFAFAFIADTCVVGFLLV-SAFFFFHLILLCRGQTTREWY-SSRR
G3Q0C2_GASAC|Gasterosteus        LIPWIMLVSGQVTARAFAFAFIADTCVVGFLLV-SAFFFFHLALMLRGQTTREWY-STRR
I3JCL8_ORENI|Oreochromis         LIPWIMLVSGQVSARAFAFAFIADTCVVGFLLV-SSFFFFHLFLLFRGQTTREWY-SSRR
H2ULS9_TAKRU|Takifugu            LIPWIMLISGQVSPRAFAFAFIADTCVVGFLLV-SAFFFFHLVLMFRGQTTREWY-SSRR
H3DHA6_TETNG|Tetraodon           LIPWIMLISGQVSARAFAFAFIADTCVVGFLLV-SAFFFFH-LFLMRGQTTREWY-SSRR
                                                                                             

A7SWQ7_NEMVE|Nematostella        IYDKG------------------------WLRNFIEVLGENWFLSWIWPKITSPLP----
B4KT36_DROMO|Drosophila          NYDAG------------------------IYYNLRGIFGQHMHVAWIFPLFASQLP----
G3MTJ6_9ACAR|Amblyomma           TYSMG------------------------LRRNLRESLGAFWFLVWLSPWIKSPVS----
C3Z4Y6_BRAFL|Branchiostoma       DYDLG------------------------WQQNLEQAFGTRWQLVWLFPLLPSPLL----
B3MMJ1_DROAN|Drosophila          QYNLG------------------------VLGNLRMFLGKWMVLTWISPFIPSPLP----
B4NLE0_DROWI|Drosophila          RWNLG------------------------LHGNSQMVLGKRMHITWLSPFIRSDLP----
B4GD12_DROPE|Drosophila          NYDLG------------------------LRANMEMIFGRRMYLTWLSPFVHSELP----
Q292N6_DROPS|Drosophila          NYDLG------------------------LRANMEMIFGRRMYLTWLSPFVHSELP----
B3NRN6_DROER|Drosophila          KYDRG------------------------LRGNLEMVLGRRMHLTWLSPFLRSDLP----
Q0IGS7_DROME|Drosophila          KYDRG------------------------LRGNLEMVLGKRMHLTWLSPFLRSDLP----
B4P4K3_DROYA|Drosophila          KYDRG------------------------LRGNLEMVLGKRMHLTWLSPFLRSDLP----
B4J5B6_DROGR|Drosophila          KYDLG------------------------LRANCEMVLGKRMHWTWLSPFVRSDLP----
B4LLZ9_DROVI|Drosophila          KYDLG------------------------LRANMEMVLGKRMHLTWISPFVRSDLP----
Q7PVS0_ANOGA|Anopheles           EYDMG------------------------RAENLRMVLGNRWYIAWLSPFVASELP----
B0WDA3_CULQU|Culex               DFDLG------------------------RMENLRMVLGERWHLAWLSPFVRSDLP----
E2AAM9_CAMFO|Camponotus          TYDMG------------------------WKDNVREVFGERWYLAWLLPYIKSQLP----
K7IP65_NASVI|Nasonia             SYSLG------------------------WKQNIKEVFGDKWYLVWLIPYVPSKLP----
G6CN66_DANPL|Danaus              PYSRGNACANCWHVLCGPLAPSLIDRRGVLSSDTRDDLPPRFAHIMCVPPAPAPGPPAVP
H9GE24_ANOCA|Anolis              KYNMG------------------------WRANLREVLGKRWHLALFTPFVASPLP----
F7E5D5_MONDO|Monodelphis         LYDLG------------------------PRHNLRAALGSRWALVWLWPFLASPLP----
G3W4T3_SARHA|Sarcophilus         LYDLG------------------------PRRNMEAALGSRWLLVWLWPFLSSPLP----
ZDH24_MOUSE|Mus                  CYDLG------------------------TCHNLQAALGPRWALVWFWPFLASPLP----
ZDH24_RAT|Rattus                 SYDLG------------------------MSHNLQAALGPRWALVWFWPFLASPLP----
G1SD06_RABIT|Oryctolagus         AYNLG------------------------PCHNLQAALGPRWALVWLWPFLASPLP----
G5BWY5_HETGA|Heterocephalus      SYDQG------------------------ARHNLQAALGPRWALIWLWPFLTSPLP----
L5KQT9_PTEAL|Pteropus            FYDLG------------------------PYHNLQAALGPRWILVWLWPFLASPLP----
G1QBQ1_MYOLU|Myotis              SYDLG------------------------PCHNLQAALGPRWILVWLWPFLASPLP----
H0VVK0_CAVPO|Cavia               SYDLG------------------------ARHNLQAALGPRWALVWLWPFLASPLP----
H0Y068_OTOGA|Otolemur            SYDLG------------------------LCHNLQAALGPRWALVWLWPFLDSPLP----
I3ME48_SPETR|Spermophilus        SYDLG------------------------PCHNLQAALGPRWALVWLWPFLASPLP----
G3U2N9_LOXAF|Loxodonta           SYDLG------------------------PYHNLQEALGPRWVLVWLWPFLASPLP----
E1BPA5_BOVIN|Bos                 AYDLG------------------------PCHNLQAALGPRWVLVWLWPFLASPLP----
F1RU50_PIG|Sus                   SYDLG------------------------PCHNLQAALGPRWVLVWLWPFLASPLP----
F6ZZE9_HORSE|Equus               SYDLG------------------------PYHNLQAALGPRWVLVWLWPFLASPLP----
G9KYT5_MUSPF|Mustela             SYDLG------------------------PCHNLQAALGPRWVLVWLWPFLASPLP----
E2RIK9_CANFA|Canis               SYDLG------------------------PCHNLQAALGPRWVLVWLWPFLASPLP----
D2HYA8_AILME|Ailuropoda          SYDLG------------------------PCHNLEAALGPRWVLVWLWPFLASPLP----
F7I2B0_CALJA|Callithrix          SYDLG------------------------LCHNLQAALGPRWVLVWLWPFLASPLP----
G1R2S0_NOMLE|Nomascus            ------------------------------------------------------------
ZDH24_HUMAN|Homo                 SYDLG------------------------PCHNLQAALGPRWALVWLWPFLASPLP----
G3RIT0_GORGO|Gorilla             SYDLG------------------------PCHNLQAALGPRWALVWLWPFLASPLP----
K7CBF0_PANTR|Pan                 SYDLG------------------------PCHNLQAALGPRWALVWLWPFLASPLP----
G7PP90_MACFA|Macaca              SYDLG------------------------PCHNLQAALGPRWALVWLWPFLASPLP----
F7GVE4_MACMU|Macaca              SYDLG------------------------PCHNLQAALGPRWALVWLWPFLASPLP----
H3BDY5_LATCH|Latimeria           QYDLG------------------------WQQNLQEALGERWYLVWIFPFITSPLP----
Q6DG77_DANRE|Danio               PYSLG------------------------TMANIRECLGKNWYFCWLCPLIPSPLP----
B3DLR2_XENTR|Xenopus             PYSLG------------------------TMANIRECLGKNWYFCWLCPLIPSPLP----
H2LCC6_ORYLA|Oryzias             PYSLG------------------------LLGNLRHTLGLRWHLCWLCPLIPSPMP----
G3Q0C2_GASAC|Gasterosteus        PYSLG------------------------LLGNLRHTLGLRWYLCWLCPLIPSPLP----
I3JCL8_ORENI|Oreochromis         PYSLG------------------------LFGNLHHTLGLRWYICWLCPLIPSPLP----
H2ULS9_TAKRU|Takifugu            PYSLG------------------------VMGNLYHTLGLRWYVCWLCPLIPSPLP----
H3DHA6_TETNG|Tetraodon           PYSLG------------------------VLGNLYHTLGLRWYICWLCPLIPSPLP----
                                                                                             

A7SWQ7_NEMVE|Nematostella        ----------------------------HNGTDYT-----------------QACNEEL-
B4KT36_DROMO|Drosophila          ----------------------------GDGYNWK---------LTTKDKSTETIATIR-
G3MTJ6_9ACAR|Amblyomma           ----------------------------GDGLHFD--------------GSVVCIKADG-
C3Z4Y6_BRAFL|Branchiostoma       ----------------------------GNGLEFP------------------VNSDVSE
B3MMJ1_DROAN|Drosophila          ----------------------------LDGVHWEVTNREKLSSNQRNRQLSQKKTEKG-
B4NLE0_DROWI|Drosophila          ----------------------------HNGINWE-------------------------
B4GD12_DROPE|Drosophila          ----------------------------HDGINWE------------------PVLTHL-
Q292N6_DROPS|Drosophila          ----------------------------HDGINWE------------------PVLTHL-
B3NRN6_DROER|Drosophila          ----------------------------HDGVNWV------------------PIAAFS-
Q0IGS7_DROME|Drosophila          ----------------------------HDGMNWE------------------PIAAFS-
B4P4K3_DROYA|Drosophila          ----------------------------HDGVNWD------------------PIAAFS-
B4J5B6_DROGR|Drosophila          ----------------------------HDGVNWL------------------P----G-
B4LLZ9_DROVI|Drosophila          ----------------------------HDGVNWE------------------PATKEE-
Q7PVS0_ANOGA|Anopheles           ----------------------------HNGVNWE------------------TLQKQT-
B0WDA3_CULQU|Culex               ----------------------------HNGVDWD------------------RVQREA-
E2AAM9_CAMFO|Camponotus          ----------------------------HDGISWH---------------------YLC-
K7IP65_NASVI|Nasonia             ----------------------------QDGVSWH-------------------RSSKWN
G6CN66_DANPL|Danaus              APLATSHSPAPTHRNGALGGSYTNLFEGGDATRHA-------------------YTNHSL
H9GE24_ANOCA|Anolis              ----------------------------GDGITFR------------------TRPPKSE
F7E5D5_MONDO|Monodelphis         ----------------------------GDGITFQ-------------------------
G3W4T3_SARHA|Sarcophilus         ----------------------------GDGITFQ------------------T------
ZDH24_MOUSE|Mus                  ----------------------------GDGISFQ------------------TPGDVG-
ZDH24_RAT|Rattus                 ----------------------------GDGITFQ------------------TPTDVG-
G1SD06_RABIT|Oryctolagus         ----------------------------GDGITFP------------------TAAEVG-
G5BWY5_HETGA|Heterocephalus      ----------------------------GDGITFQ------------------TTADVG-
L5KQT9_PTEAL|Pteropus            ----------------------------GDGITFQ------------------TAADMR-
G1QBQ1_MYOLU|Myotis              ----------------------------GDGITFQ------------------TTADVG-
H0VVK0_CAVPO|Cavia               ----------------------------GDGITFQ------------------TTADVG-
H0Y068_OTOGA|Otolemur            ----------------------------GDGITFQ------------------TKADMG-
I3ME48_SPETR|Spermophilus        ----------------------------GDGITFH------------------TTADVG-
G3U2N9_LOXAF|Loxodonta           ----------------------------GDGISFQ------------------TPADRG-
E1BPA5_BOVIN|Bos                 ----------------------------GDGITFQ------------------TAADVG-
F1RU50_PIG|Sus                   ----------------------------GDGITFQ------------------TAADVG-
F6ZZE9_HORSE|Equus               ----------------------------GDGITFQ------------------TTADVG-
G9KYT5_MUSPF|Mustela             ----------------------------GDGVTFQ------------------TAADMG-
E2RIK9_CANFA|Canis               ----------------------------GDGITFQ------------------TAADVG-
D2HYA8_AILME|Ailuropoda          ----------------------------GDGITFQ------------------TAADVG-
F7I2B0_CALJA|Callithrix          ----------------------------GDGITFQ------------------TTADVG-
G1R2S0_NOMLE|Nomascus            ------------------------------------------------------------
ZDH24_HUMAN|Homo                 ----------------------------GDGITFQ------------------TTADVG-
G3RIT0_GORGO|Gorilla             ----------------------------GDGITFQ------------------TTADVG-
K7CBF0_PANTR|Pan                 ----------------------------GDGITFQ------------------TTADVG-
G7PP90_MACFA|Macaca              ----------------------------GDGITFQ------------------TTADVG-
F7GVE4_MACMU|Macaca              ----------------------------GDGITFQ------------------TTADVG-
H3BDY5_LATCH|Latimeria           ----------------------------GDGVSFK------------------RRPDLAQ
Q6DG77_DANRE|Danio               ----------------------------GDGINFK------------------VTASLE-
B3DLR2_XENTR|Xenopus             ----------------------------GDGINFK------------------VTASLE-
H2LCC6_ORYLA|Oryzias             ----------------------------GDGIHFQ------------------VTGSLE-
G3Q0C2_GASAC|Gasterosteus        ----------------------------GDGISFQ------------------VTGPLE-
I3JCL8_ORENI|Oreochromis         ----------------------------GDGINFQ------------------VTGSLE-
H2ULS9_TAKRU|Takifugu            ----------------------------GDGISFQ------------------VTGSLE-
H3DHA6_TETNG|Tetraodon           ----------------------------GDGISFR------------------VTGSLE-
                                                                                             

A7SWQ7_NEMVE|Nematostella        -PKDM-----------------------------------------
B4KT36_DROMO|Drosophila          -SRPTV----------------------------------------
G3MTJ6_9ACAR|Amblyomma           -EKQE-----------------------------------------
C3Z4Y6_BRAFL|Branchiostoma       AVKDM-----------------------------------------
B3MMJ1_DROAN|Drosophila          -AARDSKNGGTWLWATPKLTPGQTKARKEHTRMAMDEGQEGGEMIK
B4NLE0_DROWI|Drosophila          -TKED-----------------------------------------
B4GD12_DROPE|Drosophila          -TKDD-----------------------------------------
Q292N6_DROPS|Drosophila          -TKDD-----------------------------------------
B3NRN6_DROER|Drosophila          -PKEE-----------------------------------------
Q0IGS7_DROME|Drosophila          -PKEE-----------------------------------------
B4P4K3_DROYA|Drosophila          -PKEE-----------------------------------------
B4J5B6_DROGR|Drosophila          -PKKD-----------------------------------------
B4LLZ9_DROVI|Drosophila          ----------------------------------------------
Q7PVS0_ANOGA|Anopheles           -LKSK-----------------------------------------
B0WDA3_CULQU|Culex               -AKSK-----------------------------------------
E2AAM9_CAMFO|Camponotus          -SKKD-----------------------------------------
K7IP65_NASVI|Nasonia             MNNSKCK---------------------------------------
G6CN66_DANPL|Danaus              EPEPVPLQEVAVAAALSASRLRLLHDTTMIDAALDLDDPVAPAAAL
H9GE24_ANOCA|Anolis              PLLKT-----------------------------------------
F7E5D5_MONDO|Monodelphis         -TTQD-----------------------------------------
G3W4T3_SARHA|Sarcophilus         ----------------------------------------------
ZDH24_MOUSE|Mus                  -LVTS-----------------------------------------
ZDH24_RAT|Rattus                 -LVTS-----------------------------------------
G1SD06_RABIT|Oryctolagus         -LAAS-----------------------------------------
G5BWY5_HETGA|Heterocephalus      -LMAS-----------------------------------------
L5KQT9_PTEAL|Pteropus            -LMAS-----------------------------------------
G1QBQ1_MYOLU|Myotis              -LVAS-----------------------------------------
H0VVK0_CAVPO|Cavia               -LLVS-----------------------------------------
H0Y068_OTOGA|Otolemur            -LMAS-----------------------------------------
I3ME48_SPETR|Spermophilus        -LMAS-----------------------------------------
G3U2N9_LOXAF|Loxodonta           -LMAS-----------------------------------------
E1BPA5_BOVIN|Bos                 -LMAS-----------------------------------------
F1RU50_PIG|Sus                   -LTAS-----------------------------------------
F6ZZE9_HORSE|Equus               -LMAS-----------------------------------------
G9KYT5_MUSPF|Mustela             -L--------------------------------------------
E2RIK9_CANFA|Canis               -LTPS-----------------------------------------
D2HYA8_AILME|Ailuropoda          -LVAS-----------------------------------------
F7I2B0_CALJA|Callithrix          -RTAS-----------------------------------------
G1R2S0_NOMLE|Nomascus            ----------------------------------------------
ZDH24_HUMAN|Homo                 -HTAS-----------------------------------------
G3RIT0_GORGO|Gorilla             -HTAS-----------------------------------------
K7CBF0_PANTR|Pan                 -HTAS-----------------------------------------
G7PP90_MACFA|Macaca              -HTAS-----------------------------------------
F7GVE4_MACMU|Macaca              -HTAS-----------------------------------------
H3BDY5_LATCH|Latimeria           LPAKQFYP--------------------------------------
Q6DG77_DANRE|Danio               -PKKQAVH--------------------------------------
B3DLR2_XENTR|Xenopus             -PKKQAVH--------------------------------------
H2LCC6_ORYLA|Oryzias             -PTRQFVF--------------------------------------
G3Q0C2_GASAC|Gasterosteus        -PARSSVH--------------------------------------
I3JCL8_ORENI|Oreochromis         -PSR------------------------------------------
H2ULS9_TAKRU|Takifugu            -P--------------------------------------------
H3DHA6_TETNG|Tetraodon           -PPH------------------------------------------
                                                                               
