MUSCLE (3.8) multiple sequence alignment


A7S6A3_NEMVE|Nematostella         ------------------------------------------------------------
H2V2C9_TAKRU|Takifugu             ------------------------------------------------------------
H3AQ09_LATCH|Latimeria            ------------------------------------------------------------
G7PCM0_MACFA|Macaca               ------------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          ------------------------------------------------------------
F6XXZ8_MONDO|Monodelphis          ------------------------------------------------------------
F1QRT3_DANRE|Danio                ------------------------------------------------------------
H2LTT9_ORYLA|Oryzias              ------------------------------------------------------------
G3NDP2_GASAC|Gasterosteus         ------------------------------------------------------------
I3KAB2_ORENI|Oreochromis          ------------------------------------------------------------
H3CRV3_TETNG|Tetraodon            ------------------------------------------------------------
Q28H20_XENTR|Xenopus              ------------------------------------------------------------
F7EKK0_ORNAN|Ornithorhynchus      ------------------------------------------------------------
G1KB70_ANOCA|Anolis               ------------------------------------------------------------
K7FJ57_PELSI|Pelodiscus           ------------------------------------------------------------
G1NQF0_MELGA|Meleagris            ------------------------------------------------------------
F1P165_CHICK|Gallus               ------------------------------------------------------------
H0ZMC3_TAEGU|Taeniopygia          ------------------------------------------------------------
I3LAG4_PIG|Sus                    ------------------------------------------------------------
L5L6V4_PTEAL|Pteropus             MSPHCGGLCLIYPSSESLDNKGGGFTTPQPKEKEWRARCSVISHAKNLGRSRMSRDSGRD
I3M6N4_SPETR|Spermophilus         ------------------------------------------------------------
ZDH20_MOUSE|Mus                   ------------------------------------------------------------
H0WAG6_CAVPO|Cavia                ------------------------------------------------------------
G5B3L9_HETGA|Heterocephalus       ------------------------------------------------------------
F7DV21_HORSE|Equus                ------------------------------------------------------------
ZDH20_BOVIN|Bos                   ------------------------------------------------------------
G3SXI8_LOXAF|Loxodonta            ------------------------------------------------------------
H0XAJ4_OTOGA|Otolemur             ------------------------------------------------------------
G1PP97_MYOLU|Myotis               ------------------------------------------------------------
G3SCT5_GORGO|Gorilla              ------------------------------------------------------------
G9KYT3_MUSPF|Mustela              ------------------------------------------------------------
G1LWV6_AILME|Ailuropoda           ------------------------------------------------------------
E2REV5_CANFA|Canis                ------------------------------------------------------------
G1SFG2_RABIT|Oryctolagus          ------------------------------------------------------------
F7IAP1_CALJA|Callithrix           ------------------------------------------------------------
H2Q799_PANTR|Pan                  ------------------------------------------------------------
F7E5B8_MACMU|Macaca               ------------------------------------------------------------
ZDH20_HUMAN|Homo                  ------------------------------------------------------------
H2NJD5_PONAB|Pongo                ------------------------------------------------------------
G1RS44_NOMLE|Nomascus             ------------------------------------------------------------
C3XW62_BRAFL|Branchiostoma        ------------------------------------------------------------
L7MB41_9ACAR|Rhipicephalus        ------------------------------------------------------------
G6DE89_DANPL|Danaus               ------------------------------------------------------------
E2A927_CAMFO|Camponotus           ------------------------------------------------------------
K7J025_NASVI|Nasonia              ------------------------------------------------------------
B4KLJ9_DROMO|Drosophila           ------------------------------------------------------------
B4LM13_DROVI|Drosophila           ------------------------------------------------------------
B4J5A2_DROGR|Drosophila           ------------------------------------------------------------
B4GB93_DROPE|Drosophila           ------------------------------------------------------------
B5E0C5_DROPS|Drosophila           ------------------------------------------------------------
B4MQW5_DROWI|Drosophila           ------------------------------------------------------------
B3MD30_DROAN|Drosophila           ------------------------------------------------------------
B3N6S2_DROER|Drosophila           ------------------------------------------------------------
Q7K2V5_DROME|Drosophila           ------------------------------------------------------------
B4NX32_DROYA|Drosophila           ------------------------------------------------------------
Q7Q7Z4_ANOGA|Anopheles            ------------------------------------------------------------
B0WC84_CULQU|Culex                ------------------------------------------------------------
                                                                                              

A7S6A3_NEMVE|Nematostella         ------------------------------------------------MSA---------
H2V2C9_TAKRU|Takifugu             -------------------------------------------------MA---------
H3AQ09_LATCH|Latimeria            ------------------------------------------SSPQE-------------
G7PCM0_MACFA|Macaca               ------------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          ----------------------------------------------DVKGT---------
F6XXZ8_MONDO|Monodelphis          -------------------------------------------------MT---------
F1QRT3_DANRE|Danio                ------------------------------------------XRMSGSHPSLPVFCSQGR
H2LTT9_ORYLA|Oryzias              -----------------------------------------------RKMA---------
G3NDP2_GASAC|Gasterosteus         -------------------------------------------------MA---------
I3KAB2_ORENI|Oreochromis          --------------------MARLTSLFHIFCYRDVTCRHSLLHSRGGKMA---------
H3CRV3_TETNG|Tetraodon            -------------------------------------------------MA---------
Q28H20_XENTR|Xenopus              -------------------------------------------------MA---------
F7EKK0_ORNAN|Ornithorhynchus      -------------------------------------------------VV---------
G1KB70_ANOCA|Anolis               ------------------------------------------------------------
K7FJ57_PELSI|Pelodiscus           ------------------------------------------------------------
G1NQF0_MELGA|Meleagris            ------------------------------------------------------------
F1P165_CHICK|Gallus               ------------------------------------------------------------
H0ZMC3_TAEGU|Taeniopygia          ------------------------------------------------------------
I3LAG4_PIG|Sus                    ------------------------------------------------------------
L5L6V4_PTEAL|Pteropus             GRDAAGCWAAVATVNECIPSSELRVAKLTSLCPAPLHSRLLRDARQDKSQR---------
I3M6N4_SPETR|Spermophilus         ------------------------------------------------------------
ZDH20_MOUSE|Mus                   -------------------------------------------------MA---------
H0WAG6_CAVPO|Cavia                ------------------------------------------------------------
G5B3L9_HETGA|Heterocephalus       -------------------------------------------------MA---------
F7DV21_HORSE|Equus                ------------------------------------------------------------
ZDH20_BOVIN|Bos                   -------------------------------------------------MA---------
G3SXI8_LOXAF|Loxodonta            ------------------------------------------------------------
H0XAJ4_OTOGA|Otolemur             -------------------------------------------------MA---------
G1PP97_MYOLU|Myotis               -------------------------------------------------MA---------
G3SCT5_GORGO|Gorilla              -------------------------------------------------MA---------
G9KYT3_MUSPF|Mustela              ------------------------------------------------------------
G1LWV6_AILME|Ailuropoda           -------------------------------------------------MA---------
E2REV5_CANFA|Canis                -------------------------------------------------MA---------
G1SFG2_RABIT|Oryctolagus          -------------------------------------------------MA---------
F7IAP1_CALJA|Callithrix           -----------------------ASEAGELDQEPPGASESLPSGLPRSPERWDAGLRCRQ
H2Q799_PANTR|Pan                  -------------------------------------------------MA---------
F7E5B8_MACMU|Macaca               -------------------------------------------------MA---------
ZDH20_HUMAN|Homo                  -------------------------------------------------MA---------
H2NJD5_PONAB|Pongo                -------------------------------------------------MA---------
G1RS44_NOMLE|Nomascus             -------------------------------------------------MA---------
C3XW62_BRAFL|Branchiostoma        --------------------------------------------------M---------
L7MB41_9ACAR|Rhipicephalus        -------------------------------------------MPPGLFKM---------
G6DE89_DANPL|Danaus               ------------------------------------------------------------
E2A927_CAMFO|Camponotus           ------------------------------------------------MGK---------
K7J025_NASVI|Nasonia              ------------------------------------------------MDN---------
B4KLJ9_DROMO|Drosophila           ------------------------------------------MGNDD-NRR---------
B4LM13_DROVI|Drosophila           ------------------------------------------MGNED-NRR---------
B4J5A2_DROGR|Drosophila           ------------------------------------------MGNEDIHRR---------
B4GB93_DROPE|Drosophila           ------------------------------------------MGNDD-HRR---------
B5E0C5_DROPS|Drosophila           ------------------------------------------MGNDD-HRR---------
B4MQW5_DROWI|Drosophila           ------------------------------------------MGNED-NRR---------
B3MD30_DROAN|Drosophila           ------------------------------------------MGNDD-HRR---------
B3N6S2_DROER|Drosophila           ------------------------------------------MGNDD-HRR---------
Q7K2V5_DROME|Drosophila           ------------------------------------------MGNDD-HRR---------
B4NX32_DROYA|Drosophila           ------------------------------------------MGNDD-HRR---------
Q7Q7Z4_ANOGA|Anopheles            ---------------------------------------MPHGQSYDYHRTTFDGE----
B0WC84_CULQU|Culex                ---------------------------------------MSVAGNYDHYHRNSSHSSGSS
                                                                                              

A7S6A3_NEMVE|Nematostella         ----CTVVLACMVRGFQWIP-------------------VIFINS-VIVWSYYAYVF---
H2V2C9_TAKRU|Takifugu             ----PHQALRCCKRAINWVP-------------------VLFVNL-VVGWSYYAYVV---
H3AQ09_LATCH|Latimeria            ----PHSKLKKCDILITYCMF------------------TIQLTL-LVCSRAYTSHC---
G7PCM0_MACFA|Macaca               ------------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          ----PNFICR-----ILWRS-------------------PTVYKGNRLGWFVTVPST---
F6XXZ8_MONDO|Monodelphis          ----PGRVLLCCQRTAAWVP-------------------VIFIAV-VIGWSYYTFVV---
F1QRT3_DANRE|Danio                RKMAPTHVLRCCQRGLAWIP-------------------VIFIAL-VVCWSYYAYVV---
H2LTT9_ORYLA|Oryzias              ----PTHVLRCCQRGLSWIP-------------------VVFIAL-VVCWSYYAYVV---
G3NDP2_GASAC|Gasterosteus         ----PTHVLRCCQRGLAWIP-------------------VIFIAL-VVCWSYYAYVV---
I3KAB2_ORENI|Oreochromis          ----PTHVLRCCQRGLAWIP-------------------VIFIAL-VVCWSYYAYVV---
H3CRV3_TETNG|Tetraodon            ----PVHVLRCCQRGLAWIP-------------------VIFIAL-VVCWSYYAYVV---
Q28H20_XENTR|Xenopus              ----PSHVLRCCQRVVGWIP-------------------VLFITA-VACWSYYAFVL---
F7EKK0_ORNAN|Ornithorhynchus      ----RWTV--FYQQTVGWAP-------------------LGIITKRVIIWQRYAVVL---
G1KB70_ANOCA|Anolis               ----------------------------------------VFCIL-AIACFYYLYSL---
K7FJ57_PELSI|Pelodiscus           ---------------------------------------MLFI-----------FIA---
G1NQF0_MELGA|Meleagris            ---------------------------------------MLFLVV-VFCFAFSLFIE---
F1P165_CHICK|Gallus               ------HVLKCCQRVLAWVP-------------------VVFIAL-VVAWSYYAYVV---
H0ZMC3_TAEGU|Taeniopygia          ------HVLKCCQKVLAWVP-------------------VAFIAL-VVAWSYYAYVV---
I3LAG4_PIG|Sus                    ----SCNLQTVTHVSSVFIQ-------------------PVYFSF-IILWLLQCFLV---
L5L6V4_PTEAL|Pteropus             ----RWACKGAGTRPAAWDPASVPSRSLTPAAVGTSSPRVLL----LLFWHHQNQLVVSS
I3M6N4_SPETR|Spermophilus         --------------------------------------------------------L---
ZDH20_MOUSE|Mus                   ----PWTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
H0WAG6_CAVPO|Cavia                ------------------------------------------------------------
G5B3L9_HETGA|Heterocephalus       ----PWTLWRCCQRVVGWVP-------------------VLFIAF-VVAWSYYAYVV---
F7DV21_HORSE|Equus                -------------------------------------------------------IV---
ZDH20_BOVIN|Bos                   ----PCTLWRCCQRTVGWVP-------------------VLFITF-VVVWSYYAYVV---
G3SXI8_LOXAF|Loxodonta            ------------------------------------------------------------
H0XAJ4_OTOGA|Otolemur             ----PWTLWRCCQRIVGWVP-------------------VLFITF-VVVWSYYAYVV---
G1PP97_MYOLU|Myotis               ----PGRFWRCCLHGAGWVP-------------------VLFITF-VVAWSYYAYVV---
G3SCT5_GORGO|Gorilla              ----PWTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
G9KYT3_MUSPF|Mustela              ----RSVGW-----VVGWVP-------------------VLFITF-VVVWSYYAYVV---
G1LWV6_AILME|Ailuropoda           ----PWTFWRCCQRSVGWVP-------------------VLFITF-VVVWSYYAYVV---
E2REV5_CANFA|Canis                ----PWTFWRCCQRGVGWVP-------------------VLFITF-VVVWSYYAYVV---
G1SFG2_RABIT|Oryctolagus          ----PLTFWRCCQRIVGWVP-------------------VLFITF-VVAWSYYAYVV---
F7IAP1_CALJA|Callithrix           PNMAPCTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
H2Q799_PANTR|Pan                  ----PWTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
F7E5B8_MACMU|Macaca               ----PWTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
ZDH20_HUMAN|Homo                  ----PWTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
H2NJD5_PONAB|Pongo                ----PWTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
G1RS44_NOMLE|Nomascus             ----PWTLWRCCQRVVGWVP-------------------VLFITF-VVVWSYYAYVV---
C3XW62_BRAFL|Branchiostoma        ----SNPVLNFCIRLMKWLP-------------------VVFITL-IVLWSYYAYVV---
L7MB41_9ACAR|Rhipicephalus        ----QGTVCSVCVRVFKWCP-------------------VLFITT-IVAWSYYAYVI---
G6DE89_DANPL|Danaus               ---------MWCWRAFKWLP-------------------VLLIVS-IVTWSYYAYVI---
E2A927_CAMFO|Camponotus           ----QNGSCWWCVKAVKWIP-------------------VIFILT-IVAWSYYAYVV---
K7J025_NASVI|Nasonia              ----RGSGCWWCVKAVKWIP-------------------VVFILS-IVFWSYYAYVV---
B4KLJ9_DROMO|Drosophila           ----RKSPCNCCLSAFKWIP-------------------VLFIFG-VIAWSYYAYVV---
B4LM13_DROVI|Drosophila           ----RKTPCGCCMSVFKWIP-------------------VLFIFA-VIGWSYYAYVV---
B4J5A2_DROGR|Drosophila           ----RQTPCGCCMSVFKWIP-------------------VLFIFA-VIGWSYYAYVV---
B4GB93_DROPE|Drosophila           ----RKTPCGFCMAVFKWIP-------------------VVFITA-VIAWSYYAYVV---
B5E0C5_DROPS|Drosophila           ----RKTPCGFCMAVFKWIP-------------------VVFITA-VIAWSYYAYVV---
B4MQW5_DROWI|Drosophila           ----RKTPCGFCMSVFKWIP-------------------VLFITS-VICWSYYAYVV---
B3MD30_DROAN|Drosophila           ----RKTPCGFCMAVFKWIP-------------------VLFISA-VIAWSYYAYVV---
B3N6S2_DROER|Drosophila           ----RKTPCGFCMAVFKWIP-------------------VLFITA-VIAWSYYAYVV---
Q7K2V5_DROME|Drosophila           ----RKTPCGFCMAVFKWIP-------------------VLFITA-VIAWSYYAYVV---
B4NX32_DROYA|Drosophila           ----RKTPCGFCMAVFKWIP-------------------VLFITA-VIAWSYYAYVV---
Q7Q7Z4_ANOGA|Anopheles            ----RNERCGCCVRTMKWFP-------------------VLFIAS-VIGWSYYAFVI---
B0WC84_CULQU|Culex                GGGPRAERCACCVRTMKWFP-------------------VLFIVA-VIAWSYYAFVV---
                                                                                              

A7S6A3_NEMVE|Nematostella         ------------------------------------------------------------
H2V2C9_TAKRU|Takifugu             ------------------------------------------------------------
H3AQ09_LATCH|Latimeria            ------------------------------------------------------------
G7PCM0_MACFA|Macaca               ------------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          ------------------------------------------------------------
F6XXZ8_MONDO|Monodelphis          ------------------------------------------------------------
F1QRT3_DANRE|Danio                ------------------------------------------------------------
H2LTT9_ORYLA|Oryzias              ------------------------------------------------------------
G3NDP2_GASAC|Gasterosteus         ------------------------------------------------------------
I3KAB2_ORENI|Oreochromis          ------------------------------------------------------------
H3CRV3_TETNG|Tetraodon            ------------------------------------------------------------
Q28H20_XENTR|Xenopus              ------------------------------------------------------------
F7EKK0_ORNAN|Ornithorhynchus      ------------------------------------------------------------
G1KB70_ANOCA|Anolis               ------------------------------------------------------------
K7FJ57_PELSI|Pelodiscus           ------------------------------------------------------------
G1NQF0_MELGA|Meleagris            ------------------------------------------------------------
F1P165_CHICK|Gallus               ------------------------------------------------------------
H0ZMC3_TAEGU|Taeniopygia          ------------------------------------------------------------
I3LAG4_PIG|Sus                    ------------------------------------------------------------
L5L6V4_PTEAL|Pteropus             WRTGTSWPAPAPSRTRLPPPPCPELRILPPPTSSPLAGPWAASPPAAQVRSLMFLSPLTP
I3M6N4_SPETR|Spermophilus         ------------------------------------------------------------
ZDH20_MOUSE|Mus                   ------------------------------------------------------------
H0WAG6_CAVPO|Cavia                ------------------------------------------------------------
G5B3L9_HETGA|Heterocephalus       ------------------------------------------------------------
F7DV21_HORSE|Equus                ------------------------------------------------------------
ZDH20_BOVIN|Bos                   ------------------------------------------------------------
G3SXI8_LOXAF|Loxodonta            ------------------------------------------------------------
H0XAJ4_OTOGA|Otolemur             ------------------------------------------------------------
G1PP97_MYOLU|Myotis               ------------------------------------------------------------
G3SCT5_GORGO|Gorilla              ------------------------------------------------------------
G9KYT3_MUSPF|Mustela              ------------------------------------------------------------
G1LWV6_AILME|Ailuropoda           ------------------------------------------------------------
E2REV5_CANFA|Canis                ------------------------------------------------------------
G1SFG2_RABIT|Oryctolagus          ------------------------------------------------------------
F7IAP1_CALJA|Callithrix           ------------------------------------------------------------
H2Q799_PANTR|Pan                  ------------------------------------------------------------
F7E5B8_MACMU|Macaca               ------------------------------------------------------------
ZDH20_HUMAN|Homo                  ------------------------------------------------------------
H2NJD5_PONAB|Pongo                ------------------------------------------------------------
G1RS44_NOMLE|Nomascus             ------------------------------------------------------------
C3XW62_BRAFL|Branchiostoma        ------------------------------------------------------------
L7MB41_9ACAR|Rhipicephalus        ------------------------------------------------------------
G6DE89_DANPL|Danaus               ------------------------------------------------------------
E2A927_CAMFO|Camponotus           ------------------------------------------------------------
K7J025_NASVI|Nasonia              ------------------------------------------------------------
B4KLJ9_DROMO|Drosophila           ------------------------------------------------------------
B4LM13_DROVI|Drosophila           ------------------------------------------------------------
B4J5A2_DROGR|Drosophila           ------------------------------------------------------------
B4GB93_DROPE|Drosophila           ------------------------------------------------------------
B5E0C5_DROPS|Drosophila           ------------------------------------------------------------
B4MQW5_DROWI|Drosophila           ------------------------------------------------------------
B3MD30_DROAN|Drosophila           ------------------------------------------------------------
B3N6S2_DROER|Drosophila           ------------------------------------------------------------
Q7K2V5_DROME|Drosophila           ------------------------------------------------------------
B4NX32_DROYA|Drosophila           ------------------------------------------------------------
Q7Q7Z4_ANOGA|Anopheles            ------------------------------------------------------------
B0WC84_CULQU|Culex                ------------------------------------------------------------
                                                                                              

A7S6A3_NEMVE|Nematostella         -------------------VLCFENVQSNIEK----AAYLVAFHPFFFMLIISYWRTILA
H2V2C9_TAKRU|Takifugu             -------------------ELCVYTIQNHAERSKLTVSYLVVFHAFLMMFLWSYWKTIWS
H3AQ09_LATCH|Latimeria            -------------------ELPIKSMTNVGEK----VVCLICYHMFFIMFVWSYWKSIFT
G7PCM0_MACFA|Macaca               -----------------------VSMENTGEQ----VVCLMAYHLLFGMFVWSYWKTIFT
G3WFR2_SARHA|Sarcophilus          -------------------HLCAVSMENIGEQ----VVCLIVYHLLFAMFVWSYWKTIFT
F6XXZ8_MONDO|Monodelphis          -------------------ELCICEYRGPGPGGGVGEQTEET-HL-FVMFL-CFWGD-RS
F1QRT3_DANRE|Danio                -------------------ELCLLTISSTGEK----IVYLVVFHLSFVMFVWSYWKTIFT
H2LTT9_ORYLA|Oryzias              -------------------ELCIFTIPSRAEQ----IFYLIFFHLSFIMFVWSYWKTIFT
G3NDP2_GASAC|Gasterosteus         -------------------ELCVLTIPSIGEK----IVYLIFFHISFILFVWSYWQTIFT
I3KAB2_ORENI|Oreochromis          -------------------ELCIFTIPSIGEQ----IVYLIFFHLSFVMFVWSYWKTIFT
H3CRV3_TETNG|Tetraodon            -------------------ELCVFTITSIGEQ----VVYLFFFHLSFIMFVWSYWKTIFT
Q28H20_XENTR|Xenopus              -------------------ELCVFTIKSNAEK----AVYMVIFHLLFIMFIWSYWKTIFS
F7EKK0_ORNAN|Ornithorhynchus      -------------------ELFMSNTSTVGFEGKA-VVYLVVFHLSFVMFVWSYWMTIFT
G1KB70_ANOCA|Anolis               -------------------KPCLYFIFIA-------VVYLVIFHLSFVMFVWSYWKTIFT
K7FJ57_PELSI|Pelodiscus           ------------------------------------VVYLVVFHLSFVMFVWSYWKTIFT
G1NQF0_MELGA|Meleagris            -------------------SRSSFLLPATEK-----VVYLVIFHLSFVMFVWSYGKTIFT
F1P165_CHICK|Gallus               -------------------ELCVFTISSTAEK----VVYLVIFHLSFVMFVWSYGKTIFT
H0ZMC3_TAEGU|Taeniopygia          -------------------ELCVFTISSTAEK----VVYLVVFHLSFVMFVWSYGKTIFT
I3LAG4_PIG|Sus                    -------------------MLILVTLSGNGENGKA-VVYLVAFHLFFVMFVWSYWMTIFT
L5L6V4_PTEAL|Pteropus             VKPVPHIDSSSVEILNVDLDWCSHHKPGSTGKA---VVYLVAFHLFFVMFVWSYWMTIFT
I3M6N4_SPETR|Spermophilus         -------------------EKCSVTMNSERKT----VVYLVAFHLFFVMFVWSYWMTVFT
ZDH20_MOUSE|Mus                   -------------------ELCVSTISRTGEKGKT-VVYLVAFHLFFVMFVWSYWMTIFT
H0WAG6_CAVPO|Cavia                --------------------------------GKT-VVYLVAFHLFFVMFVWSYWMTIFT
G5B3L9_HETGA|Heterocephalus       -------------------ELCVFTISGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
F7DV21_HORSE|Equus                -------------------NLCIFTVLFNRCSGKA-VVYLVGFHLFFVMFVWSYWMTVFT
ZDH20_BOVIN|Bos                   -------------------ELCVFTLSGNGENGKA-VVYLVAFHLFFVMFVWSYWMTIFT
G3SXI8_LOXAF|Loxodonta            ----------------------LVTITGNGENGKA-VVYLVAFHMFFVMFVWSYWMTIFT
H0XAJ4_OTOGA|Otolemur             -------------------ELCIFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
G1PP97_MYOLU|Myotis               -------------------ELCVFTLSGNGENGKA-VVYLVAFHLFFVMFVWSYWMTIFT
G3SCT5_GORGO|Gorilla              -------------------ELCVFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
G9KYT3_MUSPF|Mustela              -------------------ELCVFTLSGNGENGKA-VVYLVAFHLFFVMFVWSYWMTIFT
G1LWV6_AILME|Ailuropoda           -------------------ELCVFTLSGNGENGKA-VVYLVAFHLFFVMFVWSYWMTIFT
E2REV5_CANFA|Canis                -------------------ELCVFTLSGNGENGKA-VVYLVAFHLFFVMFVWSYWMTIFT
G1SFG2_RABIT|Oryctolagus          -------------------ELCVFTISGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
F7IAP1_CALJA|Callithrix           -------------------ELCVFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
H2Q799_PANTR|Pan                  -------------------ELCVFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
F7E5B8_MACMU|Macaca               -------------------ELCVFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
ZDH20_HUMAN|Homo                  -------------------ELCVFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
H2NJD5_PONAB|Pongo                -------------------ELCVFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
G1RS44_NOMLE|Nomascus             -------------------ELCVFTIFGNEENGKT-VVYLVAFHLFFVMFVWSYWMTIFT
C3XW62_BRAFL|Branchiostoma        -------------------EMCVFAITSLPQK----VVYLVLYHVFFLIFVWSYYQTIFA
L7MB41_9ACAR|Rhipicephalus        -------------------QLCLFTIDNVIQK----IFYLIGFHACFAMFAWSYWQTIFT
G6DE89_DANPL|Danaus               -------------------QLCIFTIDGTAQK----CIYLVLYHILLIMFLWSYWRTIFA
E2A927_CAMFO|Camponotus           -------------------QLCYYTIDNYVQK----AFYLLFFHLLILMFLWSYWQTVYT
K7J025_NASVI|Nasonia              -------------------PLCYETIESNVQK----VFYLIFFHIFFFLFLWSYWQTIAT
B4KLJ9_DROMO|Drosophila           -------------------ELCVLKTENNVAK----IFLLIFYHIALVLFLWSYWQTINT
B4LM13_DROVI|Drosophila           -------------------ELCVLKTENRVAM----AFMLLFYHIALLLFLWSYWQTIST
B4J5A2_DROGR|Drosophila           -------------------ELCVLNTENRIAM----VFMLLFYHVALVLFLWSYWQTINT
B4GB93_DROPE|Drosophila           -------------------ELCIRNSENLVGM----ILMLFFYHIALILFMWSYWRTIMT
B5E0C5_DROPS|Drosophila           -------------------ELCIRNSENLVGM----ILMLFFYHIALILFMWSYWRTIMT
B4MQW5_DROWI|Drosophila           -------------------ELCIRNVENRVAM----SFMLLFYHIALVLLLWSYWRTIMT
B3MD30_DROAN|Drosophila           -------------------ELCIHNSENRIGM----IFMLIFYHISLTLFMWSYWRTIMT
B3N6S2_DROER|Drosophila           -------------------ELCIRNSQNGIAM----IFMLLFYHLFLTLFMWSYWRTIMT
Q7K2V5_DROME|Drosophila           -------------------ELCIRNSENRIGM----IFMLLFYHLFLTLFMWSYWRTIMT
B4NX32_DROYA|Drosophila           -------------------ELCIRNSQNRISM----IFMLLFYHLFLTLFMWSYWRTIMT
Q7Q7Z4_ANOGA|Anopheles            -------------------QLSFFTVTNIVQR----ILFLLFYHAVLVMFLWSYYQTVFT
B0WC84_CULQU|Culex                -------------------QLTFFTVTGVLQR----ILFLLFYHLILVMFLWSYYRTVFT
                                                                             *  : ::  .:     :

A7S6A3_NEMVE|Nematostella         DQGIVPSQFALSKTDKDLVE---NGENVREVLTRVSKNLPTATRTLSGGVRYCDICCHIK
H2V2C9_TAKRU|Takifugu             TPASPSQAFSLPRMEKELYEREERAEMQQEILKKVARTLPVYTRMPDGAIRYCKPCQLIK
H3AQ09_LATCH|Latimeria            MPMNPSKEFHLSYADREQLEREERGEAQQEVLRRVAKDLPIYTRTMSGAIRYCDRCQLVK
G7PCM0_MACFA|Macaca               LPMNPSKEFHLSYAEKELLEREPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLIK
G3WFR2_SARHA|Sarcophilus          MPMNPSKEFHLSYAEKELLEREPRGETHQEILKRAAKDLPIYTRTMSGAIRYCDRCQLIK
F6XXZ8_MONDO|Monodelphis          KINNSFLSFSLSQADEEHFEKEERPDIQQEILRRAAKDLPVYTMTSTRLIRYCKKCQLIK
F1QRT3_DANRE|Danio                KPANPSKEFCLPKSEKEQYEKEQRPETQQEILKKVATSLPLYTRTGAGAIRYCDRCQVIK
H2LTT9_ORYLA|Oryzias              KPANPSKEFCLPKAEKECYEKEARPESQQEILWRVATSLPLYTRTGTGGIRYCDRCQVIK
G3NDP2_GASAC|Gasterosteus         RPANPSKEFCLPKAEKERYEKEGRPESQQEILWRAATSLPLYTRTGAGAIRYCDRCQVIK
I3KAB2_ORENI|Oreochromis          KPANPSKEFCLPKAEKERYEKEERPESQQEILWRAASSLPLYTRTGAGAIRYCDRCQVIK
H3CRV3_TETNG|Tetraodon            KPSNPSKEFCLPKAEKERYEKEERPESQQEILWRAASSLPLYTRTGAGAIRYCDRCQVIK
Q28H20_XENTR|Xenopus              RPANPSKEFCLSKSDKELYEREERQEFQQEILKRAAKDLPIYTTTGTRAIRYCDRCQLIK
F7EKK0_ORNAN|Ornithorhynchus      SPASPSKEFCLSKSDKEQYEKEERQESQHEILKRVAKDLPVYTTTASRAIRYCERCQLIK
G1KB70_ANOCA|Anolis               SPASPSSEFCLSKTDKEQYEKEERPESQQEILRRAAKDLPVYTTTTSRAIRYCDRCQLIK
K7FJ57_PELSI|Pelodiscus           SPASPSDEFCLSKSDKEQYEKEERPESQQDILRRAAKDLPIYTTTASRAIRYCDRCQLIK
G1NQF0_MELGA|Meleagris            SPASPSNEFCLSKADKEQYEKEERPESQQEILRRAAKDLPIYTTTASRAIRYCDRCQLIK
F1P165_CHICK|Gallus               SPASPSNEFCLSKADKEQYEKEERPESQQEILRRAAKDLPIYTTTASRAIRYCDRCQLIK
H0ZMC3_TAEGU|Taeniopygia          SPATPSNEFCLSKADKEQYEKEERPESQQEILRRAAKDLPIYTTTASRAIRYCDRCQLIK
I3LAG4_PIG|Sus                    SPASPSKEFYLSSSEKERYEKEFSQERQQEILRRAARGLPVYTTSATQIIFKNQECAHLK
L5L6V4_PTEAL|Pteropus             SPASPSKEFYLSSSEKERYEKEFSQERQQAILRRTARDLPIYTTSASKTIRYCERCQLMK
I3M6N4_SPETR|Spermophilus         SPAIPSKEFYLSNSDKERYEKEFSHERQQQILRRAARDLPIYTTSASRTIRYCEKCQLIK
ZDH20_MOUSE|Mus                   SPASPSKEFYLSNSEKERYEKEFSQERQQDILRRAARDLPIYTTSASKAIRYCEKCQLIK
H0WAG6_CAVPO|Cavia                SPATPCKEFYLSTSEKEAYEKEDNQERQQAILRRAARDLPIYTTTASRTIRYCEKCQLIK
G5B3L9_HETGA|Heterocephalus       SPATPSKEFYLSTSEKERYEKEFSQERQQEILRRAARDLPIYTTTASRTIRYCEKCQLIK
F7DV21_HORSE|Equus                SPASPSKEFYLSSSDKERYEKEFNQERQQEILRRTARDLPISTLSAARTIRYCERCQLIK
ZDH20_BOVIN|Bos                   SPASPSKEFCLSNSEKERYEKEFSQERQQEILRRAARDLPIYTTSASKTVRYCERCQLIK
G3SXI8_LOXAF|Loxodonta            SPASPSKEFYLSSSEKERYEKEFSQERQQEILRRAARDLPIYTTSASRTIRYCERCQLIK
H0XAJ4_OTOGA|Otolemur             SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARALPVYTVSTSRTIRYCEKCQLIK
G1PP97_MYOLU|Myotis               SPASPSKEFYLSNSEREHYEKEFSQERQQEILRRTAKDLPIYTTSGSRTIRYCERCQLIK
G3SCT5_GORGO|Gorilla              SPASPSKEFYLSNSEKERYEKEFSQERQQDILRRAARALPIYTTSASKIIRFCYLCFSIK
G9KYT3_MUSPF|Mustela              SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARDLPIYTTSASRTIRYCEKCQLIK
G1LWV6_AILME|Ailuropoda           SPASPSKEFYLSNSEKERYEKEFIQERQQEILRRAARDLPIYTTSASRTIRYCERCQLIK
E2REV5_CANFA|Canis                SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARDLPIYTTSASRTIRYCEKCQLIK
G1SFG2_RABIT|Oryctolagus          SPATPSKEFYLSNSEKERYEKEFSQERQQEILRRVARDLPIYTTSASRTIRYCEKCQLIK
F7IAP1_CALJA|Callithrix           SPASPSKEFYLSNSEKERYEKEFSQERQQDILRRAARALPIYTTSASKTIRYCEKCQLIK
H2Q799_PANTR|Pan                  SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARALPIYTTSASKTIRYCEKCQLIK
F7E5B8_MACMU|Macaca               SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARVLPIYTTSASKTIRYCEKCQLIK
ZDH20_HUMAN|Homo                  SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARALPIYTTSASKTIRYCEKCQLIK
H2NJD5_PONAB|Pongo                SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARALPIYTTSASKTIRYCEKCQLIK
G1RS44_NOMLE|Nomascus             SPASPSKEFYLSNSEKERYEKEFSQERQQEILRRAARALPIYTTSASKTIRYCEKCQLIK
C3XW62_BRAFL|Branchiostoma        PVGKPAQEFYLSKADVDRLEHEDREDRQQQYLAQMAKDLPLVTRTIGGSIRYCEPCQLIK
L7MB41_9ACAR|Rhipicephalus        EPGTIPKQFYLSPADAEHLEKELSEDNQRQMLERLAKNLPVSCRTMNGMVRYCEKCHLIK
G6DE89_DANPL|Danaus               DIKPIPDKYKLPETELEKLLSAETEDGQRTILENFAKDLPIVTRTMSGSVRYCNRCVLVK
E2A927_CAMFO|Camponotus           NLMPVPDKFKIPDVEMEKLQQAETEEAQRQILERFAQDLPVTNRTIKGAMRFCEKCQLIK
K7J025_NASVI|Nasonia              DLVKVPDKFKLPAAEMEKLLQAESESTHRQILERFAQDLPITNRTIKGEIRFCEQCQVVK
B4KLJ9_DROMO|Drosophila           PVGRVPDQWRIPDEEVNQLFRADNQETQKRILNNFARNLPVTNRTINGSVRFCEKCKIIK
B4LM13_DROVI|Drosophila           SVGRVPDQWRIPDEEVNQLFRADNQETQKRILNNFARNLPVTNRTINGSVRFCEKCKIVK
B4J5A2_DROGR|Drosophila           SVGRVPDLWRIPDEEVNHLFRADNTETQKRILNNFARNLPVTNRTMNGSVRFCEKCKIIK
B4GB93_DROPE|Drosophila           SVGRVPDQWRIPDEEVTRLFRADNPETQKRILNSFARSLPVTNRTMNGSVRFCEKCKIIK
B5E0C5_DROPS|Drosophila           SVGRVPDQWRIPDEEVTRLFRADNPETQKRILNSFARSLPVTNRTMNGSVRFCEKCKIIK
B4MQW5_DROWI|Drosophila           SVGRVPDQWRIPDEEVTRLFRADNPETQKRILNNFARNLPVTNRTMNGSVRFCEKCKIIK
B3MD30_DROAN|Drosophila           SVGRIPEQWRIPDEEVSRLLRADSQEAQKRILNNFARNLPVTNRTMNGSVRFCEKCKIIK
B3N6S2_DROER|Drosophila           SVGRIPDQWRIPDEEVSRLFRADSPETQKRILNNFARDLPVTNRTMNGSVRFCEKCKIIK
Q7K2V5_DROME|Drosophila           SVGRIPDQWRIPDEEVSRLFRADSPDTQKRILNNFARDLPVTNRTMNGSVRFCEKCKIIK
B4NX32_DROYA|Drosophila           SVGRIPDQWRIPDEEVSRLFRADSPDTQKRILNNFARDLPVTNRTMNGSVRFCEKCKIIK
Q7Q7Z4_ANOGA|Anopheles            DIGRVPSRFHVPRAELDRIVRATNEVEQKEILETFAKELPVVTRTLNASVRFCDKCRLIK
B0WC84_CULQU|Culex                DIGRVPARFRVPRSELDRLLRAQSEDEQKQILEAFAKQLPIVTRTLNASVRFCEKCRLIK
                                          : :.  :             .  *   :  **         :     *  :*

A7S6A3_NEMVE|Nematostella         PDRCHHCSMCRKCILKMDHHCPW-VNNCVGYSNYKFFLLFLFYAILYTFYVTGTVTKYFI
H2V2C9_TAKRU|Takifugu             PDRCHHCSTCERCVLKMDHHCPW-VNNCIGFSNYKFFILFLTYASLHCLVICATVTQYFI
H3AQ09_LATCH|Latimeria            PDRCHHCSVCDKCILKMDHHCPW-VNNCVGFSNYKFFLLFLAYSLLYCLFITATDLQYFI
G7PCM0_MACFA|Macaca               PDRCHHCSVCDKCILKMDHHCPW-VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFI
G3WFR2_SARHA|Sarcophilus          PDRCHHCSVCDKCILKMDHHCPW-VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFI
F6XXZ8_MONDO|Monodelphis          PDRCHHCSVCNKCVLKMDHHCPW-VNNCVGFSNYKYFLLFLFYSLLYCILVTTTVLEYFI
F1QRT3_DANRE|Danio                PDRCHHCSACDMCVLKMDHHCPW-VNNCVGFSNYKFFILFLTYSLVYCLFIAASVLQYFI
H2LTT9_ORYLA|Oryzias              PDRCHHCSACDTCVLKMDHHCPW-VNNCVGFSNYKFFILFLAYSLAYCLFIAATVLQYFI
G3NDP2_GASAC|Gasterosteus         PDRCHHCSACDMCVLKMDHHCPW-VNNCVGFSNYKFFILFLAYSLVYCLFIAATVLQYFI
I3KAB2_ORENI|Oreochromis          PDRCHHCSACDMCVLKMDHHCPW-VNNCVGFSNYKFFILFLAYSLVYCLFIAATVLQYFI
H3CRV3_TETNG|Tetraodon            PDRCHHCSACDMCVLKMDHHCPW-VNNCVGFSNYKFFILFLAYSLVYCLFIAATVLQYFI
Q28H20_XENTR|Xenopus              PDRCHHCSTCDVCVLKMDHHCPW-VNNCVGFSNYKFFLLFLMYSLLYCLFIAATVLQYFI
F7EKK0_ORNAN|Ornithorhynchus      PDRCHHCSACDICVLKMDHHCPW-VNNCVGFSNYKFFLLFLMYSLLYCLFVATTVLQYFI
G1KB70_ANOCA|Anolis               PDRCHHCSACDLCVLKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLQYFI
K7FJ57_PELSI|Pelodiscus           PDRCHHCSACDLCVLKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLQYFI
G1NQF0_MELGA|Meleagris            PDRCHHCSACDICVLKMDHHCPW-VNNCVGFSNYKFFLLFLMYSLLYCLFVAATVLQYFI
F1P165_CHICK|Gallus               PDRCHHCSACDICVLKMDHHCPW-VNNCVGFSNYKFFLLFLMYSLLYCLFVAATVLQYFI
H0ZMC3_TAEGU|Taeniopygia          PDRCHHCSACDVCVLKMDHHCPW-VNNCVGFSNYKFFLLFLMYSLLYCLFVAATVLQYFI
I3LAG4_PIG|Sus                    RINSNHISGS-MCNLPQMSWCNR-VNNCVGFSNYKFFLLFLLYSLLYCLFVATTVLQYFI
L5L6V4_PTEAL|Pteropus             PDRAHHCSACDTCILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLQYFI
I3M6N4_SPETR|Spermophilus         PDRAHHCSACDKCILKMDHHCPW-VNNCVGFSNYKFFMLFLLYSLIYCLYVAISVLEYFI
ZDH20_MOUSE|Mus                   PDRAHHCSACDRCVLKMDHHCPW-VNNCVGFTNYKFFMLFLLYSLLYCLFVAATVLEYFI
H0WAG6_CAVPO|Cavia                PDRTHHCSACDTCVLKMDHHCPW-VNNCVGFSNYKFFMLFLLYSLLYCLFVATTVLEYFI
G5B3L9_HETGA|Heterocephalus       PDRTHHCSACDTCVLKMDHHCPW-VNNCVGFSNYKFFMLFLLYSLLYCLFVATTVLEYFI
F7DV21_HORSE|Equus                PDRAHHCSACDICVLKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVATTVLQCFI
ZDH20_BOVIN|Bos                   PDRAHHCSACDMCILKMDHHCPW-VNNCVGFSNYKFFLLFLFYSLLYCLFVATTVLQYFI
G3SXI8_LOXAF|Loxodonta            PDRAHHCSACDICVLKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVATTVLQYFI
H0XAJ4_OTOGA|Otolemur             PDRAHHCSACDTCVLKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAVTVLEYFI
G1PP97_MYOLU|Myotis               PDRAHHCSACDICILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVATTVLQYFI
G3SCT5_GORGO|Gorilla              NGVRHHCAENNKCGMKKNNHTNWKVNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLEYFI
G9KYT3_MUSPF|Mustela              PDRAHHCSACDVCVLKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVATTVLQYFI
G1LWV6_AILME|Ailuropoda           PDRAHHCSACDICILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLQYFI
E2REV5_CANFA|Canis                PDRAHHCSACDMCILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVATTVLQYFI
G1SFG2_RABIT|Oryctolagus          PDRAHHCSACDTCILKMDHHCPW-VNNCVGFSNYKFFMLFLLYSLLYCLFVATTVLEYFI
F7IAP1_CALJA|Callithrix           PDRAHHCSACDSCVLKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLEYFI
H2Q799_PANTR|Pan                  PDRAHHCSACDSCILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLEYFI
F7E5B8_MACMU|Macaca               PDRAHHCSACDSCILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLEYFI
ZDH20_HUMAN|Homo                  PDRAHHCSACDSCILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLEYFI
H2NJD5_PONAB|Pongo                PDRAHHCSACDSCILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLEYFI
G1RS44_NOMLE|Nomascus             PDRAHHCSACDSCILKMDHHCPW-VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLEYFI
C3XW62_BRAFL|Branchiostoma        PDRCHHCSMCGTCVLKMDHHCPW-VNNCVGYSNYKFFVLFLGYGLLYCIYVAGTSVEYFI
L7MB41_9ACAR|Rhipicephalus        PDRAHHCSVCGRCILKMDHHCPW-VNNCVSFTNYKYFILFLAYSLIYCLFVAATTLQFFI
G6DE89_DANPL|Danaus               PDRAHHCSICARCVLKMDHHCPW-VNNCVCFHNYKFFMLFLGYALLYCLFIMSTCLPYFI
E2A927_CAMFO|Camponotus           PDRAHHCSVCSTCVLKMDHHCPW-VNNCVGFHNYKFFMLFLAYALLYCMFITATSLQYFI
K7J025_NASVI|Nasonia              PDRAHHCSVCGTCVLKMDHHCPW-VNNCVGFHNYKFFMLFLAYALLYCIFIVATSLQYFI
B4KLJ9_DROMO|Drosophila           PDRSHHCSVCSCCVLKMDHHCPW-VNNCVNFSNYKFFVLFLGYALVYCLYVAFTTLNDFI
B4LM13_DROVI|Drosophila           PDRSHHCSVCSCCVLKMDHHCPW-VNNCVNFSNYKFFVLFLGYALIYCLYVALTTLHDFI
B4J5A2_DROGR|Drosophila           PDRSHHCSVCSCCVLKMDHHCPW-VNNCVNFNNYKFFVLFLGYALIYCLYVALTTLHDFV
B4GB93_DROPE|Drosophila           PDRAHHCSVCNSCVLKMDHHCPW-VNNCVNFYNYKFFVLFLGYALIYCLYVAFTTLHDFV
B5E0C5_DROPS|Drosophila           PDRAHHCSVCNSCVLKMDHHCPW-VNNCVNFYNYKFFVLFLGYALIYCLYVAFTTLHDFV
B4MQW5_DROWI|Drosophila           PDRSHHCSVCSCCVLKMDHHCPW-VNNCVNFYNYKFFVLFLGYALIYCLYVALTTLHDFV
B3MD30_DROAN|Drosophila           PDRAHHCSVCSCCVLKMDHHCPW-VNNCVNFYNYKFFVLFLGYALVYCLYVAFTTLHDFV
B3N6S2_DROER|Drosophila           PDRAHHCSVCSCCVLKMDHHCPW-VNNCVNFYNYKYFVLFLGYALVYCLYVAFTSLHDFV
Q7K2V5_DROME|Drosophila           PDRAHHCSVCSCCVLKMDHHCPW-VNNCVNFYNYKYFVLFLGYALVYCLYVAFTSLHDFV
B4NX32_DROYA|Drosophila           PDRAHHCSVCSCCVLKMDHHCPW-VNNCVNFYNYKYFVLFLGYALVYCLYVAFTSLHDFV
Q7Q7Z4_ANOGA|Anopheles            PDRAHHCSVCGVCVLKLDHHCPW-VNNCINFTNYKYFILFLGYALLYCVYVACSTIPYME
B0WC84_CULQU|Culex                PDRAHHCSVCGVCVLKLDHHCPW-VNNCINFTNYKFFILFLGYALVYCLYVAFSTVMYME
                                      :* :    * :    .  . ****: : ***:*:*** *.  : . :  :    : 

A7S6A3_NEMVE|Nematostella         AFWS------------------------------NS----LE--GEGKLHILFLFFVALM
H2V2C9_TAKRU|Takifugu             KFWT------------------VSTPASLCAPFTQAVKKLPD--THAKFHILFLFFVAAL
H3AQ09_LATCH|Latimeria            KFWT------------------------------NG---LPD--TQAKFHIMFLFFAAAM
G7PCM0_MACFA|Macaca               KFWT------------------------------NG---LPD--TQAKFHIMFLFFAAAM
G3WFR2_SARHA|Sarcophilus          KFWT------------------------------NG---LPD--TQAKFHIMFLFFAAAM
F6XXZ8_MONDO|Monodelphis          KFWT------------------------------TN---QKT--TRAQFHVLFLFFVASM
F1QRT3_DANRE|Danio                KFWT------------------------------SD---LPE--SHAKFHVLFLFFVAAM
H2LTT9_ORYLA|Oryzias              KFWT------------------------------NE---LDG--THAKFHVLFLFFVAAM
G3NDP2_GASAC|Gasterosteus         KFWT------------------------------NE---LPD--THAKFHVLFLFFVAAM
I3KAB2_ORENI|Oreochromis          KFWT------------------------------NE---LTD--TPAKFHVLFLFFVAAM
H3CRV3_TETNG|Tetraodon            KFWT------------------------------NE---LPE--SPAKFHVLFLFFVAAM
Q28H20_XENTR|Xenopus              KFWT------------------------------NE---LPD--TRAKFHVLFLFFVAAM
F7EKK0_ORNAN|Ornithorhynchus      KFWT------------------LCRRKSAENCPKNE---LPD--THAKFHVLFLFFVAAM
G1KB70_ANOCA|Anolis               KFWT------------------------------NE---LLD--TRAKFHVLFLFFVAAM
K7FJ57_PELSI|Pelodiscus           KFWT------------------------------ND---LPD--SHAKFHVLFLFFVAAM
G1NQF0_MELGA|Meleagris            KFWT------------------------------NE---LPD--THAKFHVLFLFFVAAM
F1P165_CHICK|Gallus               KFWT------------------------------NE---LPD--THAKFHVLFLFFVAAM
H0ZMC3_TAEGU|Taeniopygia          KFWT------------------------------NE---LPD--THAKFHVLFLFFVAAM
I3LAG4_PIG|Sus                    KFWT------------------------------NE---LSD--TRAKFHVLFLFFVSTM
L5L6V4_PTEAL|Pteropus             KFWT------------------------------NE---LPD--TRAKFHVLFLFFVSTM
I3M6N4_SPETR|Spermophilus         KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
ZDH20_MOUSE|Mus                   KFWT------------------LCRRKSTENCPKNEPTVLNF--PSAKFHVLFLFFVSAM
H0WAG6_CAVPO|Cavia                KFWT------------------LCRRKSTENCPKNE---LTD--TRAKFHVLFLFFVSAM
G5B3L9_HETGA|Heterocephalus       KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
F7DV21_HORSE|Equus                KFWT------------------------------NE---LSA--TRAKFHVLFLFFVSTM
ZDH20_BOVIN|Bos                   KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSTM
G3SXI8_LOXAF|Loxodonta            KFWT------------------------------NE---LSD--TRAKFHVLFLFFVSAM
H0XAJ4_OTOGA|Otolemur             KFWT------------------------------NE---LAD--TRAKFHVLFLFFVSAM
G1PP97_MYOLU|Myotis               KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSTM
G3SCT5_GORGO|Gorilla              KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
G9KYT3_MUSPF|Mustela              KFWT------------------------------NE---LSD--TRAKFHVLFLFFVSTM
G1LWV6_AILME|Ailuropoda           KFWT------------------------------NE---LSD--TRAKFHVLFLFFVSTM
E2REV5_CANFA|Canis                KFWT------------------------------NE---LSD--TRAKFHVLFLFFVSTM
G1SFG2_RABIT|Oryctolagus          KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
F7IAP1_CALJA|Callithrix           KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
H2Q799_PANTR|Pan                  KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
F7E5B8_MACMU|Macaca               KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
ZDH20_HUMAN|Homo                  KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
H2NJD5_PONAB|Pongo                KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
G1RS44_NOMLE|Nomascus             KFWT------------------------------NE---LTD--TRAKFHVLFLFFVSAM
C3XW62_BRAFL|Branchiostoma        KFWN------------------------------KE---LDDTIGNGRFHILFLFFAAAM
L7MB41_9ACAR|Rhipicephalus        KFWT------------------------------ND---LE---GWGRFHILFLFFVAFM
G6DE89_DANPL|Danaus               RFWKMYQEYNQAHCDSLIGIGTYTKQCMDLLSGDFG---TSG--SAGRYHIVFAFFVALM
E2A927_CAMFO|Camponotus           RFWK------------------------------GE---LD---GMGRFHLLFLFFVALM
K7J025_NASVI|Nasonia              MFWR------------------------------GE---LP---GMGKFHLLFLFFVALM
B4KLJ9_DROMO|Drosophila           MFVQ-----------------------------GQP---GGS--GMGRFHILFLFFISIM
B4LM13_DROVI|Drosophila           QFVK-----------------------------GQP---TGN--GMGRFHILFLFFISIM
B4J5A2_DROGR|Drosophila           QFWK-----------------------------GQL---TGT--GMGRFHILFLFFISIM
B4GB93_DROPE|Drosophila           QFWK--------------------------VGAGQL---NGS--GVGRFHILFLFFISIM
B5E0C5_DROPS|Drosophila           QFWK--------------------------VGAGQL---NGS--GVGRFHILFLFFISIM
B4MQW5_DROWI|Drosophila           QFWK------------------------------GQ---LNG--GVGRFHILFLFFIAIM
B3MD30_DROAN|Drosophila           QFWK--------------------------VGAGQL---NGG--GMGRFHILFLFFIAIM
B3N6S2_DROER|Drosophila           EFWK-----------------------------GQL---NAS--GMGRFHILFLFFIAIM
Q7K2V5_DROME|Drosophila           EFWK--------------------------VGAGQL---NAS--GMGRFHILFLFFIAIM
B4NX32_DROYA|Drosophila           EFWK-----------------------------GQL---NAS--GMGRFHILFLFFIAIM
Q7Q7Z4_ANOGA|Anopheles            LLWT------------------------------------GK--IDGRFHILFLFFVSVM
B0WC84_CULQU|Culex                LIWS----------------------------ASGR---EGK--IDGRFHILFLFFVSLM
                                   :                                            .. *::* ** : :

A7S6A3_NEMVE|Nematostella         FCISLWSLFGYHIYLVSQNKTTL-ESFRVPHLRY-GPSKDAFHLGTRLKNVEQVFGTSVI
H2V2C9_TAKRU|Takifugu             FFISIVSLLSYHLWLVGKNRTTI-ETFSAAVFTS-GRDKSGFSLG-CSRNMTEVFGDRAK
H3AQ09_LATCH|Latimeria            FSVSLSSLFGYHCWLVSKNRSTL-EAFRAPAFRH-GTDKNGFSLG-FSKNLRQVFGDEKK
G7PCM0_MACFA|Macaca               FSVSLSSLFGYHCWLVSKNKSTL-EAFRSPVFRH-GTDKNGFSLG-FSKNMRQVFGDEKK
G3WFR2_SARHA|Sarcophilus          FSVSLSSLFGYHCWLVSKNKSTL-EAFRSPIFRH-GTDKNGFSLG-FSKNLRQVFGDEKK
F6XXZ8_MONDO|Monodelphis          FFISVLSLFCYHMWLVGKNRTTI-EAFRSPVFIN-GPDKNGFSLG-LSKNWRQVFGDEKK
F1QRT3_DANRE|Danio                FCISILSLFTYHLWLVGKNRSTI-EAFRAPVFRN-GPDKNGFSLG-FSKNIAQVFGDEKK
H2LTT9_ORYLA|Oryzias              FCISILSLFSYHLWLVGKNRSTI-EAFRAPVFRS-GSDKNGFSLG-FRKNIAQVFGDQKK
G3NDP2_GASAC|Gasterosteus         FCISILSLFSYHLWLVGKNRSTI-EAFRAPVFRS-GSDKNGFSLG-YRKNMAQVFGDQKK
I3KAB2_ORENI|Oreochromis          FCISILSLFSYHLWLVGKNRSTI-EAFRAPVFRT-GSDKNGFSLG-FRKNIAQVFGDQKK
H3CRV3_TETNG|Tetraodon            FCISILSLFSYHLWLVGKNRSTI-EAFRAPVFRT-GSDKNGFSLG-FKKNIAQVFGDQKK
Q28H20_XENTR|Xenopus              FFISILSLFSYHCWLVGKNRSTI-EAFRAPLFRN-GPEKDGFSLG-FSKNLREVFGDEKK
F7EKK0_ORNAN|Ornithorhynchus      FFISILSLFSYHCWLVGKNRSTI-EAFRAPTFRN-GPDKNGFSLG-CGKNLREVFGDEKK
G1KB70_ANOCA|Anolis               FFISILSLFSYHCWLVGKNRSTI-EAFRAPMFRN-GPDKNGFSLG-CSKNLKEVFGDEKK
K7FJ57_PELSI|Pelodiscus           FFISILSLFSYHCWLVSKNRSTI-EAFRAPTFRN-GPDKNGFSLG-CSKNLREVFGDEKK
G1NQF0_MELGA|Meleagris            FFISILSLFSYHCWLVGKNRSTI-ETFRAPTFRN-GPDKNGFSLG-CSKNLREVFGDEKK
F1P165_CHICK|Gallus               FFISILSLFSYHCWLVGKNRSTI-ETFRAPTFRN-GPDKNGFSLG-CSKNLREVFGDEKK
H0ZMC3_TAEGU|Taeniopygia          FFISILSLFSYHCWLVGKNRSTI-ETFRAPTFRN-GPDKNGFSLG-CSKNLREVFGDEKK
I3LAG4_PIG|Sus                    FFISVLSLLSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
L5L6V4_PTEAL|Pteropus             FLVSVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-YRKNWRQVFGDEKK
I3M6N4_SPETR|Spermophilus         FFISVLSLFSYHCWLVGKNRTTIAESFRTPTFSY-GVDAHGFSLG-YSKNWRQVFGDEKK
ZDH20_MOUSE|Mus                   FFVSVLSLFSYHCWLVGKNRTTI-ESFRAPMFSY-GIDGNGFSLG-CSKNWRQVFGDEKK
H0WAG6_CAVPO|Cavia                FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-YTKNWRQVFGEEKK
G5B3L9_HETGA|Heterocephalus       FFLSVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-YSKNWKQVFGDEKK
F7DV21_HORSE|Equus                FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
ZDH20_BOVIN|Bos                   FFISVLSLLSYHCWLVGKNRTTI-ESFRAPMFSY-GTDGNGFSLG-CSKNWRQVFGDEKK
G3SXI8_LOXAF|Loxodonta            FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-YSKNWREVFGDEKK
H0XAJ4_OTOGA|Otolemur             FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFAY-GSDGNGFSLG-CSKNWRQVFGDEKK
G1PP97_MYOLU|Myotis               FFISVLSLFSYHCWLVGKNRTTI-ESFSAPTFSY-GPDGNGFSLG-YSKNWRQVFGDEKK
G3SCT5_GORGO|Gorilla              FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
G9KYT3_MUSPF|Mustela              FFISVLSLFSYHCWLVGKNRTTI-ESFRSATFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
G1LWV6_AILME|Ailuropoda           FFISVLSLFSYHCWLVGKNRTTI-ESFRSPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
E2REV5_CANFA|Canis                FFISVLSLFSYHCWLVGKNRTTI-ESFRSPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
G1SFG2_RABIT|Oryctolagus          FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-YSKNWRQVFGDEKK
F7IAP1_CALJA|Callithrix           FFISVLSLFSYHCWLVGKNRTTIAESFRAPTFSY-GPDGNGFSLG-YSKNWRQVFGDEKK
H2Q799_PANTR|Pan                  FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
F7E5B8_MACMU|Macaca               FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-YSKNWRQVFGDEKK
ZDH20_HUMAN|Homo                  FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
H2NJD5_PONAB|Pongo                FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
G1RS44_NOMLE|Nomascus             FFISVLSLFSYHCWLVGKNRTTI-ESFRAPTFSY-GPDGNGFSLG-CSKNWRQVFGDEKK
C3XW62_BRAFL|Branchiostoma        FSISLVSLFGYHLYLVFSNRTTL-ESFRTPMFRH-GPDKDGFNLG-SSNNLKEVFGEDRR
L7MB41_9ACAR|Rhipicephalus        FAISLVSLFGYHCFLVMVNRSTL-EAFRPPIFRT-GPDKHGFSLG-HQANVAEVFGDNRR
G6DE89_DANPL|Danaus               FAISLGSLFGYHCYLVAHNRTTL-EAFRAPMFRG-GADKNGFSIG-AFNNFKEVFGASPD
E2A927_CAMFO|Camponotus           FAVSLNSLFFYHCYLVVHNRSTL-EAFRTPMFRT-GKDKDGFSLG-KYNNFQEVFGDNPR
K7J025_NASVI|Nasonia              FAISLNSLFFYHCYLILHNRSTL-EAFRPPMFRT-GKDKDGFSLG-KYNNFQEVFGDNSR
B4KLJ9_DROMO|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-EAFRAPIFRVGGPDKNGYNLG-RFANFCEVFGDKWQ
B4LM13_DROVI|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-EAFRAPIFRVGGPDKNGYNLG-RYANFCEVFGDKWE
B4J5A2_DROGR|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-EAFRAPIFRVGGPDKNGYNLG-RYANFCEVFGDKWE
B4GB93_DROPE|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-ESFRAPVFRVGGPDKNGFNLG-RYANFCEVFGDDWQ
B5E0C5_DROPS|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-ESFRAPVFRVGGPDKNGFNLG-RYANFCEVFGDDWQ
B4MQW5_DROWI|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-EAFRAPIFRVGGPDKNGYNLG-RFANFCEVFGDDWQ
B3MD30_DROAN|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-ESFRAPIFRVGGPDKNGYNLG-RYANFCEVFGDDWQ
B3N6S2_DROER|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-ESFRAPIFRVGGPDKNGYNLG-RYANFCEVFGDDWQ
Q7K2V5_DROME|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-ESFRAPIFRVGGPDKNGYNLG-RYANFCEVFGDDWQ
B4NX32_DROYA|Drosophila           FAISLVSLFGYHIYLVLVNRTTL-ESFRAPIFRVGGPDKNGYNLG-RYANFCEVFGDDWQ
Q7Q7Z4_ANOGA|Anopheles            FAISLVSLFGYHVYLVLLNRTTL-ESFRTPIFRFGGPDKNGFSLG-KLNNFQEVFGDDWR
B0WC84_CULQU|Culex                FAISLVSLFGYHVYLVLLNRTTL-ESFRTPIFRYGGPDKNGFSLG-KMNNFQEVFGDNRK
                                  * :*: **: ** :*:  *.:*: *:*  . :   * .  .: :*    *  :***    

A7S6A3_NEMVE|Nematostella         MWFLPVFT-------RY-------------------------------------------
H2V2C9_TAKRU|Takifugu             YWILPVFS-GQGDGQSFV---------------TRLV-------HIDPEQANSVLQHNGK
H3AQ09_LATCH|Latimeria            YWLLPIFT-SLGDGCAFP---------------TCLV-------NQDPEQPSTPAGHNPT
G7PCM0_MACFA|Macaca               YWLLPIFS-SLGDGCSFP---------------TCLV-------NQDPEQPSTPAGLSST
G3WFR2_SARHA|Sarcophilus          YWPLPVFS-SLGDGCSFP---------------TCLV-------NQDLEQQSTPAGLTPA
F6XXZ8_MONDO|Monodelphis          YWLFPVFT-SLGDGVNFP---------------TRLM--------MDTEQVTVTNYTLLF
F1QRT3_DANRE|Danio                YWLLPVFT-SQGDGLSFP---------------TRLV-------TIDPEQPTECLQPGGL
H2LTT9_ORYLA|Oryzias              YWLLPVFT-SQGDGLTFP---------------TRLV-------NADAEQAAVTLHQEPN
G3NDP2_GASAC|Gasterosteus         YWLLPVFT-SQGDGLTFP---------------ARLV------NPADVEQAAVTLQPEPG
I3KAB2_ORENI|Oreochromis          YWLLPVFT-SQGDGLTFP---------------TRLV-------NTDVEQATVTLQSEPS
H3CRV3_TETNG|Tetraodon            YWFLPVFT-SQGDGLAFP---------------TRLV-------NTDVEQPAVTLQPEAK
Q28H20_XENTR|Xenopus              YWLLPMFT-SLGDGCSFP---------------TRLV-------LGDPEQNAATVQTDST
F7EKK0_ORNAN|Ornithorhynchus      YWLLPVFTSSLGDGCNFP---------------TRLV--------MDPEQVIVTSQSEPA
G1KB70_ANOCA|Anolis               YWLLPIFT-SLGDGCNFP---------------TRLV-------IMDPEQLTVSSQNEPA
K7FJ57_PELSI|Pelodiscus           YWLLPVFT-SLGDGCNFP---------------TRLV-------IMDPEQLTVSSQNEPP
G1NQF0_MELGA|Meleagris            YWLLPIFT-SLGDGCNFP---------------TRLV-------IMDPEQLTVSSQNEPA
F1P165_CHICK|Gallus               YWLLPIFT-SLGDGCNFP---------------TRLV-------IMDPEQVTVSSQNEPA
H0ZMC3_TAEGU|Taeniopygia          YWLLPIFT-SLGDGCNFP---------------TRLV-------IMDPEQLTVSSQNEPA
I3LAG4_PIG|Sus                    YWLLPVFS-SQGDGCSFP---------------TRLV-------GTDPEQASVSNQSESG
L5L6V4_PTEAL|Pteropus             YWLLPVFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTAQDECA
I3M6N4_SPETR|Spermophilus         YWLLPIFT-SLGDGCSFP---------------TRLV-------GMDPEQAA-TGQSEHS
ZDH20_MOUSE|Mus                   YWLVPIFS-SLGDGCSFP---------------ARLV-------GMDPEQASVANQSDYV
H0WAG6_CAVPO|Cavia                YWLLPVFS-SLGDGCSFP---------------TRLV-------GMDPEQASGTNQNDYA
G5B3L9_HETGA|Heterocephalus       YWLLPVFS-SLGDGCSFP---------------ARLV-------GMDPEQASAANQNDCA
F7DV21_HORSE|Equus                YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVSNQNEYA
ZDH20_BOVIN|Bos                   YWLLPVFS-SQGDGCSFP---------------TRLV-------GTDPEQASVSNQSESA
G3SXI8_LOXAF|Loxodonta            YWLIPVFS-SLGDGCSFP---------------ARLV-------GMDPEQASVTSQNEYA
H0XAJ4_OTOGA|Otolemur             YWLLPVFS-SLGDGCSFP---------------TRLV-------GLDPEQVSVANQNEYP
G1PP97_MYOLU|Myotis               YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
G3SCT5_GORGO|Gorilla              YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
G9KYT3_MUSPF|Mustela              YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYP
G1LWV6_AILME|Ailuropoda           YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
E2REV5_CANFA|Canis                YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
G1SFG2_RABIT|Oryctolagus          YWLLPVFS-SLGDGCSFP---------------TRLV-------GMDPEQASVANQDEFP
F7IAP1_CALJA|Callithrix           YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQAFVTNQNEYA
H2Q799_PANTR|Pan                  YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
F7E5B8_MACMU|Macaca               YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
ZDH20_HUMAN|Homo                  YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
H2NJD5_PONAB|Pongo                YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNQNEYA
G1RS44_NOMLE|Nomascus             YWLLPIFS-SLGDGCSFP---------------TRLV-------GMDPEQASVTNRNEYA
C3XW62_BRAFL|Branchiostoma        LWFLPVFT-SLGDGLKFP---------------TQVQ-------YDPSEPAPTDSPATES
L7MB41_9ACAR|Rhipicephalus        LWLLPVFT-SLGDGVTYP---------------TRTQ----------LASSYNSMGSTEQ
G6DE89_DANPL|Danaus               LWAIPVFT-SLGDGCEYP---------------VRREHQLQTFTTPQDGGGYESMGTTRS
E2A927_CAMFO|Camponotus           LWFLPIFS-SLGNGVVYP---------------VRSQ-------HQGTPNTYDSMGST--
K7J025_NASVI|Nasonia              LWFLPVFT-SLGNGVVFP---------------VRSQ-------HQGVSNTYNSMGSTQN
B4KLJ9_DROMO|Drosophila           YWFLPVFT-SKGDGLYFV---------------TSTD-----QFGNGNAQRYEAMGRTAA
B4LM13_DROVI|Drosophila           LWFLPVFT-SKGDGLSYR---------------TSSD-------QTGPGQRYEAMGNTTA
B4J5A2_DROGR|Drosophila           LWFLPVFT-SKGDGLSYP---------------TANE---QMGNGNANGQRYEAMGQTTT
B4GB93_DROPE|Drosophila           YWPLPIFT-SFGDGISY-------------------------------------------
B5E0C5_DROPS|Drosophila           YWPLPIFT-SFGDGISY-------------------------------------------
B4MQW5_DROWI|Drosophila           YWFLPIFT-SRGDGLTYP---------------TSTD-----QNGDIPAQRYDTMGQTTT
B3MD30_DROAN|Drosophila           YWFLPVFS-SFGDGIRY-------------------------------------------
B3N6S2_DROER|Drosophila           YWFLPVFS-SRGDGYSYP---------------TSSD--QSRVSTTSPVQRYDAMGDTAT
Q7K2V5_DROME|Drosophila           YWFLPVFS-SFGDGKTF-------------------------------------------
B4NX32_DROYA|Drosophila           YWFLPVFS-SRGDGYSYP---------------TSSD--QSRVSTTSPVQRYDAMGDTAA
Q7Q7Z4_ANOGA|Anopheles            LWFVPVYT-SLGDGIVFP---------------CR-------------------------
B0WC84_CULQU|Culex                LWFVPVYT-SLGDGMVYPVHASHLAASTPPPGMTTLVMSPSHHHQQPLQLPPPISAAGRR
                                   * .*:::        :                                           

A7S6A3_NEMVE|Nematostella         ------------------------------------------------------------
H2V2C9_TAKRU|Takifugu             R-----------------------------------------------------------
H3AQ09_LATCH|Latimeria            T-----------------------------------------------------------
G7PCM0_MACFA|Macaca               A-----------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          V-----------------------------------------------------------
F6XXZ8_MONDO|Monodelphis          F-----------------------------------------------------------
F1QRT3_DANRE|Danio                D-----------------------------------------------------------
H2LTT9_ORYLA|Oryzias              K-----------------------------------------------------------
G3NDP2_GASAC|Gasterosteus         K-----------------------------------------------------------
I3KAB2_ORENI|Oreochromis          K-----------------------------------------------------------
H3CRV3_TETNG|Tetraodon            L-----------------------------------------------------------
Q28H20_XENTR|Xenopus              K-----------------------------------------------------------
F7EKK0_ORNAN|Ornithorhynchus      K-----------------------------------------------------------
G1KB70_ANOCA|Anolis               K-----------------------------------------------------------
K7FJ57_PELSI|Pelodiscus           K-----------------------------------------------------------
G1NQF0_MELGA|Meleagris            K-----------------------------------------------------------
F1P165_CHICK|Gallus               K-----------------------------------------------------------
H0ZMC3_TAEGU|Taeniopygia          K-----------------------------------------------------------
I3LAG4_PIG|Sus                    R-----------------------------------------------------------
L5L6V4_PTEAL|Pteropus             R-----------------------------------------------------------
I3M6N4_SPETR|Spermophilus         R-----------------------------------------------------------
ZDH20_MOUSE|Mus                   R-----------------------------------------------------------
H0WAG6_CAVPO|Cavia                R-----------------------------------------------------------
G5B3L9_HETGA|Heterocephalus       G-----------------------------------------------------------
F7DV21_HORSE|Equus                R-----------------------------------------------------------
ZDH20_BOVIN|Bos                   R-----------------------------------------------------------
G3SXI8_LOXAF|Loxodonta            R-----------------------------------------------------------
H0XAJ4_OTOGA|Otolemur             R-----------------------------------------------------------
G1PP97_MYOLU|Myotis               R-----------------------------------------------------------
G3SCT5_GORGO|Gorilla              R-----------------------------------------------------------
G9KYT3_MUSPF|Mustela              R-----------------------------------------------------------
G1LWV6_AILME|Ailuropoda           R-----------------------------------------------------------
E2REV5_CANFA|Canis                R-----------------------------------------------------------
G1SFG2_RABIT|Oryctolagus          R-----------------------------------------------------------
F7IAP1_CALJA|Callithrix           R-----------------------------------------------------------
H2Q799_PANTR|Pan                  R-----------------------------------------------------------
F7E5B8_MACMU|Macaca               R-----------------------------------------------------------
ZDH20_HUMAN|Homo                  R-----------------------------------------------------------
H2NJD5_PONAB|Pongo                R-----------------------------------------------------------
G1RS44_NOMLE|Nomascus             R-----------------------------------------------------------
C3XW62_BRAFL|Branchiostoma        P-----------------------------------------------------------
L7MB41_9ACAR|Rhipicephalus        A-----------------------------------------------------------
G6DE89_DANPL|Danaus               S-----------------------------------------------------------
E2A927_CAMFO|Camponotus           ------------------------------------------------------------
K7J025_NASVI|Nasonia              R-----------------------------------------------------------
B4KLJ9_DROMO|Drosophila           G-----------------------------------------------------------
B4LM13_DROVI|Drosophila           NAASNRLDVQATDKLIDAIPLNNHQPHLELDNGQSSSHNHPLIPPSQVVVNIEQTAAAAA
B4J5A2_DROGR|Drosophila           ATTANVGSNRLEGQPTDKLIEAIPLNNHHPHVELENGQSSSNNHPLIPSSQIIVNVEQAA
B4GB93_DROPE|Drosophila           ------------------------------------------------------------
B5E0C5_DROPS|Drosophila           ------------------------------------------------------------
B4MQW5_DROWI|Drosophila           S-----------------------------------------------------------
B3MD30_DROAN|Drosophila           ------------------------------------------------------------
B3N6S2_DROER|Drosophila           S---------------------------RLDGNPTDKLIGASPLDTTNHHHNQSPHQVRS
Q7K2V5_DROME|Drosophila           ------------------------------------------------------------
B4NX32_DROYA|Drosophila           S-------------------RLDGNPTDKLIGASPLDNTNHHHNQSPHQVRSTSVQPTQL
Q7Q7Z4_ANOGA|Anopheles            ------------------------------------------------------------
B0WC84_CULQU|Culex                N-----------------------------------------------------------
                                                                                              

A7S6A3_NEMVE|Nematostella         ------------------------------------------------------------
H2V2C9_TAKRU|Takifugu             -------------------------------------------------------QNNG-
H3AQ09_LATCH|Latimeria            ---------------------------------------------------------KNI
G7PCM0_MACFA|Macaca               -------------------------------------------------------K-NS-
G3WFR2_SARHA|Sarcophilus          -------------------------------------------------------K--NL
F6XXZ8_MONDO|Monodelphis          -------------------------------------------------------S-TG-
F1QRT3_DANRE|Danio                -------------------------------------------------------K-GA-
H2LTT9_ORYLA|Oryzias              ------------------------------------------------------------
G3NDP2_GASAC|Gasterosteus         -------------------------------------------------------RAFR-
I3KAB2_ORENI|Oreochromis          ------------------------------------------------------------
H3CRV3_TETNG|Tetraodon            -------------------------------------------------------S----
Q28H20_XENTR|Xenopus              -------------------------------------------------------H-VGP
F7EKK0_ORNAN|Ornithorhynchus      -------------------------------------------------------S-PG-
G1KB70_ANOCA|Anolis               -------------------------------------------------------S-SG-
K7FJ57_PELSI|Pelodiscus           -------------------------------------------------------S-SG-
G1NQF0_MELGA|Meleagris            -------------------------------------------------------S-SG-
F1P165_CHICK|Gallus               -------------------------------------------------------S-SG-
H0ZMC3_TAEGU|Taeniopygia          -------------------------------------------------------S-SV-
I3LAG4_PIG|Sus                    -------------------------------------------------------S-IG-
L5L6V4_PTEAL|Pteropus             -------------------------------------------------------S-IG-
I3M6N4_SPETR|Spermophilus         -------------------------------------------------------S-IG-
ZDH20_MOUSE|Mus                   -------------------------------------------------------S-IG-
H0WAG6_CAVPO|Cavia                -------------------------------------------------------S-IA-
G5B3L9_HETGA|Heterocephalus       -------------------------------------------------------S-IG-
F7DV21_HORSE|Equus                -------------------------------------------------------S-IG-
ZDH20_BOVIN|Bos                   -------------------------------------------------------S-IG-
G3SXI8_LOXAF|Loxodonta            -------------------------------------------------------S-IG-
H0XAJ4_OTOGA|Otolemur             ------------------------------------------------------------
G1PP97_MYOLU|Myotis               -------------------------------------------------------S-IG-
G3SCT5_GORGO|Gorilla              -------------------------------------------------------S-SG-
G9KYT3_MUSPF|Mustela              -------------------------------------------------------S-IG-
G1LWV6_AILME|Ailuropoda           -------------------------------------------------------S-IG-
E2REV5_CANFA|Canis                -------------------------------------------------------S-IG-
G1SFG2_RABIT|Oryctolagus          -------------------------------------------------------S-SG-
F7IAP1_CALJA|Callithrix           -------------------------------------------------------S-SG-
H2Q799_PANTR|Pan                  -------------------------------------------------------S-SG-
F7E5B8_MACMU|Macaca               -------------------------------------------------------S-SG-
ZDH20_HUMAN|Homo                  -------------------------------------------------------S-SG-
H2NJD5_PONAB|Pongo                -------------------------------------------------------S-SG-
G1RS44_NOMLE|Nomascus             -------------------------------------------------------S-SG-
C3XW62_BRAFL|Branchiostoma        -------------------------------------------------DSPDSVG-FG-
L7MB41_9ACAR|Rhipicephalus        -------------------------------------------------------S-LG-
G6DE89_DANPL|Danaus               ---------------------------------------------------------FG-
E2A927_CAMFO|Camponotus           ------------------------------------------------------------
K7J025_NASVI|Nasonia              ------------------------------------------------------------
B4KLJ9_DROMO|Drosophila           --------------------------------------------------AATSNS-FG-
B4LM13_DROVI|Drosophila           AASPAAAGGASTAGAHATNHVIDMIGDQVMTAPAPAAKDVNVPNGGPPAIPTHNVV-FG-
B4J5A2_DROGR|Drosophila           AKLDPNHHSGTAI---------------DMIGDRMAPFTAKETNGAPPSSPANHIV-FG-
B4GB93_DROPE|Drosophila           ------------------------------------------------------------
B5E0C5_DROPS|Drosophila           ------------------------------------------------------------
B4MQW5_DROWI|Drosophila           -------------------------------------------------------S-FG-
B3MD30_DROAN|Drosophila           ------------------------------------------------------------
B3N6S2_DROER|Drosophila           TSVQPTQL----L---------------QVQPSSPYQDELNGRQEQLANGSTAAAS-FG-
Q7K2V5_DROME|Drosophila           ------------------------------------------------------------
B4NX32_DROYA|Drosophila           LQVQPPSPFRDELNERQEQLANDQSLNCITAAARSRPGECGVNGAAVYIDMIGDHP-FG-
Q7Q7Z4_ANOGA|Anopheles            ------------------------------------------------------------
B0WC84_CULQU|Culex                -----------------------------------------------HNDDDGAEN-DGE
                                                                                              

A7S6A3_NEMVE|Nematostella         -----------------------DDWSYR-------------------------------
H2V2C9_TAKRU|Takifugu             VSRPF-CVKGLTCSFNTRLLLSQSRW----------------------------------
H3AQ09_LATCH|Latimeria            EGHPF-PAKPL-RESQSHLLGSAQSWTEAA--GDEQKDKLGMNNPAMNIENET-------
G7PCM0_MACFA|Macaca               ENHQF-PAKPL-RESQSHLLTDSQSWTESS--TNPGKCKAGMSNPALTMENET-------
G3WFR2_SARHA|Sarcophilus          EGHQF-PSKPL-RESQSHLLTDPHSWADSS--TNSDKGKVGMSNPALTIENET-------
F6XXZ8_MONDO|Monodelphis          STENF-PVAPL-SESKNFLLATDS------------------------------------
F1QRT3_DANRE|Danio                VEVSAEQTSPL-SESQNRLLGNDYHSEEDH--KETEVLKSDESEAITISIESES------
H2LTT9_ORYLA|Oryzias              STADV-PAGPF-SDSQNHLLGDEQRGHNMEDSLADGALESGDHTPFGLTAETCT------
G3NDP2_GASAC|Gasterosteus         SAADV-PESPV-SESQNRLLSNDQHANDIGD-HQELTATKGISSYRSVILSN--------
I3KAB2_ORENI|Oreochromis          SAADI-TVSPL-SESQNRLLSNEQHANNVGDHLANNTLKSAESETITISMESES------
H3CRV3_TETNG|Tetraodon            -AADV-PSSPL-SESQNRLLSSEQDANSVGAHVENETLQSAESESIIYIEK---------
Q28H20_XENTR|Xenopus              SSQTF-PARPL-SESQNRLLGSESQWTDSA--PGEEPTDKGVESHVAVLIES--------
F7EKK0_ORNAN|Ornithorhynchus      TNQPL-PIRPL-SESKNRLLSSESQWLDGG--SEEEGVKSEIKNHVTVSIES--------
G1KB70_ANOCA|Anolis               PSQPF-PTRPL-SESQNRLLANDNQWAEAS--SEDENVKSGVKKHIVVSLES--------
K7FJ57_PELSI|Pelodiscus           ASQPF-PARPL-SESQNRLLDNESQWVEGG--SEEENVKSGAKKHVIVSLES--------
G1NQF0_MELGA|Meleagris            ANQPF-PTRPL-SESKNRLLASDSQWVESG--PEDENVKSGTKKHIIVSLES--------
F1P165_CHICK|Gallus               ANQPFPPTRPL-SESQNRLLASDSQWVESG--PEDENVKSGTKKHIIVSLES--------
H0ZMC3_TAEGU|Taeniopygia          ANQSF-PTRPL-SESQNRLLSGDCQWVETG--PEEENVKSGAKKHIIVSLES--------
I3LAG4_PIG|Sus                    SNQPF-PIKPL-SESKNRLLDSESQWLEDG--AEEGVVRPGTNNHVTVAVEN--------
L5L6V4_PTEAL|Pteropus             SNQPF-PVKPL-SESKNRLLEAESAWAGNG--SE-DAGRPGTHNHGTVAIGNGAPLVHN-
I3M6N4_SPETR|Spermophilus         SNQPF-PIRPL-SESKNRLLDNESQWLENG--AEEGVVRSGNNSHLKTLLHL--------
ZDH20_MOUSE|Mus                   SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGVTKSGTNNHVTVEIEN--------
H0WAG6_CAVPO|Cavia                SNPPF-PTRPL-SESKNRLLDTDCQWLENG--AEDGAIRSGTNNHVTVAVEN--------
G5B3L9_HETGA|Heterocephalus       SNPPF-PIRPL-SESKNRLLDTESQWLENG--VEEGAIRSGTNNDVTVAVEN--------
F7DV21_HORSE|Equus                SNQPF-PVKPL-SESKNRLLDSESQWLENG--SEESTVRSGTNNHVTVAIEN--------
ZDH20_BOVIN|Bos                   SNQPF-PIKPL-SESKNRLLDSDPQWLESG--SEEGVGGSGTNNHVTVAIEN--------
G3SXI8_LOXAF|Loxodonta            SNQPF-PIKPL-SESKNRLLDSESQWTEIR--SEEGIVRSGTNNHVTVTVEN--------
H0XAJ4_OTOGA|Otolemur             ------------RSKLQR------------------------------------------
G1PP97_MYOLU|Myotis               SNQPF-PIKPL-SESKNRLLDSESQWTENG--SEEGTVRSGNTCHLKTSLHM--------
G3SCT5_GORGO|Gorilla              SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGIVKSGTNNHVTVAIEN--------
G9KYT3_MUSPF|Mustela              SNQPF-PIKPL-SESKNRLLDSESQWIENG--SEEGTVRS--------------------
G1LWV6_AILME|Ailuropoda           SNQPF-PIKPL-SESKNRLLDNESQWIENG--SEEGTVRSGTNNHVTVAIEN--------
E2REV5_CANFA|Canis                SNQPF-PIKPL-SESKNRLLDSESQWIENG--SEESTVRSGTNNHVTVAIEN--------
G1SFG2_RABIT|Oryctolagus          SNQPF-PIKPL-SESKNRLLDNESQWLENG--AEEG-VRSGTNNHVTVAIEN--------
F7IAP1_CALJA|Callithrix           SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGIIRSGV------------------
H2Q799_PANTR|Pan                  SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGIIKSGTNNHVTMAIEN--------
F7E5B8_MACMU|Macaca               SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGIVKSGTNNHVTVAIEN--------
ZDH20_HUMAN|Homo                  SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGIVKSGTNNHVTVAIEN--------
H2NJD5_PONAB|Pongo                SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGIVKSGTNNHVTVAIEN--------
G1RS44_NOMLE|Nomascus             SNQPF-PIKPL-SESKNRLLDSESQWLENG--AEEGIVKSGTNNHVTVAIEN--------
C3XW62_BRAFL|Branchiostoma        DGMSF-PTRRT-SEDSHQLLNDRQRWAEEG--EGDVSDRETVPLR---------------
L7MB41_9ACAR|Rhipicephalus        DGVTF-PQKIV-DEDTDGLLNQRQRWAETD--EEAGHSDEGMPAPVSRAEKMHIADGDHP
G6DE89_DANPL|Danaus               DGFVY-PQRTT-DEDTESLLSSE-RWERWG--QRARPFDGSSSFDEL-------------
E2A927_CAMFO|Camponotus           QNRSTIDQMTLVQEATILALGAGTAVIGPS--VDADQPLMNTTESV--------------
K7J025_NASVI|Nasonia              ------------------------------------------------------------
B4KLJ9_DROMO|Drosophila           DGISY-PIRHL-EEDTESLLGYHSDTRIEL--EEDFLPEARFQDSIIP------------
B4LM13_DROVI|Drosophila           DGISY-PIRHL-EEDTESLLGYHSDTRIEL--EEDFLPEARFQDSIIP------------
B4J5A2_DROGR|Drosophila           DGISY-PIRHL-EEDTESLLGYHSDTRIEL--EEDFLPEARFQDSIIP------------
B4GB93_DROPE|Drosophila           ------PIRHL-EDDSETLLGYHSDTRIEL--DEDCLPESRFLHSIP-------------
B5E0C5_DROPS|Drosophila           ------PIRHL-EDDSETLLGYHSDTRIEL--DEDCLPESRFLHSIP-------------
B4MQW5_DROWI|Drosophila           DGISY-PIRHLEEEDTESLLGYHSDTRIEM--EEDFLPEPRFPDQIP-------------
B3MD30_DROAN|Drosophila           ------PIRHL-EEDTESLLGYHSDTRIEL--EEDFLPEPRFQDSIP-------------
B3N6S2_DROER|Drosophila           DGKTF-PIRHM-EEDTESLLGYHSDTRIEL--EEDFLPEPRFQDSIP-------------
Q7K2V5_DROME|Drosophila           ------PIRHM-EEDTESLLGYHSDTRIEL--EEDFLPEPRFQDSIP-------------
B4NX32_DROYA|Drosophila           DGKTF-PIRHM-EEDTESLLGYHSDTRIEL--EEDFLPEPRFQDSIP-------------
Q7Q7Z4_ANOGA|Anopheles            DVAPY-SIEFA-A-----------------------------------------------
B0WC84_CULQU|Culex                EFTTTTTTSKL-ETVNEHKYNHHHHLYDNV--QAPVVPPVRHNGTVPNGDVAGGRRRPED
                                                                                              

A7S6A3_NEMVE|Nematostella         --
H2V2C9_TAKRU|Takifugu             --
H3AQ09_LATCH|Latimeria            --
G7PCM0_MACFA|Macaca               --
G3WFR2_SARHA|Sarcophilus          --
F6XXZ8_MONDO|Monodelphis          --
F1QRT3_DANRE|Danio                --
H2LTT9_ORYLA|Oryzias              --
G3NDP2_GASAC|Gasterosteus         --
I3KAB2_ORENI|Oreochromis          --
H3CRV3_TETNG|Tetraodon            --
Q28H20_XENTR|Xenopus              --
F7EKK0_ORNAN|Ornithorhynchus      --
G1KB70_ANOCA|Anolis               --
K7FJ57_PELSI|Pelodiscus           --
G1NQF0_MELGA|Meleagris            --
F1P165_CHICK|Gallus               --
H0ZMC3_TAEGU|Taeniopygia          --
I3LAG4_PIG|Sus                    --
L5L6V4_PTEAL|Pteropus             --
I3M6N4_SPETR|Spermophilus         --
ZDH20_MOUSE|Mus                   --
H0WAG6_CAVPO|Cavia                --
G5B3L9_HETGA|Heterocephalus       --
F7DV21_HORSE|Equus                --
ZDH20_BOVIN|Bos                   --
G3SXI8_LOXAF|Loxodonta            --
H0XAJ4_OTOGA|Otolemur             --
G1PP97_MYOLU|Myotis               --
G3SCT5_GORGO|Gorilla              --
G9KYT3_MUSPF|Mustela              --
G1LWV6_AILME|Ailuropoda           --
E2REV5_CANFA|Canis                --
G1SFG2_RABIT|Oryctolagus          --
F7IAP1_CALJA|Callithrix           --
H2Q799_PANTR|Pan                  --
F7E5B8_MACMU|Macaca               --
ZDH20_HUMAN|Homo                  --
H2NJD5_PONAB|Pongo                --
G1RS44_NOMLE|Nomascus             --
C3XW62_BRAFL|Branchiostoma        --
L7MB41_9ACAR|Rhipicephalus        V-
G6DE89_DANPL|Danaus               --
E2A927_CAMFO|Camponotus           --
K7J025_NASVI|Nasonia              --
B4KLJ9_DROMO|Drosophila           --
B4LM13_DROVI|Drosophila           --
B4J5A2_DROGR|Drosophila           --
B4GB93_DROPE|Drosophila           --
B5E0C5_DROPS|Drosophila           --
B4MQW5_DROWI|Drosophila           --
B3MD30_DROAN|Drosophila           --
B3N6S2_DROER|Drosophila           --
Q7K2V5_DROME|Drosophila           --
B4NX32_DROYA|Drosophila           --
Q7Q7Z4_ANOGA|Anopheles            --
B0WC84_CULQU|Culex                VV
                                    
