MUSCLE (3.8) multiple sequence alignment


G6DDQ2_DANPL|Danaus               -----------------MSF----------------KRLCHWGPICVLGIIKLITWSMVH
E2AIW9_CAMFO|Camponotus           --------------MCISPL----------------KKICHWGPLSALGIIKIITLMTIH
K7J230_NASVI|Nasonia              --------------MCFGPF----------------KRICNWGPLTALVIIKIITLMSIH
B4GZ57_DROPE|Drosophila           ------------MSAEISGF----------------RRFIHWGPITALSIIKCITLTTLY
Q29B32_DROPS|Drosophila           ------------MSAEISGF----------------RRFIHWGPITALSIIKCITLTTLY
B4NJE7_DROWI|Drosophila           MSGFRRNYC----------------------------RFFHWGPITALSIIKCITLTTLY
B4JTP9_DROGR|Drosophila           ------------MSAKISGF----------------RRFLHWGPITALSIIKCITLTTLY
B4K872_DROMO|Drosophila           ------------MSAEISGF----------------RRFLHWGPITALSIIKCVTLTTLY
B4LY95_DROVI|Drosophila           ------------MSAEISGF----------------RRFLHWGPITALSIIKCITLTTLY
B3M2Q2_DROAN|Drosophila           ------------MSAELSGF----------------RRFLHWGPITALSIIKCITLTTLY
Q9VG80_DROME|Drosophila           ------------MSPEISGF----------------RRFLHWGPITALSIIKCITLTTLY
B3P1B3_DROER|Drosophila           ------------MSAEISGF----------------RRFLHWGPIAALSIIKCITLTTLY
B4PNT1_DROYA|Drosophila           ------------MSAEISGF----------------RRFLHWGPIAALSIIKCITLTTLY
B0X823_CULQU|Culex                -----------------MTT----------------KPLRRNAEKCHEAIIKSITFMTLY
Q7PNJ3_ANOGA|Anopheles            -----------MFLGWYNSI----------------RRFLHWGPLTAIGIIQSITVMTIY
C3ZWI2_BRAFL|Branchiostoma        -------MAPRIDWRDL-------------------RRLCHWGPLVALFIIVYCYVMGVG
Q4T1U0_TETNG|Tetraodon            ----XGC--------------------------------CH---------AAIIFIMTMY
E7F6D7_DANRE|Danio                ----MNILSAIIVFENLHEV----------------KRLFHWGPIIALTVIGVCSSMAIL
H2U6U0_TAKRU|Takifugu             ----MNIFSMVVTFENLHEV----------------RRLCHWGPIIALSVISICSTMAIL
H2LWT2_ORYLA|Oryzias              ----MNFLSALVRFENLHEV----------------RRLCHWGPIIALSVIAICSTMAII
G3NBP8_GASAC|Gasterosteus         ----MNFLSTFVTFQNLHEV----------------RRLCHWGPIIALSVIVICSTMAIV
I3KH45_ORENI|Oreochromis          ----MNFLSTFVTFKNLHEV----------------RRLCHWGPIIALSVIAICSTMAIL
F7B8P9_XENTR|Xenopus              ----AVMLDSYLSFETLREL----------------KRLLHWGPIIALGVIIICSIMAIL
H3AT93_LATCH|Latimeria            ----MGVLCSIIKFENLHEL----------------KRLCHWGPIIALTVIAVCSTVAII
F7F8E7_ORNAN|Ornithorhynchus      ----MGVLCSVIKFENLHEL----------------RRLCHWGPIIALGVIAICSTMAMI
F6ST88_MONDO|Monodelphis          ----MGVLYSVIRFENLHEL----------------KRLCHWGPIIALGVIAICSTMAMI
G3X1U7_SARHA|Sarcophilus          ----MSINEDSRTYDT-------------------------WKCIYKKGTLQ--------
F7BDK1_HORSE|Equus                ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALSVIAICSTMAMI
L5K3B1_PTEAL|Pteropus             ----MSTFCSIIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
ZDHC6_MOUSE|Mus                   ----MGIFCSVIKFENLQDL----------------RRLCHWGPIIALGVIAICSTMAMI
Q32PY5_RAT|Rattus                 ----MSTLCSVIKFENLQDL----------------RRLCHWGPIIALGVIAICSTMAMI
G5BKD2_HETGA|Heterocephalus       ----MNTLCSVIKFENLQEL----------------KRLCHWGPIVALGVIAICSTMAMI
H0V760_CAVPO|Cavia                ----MNALCSVIKFENLQEL----------------KRLCHWGPIIALGVIATCSTVAMI
H0XNL2_OTOGA|Otolemur             ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
G3T188_LOXAF|Loxodonta            ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
I3MLS9_SPETR|Spermophilus         ----MGAFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
G1SK13_RABIT|Oryctolagus          ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
G1NWP6_MYOLU|Myotis               ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
ZDHC6_BOVIN|Bos                   ----MGTFCSVVKFENLQEL----------------KRLCHWGPIIALGVIAICSAMAMI
D2GX33_AILME|Ailuropoda           ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
F6XXY3_CANFA|Canis                ----MDTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
G9KYU0_MUSPF|Mustela              ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
F1S5J7_PIG|Sus                    ----MGTFCSVIRFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
F7IKK1_CALJA|Callithrix           ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
G7PDZ3_MACFA|Macaca               ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
H9ETH9_MACMU|Macaca               ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
G3SHQ9_GORGO|Gorilla              ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
ZDHC6_HUMAN|Homo                  ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
H2Q2K7_PANTR|Pan                  ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
ZDHC6_PONAB|Pongo                 ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
G1S129_NOMLE|Nomascus             ----MGTFCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
H9GF83_ANOCA|Anolis               ----MGVLCSVIRFENLHEL----------------RRLCHWGPIIALSVIAICSAMAMI
K7FG36_PELSI|Pelodiscus           ----MGALCSVIKFENLQEL----------------KRLCHWGPIIALGVIAICSTMAMI
H0ZKK9_TAEGU|Taeniopygia          ------------------------------------------------------------
F1NN38_CHICK|Gallus               ------------------------------------------------------------
G1NEM3_MELGA|Meleagris            ------------------------------------------------------------
G3MGC2_9ACAR|Amblyomma            YFSPRPAFGYSVKLDPLQEAEMEPQPGVLDILAQFCQRLVHWGPVTALLIIKFIFLTSLY
A7RQ92_NEMVE|Nematostella         ----MP------------------------------RGICHWGPLLALSIIITLFLGGLY
                                                                                              

G6DDQ2_DANPL|Danaus               LIGMWWPPYLTLGGALHAAFFLSLAASTLYFFMQALLEGPGYVPQGWKPAEECDVQYLQY
E2AIW9_CAMFO|Camponotus           CSKQWWSPQESIPAATSFLLFFTLSGLTLFHFISAIFEGPGYLKLKWMPENVTDKQYLQY
K7J230_NASVI|Nasonia              CSRQWWSPNKSALSDISFIVFITFSGLTLYHFINSIYEGPGYLPFNWVPENENDCQFLQF
B4GZ57_DROPE|Drosophila           MNSMWWPPNESFAGFAHQALFLMLSTLATFNYVMATLTGPGLLPRQWQPKEPKDTEYLQY
Q29B32_DROPS|Drosophila           MNSMWWPPNESFAGFAHQALFLMLSTLATFNYVMATLTGPGLLPRQWQPKELKDTEYLQY
B4NJE7_DROWI|Drosophila           MNSMWWPPNESFAAFAHQGLFLMLSTLATFNYVMATLTGPGLLPKQWHPKDPKDTQFLQY
B4JTP9_DROGR|Drosophila           MNSMWWPPNESFAAFAHQALFLLLSTLATYNYIMATLTGPGLLPKQWQPKESKDIELLQY
B4K872_DROMO|Drosophila           MNSMWWPPNESFAAFAHQALFLLLSTLATFNYIMATLTGPGLLPKQWQPKDPKDTEWLQY
B4LY95_DROVI|Drosophila           MNSMWWPPNESFAAFAHQALFLLLSTLATFNYIMATVTGPGLLPKQWQPKDPKDTEWLQY
B3M2Q2_DROAN|Drosophila           MNSMWWPPNESFAAFAHQALFLLLSTLATFNYVMATLTGPGLMPKQWQPKDPKDTQFLQY
Q9VG80_DROME|Drosophila           MNSMWWPPNKSFAGFAHQALFLLLSTLATFNYVMATLTGPGLMPKQWHPKDPKDAQFLQY
B3P1B3_DROER|Drosophila           MNSMWWPPNESFAGFAHQALFLLLSTLATFNYVMATLTGPGLMPKRWHPKDPKAAQFLQY
B4PNT1_DROYA|Drosophila           MNSMWWPPNESFAGFAHQALFLLLSTLATFNYVMATLTGPGLMPKRWHPKDPKDAQFLQY
B0X823_CULQU|Culex                MNAMWWPPNRSLGGFVNQTIFLILSASTGFNFVMASLIGPKFLPLRWRPKNPKDEQFLQF
Q7PNJ3_ANOGA|Anopheles            MNSMWWPSHTSLWALINQTVFVLLSLGTGFYFVMASLTGPGYLRLKWRPAHHSADEQLQF
C3ZWI2_BRAFL|Branchiostoma        CILIWWPPV-TAAGVAHLIVYTAWELTILYNFFQAMLLGPGFVPLGWKPEKEEDCQFLQY
Q4T1U0_TETNG|Tetraodon            THIY---------DRVSLPLRHCFSISVDLDCFTV--TGSSTLARAFACFLTADIIWLEH
E7F6D7_DANRE|Danio                DSIIWYWPLDTTGGSINFIMLINWTVLILYNYFNAMFVGPGYIPLEWKPEKQQDIMYLQF
H2U6U0_TAKRU|Takifugu             DSIIWYWPLDTTGGSINFIMLINWTVLILYNYFNAMFVGPGYIPLDWKPGNQHHTQYLQY
H2LWT2_ORYLA|Oryzias              DSVIWYWPLDTTAGSINFLMLLNWTVLILYNYFNAMFVGPGYIPLGWKPENPKDTQFLQY
G3NBP8_GASAC|Gasterosteus         DSIIWYWPLDTTGGSINFIMLLNWTVLILYNYFNAMFVGPGYIPLGWKPERQQDAQYLQY
I3KH45_ORENI|Oreochromis          DSIIWYWPLDTTGGSINFIMLINWTVLILYNYFNAMFVGPGYIPLGWKPENQQDTQYLQY
F7B8P9_XENTR|Xenopus              DSILWYWPLDTPGGSLNFLTLVNWTVMILYNYFNAMFIGPGFVPLGWKPERTQDCAYLQY
H3AT93_LATCH|Latimeria            DSVIWYWPLDTTGGSVNFIMLINWTVLILYNYFNAMFVGPGYVPFGWKPESPQDSMYLQY
F7F8E7_ORNAN|Ornithorhynchus      DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFIGPGYVPLDWKPEKSQDSMYLQY
F6ST88_MONDO|Monodelphis          DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGYVPLKWKPEKAQDTTYLQF
G3X1U7_SARHA|Sarcophilus          ------------GGSVNFIMLINWTVMILYNYFNAMFVGPGYVPLKWKPEKAQDSMYLQF
F7BDK1_HORSE|Equus                DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEHSQDSMYLQY
L5K3B1_PTEAL|Pteropus             DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFIGPGFVPLGWKPENSQDSMYLQY
ZDHC6_MOUSE|Mus                   DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFAGPGFVPRGWKPEKSQDSMYLQY
Q32PY5_RAT|Rattus                 DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFAGPGFVPRGWKPENPQDSMYLQY
G5BKD2_HETGA|Heterocephalus       DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEDSQDGMYLQY
H0V760_CAVPO|Cavia                DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPENSQDIMYLQY
H0XNL2_OTOGA|Otolemur             DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPENSQDTVYLQY
G3T188_LOXAF|Loxodonta            DSVLWYWPLHTTGGSVNFIMLINWTIMILYNYFNAVFVGPGFVPLGWKPENSQDSMYLQY
I3MLS9_SPETR|Spermophilus         DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPENSQDSMYLQY
G1SK13_RABIT|Oryctolagus          DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPENSQDTMYLQY
G1NWP6_MYOLU|Myotis               DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFIGPGFVPLGWKPENSQDSMYLQY
ZDHC6_BOVIN|Bos                   DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPENSQDSVYLQY
D2GX33_AILME|Ailuropoda           DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFIGPGFVPLGWKPENSQDSMYLQY
F6XXY3_CANFA|Canis                DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFIGPGFVPLGWKPENSQDSMYLQY
G9KYU0_MUSPF|Mustela              DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFIGPGFVPLGWKPENSQDSMYLQY
F1S5J7_PIG|Sus                    DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPENSQDSMYLQY
F7IKK1_CALJA|Callithrix           DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEISQDTMYLQY
G7PDZ3_MACFA|Macaca               DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLRWKPEISQDTMYLQY
H9ETH9_MACMU|Macaca               DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLRWKPEISQDTMYLQY
G3SHQ9_GORGO|Gorilla              DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEISQDTMYLQY
ZDHC6_HUMAN|Homo                  DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEISQDTMYLQY
H2Q2K7_PANTR|Pan                  DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEISQDTMYLQY
ZDHC6_PONAB|Pongo                 DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEISQDTMYLQY
G1S129_NOMLE|Nomascus             DSVLWYWPLHTTGGSVNFIMLINWTVMILYNYFNAMFVGPGFVPLGWKPEISQDTMYLQY
H9GF83_ANOCA|Anolis               DAVLWYWPLDTTGGSINFIMLINWTVMILYNYFNAMFVGPGYVPFGWKPENSQDCMYLQY
K7FG36_PELSI|Pelodiscus           DAVLWYWPLDTTGGSVNFIMLINWTVMILYNYFNAMFIGPGYVPLGWKPEKSQDCMYLQY
H0ZKK9_TAEGU|Taeniopygia          -------------------MLLNWTVMILYNYFSAMFVGPGYVPLGWTPEKSQDCMYLQY
F1NN38_CHICK|Gallus               -----------------------------------XFVGPGYVPLGWTPEKSQDCMYLQY
G1NEM3_MELGA|Meleagris            -------------------------------------------PFFYLKEKSQDCMYLQY
G3MGC2_9ACAR|Amblyomma            VTSMWLSPYGSTLGSVNHAVFIGWVXVLLYNFFMAVAMGPGFVPLKWRPEHPDDEQFLQY
A7RQ92_NEMVE|Nematostella         CIILVYTPWHSLGAMLHLGVYLNWAFLILYNFLRGIWLGPGYVPFKWRPAKESDTECLQF
                                                                                :          *:.

G6DDQ2_DANPL|Danaus               CTTCKGYKAP-RSHHCRKCGHCIKKMDHHCPWINCCVGHNNHAYFTLFLISAVLGCLHAS
E2AIW9_CAMFO|Camponotus           CIICQGYKAP-RSHHCRKCNRCVLKMDHHCPWINTCVGHYNHGHFTAFLASAVGGCCVST
K7J230_NASVI|Nasonia              CTVCQGYKAP-RSHHCRKCGRCILKMDHHCPWINNCVGHYNHGYFTAFLASAVAGCCVST
B4GZ57_DROPE|Drosophila           CKACEGYKAP-RSHHCRKCNRCVKKMDHHCPWINHCVGWANHAYFSYFLLFSILGSMQAT
Q29B32_DROPS|Drosophila           CKACEGYKAP-RSHHCRKCNRCVKKMDHHCPWINHCVGWANHAYFSYFLLFSILGSMQAT
B4NJE7_DROWI|Drosophila           CKQCEGFKAP-RSHHCRKCNRCVKKMDHHCPWINHCVGWANHAYFTYFLLFSILGSLQGT
B4JTP9_DROGR|Drosophila           CKECEGYKAP-RSHHCRKCNRCVKKMDHHCPWINHCVGWANHAYFSYFLFFSIIGSLHGS
B4K872_DROMO|Drosophila           CKECEGYKAP-RSHHCRKCNRCVKKMDHHCPWINHCVGWANHAYFTYFLLFSILGSLHGS
B4LY95_DROVI|Drosophila           CKQCEGYKAP-RSHHCRKCNRCVKKMDHHCPWINHCVGWANHAYFCYFLLFSILGSLHGS
B3M2Q2_DROAN|Drosophila           CKKCEGYKAP-RSHHCRKCDRCVKKMDHHCPWINHCVGWANHAYFTFFLLFSILGSLHGT
Q9VG80_DROME|Drosophila           CKKCEGYKAP-RSHHCRKCDRCVKKMDHHCPWINHCVGWANHAYFTYFLLFSILGSLQGT
B3P1B3_DROER|Drosophila           CKKCEGYKAP-RSHHCRKCDRCVKKMDHHCPWINHCVGWANHAYFTYFLLFSILGSLQGT
B4PNT1_DROYA|Drosophila           CKKCEGYKAP-RSHHCRKCDRCVKKMDHHCPWINHCVGWANHAYFTYFLLFSILGSLQGT
B0X823_CULQU|Culex                CSSCEGFKAP-RSHHCRKCD--------------------------SFLAFAVAGCLHAT
Q7PNJ3_ANOGA|Anopheles            CIVCGGYKAP-RSHHCRKCDRCVIKMDHHCPWINNCVGWANHGYFTAFLAFAVLGCIHGT
C3ZWI2_BRAFL|Branchiostoma        CKQCQGYKSP-RSHHCRKCKRCVMKMDHHCPWINTCCGHLNHTRFILFLLSAPLGCLHAT
Q4T1U0_TETNG|Tetraodon            CKDQHEFHSSISAPHTLQCA-CL------------CC-------YTLCLRF---GTRHHF
E7F6D7_DANRE|Danio                CRLCQGYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHLNHAYFTSFLLLAPLGCIHAA
H2U6U0_TAKRU|Takifugu             CKVCHGYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHLNHAYFTSFLLLAPLGCSHAA
H2LWT2_ORYLA|Oryzias              CRICQGYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHLNHAYFTSFLLLAPLGCSHAA
G3NBP8_GASAC|Gasterosteus         CSVCQGYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHMNHAYFTSFLLLAPLGCSHAA
I3KH45_ORENI|Oreochromis          CRGCQGYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHLNHAYFTSFLLLAPLGCSHAA
F7B8P9_XENTR|Xenopus              CKVCEGYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHRNHSSFTLFLILAPLGCIHAA
H3AT93_LATCH|Latimeria            CLVCQGYKAP-RSHHCRRCNRCVMKMDHHCPWINNCCGHHNHAYFTLFLLLAPLGCIHAS
F7F8E7_ORNAN|Ornithorhynchus      CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFILFLLLAPLGCIHAA
F6ST88_MONDO|Monodelphis          CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGFQNHASFTLFLLLAPLGCIHAA
G3X1U7_SARHA|Sarcophilus          CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
F7BDK1_HORSE|Equus                CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
L5K3B1_PTEAL|Pteropus             CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
ZDHC6_MOUSE|Mus                   CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHQNHASFTLFLLLAPLGCTHAA
Q32PY5_RAT|Rattus                 CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHQNHASFTLFLLLAPLGCTHAA
G5BKD2_HETGA|Heterocephalus       CKACQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGHQNHASFTLFLLLAPLGCIHAA
H0V760_CAVPO|Cavia                CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
H0XNL2_OTOGA|Otolemur             CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGFQNHASFTLFLLLAPLGCIHAA
G3T188_LOXAF|Loxodonta            CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
I3MLS9_SPETR|Spermophilus         CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
G1SK13_RABIT|Oryctolagus          CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
G1NWP6_MYOLU|Myotis               CQVCQAYKAP-RSHHCRKCNRCVLKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
ZDHC6_BOVIN|Bos                   CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
D2GX33_AILME|Ailuropoda           CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
F6XXY3_CANFA|Canis                CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
G9KYU0_MUSPF|Mustela              CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
F1S5J7_PIG|Sus                    CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
F7IKK1_CALJA|Callithrix           CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
G7PDZ3_MACFA|Macaca               CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
H9ETH9_MACMU|Macaca               CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
G3SHQ9_GORGO|Gorilla              CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
ZDHC6_HUMAN|Homo                  CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
H2Q2K7_PANTR|Pan                  CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
ZDHC6_PONAB|Pongo                 CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
G1S129_NOMLE|Nomascus             CKVCQAYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAA
H9GF83_ANOCA|Anolis               CKICQSYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGFQNHASFTLFLLLAPLGCIHAA
K7FG36_PELSI|Pelodiscus           CKVCQSYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAS
H0ZKK9_TAEGU|Taeniopygia          CKVCQSYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAS
F1NN38_CHICK|Gallus               CKVCQSYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAS
G1NEM3_MELGA|Meleagris            CKVCQSYKAP-RSHHCRKCNRCVMKMDHHCPWINNCCGYQNHASFTLFLLLAPLGCIHAS
G3MGC2_9ACAR|Amblyomma            CANCDGFKTP-RSHHCRKCERCVLKMDHHCPWINTCCGHRNHANFTLFLFFAVCGSMHAT
A7RQ92_NEMVE|Nematostella         CHVCQGYKAP-RAHHCSKCNRCVMKMDHHCPWINNCVGHYNMKSFTLFLFFVPLGCTHCA
                                  *     :::.  : *  .*                             *     *     

G6DDQ2_DANPL|Danaus               IVLSICLY----------------HAIHRVWYLQYG------------------------
E2AIW9_CAMFO|Camponotus           VILISWVT----------------TVLS--------------------------------
K7J230_NASVI|Nasonia              YIMVKWLL----------------TVFS--------------------------------
B4GZ57_DROPE|Drosophila           VVLCGSFY----------------RGIYRYYYLTHG------------------------
Q29B32_DROPS|Drosophila           VVLCGSFY----------------RGIYRYYYLTHG------------------------
B4NJE7_DROWI|Drosophila           VVLSCSFY----------------RGIYRYYYLTHG------------------------
B4JTP9_DROGR|Drosophila           VVLSCSFY----------------RGIYRYYYLTHS------------------------
B4K872_DROMO|Drosophila           IVLSCSFY----------------RGIHRYYYLTHG------------------------
B4LY95_DROVI|Drosophila           VVLSCSFY----------------RGIHRYYYLTHG------------------------
B3M2Q2_DROAN|Drosophila           VVLCCSFW----------------RGIYRYYYLTHG------------------------
Q9VG80_DROME|Drosophila           VVLCCSFW----------------RGIYRYYYLTHG------------------------
B3P1B3_DROER|Drosophila           VVLCCSFW----------------RGIYRYYYLTHG------------------------
B4PNT1_DROYA|Drosophila           VVLCCSFW----------------RGIYRYYYLTHG------------------------
B0X823_CULQU|Culex                VILFGSLY----------------AGLHRDWYVYYG------------------------
Q7PNJ3_ANOGA|Anopheles            VILGSSLY----------------VGLYRDWYVYYG------------------------
C3ZWI2_BRAFL|Branchiostoma        VVYGCTMYRSCSPDCVHGVGADYPVQLL--PSHAAGAGLRAARMETGGTMAPRIDWRDLR
Q4T1U0_TETNG|Tetraodon            LLY---------------------------------------------------------
E7F6D7_DANRE|Danio                LIFIMTMY----------------TQLY--DRISFG------------------------
H2U6U0_TAKRU|Takifugu             IIFIMTMY----------------TQLY--DRISFG------------------------
H2LWT2_ORYLA|Oryzias              FIFVMTMY----------------TQLY--ERISFG------------------------
G3NBP8_GASAC|Gasterosteus         IIFIMTMY----------------TQLY--ERISFG------------------------
I3KH45_ORENI|Oreochromis          VIFIMTMY----------------TQLY--ERISFG------------------------
F7B8P9_XENTR|Xenopus              YIFIMTMY----------------TQLY--NRISFG------------------------
H3AT93_LATCH|Latimeria            FIFIMTMY----------------TQLY--NRISFG------------------------
F7F8E7_ORNAN|Ornithorhynchus      FIFVMTMY----------------TQLY--NRISFG------------------------
F6ST88_MONDO|Monodelphis          FIFVMTMY----------------TQLY--NRISFG------------------------
G3X1U7_SARHA|Sarcophilus          FIFVMTMY----------------TQLY--NRISFG------------------------
F7BDK1_HORSE|Equus                FIFVMTMY----------------TQLY--NRLSFG------------------------
L5K3B1_PTEAL|Pteropus             FIFVMTMY----------------TQLY--NRLSFG------------------------
ZDHC6_MOUSE|Mus                   FIFVMTMY----------------TQLY--NRLSFG------------------------
Q32PY5_RAT|Rattus                 FIFVMTMY----------------TQLY--NRLSFG------------------------
G5BKD2_HETGA|Heterocephalus       FIFVMTMY----------------TQLY--NRLSFG------------------------
H0V760_CAVPO|Cavia                FIFVMTMY----------------TQLY--NRLSFG------------------------
H0XNL2_OTOGA|Otolemur             FIFVMTMY----------------TQLY--NRLSFG------------------------
G3T188_LOXAF|Loxodonta            FIFIMTMY----------------TQLY--NRLSFG------------------------
I3MLS9_SPETR|Spermophilus         FIFVMTMY----------------TQLY--NRLSFG------------------------
G1SK13_RABIT|Oryctolagus          FIFVMTMY----------------TQLY--NRLSFG------------------------
G1NWP6_MYOLU|Myotis               FIFVMTMY----------------TQLY--NRLSFG------------------------
ZDHC6_BOVIN|Bos                   FIFVMTMY----------------TQLY--NRLSFG------------------------
D2GX33_AILME|Ailuropoda           FIFVMTMY----------------TQLY--NRLSFG------------------------
F6XXY3_CANFA|Canis                FIFVMTMY----------------TQLY--NRLSFG------------------------
G9KYU0_MUSPF|Mustela              FIFVMTMY----------------TQLY--NRLSFG------------------------
F1S5J7_PIG|Sus                    FIFVMTMY----------------TQLY--NRLSFG------------------------
F7IKK1_CALJA|Callithrix           FIFVMTMY----------------TQLY--NRLSFG------------------------
G7PDZ3_MACFA|Macaca               FIFVMTMY----------------TQLY--NRLSFG------------------------
H9ETH9_MACMU|Macaca               FIFVMTMY----------------TQLY--NRLSFG------------------------
G3SHQ9_GORGO|Gorilla              FIFVMTMY----------------TQLY--HRLSFG------------------------
ZDHC6_HUMAN|Homo                  FIFVMTMY----------------TQLY--HRLSFG------------------------
H2Q2K7_PANTR|Pan                  FIFVMTMY----------------TQLY--HRLSFG------------------------
ZDHC6_PONAB|Pongo                 FIFVMTMY----------------TQLY--HRLSFG------------------------
G1S129_NOMLE|Nomascus             FIFVMTMY----------------TQLY--HRLSFG------------------------
H9GF83_ANOCA|Anolis               FIFVMTMY----------------TQLY--NRVSFG------------------------
K7FG36_PELSI|Pelodiscus           FIFIMTMY----------------TQLY--NRISFG------------------------
H0ZKK9_TAEGU|Taeniopygia          FIFIMTMY----------------TQLY--NRISFG------------------------
F1NN38_CHICK|Gallus               FIFVMTMY----------------TQLY--NRISFG------------------------
G1NEM3_MELGA|Meleagris            FIFVMTMY----------------TQLY--NRISFG------------------------
G3MGC2_9ACAR|Amblyomma            VLLVMGLA-----------------KAY--HRKYY-------------------------
A7RQ92_NEMVE|Nematostella         IILFLCLY----------------NEVY--------------------------------
                                   :                                                          

G6DDQ2_DANPL|Danaus               ------------------------------------------------------------
E2AIW9_CAMFO|Camponotus           ------------------------------------------------------------
K7J230_NASVI|Nasonia              ------------------------------------------------------------
B4GZ57_DROPE|Drosophila           ------------------------------------------------------------
Q29B32_DROPS|Drosophila           ------------------------------------------------------------
B4NJE7_DROWI|Drosophila           ------------------------------------------------------------
B4JTP9_DROGR|Drosophila           ------------------------------------------------------------
B4K872_DROMO|Drosophila           ------------------------------------------------------------
B4LY95_DROVI|Drosophila           ------------------------------------------------------------
B3M2Q2_DROAN|Drosophila           ------------------------------------------------------------
Q9VG80_DROME|Drosophila           ------------------------------------------------------------
B3P1B3_DROER|Drosophila           ------------------------------------------------------------
B4PNT1_DROYA|Drosophila           ------------------------------------------------------------
B0X823_CULQU|Culex                ------------------------------------------------------------
Q7PNJ3_ANOGA|Anopheles            ------------------------------------------------------------
C3ZWI2_BRAFL|Branchiostoma        RLCHWGPLVALFIIVYCYVMGVGCILIWWPPVTAAGEGGRLPVSPVLCVMKMDHHCPWIN
Q4T1U0_TETNG|Tetraodon            ------------------------------------------------------------
E7F6D7_DANRE|Danio                ----------------------------WSSVKIDMSAAR--------------------
H2U6U0_TAKRU|Takifugu             ----------------------------WSTVKINMSAA---------------------
H2LWT2_ORYLA|Oryzias              ----------------------------WSTVKIDMSAV---------------------
G3NBP8_GASAC|Gasterosteus         ----------------------------WSTVKIDMSAV---------------------
I3KH45_ORENI|Oreochromis          ----------------------------WSTVRIDMSAV---------------------
F7B8P9_XENTR|Xenopus              ----------------------------WNSVKIDMSAPR--------------------
H3AT93_LATCH|Latimeria            ----------------------------WSSVKIDMSAVK--------------------
F7F8E7_ORNAN|Ornithorhynchus      ----------------------------WSTVKIDMSAAR--------------------
F6ST88_MONDO|Monodelphis          ----------------------------WNTVKIDMSAAK--------------------
G3X1U7_SARHA|Sarcophilus          ----------------------------WNTVKIDMSAVK--------------------
F7BDK1_HORSE|Equus                ----------------------------WNTVKIDMSAAR--------------------
L5K3B1_PTEAL|Pteropus             ----------------------------WNTVKIDMSAAR--------------------
ZDHC6_MOUSE|Mus                   ----------------------------WNTVKIDMSAAR--------------------
Q32PY5_RAT|Rattus                 ----------------------------WNTVKIDMSAAR--------------------
G5BKD2_HETGA|Heterocephalus       ----------------------------WNTVKIDMSAAR--------------------
H0V760_CAVPO|Cavia                ----------------------------WNTVKIDMSAAR--------------------
H0XNL2_OTOGA|Otolemur             ----------------------------WSTVKIDMSAAR--------------------
G3T188_LOXAF|Loxodonta            ----------------------------WNTVRIDMSAAR--------------------
I3MLS9_SPETR|Spermophilus         ----------------------------WNTVKIDMSAAR--------------------
G1SK13_RABIT|Oryctolagus          ----------------------------WNTVKIDMSAAR--------------------
G1NWP6_MYOLU|Myotis               ----------------------------WNTVKIDMSAAR--------------------
ZDHC6_BOVIN|Bos                   ----------------------------WNTVKIDMSAAR--------------------
D2GX33_AILME|Ailuropoda           ----------------------------WNTVKIDMSAAR--------------------
F6XXY3_CANFA|Canis                ----------------------------WNTVKIDMSAAR--------------------
G9KYU0_MUSPF|Mustela              ----------------------------WNTVKIDMSAAR--------------------
F1S5J7_PIG|Sus                    ----------------------------WNTVKIDMSAAR--------------------
F7IKK1_CALJA|Callithrix           ----------------------------WNTVKIDMSAAR--------------------
G7PDZ3_MACFA|Macaca               ----------------------------WNTVKIDMSAAR--------------------
H9ETH9_MACMU|Macaca               ----------------------------WNTVKIDMSAAR--------------------
G3SHQ9_GORGO|Gorilla              ----------------------------WNTVKIDMSAAR--------------------
ZDHC6_HUMAN|Homo                  ----------------------------WNTVKIDMSAAR--------------------
H2Q2K7_PANTR|Pan                  ----------------------------WNTVKIDMSAAR--------------------
ZDHC6_PONAB|Pongo                 ----------------------------WNTVKIDMSAAR--------------------
G1S129_NOMLE|Nomascus             ----------------------------WNTVKIDMSAAR--------------------
H9GF83_ANOCA|Anolis               ----------------------------WSSVRIDMSAAR--------------------
K7FG36_PELSI|Pelodiscus           ----------------------------WNSVKIDMSAAK--------------------
H0ZKK9_TAEGU|Taeniopygia          ----------------------------WSSVKIDMSAAK--------------------
F1NN38_CHICK|Gallus               ----------------------------WSSVKIDMSAAK--------------------
G1NEM3_MELGA|Meleagris            ----------------------------WSSVKIDMSAAK--------------------
G3MGC2_9ACAR|Amblyomma            -----------------------------------MRQGQ--------------------
A7RQ92_NEMVE|Nematostella         ------------------------------------------------------------
                                                                                              

G6DDQ2_DANPL|Danaus               -------------------------------------------------DGTEPLIYVTL
E2AIW9_CAMFO|Camponotus           -------------------------------------------------LKQLPFPPPSV
K7J230_NASVI|Nasonia              -------------------------------------------------TRPLPFQPPSV
B4GZ57_DROPE|Drosophila           -------------------------------------------------LVHLASVQFTV
Q29B32_DROPS|Drosophila           -------------------------------------------------LVHLASVQFTV
B4NJE7_DROWI|Drosophila           -------------------------------------------------LTHLASVQFTL
B4JTP9_DROGR|Drosophila           -------------------------------------------------LAHLASVQFTV
B4K872_DROMO|Drosophila           -------------------------------------------------QAHLASVQFTV
B4LY95_DROVI|Drosophila           -------------------------------------------------MAYLASVQFTI
B3M2Q2_DROAN|Drosophila           -------------------------------------------------LAHLASVQFTL
Q9VG80_DROME|Drosophila           -------------------------------------------------LAHLASVQFTL
B3P1B3_DROER|Drosophila           -------------------------------------------------LTHLASVQFTL
B4PNT1_DROYA|Drosophila           -------------------------------------------------LAHLASVQFTL
B0X823_CULQU|Culex                -------------------------------------------------QYSKATVHLGL
Q7PNJ3_ANOGA|Anopheles            -------------------------------------------------QLSKVNVKLTV
C3ZWI2_BRAFL|Branchiostoma        TCCGHLNHTRFILFLLSAPLGCLHATVVYGCTMYRYLYLGSSYYYVVDDNDLEPLIDVDL
Q4T1U0_TETNG|Tetraodon            ------------------------------------------------------------
E7F6D7_DANRE|Danio                -------------------------------------------------HIHHPIMPFSI
H2U6U0_TAKRU|Takifugu             -------------------------------------------------RQFQPLIPFSV
H2LWT2_ORYLA|Oryzias              -------------------------------------------------RQFQPLMPFSV
G3NBP8_GASAC|Gasterosteus         -------------------------------------------------RQFQPLMPFSV
I3KH45_ORENI|Oreochromis          -------------------------------------------------RQFQPLMPFSV
F7B8P9_XENTR|Xenopus              -------------------------------------------------RDPAPIVPFGI
H3AT93_LATCH|Latimeria            -------------------------------------------------RDPRPIIPFGI
F7F8E7_ORNAN|Ornithorhynchus      -------------------------------------------------RDPLPVVPFGL
F6ST88_MONDO|Monodelphis          -------------------------------------------------RDPLPIIPFGL
G3X1U7_SARHA|Sarcophilus          -------------------------------------------------RDPLPIIPFGL
F7BDK1_HORSE|Equus                -------------------------------------------------RDPLPVIPFGL
L5K3B1_PTEAL|Pteropus             -------------------------------------------------RDPLPIIPFGL
ZDHC6_MOUSE|Mus                   -------------------------------------------------RDPPPIVPFGL
Q32PY5_RAT|Rattus                 -------------------------------------------------RDPPPIVPFGL
G5BKD2_HETGA|Heterocephalus       -------------------------------------------------RDPLPVVPFGL
H0V760_CAVPO|Cavia                -------------------------------------------------RKPLPMVPFGL
H0XNL2_OTOGA|Otolemur             -------------------------------------------------RDPVPIIPFGL
G3T188_LOXAF|Loxodonta            -------------------------------------------------RDPLPLVPFGL
I3MLS9_SPETR|Spermophilus         -------------------------------------------------RDPLPIVPFGL
G1SK13_RABIT|Oryctolagus          -------------------------------------------------RDPLPIVPFGL
G1NWP6_MYOLU|Myotis               -------------------------------------------------RDPLPIIPFGL
ZDHC6_BOVIN|Bos                   -------------------------------------------------RDPLPIIPFGL
D2GX33_AILME|Ailuropoda           -------------------------------------------------RDPLPIIPFGL
F6XXY3_CANFA|Canis                -------------------------------------------------RDPLPIIPFGL
G9KYU0_MUSPF|Mustela              -------------------------------------------------RDPLPIIPFGL
F1S5J7_PIG|Sus                    -------------------------------------------------RDPLPIIPFGL
F7IKK1_CALJA|Callithrix           -------------------------------------------------RDPLPIVPFGL
G7PDZ3_MACFA|Macaca               -------------------------------------------------RDPLPIVPFGL
H9ETH9_MACMU|Macaca               -------------------------------------------------RDPLPIVPFGL
G3SHQ9_GORGO|Gorilla              -------------------------------------------------RDPLPIVPFGL
ZDHC6_HUMAN|Homo                  -------------------------------------------------RDPLPIVPFGL
H2Q2K7_PANTR|Pan                  -------------------------------------------------RDPLPIVPFGL
ZDHC6_PONAB|Pongo                 -------------------------------------------------RDPLPIVPFGL
G1S129_NOMLE|Nomascus             -------------------------------------------------RDPLPIVPFGL
H9GF83_ANOCA|Anolis               -------------------------------------------------RDPRPIIPFGL
K7FG36_PELSI|Pelodiscus           -------------------------------------------------RDPLPIIPFGL
H0ZKK9_TAEGU|Taeniopygia          -------------------------------------------------RDPRPIIPFGL
F1NN38_CHICK|Gallus               -------------------------------------------------RDPRTIIPFGL
G1NEM3_MELGA|Meleagris            -------------------------------------------------RDPRTIIPFGL
G3MGC2_9ACAR|Amblyomma            -------------------------------------------------EDNLVYLG--F
A7RQ92_NEMVE|Nematostella         ----------------------------------------------------LRLLPFDV
                                                                                              

G6DDQ2_DANPL|Danaus               TTLLLSLLATGMAVGVVLAVGALLYLQMRSILRNRTTIEDWIVDKAACRRDE--RGLPQF
E2AIW9_CAMFO|Camponotus           CTLILVVFSIGLSIGVVLAVGMLLYFQMSAIVRNRTEIEDWILEKARYRRDD---TDVEY
K7J230_NASVI|Nasonia              FIVVSVLFSIGLSIGVVIAVGMLLYFQIHAIIKNQTGIECWILEKANYRRST---TAEQF
B4GZ57_DROPE|Drosophila           YSIIMCITGMGLAIGVVIGLGMLLFIQLKTIVANQTGIEIWIVEKAIYRRYAIGESEDSF
Q29B32_DROPS|Drosophila           YSIIMCITGMGLAIGVVIGLGMLLFIQLKTIVANQTGIEIWIVEKAIYRRYAIGESEDSF
B4NJE7_DROWI|Drosophila           MSIIMCILGMGLAIGVVIGLSMLLYIQLKTIVTNQTGIEIWIVEKARYRLYRNGESEDEF
B4JTP9_DROGR|Drosophila           NSIIMCILGMGLAIGVVIGLSMLLYIQLKTIITNQTGIEIWIVEKALYRRYR-SATNEPF
B4K872_DROMO|Drosophila           ASIVMCILGMGLAIGVVIGLSMLLYIQLKTIVTNQTGIEIWIVEKAIYRRYK-SENYEPF
B4LY95_DROVI|Drosophila           GSIVMCILGMGLAIGVVIGLGMLLFIQLKTIIINQTGIELWIVEKAIYRRYK-ADSYEPF
B3M2Q2_DROAN|Drosophila           TSIIMCILGMGLSIGVVIGLSMLLYIQMKTIVTNQTGIEIWIVEKAIYRRYRNPDSDDDF
Q9VG80_DROME|Drosophila           LSIIMCILGMGLAIGVVIGLSMLLFIQLKTIVNNQTGIEIWIVEKAIYRRYRNADCDDEF
B3P1B3_DROER|Drosophila           LSIIMCILGMGLAIGVVIGLSMLLFIQLKTIVNNQTGIEIWIVEKAIYRRYRNADCDDEF
B4PNT1_DROYA|Drosophila           LSIIMCILGMGLAIGVVIGLSMLLFIQLKTIVNNQTGIEIWIVEKALYRRYRNADCDNEF
B0X823_CULQU|Culex                WSLILGVFNIGLAIGVIIAVGMLLFFQVRAIVNNRTGIEDWIVEKAKHRREG---TEETF
Q7PNJ3_ANOGA|Anopheles            SSLVLCVFNIGLAIGVVLTVGALLVYQVRSILNNRTAIEDWIVEKARFRAER---NEQTF
C3ZWI2_BRAFL|Branchiostoma        YFFAMLFFATGLSIGVTVAVGILFSIQMKIVLTNQTGIETWILDKAKDRPRL---EGDKF
Q4T1U0_TETNG|Tetraodon            --------------------AMLFFIQIKVIIFNKTSIESWIEEKAKDRIQH-YQTGEEF
E7F6D7_DANRE|Danio                AAFAATLFALGLALGTTIAVGMLFFIQMKVILRNRTSIEAWIEEKAKDRIQY-YQTGEDF
H2U6U0_TAKRU|Takifugu             PAFAATLFALGLALGTTIAVGMLFFIQMKVIIRNKTSIESWIEEKAKDRIQH-YQTGEEF
H2LWT2_ORYLA|Oryzias              PAFAATLFALGLALGTTIAVGMLFFIQMKVILRNKTSIESWIEEKAKDRIQH-YQTGEEF
G3NBP8_GASAC|Gasterosteus         PAFAASLFALGLALGTTIAVGMLFFIQMKVILRNKTSIESWIEEKAKDRIQH-YQTGEDF
I3KH45_ORENI|Oreochromis          PAFAATLFALGLALGTTIAVGMLFVIQMKVILRNKTSIESWIEEKAKDRIQH-YQTGEEF
F7B8P9_XENTR|Xenopus              SAFAVTLFALGLALGTTIAVGMLFFIQMKVILRNKTSIESWIEEKAKDRIQY-YQTDETF
H3AT93_LATCH|Latimeria            SPFAASLFALGLALGTTIAVGMLFFIQIKVILRNKTSVELWIEEKAKDRIQY-YQTGEVF
F7F8E7_ORNAN|Ornithorhynchus      SAFAASLFALGLALGTTVAVGMLFFIQMKVILRNKTSIESWIEEKAKDRIQY-YQTGEVF
F6ST88_MONDO|Monodelphis          SAFAASLFALGLAVGTTIAVGMLFFIQMKVILRNKTSIESWIEEKAKDRIQF-YQTAEIF
G3X1U7_SARHA|Sarcophilus          SAFAASLFALGLAVGTTIAVGMLFFIQMKVILRNKTSIESWIEEKAKDRIQY-YQTAESF
F7BDK1_HORSE|Equus                AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKVNFIITG-PELTSVP
L5K3B1_PTEAL|Pteropus             AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
ZDHC6_MOUSE|Mus                   AAFAATLFALGLALGTTIAVGMLFFIQIKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
Q32PY5_RAT|Rattus                 AAFAATLFALGLALGTTIAVGMLFFIQIKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
G5BKD2_HETGA|Heterocephalus       AAFAATLFALGLAVGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
H0V760_CAVPO|Cavia                AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
H0XNL2_OTOGA|Otolemur             AAFAATLFALGLALGTTIAVGMLFFIQMKIILGNKTSIESWIEEKAKDRIQY-HQLDKAF
G3T188_LOXAF|Loxodonta            AAFAATLFALGLAIGTTIAVGMLFFIQMKIVLRNKTSIESWIEEKAKDRIQY-YQLDEVF
I3MLS9_SPETR|Spermophilus         AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
G1SK13_RABIT|Oryctolagus          AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLEEVF
G1NWP6_MYOLU|Myotis               AAFAATLFALGLALGTTIAVGMLFFIQIKIILRNQTSIESWIEEKAKDRIQY-YQLDEVF
ZDHC6_BOVIN|Bos                   AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
D2GX33_AILME|Ailuropoda           AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
F6XXY3_CANFA|Canis                AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
G9KYU0_MUSPF|Mustela              AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
F1S5J7_PIG|Sus                    AAFAATLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
F7IKK1_CALJA|Callithrix           AAFAATLFALGLALGTTIAVGMLFVIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
G7PDZ3_MACFA|Macaca               AAFATTLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
H9ETH9_MACMU|Macaca               AAFATTLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
G3SHQ9_GORGO|Gorilla              AAFATTLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
ZDHC6_HUMAN|Homo                  AAFATTLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
H2Q2K7_PANTR|Pan                  AAFATTLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
ZDHC6_PONAB|Pongo                 AAFATTLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
G1S129_NOMLE|Nomascus             AAFATTLFALGLALGTTIAVGMLFFIQMKIILRNKTSIESWIEEKAKDRIQY-YQLDEVF
H9GF83_ANOCA|Anolis               SAFAASLFALGLALGTTIAVGMLFFIQMKVILRNKTSIESWIEEKAKDRINY-YQTKETF
K7FG36_PELSI|Pelodiscus           SAFAASLFALGLALGTTIAVGMLFIIQMKVILRNKTSIESWIEDKAKDRIQY-YQRGEIF
H0ZKK9_TAEGU|Taeniopygia          SAFAASLFALGLALGTTIAVGMLFIIQMKVILTNKTSIESWIEEKAKDRIQY-YQTGETF
F1NN38_CHICK|Gallus               SAFAASLFALGLALGTTIAVGMLFIIQMKVILTNKTSIESWIEEKAKDRIQY-YQTDETF
G1NEM3_MELGA|Meleagris            SAFAASLFALGLALGTTIAVGMLFIIQMKVILTNKTSIESWIEEKAKDRIQY-YQTDETF
G3MGC2_9ACAR|Amblyomma            LPFLATVLSLGLAIGVIIAVGSLFFIQLKIIVRNETTIENWIVAKAQMRER---ENEEDF
A7RQ92_NEMVE|Nematostella         YHLIFVTFCIGLSIGVTVAVGLLLYYQVKGIRINETAIESWIVEKAN-RPR---PKGEVF
                                                      . *:  *:  :  * * :* **  *.              

G6DDQ2_DANPL|Danaus               QFPYDLG--WRRNLRLV--WSGHQY-DGIHWPVREGHGQYDLTMEQKAQKADKAVRSRVY
E2AIW9_CAMFO|Camponotus           VHPYSKG--WRFNISQVFTLDCTPVGDGITWPVIDGCDQYTLTREQLAQKLDKRKRARKY
K7J230_NASVI|Nasonia              VHPYSKN--WLFNIRQVLSWHCSAPGDGINWPVVEGCDQYTLTREQLAQKQEKRKRAKRY
B4GZ57_DROPE|Drosophila           IYPYDLG-WWLN-LKQVFNDECQKLGDGIDWPVLKGCDQYTLTREQLAQKEEKRARTRTY
Q29B32_DROPS|Drosophila           VYPYDLG-WWLN-LKQVFNDECQKLGDGIDWPVLKGCDQYTLTREQLAQKEEKRARTRTY
B4NJE7_DROWI|Drosophila           VYPYDLG--WKLNMRQVFDEDCRSRGDGIEWAVAKGCDQFTLTREQLAQKEEKRARTRTY
B4JTP9_DROGR|Drosophila           IYPYDLG--WRLNLRQVFNEECQKRGDGIEWPVVDGCDQYTLTREQLAQKDEKRARTRVY
B4K872_DROMO|Drosophila           VYPYDLG--WRLNLRQVFNEECQKRGDGIEWPVVQGCDQYTLTREQLAQKEEKRARTRVY
B4LY95_DROVI|Drosophila           VYPYDLG--WRLNLRQVFNDECQKRGDGIEWPVVKGCDQYTLTREQLAQKQEKRARTRVY
B3M2Q2_DROAN|Drosophila           LYPYNLG--WRDNLRQVFNDECQKRGEGIEWPVAEGCDQYTLTREQLAQKEEKRARTRTY
Q9VG80_DROME|Drosophila           LYPYDLG--WRANLRLVFNDECQKRGDGIEWPVVEGCDQYTLTREQLAQKEEKRARTRTF
B3P1B3_DROER|Drosophila           LYPYDLG--WRSNLRLVFNDECQKRGDGIEWPVAEGCDQYTLTREQLAQKEEKRARTRTF
B4PNT1_DROYA|Drosophila           LYPYDLG--WRANLRLVFNDECQKRGDGIEWPVAEGCDQYTLTREQLAQKEEKRARTRTF
B0X823_CULQU|Culex                RYPYDLG-KWKN-IMQVASLTCSPIGNGVEWAIAEGCDQFTLTREQLKQKSEKRARTRTY
Q7PNJ3_ANOGA|Anopheles            VYPYDLG-RWSN-VKQVINFTCRPVGNGYEWPVVEGCDQYTLTREQLAQKEEKRARTRTY
C3ZWI2_BRAFL|Branchiostoma        VYPYHLG--WRRNFWEVFAWQGYPRGDGITWPVMEGCNQYTLTVE--------------F
Q4T1U0_TETNG|Tetraodon            IFPYDLGSCWLN-FKQVFTWTGMPKGDGLEWPVHPKCHQHTLTIEQLKQKADKRVRSVQY
E7F6D7_DANRE|Danio                IFPYDLGSRWEN-FKQVFTWSGAPMGDGIEWPVHEKCDQYTLTIEQLKQKHDKRQRSVEY
H2U6U0_TAKRU|Takifugu             IFPYDLGSCWLN-FKQVFTWTGTPKGDGLEWPVHPKCHQHTLTIEQLKQKADKRVRSVQY
H2LWT2_ORYLA|Oryzias              VFPYDLGSRWLN-FKHVFTLSGTPRGNGLEWPVHSKCHQYTLTIEQLKQKADKRVRSVQY
G3NBP8_GASAC|Gasterosteus         TFPYDLGTRWLN-FKQVFTWSGTPKGDGIEWPVHPKCHQHTLTIEQLKQKADKRVRSVQY
I3KH45_ORENI|Oreochromis          IFPYDLGSRWLN-FKQVFTWSGTPRGDGIVWPVHPKCHQHTLTIEQLKQKADKRVRSVQY
F7B8P9_XENTR|Xenopus              IFPYDLGSRWKN-FRQVFTWAGSPEGDGMEWAVREGCHPFALTVEQLKQKADKRVRSVRY
H3AT93_LATCH|Latimeria            VFPYDLGSRWEN-FKQVFTWSGVPEGDGLEWPIKEGSHQYTLTIEQLKQKADKRVRSVQY
F7F8E7_ORNAN|Ornithorhynchus      IFPYDMGSRWKN-FKQVFTWSGVPEGDGLEWPIKEGCHQYSLTIEQLKQKADKRVRSVRY
F6ST88_MONDO|Monodelphis          VFPYDMGSRWQN-FKQVFTWSGVPEGDGLEWPIREGCHPYSLTIEQLKQKADKRVRSVRY
G3X1U7_SARHA|Sarcophilus          VFPYDMGSRWQN-FKQVFTWSGIPEGDGLEWPIREGCHPYSLTIEQLKQKADKRVRSVRY
F7BDK1_HORSE|Equus                IFLYFISFQITNKQKPLWAKPNTPTG---SWPDEQ-CHKSSFPIEQLKQKADKRVRSVRY
L5K3B1_PTEAL|Pteropus             VFPYDMGSRWKN-FKQVFTWSGVPEGDGLEWPIREGCHQYSLTV--------------RY
ZDHC6_MOUSE|Mus                   IFPYDMGSKWKN-FKQVFTWSGVPEGDGLEWPIREGCDQYSLTIEQLKQKADKRVRSVRY
Q32PY5_RAT|Rattus                 VFPYDMGSKWKN-LKQVFTWSGVPEGDGLEWPIREGCHQYSLTIEQLKQKADKRVRSVRY
G5BKD2_HETGA|Heterocephalus       VFPYDMESRWKN-FRQVFTWSGVPAGDGLEWPVKEGCQQYSLTIEQLKQKADKRVRSVRY
H0V760_CAVPO|Cavia                VFPYDMGSRWEN-FKQVFTWSGVPEGDGLEWPIREGCHQYSLTIEQLKQKADKRVRSVRY
H0XNL2_OTOGA|Otolemur             VFPYDMGSRWKN-FKQVFTWSGVPEGDGLEWPIKEGCHPYSLTIEQLKQKADKRDRSVRY
G3T188_LOXAF|Loxodonta            VFPYDLGSRWKN-FKQVFTWSGVPEGDGLEWPIREGCHQYTLTIEQLKQKADKRVRSVRY
I3MLS9_SPETR|Spermophilus         VFPYDMGSKWKN-FTQVFTWSGVPEGDGLEWPVREDCHPYSLTIEQLKQKADKRVRSVRY
G1SK13_RABIT|Oryctolagus          VFPYDLGDRWKN-FKQVFTWSGAPDGDGLEWPIREGCHQYSLTIEQLKQKADKRVRSVRY
G1NWP6_MYOLU|Myotis               VFPYDMGSRWKN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
ZDHC6_BOVIN|Bos                   VFPYDMGSRWKN-FKQVFTWSGVPEGDGLDWPIREGCHQYSLTIEQLKQKADKRVRSVRY
D2GX33_AILME|Ailuropoda           VFPYDMGSRWKN-FKQVFTWSGVPKGDGLAWPIREGCHQYSLTIEQLKQKADKRIRSVRY
F6XXY3_CANFA|Canis                VFPYDMGSRWKN-FKQVFTWSGVPEGDGLAWPVREDCHQYSLTIEQLKQKADKRIRSVRY
G9KYU0_MUSPF|Mustela              VFPYDMGSRWKN-FKQVFTWSGVPEGDGLAWPVRKDCHPYSLTIEQLKQKADKRVRSVRY
F1S5J7_PIG|Sus                    VFPYDMGSRWKN-FKQVFTWSGVPEGDGLEWPIREGCHQYSLTIEQLKQKADKRVRSVRY
F7IKK1_CALJA|Callithrix           VFPYDMGSRWRN-FKQVFTWSGIPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
G7PDZ3_MACFA|Macaca               VFPYDMGSRWRN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
H9ETH9_MACMU|Macaca               VFPYDMGSRWRN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
G3SHQ9_GORGO|Gorilla              VFPYDMGSRWRN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
ZDHC6_HUMAN|Homo                  VFPYDMGSRWRN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
H2Q2K7_PANTR|Pan                  VFPYDMGSRWRN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
ZDHC6_PONAB|Pongo                 VFPYDMGSRWRN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
G1S129_NOMLE|Nomascus             VFPYDMGSRWRN-FKQVFTWSGVPEGDGLEWPVREGCHQYSLTIEQLKQKADKRVRSVRY
H9GF83_ANOCA|Anolis               IFPYDLGSKWNN-FKQVFTWSGISEGDGFEWPVKEGCHQYSLTIEQLKQKADKRVRSVRY
K7FG36_PELSI|Pelodiscus           VFPYDLGSKWKN-FKQVFTWSGIPEGDGLDWPVKEGCHQYTLTIEQLKQKTDKRMRSVHY
H0ZKK9_TAEGU|Taeniopygia          IFPYDMGSKWKN-FRQVFTWSGIPEGDGLDWPVRDGCHQYSLTIEQLKQKADKRVRSVRY
F1NN38_CHICK|Gallus               IFPYDMGSKWKN-FKQVFTWSGIPEGDGLDWPVREGCHRYSLTIEQLKQKADKRVRSVRY
G1NEM3_MELGA|Meleagris            IFPYDMGSKWKN-FKQVFTWSGIPEGDGLDWPVREGCHRYSLTIEQLKQKADKRVRSVRY
G3MGC2_9ACAR|Amblyomma            IYPYNLGVA-EN-LKQVFF---TPLGDGITWPVVPGCNQYTLTVEQILQKHDKRLRTRLY
A7RQ92_NEMVE|Nematostella         VYPYNFG--WKENFRQVLCWSHDYLGDGITWPVLPGCDQYTLTVEQLWQKELKRNRTVTH
                                   . *            :             *.         :.                .

G6DDQ2_DANPL|Danaus               AAASTYSGRWVPL-LQYPRAALGPPCSDEPRLSLRVGDRVKVTRHR-RHWLFGEKVLS--
E2AIW9_CAMFO|Camponotus           RVVKTASGSRFPI-RHGCGVFCHPPCTDEPRIKLDIDDIVIATRWK-KYWLFGEKEQK--
K7J230_NASVI|Nasonia              RVIARATGSWVPI-GHGLKVLCSPPITDEARIKLEIGDTVIVTRWR-NNWLFGEKESL--
B4GZ57_DROPE|Drosophila           KCHSPVTGRWLPVCSQGWSVCMGAPCTDEPRIRLQPGDIIKVTRFR-KHWLFGERELT--
Q29B32_DROPS|Drosophila           KCHSPVTGRWLPVCSQGWSVCMGAPCTDEPRIRLQPGDIIKVTRFR-KHWLFGERELT--
B4NJE7_DROWI|Drosophila           KCIGNVTGRWLPIWSQGWRVCVAAPCTDEPRIRLQPDDIIKVTRFR-KHWLFGERVPT--
B4JTP9_DROGR|Drosophila           KCISNVTGRWLPIFSQGWRVCVSAPCTDEPRIRLQPDDIIRVTRFR-RHWLFGERVPS--
B4K872_DROMO|Drosophila           KCISPVTGRWLPIFSQGWRVCVNAPCTDEPRIRLRPDDIIKVTRFR-RHWLFGERVLS--
B4LY95_DROVI|Drosophila           KCISPVSGRWMPICSQGWRICINAPCTDEPRIRLQPDDIIKVTRFR-RHWLFGERVPS--
B3M2Q2_DROAN|Drosophila           KCIRPVTGRWLPLFSQGWRVCVGAPCSDEPRIHLRPDDIIRVTRFR-SHWLFGERVPS--
Q9VG80_DROME|Drosophila           KCTRPVTGRWLPIFSQGWRVCVAAPCSDEPRISLRPNDMIKVTRFR-NHWLFGERVLS--
B3P1B3_DROER|Drosophila           RCIRPVTGRWLPIFSQGWRVCVAAPCSDEPRISLRPNDLIKVTRFR-NHWLFGERVLS--
B4PNT1_DROYA|Drosophila           RCIGPVTGRWLPIFSQGWRVCVAAPCSDEPRISLRTNDMIKVTRFR-THWLFGERVLS--
B0X823_CULQU|Culex                SINRSVSGSWVPLWSQGCRVCLSPPLTDEPRIKLDVGDVVRVTRWR-KHWLFGEKVLEET
Q7PNJ3_ANOGA|Anopheles            TIVRPATGSWFPLFSQGPSVCLSPPLTDEPRIKLEVDDIVRVTRWR-KHWLFGEKLQE--
C3ZWI2_BRAFL|Branchiostoma        AIVDNYSGSWFPI-TKGIRVCCCIPCTEEPRIKVKRGDVVMVTRAY-RKWLYGEKV----
Q4T1U0_TETNG|Tetraodon            QAVEDYNGACCPL-SKGLQTFCRTPCTEEPRIPLSKGDIILATRGT-KWWMYGDKVLS--
E7F6D7_DANRE|Danio                RVVEEYNGACCPL-GKGLNTFFRTPCTEEPRIKLTKGETIFATRGT-KWWMYGDKVLN--
H2U6U0_TAKRU|Takifugu             QAVEDYNGACCPL-SKGLQTFFRTPCTEEPRIPLSKGETILATRGT-KWWMYGDKMLS--
H2LWT2_ORYLA|Oryzias              QAVEDYNGACCPL-NKGFRTFFRTPCTEEPRIPLSKGETILATRGT-KWWMYGDKIVS--
G3NBP8_GASAC|Gasterosteus         RAVEDYNGACCPL-SKGFQTFFRTPCTEEPRIPLNKGDTILATRGT-KWWMYGDKVLK--
I3KH45_ORENI|Oreochromis          RAVEDYNGACCPL-SKGLQTFFRTPCTEEPRIPLCKGDTILATRGT-KWWMYGDKVLS--
F7B8P9_XENTR|Xenopus              RAVEEYSGACCPL-TKGIRTLFSTPCTEEPRMKLHKGDLVLATRGL-KHWLYGDKLFE--
H3AT93_LATCH|Latimeria            RAIEDYSGACCPV-TKGIKLLFTTPCTEEPRIKLRKGDLILATRGL-KHWLYGDKILD--
F7F8E7_ORNAN|Ornithorhynchus      RAMEDYSGACCPL-NKGIKTFFTTPCTEEPRIELHKGDLILVTRGL-KHWMYGDKILN--
F6ST88_MONDO|Monodelphis          KVIDAYSGACCPL-NKGIKTFFTTPCTEEPRISLKKGELILVTRGL-RHWMYGDKILD--
G3X1U7_SARHA|Sarcophilus          KVIDDYSGACCPF-NKGIKTFFTTPCTEEPRISLKKGELILVTRGL-RHWMYGDKILD--
F7BDK1_HORSE|Equus                KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLRKGEFILATRGL-RYWLYGDKILD--
L5K3B1_PTEAL|Pteropus             KVIENYSGACCPL-NKGIKTFLTSPCTEEPRIRLQTGEFILATRGL-RYWLYGDKILD--
ZDHC6_MOUSE|Mus                   KVIEDYNGACCPL-NRGVRTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKILD--
Q32PY5_RAT|Rattus                 KVVEDYNGACCPL-NRGVRTFFTSPCTEEPRIQLQKGELVLATRGL-RYWLYGDKILD--
G5BKD2_HETGA|Heterocephalus       KAIEDYNGACCPL-NRGIKTFFTSPCTEEPRIQIRKGEFILATRGL-RYWLYGDKILD--
H0V760_CAVPO|Cavia                KVIEDYSGACCPL-NRGVKTFFTSPCTEEPRIQLRRGEFVLATRGL-RYWLYGDKILD--
H0XNL2_OTOGA|Otolemur             KVIEDYNGACCPL-NKGIKTFFTSPCTEEPRIQLQKGEFILATRGL-RYWLYGDKILD--
G3T188_LOXAF|Loxodonta            KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKLLD--
I3MLS9_SPETR|Spermophilus         KVTEDYSGSCCPL-NKGIKTIFTIPCTEEPRIQLRKGEFILATRGL-RYWLYGDKILD--
G1SK13_RABIT|Oryctolagus          KVIDDYSGACCPL-NKGIKTFFTSPCTEEPRIQLQKGEFILATRGL-RYWLYGDKILD--
G1NWP6_MYOLU|Myotis               KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIPLQKGEFILATRGL-RYWLYGDKILD--
ZDHC6_BOVIN|Bos                   KVIEDYSGTCCPL-NRGIKTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKILD--
D2GX33_AILME|Ailuropoda           RVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKILD--
F6XXY3_CANFA|Canis                RVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKILD--
G9KYU0_MUSPF|Mustela              RVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKILD--
F1S5J7_PIG|Sus                    KVIEDYSGSCCPL-NKGIKTFFTSPCTEEPRIRLQKGEFVLATRGL-RYWLYGDKILD--
F7IKK1_CALJA|Callithrix           KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLQKGEFVLATRGLRRYWLYGDKILD--
G7PDZ3_MACFA|Macaca               KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKILD--
H9ETH9_MACMU|Macaca               KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIRLQKGEFILATRGL-RYWLYGDKILD--
G3SHQ9_GORGO|Gorilla              KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIQLQKGEFILATRGL-RYWLYGDKILD--
ZDHC6_HUMAN|Homo                  KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIQLQKGEFILATRGL-RYWLYGDKILD--
H2Q2K7_PANTR|Pan                  KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIQLQKGEFILATRGL-RYWLYGDKILD--
ZDHC6_PONAB|Pongo                 KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIQLQKGEFILATRGL-RYWLYGDKILD--
G1S129_NOMLE|Nomascus             KVIEDYSGACCPL-NKGIKTFFTSPCTEEPRIQLQKGEFILATRGL-RYWLYGDKIID--
H9GF83_ANOCA|Anolis               QAIEDYNGACCPL-TKGLRTFFTTPCTEEPRIILCKGDQILATRGL-KQWMYGEKITD--
K7FG36_PELSI|Pelodiscus           RAVEDYGGACCPV-TKGVKTFFTTPCTEEPRIALRKGDLIFATRGL-KHWMYGDKVLD--
H0ZKK9_TAEGU|Taeniopygia          RAIEDYSGVCCPV-TKGVKTFFTTPCTEEPRIALSKGDLILATRGL-KHWMYGEKILI--
F1NN38_CHICK|Gallus               RAIEDYSGVCCPV-TKGVKTFFTTPCTEEPRIALSKGDLILATRGL-KHWMYGEKILN--
G1NEM3_MELGA|Meleagris            RAIEDYSGVCCPV-TKGVKTFFTTPCTEEPRIALSKGDLILATRGL-KHWMYGEKILN--
G3MGC2_9ACAR|Amblyomma            TVVQPYRGSFFPI-SHGCTVCMTTPLTDEPXXXVSPGDRVLVTRWK-KHWLYGELESA--
A7RQ92_NEMVE|Nematostella         DVVKSYNGAILAW-REGLWTCCSTPWTDESRMKIIPGDVVMVTRWR-KHWLYGEKVTN--
                                         *   .            * ::*.   :  .: : .**     *::*:      

G6DDQ2_DANPL|Danaus               ---------------------------------------EQEAVGGL--R-----GDRGW
E2AIW9_CAMFO|Camponotus           --------------------------------------KGDNNVGSK--R------IRGW
K7J230_NASVI|Nasonia              ---------------------------------------TVITDGKD--NR-----IRGW
B4GZ57_DROPE|Drosophila           ---------------------------------------KQELGADK--THRRKGHIRGW
Q29B32_DROPS|Drosophila           ---------------------------------------KQELGADK--THQRKGHIRGW
B4NJE7_DROWI|Drosophila           ---------------------------------------EKELADGK--KRLRKGAIRGW
B4JTP9_DROGR|Drosophila           ---------------------------------------EREQKHRL--R---KGAMRGW
B4K872_DROMO|Drosophila           ---------------------------------------EQEHAAGSEKKSQRKGPIRGW
B4LY95_DROVI|Drosophila           ---------------------------------------ELEHTAVAQKRRQRKGPIRGW
B3M2Q2_DROAN|Drosophila           ---------------------------------------EQEIRGEK--KHQRKGHIRGW
Q9VG80_DROME|Drosophila           ---------------------------------------EQELAGVK--KRQRKGPIRGW
B3P1B3_DROER|Drosophila           ---------------------------------------EQELAGDK--KRQRKGPIRGW
B4PNT1_DROYA|Drosophila           ---------------------------------------EQELAGDK--KRQRKGPIRGW
B0X823_CULQU|Culex                EEPERNGTVQKAQKKHKQHKKKSDQPEVDEPEKEKEEEAPSSKTPHR--R------IRGW
Q7PNJ3_ANOGA|Anopheles            ---------------------------------------PTKKTIPK--R------VRGW
C3ZWI2_BRAFL|Branchiostoma        ----------------------------------------TRIKDGP--P------EKGW
Q4T1U0_TETNG|Tetraodon            ---------------------------------------KQQVAVGE--R------VRGW
E7F6D7_DANRE|Danio                ---------------------------------------EEQAKAGV--R------IRGW
H2U6U0_TAKRU|Takifugu             ---------------------------------------EQQVAVGE--R------VRGW
H2LWT2_ORYLA|Oryzias              ---------------------------------------EEEMRAGV--R------VRGW
G3NBP8_GASAC|Gasterosteus         ---------------------------------------EEHNSGRE--R------VRGW
I3KH45_ORENI|Oreochromis          ---------------------------------------EEEVRAGE--R------VRGW
F7B8P9_XENTR|Xenopus              ---------------------------------------GELPDDVI--R------VRGW
H3AT93_LATCH|Latimeria            ---------------------------------------EEQMRAGV--R------IRGW
F7F8E7_ORNAN|Ornithorhynchus      -----------------------------------------SAAEGT--R------VRGW
F6ST88_MONDO|Monodelphis          ---------------------------------------YLATEDGS--R------IRGW
G3X1U7_SARHA|Sarcophilus          ---------------------------------------HLTTEDGS--R------IRGW
F7BDK1_HORSE|Equus                ---------------------------------------DSFIEGVS--R------IRGW
L5K3B1_PTEAL|Pteropus             ---------------------------------------DSFTEATA--E------LCSA
ZDHC6_MOUSE|Mus                   ---------------------------------------DSFIEGTS--R------VRGW
Q32PY5_RAT|Rattus                 ---------------------------------------DSFIEGTS--R------IRGW
G5BKD2_HETGA|Heterocephalus       ---------------------------------------DSFVEGLS--R------IRGW
H0V760_CAVPO|Cavia                ---------------------------------------DSFMEGVS--R------IRGW
H0XNL2_OTOGA|Otolemur             ---------------------------------------DYFREGVS--R------IRGW
G3T188_LOXAF|Loxodonta            ---------------------------------------DSFIEGVS--R------MRGW
I3MLS9_SPETR|Spermophilus         ---------------------------------------DSFAEGVS--R------IRGW
G1SK13_RABIT|Oryctolagus          ---------------------------------------DSIVEGVS--R------IRGW
G1NWP6_MYOLU|Myotis               ---------------------------------------DSFIEGVS--R------IRGW
ZDHC6_BOVIN|Bos                   ---------------------------------------DSVLEGVS--R------IRGW
D2GX33_AILME|Ailuropoda           ---------------------------------------DAFVEGVS--R------IRGW
F6XXY3_CANFA|Canis                ---------------------------------------DASVEGVS--R------IRGW
G9KYU0_MUSPF|Mustela              ---------------------------------------DASVEGVS--R------IRGW
F1S5J7_PIG|Sus                    ---------------------------------------DSIIEGVS--R------VRGW
F7IKK1_CALJA|Callithrix           ---------------------------------------DSFIEGVS--R------IRGW
G7PDZ3_MACFA|Macaca               ---------------------------------------DSFIEGVS--R------IRGW
H9ETH9_MACMU|Macaca               ---------------------------------------DSFIEGVS--R------IRGW
G3SHQ9_GORGO|Gorilla              ---------------------------------------DSFIEGVS--R------IRGW
ZDHC6_HUMAN|Homo                  ---------------------------------------DSFIEGVS--R------IRGW
H2Q2K7_PANTR|Pan                  ---------------------------------------DSFIEGVS--R------IRGW
ZDHC6_PONAB|Pongo                 ---------------------------------------DSFIEGVS--R------IRGW
G1S129_NOMLE|Nomascus             ---------------------------------------DSFIEGVS--R------IRGW
H9GF83_ANOCA|Anolis               ----------------------------------------LATDDGK--R------VRGW
K7FG36_PELSI|Pelodiscus           ----------------------------------------SDVD-GM--R------VRGW
H0ZKK9_TAEGU|Taeniopygia          ----------------------------------------SAADGGI--R------ERGW
F1NN38_CHICK|Gallus               ----------------------------------------SAGDGGI--R------ERGW
G1NEM3_MELGA|Meleagris            ----------------------------------------SAGDGGI--R------ERGW
G3MGC2_9ACAR|Amblyomma            ---------------------------------------KFSTKASC--R------LKGW
A7RQ92_NEMVE|Nematostella         -------------------------------------------------H------LNG-
                                                                                            . 

G6DDQ2_DANPL|Danaus               F----PRSAATGLD-----------THTYTH-------------------TNTH------
E2AIW9_CAMFO|Camponotus           L----PRPCVIEVIENDL-------YDSNNL-------------------FKEN------
K7J230_NASVI|Nasonia              F----PRPCAIPVN-----------SEKDKDLDNYFENDLDVQYLIPNVSPTSKSMQTEL
B4GZ57_DROPE|Drosophila           F----PRRSAVEVIEVHECG-----GEPGSD-------------------NLPENGTCNG
Q29B32_DROPS|Drosophila           F----PRRSAVEVIEVHECG-----GEPGSD-------------------NLPENGTCNG
B4NJE7_DROWI|Drosophila           F----PRRSVIEINEVIQDC-----LDSSGE-------------------LSPSQ----N
B4JTP9_DROGR|Drosophila           F----PRRSAVPLTEVPD-------SESSDD-------------------VKNSKSSTNN
B4K872_DROMO|Drosophila           F----PRRSVVALTEVPD-------SESSDD-------------------IKPVKSTTSN
B4LY95_DROVI|Drosophila           F----PRRSVVAITEMPD-------SDSSDD-------------------VKTIKTSTSN
B3M2Q2_DROAN|Drosophila           F----PRQAAVELIEPEQDSS----GDGSHD-------------------ENPPAQNING
Q9VG80_DROME|Drosophila           F----PRRSAVEVIEAVHEGS----GDGNSE-------------------TPAPAAQNGN
B3P1B3_DROER|Drosophila           F----PRRSAVEVIEAVQEGSG---GDGNSE-------------------TPTPLAQNGN
B4PNT1_DROYA|Drosophila           F----PRRSAVEVIEAVQEGSG---GDGNSE-------------------TPAPLAQNGN
B0X823_CULQU|Culex                F----PRQCAVELVE----------DDDDTE-------------------QQKHFSE---
Q7PNJ3_ANOGA|Anopheles            F----PRKCAVEYI-----------ELDDDD-------------------AVVS------
C3ZWI2_BRAFL|Branchiostoma        F----PRPCAEKII----NELH---YPLQNQ-------------------AADF------
Q4T1U0_TETNG|Tetraodon            F----PRRCVEKCH-----------YDSAAN-------------------ENTS------
E7F6D7_DANRE|Danio                F----PRRCVEKCL-----------YDSANN-------------------STSE------
H2U6U0_TAKRU|Takifugu             F----PRRCVEKCH-----------YDSAAS-------------------ENTS------
H2LWT2_ORYLA|Oryzias              F----PRRCVEKCH-----------YDTAAN-------------------ESTS------
G3NBP8_GASAC|Gasterosteus         F----PRRCVEKCH-----------YDTAAS-------------------DSTS------
I3KH45_ORENI|Oreochromis          F----PRRCVEKCH-----------YDTAAS-------------------DATS------
F7B8P9_XENTR|Xenopus              F----PRRCVVKCV-----------SDSGSD-------------------QSDD------
H3AT93_LATCH|Latimeria            F----PRRCVEKCL-----------YDTATE-------------------QPVD------
F7F8E7_ORNAN|Ornithorhynchus      F----PRKCVEKCL-----------YDVEAD-------------------QEIE------
F6ST88_MONDO|Monodelphis          F----PRKCVEKFH-----------CDAETD-------------------QASE------
G3X1U7_SARHA|Sarcophilus          F----PRKCVEKCH-----------YDAESD-------------------QISE------
F7BDK1_HORSE|Equus                F----PRNCVEKCP-----------CDTETD-------------------QAPE------
L5K3B1_PTEAL|Pteropus             FLDSESRKTIQELSQLQLEARKQHRSQDHLE-------------------YGKD------
ZDHC6_MOUSE|Mus                   F----PRNCVEKCP-----------CDGDSD-------------------PAPE------
Q32PY5_RAT|Rattus                 F----PRNCVEKCP-----------CDGESD-------------------PAPE------
G5BKD2_HETGA|Heterocephalus       F----PRNCVEKCP-----------CDTETD-------------------PTPE------
H0V760_CAVPO|Cavia                F----PRNCVEKCP-----------CDTETD-------------------STPE------
H0XNL2_OTOGA|Otolemur             F----PRNCVEKCP-----------CDAEAD-------------------QAPA------
G3T188_LOXAF|Loxodonta            F----PRNCVEKCP-----------CDAETN-------------------QAPE------
I3MLS9_SPETR|Spermophilus         F----PRKCVEKCP-----------CEAETD-------------------PAPE------
G1SK13_RABIT|Oryctolagus          F----PRNCVEKCP-----------CDAEAD-------------------PAPE------
G1NWP6_MYOLU|Myotis               F----PRNCVEKCP-----------CDAETE-------------------QALE------
ZDHC6_BOVIN|Bos                   F----PRNCVEKCP-----------CDAETD-------------------QAPE------
D2GX33_AILME|Ailuropoda           F----PRNCVEKCP-----------CDAETD-------------------QAPE------
F6XXY3_CANFA|Canis                F----PRNCVEKCP-----------CDAETD-------------------QAPE------
G9KYU0_MUSPF|Mustela              F----PRNCVEKCP-----------CDAETD-------------------QAPE------
F1S5J7_PIG|Sus                    F----PRNCVEKCP-----------CDTETE-------------------SAPE------
F7IKK1_CALJA|Callithrix           F----PRKCVEKCP-----------CDTETD-------------------QAPE------
G7PDZ3_MACFA|Macaca               F----PRKCVEKCP-----------CDAETD-------------------QAPE------
H9ETH9_MACMU|Macaca               F----PRKCVEKCP-----------CDAETD-------------------QAPE------
G3SHQ9_GORGO|Gorilla              F----PRKCVEKCP-----------CDAETD-------------------QAPE------
ZDHC6_HUMAN|Homo                  F----PRKCVEKCP-----------CDAETD-------------------QAPE------
H2Q2K7_PANTR|Pan                  F----PRKCVEKCP-----------CDAETD-------------------QAPE------
ZDHC6_PONAB|Pongo                 F----PRKCVEKCP-----------CDAETD-------------------QAPE------
G1S129_NOMLE|Nomascus             F----PRKCVEKCP-----------CDAETD-------------------QAPE------
H9GF83_ANOCA|Anolis               F----PRRCVEKCL-----------YDSETD-------------------QPLD------
K7FG36_PELSI|Pelodiscus           F----PRKCVEKCP-----------HDSEMD-------------------QPLD------
H0ZKK9_TAEGU|Taeniopygia          F----PRKCVEKYQ-----------YDSETD-------------------QPVD------
F1NN38_CHICK|Gallus               F----PRKCVEKCQ-----------YDSETD-------------------QPVD------
G1NEM3_MELGA|Meleagris            F----PRKCVEKCQ-----------YDSETD-------------------QPVD------
G3MGC2_9ACAR|Amblyomma            F----PRQCAVEVAGSKGSRS----CTEASS-------------------SYAD------
A7RQ92_NEMVE|Nematostella         ------------------------------------------------------------
                                                                                              

G6DDQ2_DANPL|Danaus               ----------TG--------KNKHKPD
E2AIW9_CAMFO|Camponotus           ---------------------------
K7J230_NASVI|Nasonia              NYDHSVQKVSVG-------NKKKNK--
B4GZ57_DROPE|Drosophila           GHAQLRQQQRNG-------HAKKYM--
Q29B32_DROPS|Drosophila           GHAQLRQQQRNG-------HAKKYM--
B4NJE7_DROWI|Drosophila           GHSQLKQQQRNG-------HSKKYM--
B4JTP9_DROGR|Drosophila           GHSHGK-QQRNG-------HSKKYM--
B4K872_DROMO|Drosophila           GHTHGKQQQRNG-------HTKKCM--
B4LY95_DROVI|Drosophila           GHSHGKQQQRNG-------LSKKYM--
B3M2Q2_DROAN|Drosophila           YHRHLKQQQRNG-------HAKKYM--
Q9VG80_DROME|Drosophila           AHSHLKQQQRNG-------HAKKYM--
B3P1B3_DROER|Drosophila           AHSHLKQQQRNG-------HAKKYM--
B4PNT1_DROYA|Drosophila           AHSHLKQQQRNG-------HAKKYM--
B0X823_CULQU|Culex                --------------------KKKNK--
Q7PNJ3_ANOGA|Anopheles            -----------GVPPIYELANKKDV--
C3ZWI2_BRAFL|Branchiostoma        -----------E-------HDKKED--
Q4T1U0_TETNG|Tetraodon            --------------------DKKVN--
E7F6D7_DANRE|Danio                --------------------EKKEQ--
H2U6U0_TAKRU|Takifugu             -----------E-------KKKLNR--
H2LWT2_ORYLA|Oryzias              -----------D--------KKTDR--
G3NBP8_GASAC|Gasterosteus         --------------------DKKAN--
I3KH45_ORENI|Oreochromis          --------------------DKKVN--
F7B8P9_XENTR|Xenopus              --------------------EKKTR--
H3AT93_LATCH|Latimeria            -----------D--------EKKDR--
F7F8E7_ORNAN|Ornithorhynchus      -----------G--------EKKNR--
F6ST88_MONDO|Monodelphis          -----------G--------EKKNR--
G3X1U7_SARHA|Sarcophilus          -----------G--------EKKNR--
F7BDK1_HORSE|Equus                -----------G--------EKKTR--
L5K3B1_PTEAL|Pteropus             -----------G--------KGERP--
ZDHC6_MOUSE|Mus                   -----------G--------EKKNR--
Q32PY5_RAT|Rattus                 -----------G--------EKKNR--
G5BKD2_HETGA|Heterocephalus       -----------G--------EKKNR--
H0V760_CAVPO|Cavia                -----------G--------KKKNR--
H0XNL2_OTOGA|Otolemur             -----------D--------EKKNR--
G3T188_LOXAF|Loxodonta            -----------G--------EKKNR--
I3MLS9_SPETR|Spermophilus         -----------G--------EKKNR--
G1SK13_RABIT|Oryctolagus          -----------G--------EKKNR--
G1NWP6_MYOLU|Myotis               -----------G--------EKKNR--
ZDHC6_BOVIN|Bos                   -----------G--------EKKNR--
D2GX33_AILME|Ailuropoda           -----------G--------EKKNR--
F6XXY3_CANFA|Canis                -----------G--------EKKNR--
G9KYU0_MUSPF|Mustela              -----------G--------EKKN---
F1S5J7_PIG|Sus                    -----------G--------EKKNR--
F7IKK1_CALJA|Callithrix           -----------G--------EKKNR--
G7PDZ3_MACFA|Macaca               -----------G--------EKKNR--
H9ETH9_MACMU|Macaca               -----------G--------EKKNR--
G3SHQ9_GORGO|Gorilla              -----------G--------EKKNR--
ZDHC6_HUMAN|Homo                  -----------G--------EKKNR--
H2Q2K7_PANTR|Pan                  -----------G--------EKKNR--
ZDHC6_PONAB|Pongo                 -----------G--------EKKNR--
G1S129_NOMLE|Nomascus             -----------G--------EKKNR--
H9GF83_ANOCA|Anolis               -----------G--------EKKTR--
K7FG36_PELSI|Pelodiscus           -----------G--------EKKNR--
H0ZKK9_TAEGU|Taeniopygia          -----------G--------EKKSK--
F1NN38_CHICK|Gallus               -----------G--------EKKSR--
G1NEM3_MELGA|Meleagris            -----------G--------EKKSR--
G3MGC2_9ACAR|Amblyomma            --------------------HKKYK--
A7RQ92_NEMVE|Nematostella         ------------------------K--
                                                             
