MUSCLE (3.8) multiple sequence alignment


Q7PZ51_ANOGA|Anopheles            ------------MYQSACTAAAAGGCSEPERHDRDGLITHETAVAPVEHDYSGFDIVKAT
L7M222_9ACAR|Rhipicephalus        MDEEVDPSCAPVYYTAGQGPCGGGASATSGGSGGDAGCRQSPPPRVPEEDYSSFDIVKAT
G3SEE3_GORGO|Gorilla              -----------------------------------------------------------S
H2M9Y0_ORYLA|Oryzias              PVFAVQEIKPQTHY--------------------NHGFSENVSRKNHVDDYSTWDIVKAT
A7T1Q5_NEMVE|Nematostella         ------------------------------------------------------------
C3Y8Y5_BRAFL|Branchiostoma        ------------------------------------------------------------
F6UP47_XENTR|Xenopus              ------------------------------------------------------------
F1QAM1_DANRE|Danio                ------------------------------------------------------------
G3P3E7_GASAC|Gasterosteus         ------------------------------------------------------------
I3KUW6_ORENI|Oreochromis          ------------------------------------------------------------
H2V266_TAKRU|Takifugu             ------------------------------------------------------------
Q4S4G0_TETNG|Tetraodon            ------------------------------------------------------------
L5JRT7_PTEAL|Pteropus             ------------------------------------------------------------
H3B8Z0_LATCH|Latimeria            ------------------------------------------------------------
G1TQU5_RABIT|Oryctolagus          ------------------------------------------------------------
E2QWM7_CANFA|Canis                ------------------------------------------------------------
ZDHC4_MOUSE|Mus                   ------------------------------------------------------------
ZDHC4_RAT|Rattus                  ------------------------------------------------------------
G3T697_LOXAF|Loxodonta            ------------------------------------------------------------
H0V622_CAVPO|Cavia                ------------------------------------------------------------
G5BF44_HETGA|Heterocephalus       ------------------------------------------------------------
H0WGE9_OTOGA|Otolemur             ------------------------------------------------------------
F7CZA7_HORSE|Equus                ------------------------------------------------------------
G1PVW3_MYOLU|Myotis               ------------------------------------------------------------
ZDHC4_BOVIN|Bos                   ------------------------------------------------------------
D2H4A4_AILME|Ailuropoda           ------------------------------------------------------------
G9KYT7_MUSPF|Mustela              ------------------------------------------------------------
I3MHN2_SPETR|Spermophilus         ------------------------------------------------------------
F6Z4M3_CALJA|Callithrix           ------------------------------------------------------------
G7P086_MACFA|Macaca               ------------------------------------------------------------
F6RN23_MACMU|Macaca               ------------------------------------------------------------
H2PLG1_PONAB|Pongo                ------------------------------------------------------------
ZDHC4_HUMAN|Homo                  ------------------------------------------------------------
G1S0D5_NOMLE|Nomascus             ------------------------------------------------------------
H2QU60_PANTR|Pan                  ------------------------------------------------------------
H0ZYN2_TAEGU|Taeniopygia          ------------------------------------------------------------
E1C0F2_CHICK|Gallus               ------------------------------------------------------------
G1N3D2_MELGA|Meleagris            ------------------------------------------------------------
K7FM17_PELSI|Pelodiscus           ------------------------------------------------------------
F7F2T2_ORNAN|Ornithorhynchus      ------------------------------------------------------------
F7BGJ5_MONDO|Monodelphis          ------------------------------------------------------------
G3VIW1_SARHA|Sarcophilus          ------------------------------------------------------------
                                                                                              

Q7PZ51_ANOGA|Anopheles            QYGAIARVKELIEA-GWDVNQPDSETVTLLHWAAINNRKDIIKYFLDKGAIVDAVGGELN
L7M222_9ACAR|Rhipicephalus        QYGIFERCRYLVEVEGYNVNQPDAEDVTLLHWAAINNRREIVSFYISKGAVVDAIGGELR
G3SEE3_GORGO|Gorilla              RYGIYERCRELVEA-GYDVRQPDKENVTLLHWAAINNRIDLVKYYISKGAIVDQLGGDLN
H2M9Y0_ORYLA|Oryzias              QYGIFERCRELVEA-GFDVRQPDKENVTLLHWAAINNRIDLVKYYISKGAIVDQLGGDLN
A7T1Q5_NEMVE|Nematostella         ------------------------------------------------------------
C3Y8Y5_BRAFL|Branchiostoma        ------------------------------------------------------------
F6UP47_XENTR|Xenopus              ------------------------------------------------------------
F1QAM1_DANRE|Danio                ------------------------------------------------------------
G3P3E7_GASAC|Gasterosteus         ------------------------------------------------------------
I3KUW6_ORENI|Oreochromis          ------------------------------------------------------------
H2V266_TAKRU|Takifugu             ------------------------------------------------------------
Q4S4G0_TETNG|Tetraodon            ------------------------------------------------------------
L5JRT7_PTEAL|Pteropus             ------------------------------------------------------------
H3B8Z0_LATCH|Latimeria            ------------------------------------------------------------
G1TQU5_RABIT|Oryctolagus          ------------------------------------------------------------
E2QWM7_CANFA|Canis                ------------------------------------------------------------
ZDHC4_MOUSE|Mus                   ------------------------------------------------------------
ZDHC4_RAT|Rattus                  ------------------------------------------------------------
G3T697_LOXAF|Loxodonta            ------------------------------------------------------------
H0V622_CAVPO|Cavia                ------------------------------------------------------------
G5BF44_HETGA|Heterocephalus       ------------------------------------------------------------
H0WGE9_OTOGA|Otolemur             ------------------------------------------------------------
F7CZA7_HORSE|Equus                ------------------------------------------------------------
G1PVW3_MYOLU|Myotis               ------------------------------------------------------------
ZDHC4_BOVIN|Bos                   ------------------------------------------------------------
D2H4A4_AILME|Ailuropoda           ------------------------------------------------------------
G9KYT7_MUSPF|Mustela              ------------------------------------------------------------
I3MHN2_SPETR|Spermophilus         ------------------------------------------------------------
F6Z4M3_CALJA|Callithrix           ------------------------------------------------------------
G7P086_MACFA|Macaca               ------------------------------------------------------------
F6RN23_MACMU|Macaca               ------------------------------------------------------------
H2PLG1_PONAB|Pongo                ------------------------------------------------------------
ZDHC4_HUMAN|Homo                  ------------------------------------------------------------
G1S0D5_NOMLE|Nomascus             ------------------------------------------------------------
H2QU60_PANTR|Pan                  ------------------------------------------------------------
H0ZYN2_TAEGU|Taeniopygia          ------------------------------------------------------------
E1C0F2_CHICK|Gallus               ------------------------------------------------------------
G1N3D2_MELGA|Meleagris            ------------------------------------------------------------
K7FM17_PELSI|Pelodiscus           ------------------------------------------------------------
F7F2T2_ORNAN|Ornithorhynchus      ------------------------------------------------MIVLPYLRKKLL
F7BGJ5_MONDO|Monodelphis          ----------------------------------------------------MLIPQEAW
G3VIW1_SARHA|Sarcophilus          ------------------------------------------------------------
                                                                                              

Q7PZ51_ANOGA|Anopheles            ATPLHWATRQGHLGAVVL-LLAAGADPSLRDAEGCSCIHLAAQFGHTALVAYFIARGVNP
L7M222_9ACAR|Rhipicephalus        STPLHWATRQGHLGMVVL-LMRHGADASLVDGEGCSCIHLAAQSGHTAIVAYLVAKGQPV
G3SEE3_GORGO|Gorilla              STPLHWATRQGHLSMVVQ-LMKYGADPSLIDGEGCSCIHLAAQFGHTSIVAYLIAKGQDV
H2M9Y0_ORYLA|Oryzias              STPLHWATRQGHLSMVVQ-LMKYGADPSLIDGEGCSCIHLAAQFGHTSIVAYLIAKGQDV
A7T1Q5_NEMVE|Nematostella         ------------MDFLTLAFAYT-------------------------------------
C3Y8Y5_BRAFL|Branchiostoma        ------------------------------------------------------------
F6UP47_XENTR|Xenopus              ------------MDFLWL-FLTY-------------------------------------
F1QAM1_DANRE|Danio                ------------MDFLTL-FGIY-------------------------------------
G3P3E7_GASAC|Gasterosteus         ------------MDFLTL-FA-Y-------------------------------------
I3KUW6_ORENI|Oreochromis          ------------MDFLTL-FGIY-------------------------------------
H2V266_TAKRU|Takifugu             ------------MDFLTL-FAIY-------------------------------------
Q4S4G0_TETNG|Tetraodon            ------------MDFLTL-FAIY-------------------------------------
L5JRT7_PTEAL|Pteropus             ------------------------------------------------------------
H3B8Z0_LATCH|Latimeria            ------------MDFLTL-FLIY-------------------------------------
G1TQU5_RABIT|Oryctolagus          ------------MEFLVL-FLFY-------------------------------------
E2QWM7_CANFA|Canis                ------------MDFLVL-FLFY-------------------------------------
ZDHC4_MOUSE|Mus                   ------------MDFLVL-FLFY-------------------------------------
ZDHC4_RAT|Rattus                  ------------MDFLVL-FSFY-------------------------------------
G3T697_LOXAF|Loxodonta            ------------MEFLVL-FSLY-------------------------------------
H0V622_CAVPO|Cavia                ------------MDFLTL-FLIY-------------------------------------
G5BF44_HETGA|Heterocephalus       ------------MDFLVL-FLLY-------------------------------------
H0WGE9_OTOGA|Otolemur             ------------MDFLVL-FLFY-------------------------------------
F7CZA7_HORSE|Equus                ------------MDFLVL-FVFY-------------------------------------
G1PVW3_MYOLU|Myotis               ------------MDFLVL-FSFY-------------------------------------
ZDHC4_BOVIN|Bos                   ------------MDFLVL-FLLY-------------------------------------
D2H4A4_AILME|Ailuropoda           ------------MDFLVL-FLFY-------------------------------------
G9KYT7_MUSPF|Mustela              ------------MDFLVL-FLFY-------------------------------------
I3MHN2_SPETR|Spermophilus         ------------MDFLIL-FLFY-------------------------------------
F6Z4M3_CALJA|Callithrix           ------------MDFLVL-FLFY-------------------------------------
G7P086_MACFA|Macaca               ------------MDFLIL-FLFY-------------------------------------
F6RN23_MACMU|Macaca               ------------MDFLIL-FLFY-------------------------------------
H2PLG1_PONAB|Pongo                ------------MDFLVL-FLFY-------------------------------------
ZDHC4_HUMAN|Homo                  ------------MDFLVL-FLFY-------------------------------------
G1S0D5_NOMLE|Nomascus             ------------MDFLVL-FLFY-------------------------------------
H2QU60_PANTR|Pan                  ------------MDFLVL-FLFY-------------------------------------
H0ZYN2_TAEGU|Taeniopygia          ------------MEFLTL-FLIY-------------------------------------
E1C0F2_CHICK|Gallus               ------------MDFLPL-LLLY-------------------------------------
G1N3D2_MELGA|Meleagris            ------------LSDVPM---KH-------------------------------------
K7FM17_PELSI|Pelodiscus           ------------MDFLSL-FIIY-------------------------------------
F7F2T2_ORNAN|Ornithorhynchus      FMQVKVAPKAPKMDFLVL-FLIY-------------------------------------
F7BGJ5_MONDO|Monodelphis          YWK---TPPAFKMDFLVL-FLIY-------------------------------------
G3VIW1_SARHA|Sarcophilus          ------------MDFLVL-FLIY-------------------------------------
                                                                                              

Q7PZ51_ANOGA|Anopheles            DLQDRGGMTALMWAAWKISALDPVRLLLTLGANPSLADHTHGNTALHW--AILARNAT--
L7M222_9ACAR|Rhipicephalus        NQADSNGMTPLMWAAYRVMTNDPCRLLITLGASLTMCDTYHRNTPLHW--AVYVRNSS--
G3SEE3_GORGO|Gorilla              DMMDQNGMTPLMWAAYRTHSVDPTRLLLTFNVSVNLGDKYHKNTALHW--AVLAGNTT--
H2M9Y0_ORYLA|Oryzias              DMMDQNGMTPLMWAAYRTHSVDPTRLLLTFNVSVNLGDKYHKNTALHW--AVLAGNTT--
A7T1Q5_NEMVE|Nematostella         -----------------------ACFTVICYVLLCGGSSFHRGGVISWIRRKILYGYLLV
C3Y8Y5_BRAFL|Branchiostoma        ------------------------------------------------------------
F6UP47_XENTR|Xenopus              -----------------------VTFLIVGIFAFCFLSERSRTSLD----RALHRAGA--
F1QAM1_DANRE|Danio                -----------------------VAVVLTCIALVCKYSGHQQTPL-----GQLVGAFT--
G3P3E7_GASAC|Gasterosteus         -----------------------VAVVLACIALVCKHSGRQQTPL-----GVLLGSVG--
I3KUW6_ORENI|Oreochromis          -----------------------VVVVLTCIALVCRYSGQQHSPL-----NSLYSFAL--
H2V266_TAKRU|Takifugu             -----------------------VLVVLMCIVLVCKYSGRQHTPFTTL--STVISSSS--
Q4S4G0_TETNG|Tetraodon            -----------------------VLVVLTCIVLVCKYSGQQQTPF-----TTLSTYVG--
L5JRT7_PTEAL|Pteropus             ------------------------------------------------------------
H3B8Z0_LATCH|Latimeria            -----------------------SVLVLTSIVLIIKYPGQDESFL-----RRVFNSLT--
G1TQU5_RABIT|Oryctolagus          -----------------------LAVVLTSVVLLCVCSKTPRL-------QGLVRRGA--
E2QWM7_CANFA|Canis                -----------------------LVLVLIGVVTVCICSKTHYL-------KGVVRGGA--
ZDHC4_MOUSE|Mus                   -----------------------LAFLLICVVLICIFTKSQRL-------KAVVLGGA--
ZDHC4_RAT|Rattus                  -----------------------LAFLLICVIMICIFTKSQRL-------KAVVLGGA--
G3T697_LOXAF|Loxodonta            -----------------------LALLLIGVALICICARTQYL-------DGLVRGGA--
H0V622_CAVPO|Cavia                -----------------------LDFMMISVLMIWIYPRSHHL-------TSLVQGGT--
G5BF44_HETGA|Heterocephalus       -----------------------LAFGLTSVIMICICSKSHHL-------SSLFQGGT--
H0WGE9_OTOGA|Otolemur             -----------------------LALVLIGGGMICICSKTHRL-------KGLVREGA--
F7CZA7_HORSE|Equus                -----------------------LTLVLISGVMICVCSKTGYL-------KGPVRRGT--
G1PVW3_MYOLU|Myotis               -----------------------LALLLIGGALLCICLKTRYL-------KGLVRGGA--
ZDHC4_BOVIN|Bos                   -----------------------LALVLLGFVMICIGSKTHYL-------QGLISRGA--
D2H4A4_AILME|Ailuropoda           -----------------------VTLVLIGIVTICICSKTHYR-------KGLVRGGA--
G9KYT7_MUSPF|Mustela              -----------------------LALVLIGVVMICICSKTHYL-------KGLVRGAA--
I3MHN2_SPETR|Spermophilus         -----------------------LVFMLVSVVMVCICSKTNRL-------KGLVQGGA--
F6Z4M3_CALJA|Callithrix           -----------------------LASVLMGLVLICICSKTHCS-------KGLVKGGA--
G7P086_MACFA|Macaca               -----------------------LALVVMGLVLICVCSKTHSL-------KGLARGGA--
F6RN23_MACMU|Macaca               -----------------------LALVVMGLVLICVCSKTHSL-------KGLARGGA--
H2PLG1_PONAB|Pongo                -----------------------LASVLMGLVLICVCSKTHSL-------KGLARGGA--
ZDHC4_HUMAN|Homo                  -----------------------LASVLMGLVLICVCSKTHSL-------KGLARGGA--
G1S0D5_NOMLE|Nomascus             -----------------------LASVLMGLVLICVCSKTHSL-------KGLARGGA--
H2QU60_PANTR|Pan                  -----------------------LASVLMGLVLICVCSKTHSL-------KGLARGGA--
H0ZYN2_TAEGU|Taeniopygia          -----------------------LCSLLALAALLCLCSGREEGFL-----ARSANRAS--
E1C0F2_CHICK|Gallus               -----------------------LCLVLAVAVLYCSHAGSGGGRL-----GRAARTAG--
G1N3D2_MELGA|Meleagris            -----------------------IVVQKLLSSIPCLASYTLYNLI-----KAPYNFHTLT
K7FM17_PELSI|Pelodiscus           -----------------------LLLVLASIVLVCIYSGRKESFP-----ARGLSCIT--
F7F2T2_ORNAN|Ornithorhynchus      -----------------------LVLILSSVILVCTRSERIHNLA-----DAVLTAGS--
F7BGJ5_MONDO|Monodelphis          -----------------------LVCVLTGVLLLCAYSKKNHSLA-----GEILTDGS--
G3VIW1_SARHA|Sarcophilus          -----------------------LACVLTSILLLCIYSKRTHNFA-----GGILTDGS--
                                                                                              

Q7PZ51_ANOGA|Anopheles            -AISTLVLKGKANMEVPNLRGDTPLTMLQPHLGSIWIGTKVSDRIREATQQSHRRNPLVR
L7M222_9ACAR|Rhipicephalus        -AVS-LLIKAGSDLSARNAQGDTPR-MMAEKLKSIWIEERLLEAEAAQAQGH----FLVR
G3SEE3_GORGO|Gorilla              -VIS-LLLEAGANVDAQNIKGESAL-DLAKQRKNVWMINHL--QEARQAKGYDNPSFLRK
H2M9Y0_ORYLA|Oryzias              -VIS-LLLDANANVDAQNIKGETPL-DLAKQRKNVWMINHL--QEARQAKGYDSPSYLKR
A7T1Q5_NEMVE|Nematostella         EGACINCL----------------------------------------------------
C3Y8Y5_BRAFL|Branchiostoma        ------------------------------------------------------------
F6UP47_XENTR|Xenopus              --ILSLVL----------------------------------------------------
F1QAM1_DANRE|Danio                -RIVSPCI----------------------------------------------------
G3P3E7_GASAC|Gasterosteus         -KVVAPIT----------------------------------------------------
I3KUW6_ORENI|Oreochromis          -KRLASIT----------------------------------------------------
H2V266_TAKRU|Takifugu             -QVAAPLT----------------------------------------------------
Q4S4G0_TETNG|Tetraodon            -KVAAPLT----------------------------------------------------
L5JRT7_PTEAL|Pteropus             ------------------------------------------------------------
H3B8Z0_LATCH|Latimeria            -KIISPVI----------------------------------------------------
G1TQU5_RABIT|Oryctolagus          -QVFSCVI----------------------------------------------------
E2QWM7_CANFA|Canis                -QIISCII----------------------------------------------------
ZDHC4_MOUSE|Mus                   -QVCSRVI----------------------------------------------------
ZDHC4_RAT|Rattus                  -QVCARVT----------------------------------------------------
G3T697_LOXAF|Loxodonta            -QILSRII----------------------------------------------------
H0V622_CAVPO|Cavia                -QLFSCII----------------------------------------------------
G5BF44_HETGA|Heterocephalus       -QLCSCII----------------------------------------------------
H0WGE9_OTOGA|Otolemur             -QIFSCII----------------------------------------------------
F7CZA7_HORSE|Equus                -QIFSYII----------------------------------------------------
G1PVW3_MYOLU|Myotis               -QIFSYIV----------------------------------------------------
ZDHC4_BOVIN|Bos                   -QVFSYII----------------------------------------------------
D2H4A4_AILME|Ailuropoda           -QIISYII----------------------------------------------------
G9KYT7_MUSPF|Mustela              -QIISYII----------------------------------------------------
I3MHN2_SPETR|Spermophilus         -QICSCII----------------------------------------------------
F6Z4M3_CALJA|Callithrix           -QIFSYII----------------------------------------------------
G7P086_MACFA|Macaca               -QIFCCVI----------------------------------------------------
F6RN23_MACMU|Macaca               -QIFSCVI----------------------------------------------------
H2PLG1_PONAB|Pongo                -QIFSCII----------------------------------------------------
ZDHC4_HUMAN|Homo                  -QIFSCII----------------------------------------------------
G1S0D5_NOMLE|Nomascus             -QIFSCII----------------------------------------------------
H2QU60_PANTR|Pan                  -QIFSCII----------------------------------------------------
H0ZYN2_TAEGU|Taeniopygia          -QVLSLVI----------------------------------------------------
E1C0F2_CHICK|Gallus               -QVLSLVI----------------------------------------------------
G1N3D2_MELGA|Meleagris            -QVLSLVI----------------------------------------------------
K7FM17_PELSI|Pelodiscus           -QISSFII----------------------------------------------------
F7F2T2_ORNAN|Ornithorhynchus      -QVFSCVI----------------------------------------------------
F7BGJ5_MONDO|Monodelphis          -QVFSRFM----------------------------------------------------
G3VIW1_SARHA|Sarcophilus          -QVFSHFV----------------------------------------------------
                                                                                              

Q7PZ51_ANOGA|Anopheles            MTLDKRFRWWSMIATPFLVFYLVGLVFCAD-TQIIIK-IFLLACLYSVAYTIGQHLFDEN
L7M222_9ACAR|Rhipicephalus        IVRDKTLKYWAMFSSPFVAFYAIGLVLDSQ-ETYLVKFGLLFI-MGLATMFLSKCLFDER
G3SEE3_GORGO|Gorilla              LKADKEFRQKVMLGTPFLVIWLVGFIADLNIDSWLIK-GLMYGGVWATVQFLSKSFFDHS
H2M9Y0_ORYLA|Oryzias              LKMDKEFRQKVMLGTPFVVVWLVGFIADLDIDSWLIK-SVMYAGVWVAVQFLSKAFFDHS
A7T1Q5_NEMVE|Nematostella         -------------------------------PTFITR---------GTSRIVD-FVFYTR
C3Y8Y5_BRAFL|Branchiostoma        ------------------------------------------------------------
F6UP47_XENTR|Xenopus              -------------------------------PAWLPR---------RYKSCFQTSCFPNR
F1QAM1_DANRE|Danio                -------------------------------PQWLQS---------ICYRTMH-RLFHQR
G3P3E7_GASAC|Gasterosteus         -------------------------------PRWLQR---------FSQRTLH-RLFHRR
I3KUW6_ORENI|Oreochromis          -------------------------------PKWLQK---------FSQWTLH-RLFHQR
H2V266_TAKRU|Takifugu             -------------------------------PKWVRR---------LSQRALH-RFFHQR
Q4S4G0_TETNG|Tetraodon            -------------------------------PKWVRR---------LSQWTLH-RLFHQR
L5JRT7_PTEAL|Pteropus             ------------------------------------------------------------
H3B8Z0_LATCH|Latimeria            -------------------------------PLWLQT---------ATHHFLH-KLFHTR
G1TQU5_RABIT|Oryctolagus          -------------------------------PECLQR---------AVQRLLR-YLFHTR
E2QWM7_CANFA|Canis                -------------------------------PKCLQR---------AMPKLLH-YLFRTR
ZDHC4_MOUSE|Mus                   -------------------------------PQCLQR---------AVQTLLH-QLFHTR
ZDHC4_RAT|Rattus                  -------------------------------PQCFQR---------AVQTLLH-QLFHTR
G3T697_LOXAF|Loxodonta            -------------------------------PECLQR---------AVHRLLH-YLFHTR
H0V622_CAVPO|Cavia                -------------------------------PQCLQR---------AMQRWLR-YFFYTR
G5BF44_HETGA|Heterocephalus       -------------------------------PQCFQR---------AIQRCLH-YFFHTR
H0WGE9_OTOGA|Otolemur             -------------------------------PECLQR---------AMQRLLH-YLFHTR
F7CZA7_HORSE|Equus                -------------------------------PECLQR---------AMLRLHH-YLFHTQ
G1PVW3_MYOLU|Myotis               -------------------------------PEWFQR---------AMLRLLH-YLFHTR
ZDHC4_BOVIN|Bos                   -------------------------------PECLQR---------AMLSVLH-YLFHTR
D2H4A4_AILME|Ailuropoda           -------------------------------PECLQR---------AMLKLLH-YLFHTR
G9KYT7_MUSPF|Mustela              -------------------------------PECLQR---------AVLKLLH-YLFHTR
I3MHN2_SPETR|Spermophilus         -------------------------------PECIQR---------AVRKLLH-YLFHTR
F6Z4M3_CALJA|Callithrix           -------------------------------PECLQR---------AMHRLLH-YLFHTR
G7P086_MACFA|Macaca               -------------------------------PECLQR---------AMHRSLH-YLFHTR
F6RN23_MACMU|Macaca               -------------------------------PECLQR---------AMHRSLH-YLFHTR
H2PLG1_PONAB|Pongo                -------------------------------PERLQR---------AVHGLLH-YLFHTR
ZDHC4_HUMAN|Homo                  -------------------------------PECLQR---------AVHGLLH-YLFHTR
G1S0D5_NOMLE|Nomascus             -------------------------------PERLQR---------AVHGLLH-YLFHTR
H2QU60_PANTR|Pan                  -------------------------------PECLQR---------AVHGLLH-YLFHTR
H0ZYN2_TAEGU|Taeniopygia          -------------------------------PSQLRR---------VTHRALH-RLFHTR
E1C0F2_CHICK|Gallus               -------------------------------PTRIQS---------VTQKVLL-RLFHTR
G1N3D2_MELGA|Meleagris            -------------------------------PTRLQS---------VTQKVLL-RLFHTR
K7FM17_PELSI|Pelodiscus           -------------------------------PTWLQR---------PTQRMLH-RLFHTR
F7F2T2_ORNAN|Ornithorhynchus      -------------------------------PGWLQR---------AAHRVLH-HLLHTR
F7BGJ5_MONDO|Monodelphis          -------------------------------PGWLQR---------ATQRVFH-RLFHTR
G3VIW1_SARHA|Sarcophilus          -------------------------------PRWLQR---------ATQKTFH-HLFHTR
                                                                                              

Q7PZ51_ANOGA|Anopheles            LMALLPLSVYMATKLWFYVTW-LTYIAPT--VSFL-ASLAFLACSAGLWVCFLKSWRGNP
L7M222_9ACAR|Rhipicephalus        TMNILPMAVYLATKFWMYITW-VTDLWPY--VGTFWVNVGFVISSVPLFYSFYKSWRADP
G3SEE3_GORGO|Gorilla              MHSALPLGIYLATKFWMYVTW-FFWFWNDAHLNFLFIHLPFLANSVALFYNFGKSWKSDP
H2M9Y0_ORYLA|Oryzias              MHSALPLGIYLATKFWMYATW-FYWFWND--LPFATVHVPFLINSLVLFYNFGKSWKSDP
A7T1Q5_NEMVE|Nematostella         NHFLQAFYLFLVIGGSLVYSLHILPYFDKMN---SFAYSTYCLIIINISF-FVICCYAEP
C3Y8Y5_BRAFL|Branchiostoma        --------------------------------------LPLYILCVNAVL-FCALSLGDP
F6UP47_XENTR|Xenopus              NGAFVILHLILDILVFAEYSWEVLGYCLELEISRPFIFLPYICISVNLYF-FYRCCAADP
F1QAM1_DANRE|Danio                NNFFLYLHLLLEVVVYGEFTYEVFGFCLDMGSSSLSLCVPYILLALKSCL-FYLCCSRDP
G3P3E7_GASAC|Gasterosteus         NNMFIYLHVLLEGAVYAEFTYEVFGFCREMDTTLTHLTVPYVLLVLQAVF-FYLCARRDP
I3KUW6_ORENI|Oreochromis          SNAFIYLHILLEGAVYAEFTYEVFGFCREMDTTLISLSVPYILLAIKTSF-FYLCIKTDP
H2V266_TAKRU|Takifugu             SNTFIYLHILLEVAVYAEFTYEVFGFCREMDTGLLSLCVPYILLAIKTFF-FYLCITRDP
Q4S4G0_TETNG|Tetraodon            NKMFIYLHILLEVAVYAEFTYEVFGFCREMDTGLASLCVPYILLVVKTFF-FYLCITGDP
L5JRT7_PTEAL|Pteropus             ------------------------------------------------------------
H3B8Z0_LATCH|Latimeria            NAIFLILHFVLEAAVYGEYTWEVFQYCRELGFSLPSLLVPYFLLAVKSYF-FYLCCITDP
G1TQU5_RABIT|Oryctolagus          -YLLHTLHV-------------IFFRSEEL---VEFLLNARVVRDRGWGYQWVGVWPG-P
E2QWM7_CANFA|Canis                NHTFIILHLILQGMVYSEYTWEIFGYCRELEFSLCYLLLPYFLLIINLVF-FTLSCVSDP
ZDHC4_MOUSE|Mus                   HPTFIVLHLLLQGLVYAEYTCEVFGYCRELEFSLPYLLLPYVLLSVNLVF-FTLTCAANP
ZDHC4_RAT|Rattus                  HPAFLALHLLLQGLVYAEYTYEVFSYCRELEFSLPCLLLPYVLLSVNLVF-FTLTCSTNP
G3T697_LOXAF|Loxodonta            NYTFIILHLVLQGMVYTEYTREVFGYCQELEFSLYYLLLPYLLLLVNLCF-FALSCVTNP
H0V622_CAVPO|Cavia                NYTFVILQLVLQGLVYIEYTWEILGYCQELEFSLCYLLLPYLLLTVNLVF-FALTCLTNP
G5BF44_HETGA|Heterocephalus       NHTFIVLHLVLQGLVYIEYTWEIFGYCQELEFSLCYLLLPYLWLIINLVF-FALTCVTNP
H0WGE9_OTOGA|Otolemur             NHIFIILHLILEGMVYGEYTWEILGFCQELEFSLYYLLLPYLLLIINLFF-FTLTCITNP
F7CZA7_HORSE|Equus                NRTFILLHLTLQGMVYAEYTWEIFGYCQQLEFSLYYLLLPYLLLIVNLVF-FTLSSVTNP
G1PVW3_MYOLU|Myotis               NHTFIILHLLLQGMVYTEYTWEILGYCQELDFSLCYLLLPYLLLVVNLIF-FTLSCVTDP
ZDHC4_BOVIN|Bos                   NYTFVVLHLILQGMVYTEYTWEIFGLCQQLEFSLYYLFLPYLLLIVNLLF-FTLSCVTNP
D2H4A4_AILME|Ailuropoda           NYTFVLLHLILQGMVYSEYTWEIFGYCQELEFSLHYLLLPYLLLIGNLVF-FTLSCVSNP
G9KYT7_MUSPF|Mustela              NHTFILLHLVLQGMVYSEYTCEVFGYCRELEFPLHYLLLPYLLLIVNLVF-FTLSCVSNP
I3MHN2_SPETR|Spermophilus         NHAFIILHLVLQGTVYTEYTWEIFGYCQELEFSLYYLLLPYLLLIICLIF-FTLTCLTNP
F6Z4M3_CALJA|Callithrix           NHSFIVLHLVLQGMVYTEYTWELFGYCQELEFSLYYLLLPYLLLIVNLFS-FILTCVTNP
G7P086_MACFA|Macaca               NHTFIVLHLVLQAMVYTEYTWEVFGYCQELEFSLYYLLLPYLLLVVNLFS-FTLTCVTNP
F6RN23_MACMU|Macaca               NHTFIVLHLVLQAMVYTEYTWEVFGYCQELEFSLYYLLLPYLLLVVNLFS-FTLTCVTNP
H2PLG1_PONAB|Pongo                NHTFIVLHLVLQGMVYTEYTWEVFGYCQELDFSLYYLLLPYLLLVVNLFS-FTLTCVTNP
ZDHC4_HUMAN|Homo                  NHTFIVLHLVLQGMVYTEYTWEVFGYCQELELSLHYLLLPYLLLGVNLFF-FTLTCGTNP
G1S0D5_NOMLE|Nomascus             NHTFIVLHLVLQGMVYTEYTWEVFGYCQELEFSLYYLLLPYLLLVVNLFS-FTLTCVTNP
H2QU60_PANTR|Pan                  NHTFIVLHLVLQGMVYTEYTWEVFGYCQELEFSLYYLLLPYLLLVVNLFF-FTLTCVTNP
H0ZYN2_TAEGU|Taeniopygia          SCLFVVLHVALQAAVFGEYTWEVFGYCWELQFHLLLLLLPYLLLAGNLGC-FLLCSRANP
E1C0F2_CHICK|Gallus               NYLFVVLHIALQAAVYAEYTWEVFVYCWELEFHLVMLLLPYLLLAGNVGC-FILCSCANP
G1N3D2_MELGA|Meleagris            NYLFVVLHIALQAAVYAEYTWEVFVYCWELEFHLVLLLLPYLLLLGNMGC-FILCSCANP
K7FM17_PELSI|Pelodiscus           SCLFIVLHLALQVTIFGEYSWEIFGYCQELEFDTHYLLLPYVLLAVNMGF-FILCSVTNP
F7F2T2_ORNAN|Ornithorhynchus      NYAFFTLHLALQVAVYCEYTWEIFGYCRELEFSLNYLLLPYLLFIVNLIF-FILSCITNP
F7BGJ5_MONDO|Monodelphis          NCTFIILHLVLEGAVYSEYTWEIFNYCQELEFSVYHLLLPYLLLMINLFF-FILSCTTNP
G3VIW1_SARHA|Sarcophilus          NYVFIILHLALEGAVYSEYAWEIFHYCLELEFSLYHLLLPYLLLIINLFF-FILSCMTNP
                                                                                              

Q7PZ51_ANOGA|Anopheles            GVIQPTQEQ--RFRTIIELSERGASGFEPSAFCSACLVRRPVRSKHCSVCDRCVARF-DH
L7M222_9ACAR|Rhipicephalus        GIISANTEQ--KYRTIVELAEQD--GFDPAVFCSTCLVRRPLRSKHCSVCNHCVARF-DH
G3SEE3_GORGO|Gorilla              GIIKATEEQ--KKKTIVELAETG--SLDLSIFCSTCLIRKPVRSKHCGVCNRCIAKF-DH
H2M9Y0_ORYLA|Oryzias              GIIKASEEQ--KKKTIVELAETG--SLDLSIFCSTCLIRKPVRSKHCAVCNRCIAKF-DH
A7T1Q5_NEMVE|Nematostella         GVVTPSNMA--ASIQRYKYDGY---YYIRK-ECPTCELDKPARSKHCSLCKACINRF-DH
C3Y8Y5_BRAFL|Branchiostoma        GVIVKRNVE--RHLKLYEFDGQ---LYRQDEQCRTCQFEKPARSKHCAFGNHCVYRF-DH
F6UP47_XENTR|Xenopus              GIVNKKNEA--SYVQLYEYDCI---LFHPEQQCPTCQITKPARSKHCRVCGCCIHRF-DH
F1QAM1_DANRE|Danio                GTLTKSNLS--AHLKIYQYDEK---LFQQGMKCSTCQLIKPARSKHCRVCNRCVQRF-DH
G3P3E7_GASAC|Gasterosteus         GTVTKKKIS--GQLSLYPYDGR---LFHPGVSCETCQLIKPARSKHCRVCDRCVQRF-DH
I3KUW6_ORENI|Oreochromis          GTVTKKKVA--GQLHIYSYDRR---LFHPGISCSTCQLVKPARSKHCRVCNRCVQRF-DH
H2V266_TAKRU|Takifugu             GTVTKKKMS--GQLHTYPYDRR---LFHPGANCPTCHLAKPARSKHCRVCNRCVMRF-DH
Q4S4G0_TETNG|Tetraodon            GTVTKKNVS--GQLRVYPYDRR---LFHPGATCPTCQLPKPARSKHCRVCNRCVIRF-DH
L5JRT7_PTEAL|Pteropus             -----------------------------------------MRSRHWHVCNQCVHHL-DH
H3B8Z0_LATCH|Latimeria            GTITKLNHE--SLLQVYMYDEV---LYQKFIVCPTCNLRKPARSKHCRVCNRCVHRF-DH
G1TQU5_RABIT|Oryctolagus          RLLHTAGQAASSFLSLMIIVST---LQLQEVLCKCSVSHGVSGAKHLRVCDCCVHRF-DH
E2QWM7_CANFA|Canis                GTITKANEL--LFLQVYEFDEV---MFLKNMKCSTCNLRKPARSKHCKYVCYKIHPFLGH
ZDHC4_MOUSE|Mus                   GTITKANES--FLLQVYKFDDV---MFPKNSRCPTCDLRKPARSKHCRLCDRCVHRF-DH
ZDHC4_RAT|Rattus                  GTITKTNVL--LLLQVYEFDEV---MFPKNSRCSTCDLRKPARSKHCRVCDRCVHRF-DH
G3T697_LOXAF|Loxodonta            GTITKANEL--LFLQVYEFDEV---MFRKNVRCPTCDLRKPARSKHCRVCNRCVHRF-DH
H0V622_CAVPO|Cavia                GTITRTNEL--LLLQVYEFDGV---MFPKNARCSSCGLKKPARSKHCSVCNRCVHRF-DH
G5BF44_HETGA|Heterocephalus       GTITKTNEL--LFLQVYEFDDV---MFPKNVRCSTCGLKKPARSKHCSVCNHCVHRF-DH
H0WGE9_OTOGA|Otolemur             AIITKSNEL--LFLQVYEFDEV---MFQKNMKCSTCDLRKPARSKHCRVCNWCVHRF-DH
F7CZA7_HORSE|Equus                GTVTKANEL--LLLPVYEFDEV---LFPKNMRCSTCGLRKPARSKHCAVCNRCVHRF-DH
G1PVW3_MYOLU|Myotis               GTITKANES--LFLQVYEFDEV---MFPKNGRCSTCDLRKPARSKHCSVCNRCVHRF-DH
ZDHC4_BOVIN|Bos                   GTITKANEL--LFLQVYEFDGV---MFPKNVRCPTCDLRKPARSKHCSVCNRCVHRF-DH
D2H4A4_AILME|Ailuropoda           GTITKANEL--LFLQAYEFDEV---MFSKNRKCSTCNLRKPARSKHCSVCNRCVHRF-DH
G9KYT7_MUSPF|Mustela              GTITKANEL--SFLQVYEFDEV---MFSKNMKCSTCNLRKPARSKHCSVCNRCVHRF-DH
I3MHN2_SPETR|Spermophilus         GTITKENEL--LFLQVYEFDEV---MFPKNARCSTCDLRKPARSKHCSVCNWCVHRF-DH
F6Z4M3_CALJA|Callithrix           GIITKANEL--LFLHVYEFDEV---MFLKNVRCSTCDLRKPARSKHCSVCNWCVHRF-DH
G7P086_MACFA|Macaca               GIITKANEL--LFLHVYEFDEV---MFPKNVRCSTCALRKPARSKHCSVCNWCVHRF-DH
F6RN23_MACMU|Macaca               GIITKANEL--LFLHVYEFDEV---MFPKNVRCSTCALRKPARSKHCSVCNWCVHRF-DH
H2PLG1_PONAB|Pongo                GVITKANEL--LFLHVYEFDEL---MFPKNVRCSTCDLRKPARSKHCSVCNWCVHRF-DH
ZDHC4_HUMAN|Homo                  GIITKANEL--LFLHVYEFDEV---MFPKNVRCSTCDLRKPARSKHCSVCNWCVHRF-DH
G1S0D5_NOMLE|Nomascus             GIITKANEL--LFLHVYEFDEV---MFPKNVRCSTCDLRKPARSKHCSVCNWCVHRF-DH
H2QU60_PANTR|Pan                  GIITKANEL--LFLHVYEFDEV---MFPKNVRCSTCDLRKPARSKHCSVCNWCVHRF-DH
H0ZYN2_TAEGU|Taeniopygia          GTVTKSNAA--SLVKVYAYDGV---MFQKGLVCPTCSVEKPARSKHCSVCRTCVHRF-DH
E1C0F2_CHICK|Gallus               GVITKSNHA--SLMKTYAYDGV---LFQKGTVCATCNMEKPARSKHCSFCDICVHRF-DH
G1N3D2_MELGA|Meleagris            GIITKSNHA--SLVKTYAYDGV---LFQKGIVCATCNVEKPARSKHCSFCNICVHRF-DH
K7FM17_PELSI|Pelodiscus           GTVTQSNQE--SFLKAYAYDGV---MFQKNIMCPTCNVEKPARSKHCSVCNSCVHRF-DH
F7F2T2_ORNAN|Ornithorhynchus      GTITKSNQA--VFLGAYEYDEV---MFQKNSRCPTCNLEKPARSKHCSICDRCVHRF-DH
F7BGJ5_MONDO|Monodelphis          GIITKSNGT--SFLQIYEYDEV---IFLKNMKCPTCNLRKPARSKHCNVCNRCVHRF-DH
G3VIW1_SARHA|Sarcophilus          GIITKSNEA--SFLQVYEYDEV---IFLKNMNCPTCNLRKPARSKHCSICNRCVHRF-DH
                                                                             :.*       :  : .*

Q7PZ51_ANOGA|Anopheles            HCPWVGNCIGAKNHKYFMGFLWMLLIMCGWMLYGGSNFYVQTCSINM---------DEGL
L7M222_9ACAR|Rhipicephalus        HCPWVNNCVGAGNHVYFVNYLIFLLAMLGWSWYGCFAFWKEHTLWAALSQSG--------
G3SEE3_GORGO|Gorilla              HCPWVGNCVGAGNHRYFMGYLFFLLFMICWMIYGCISYW-------GLHCETTYT-KDGF
H2M9Y0_ORYLA|Oryzias              HCPWVGNCVGSGNHRYFMAYLFFLLCMICWMIYGCISYW-------RVHCATTYA-KDGF
A7T1Q5_NEMVE|Nematostella         HCSWVNNCIGANNYGFFIGFIFTAAALCIYVTFLVMIVFVYISITQRLLEGQYVD-SEGN
C3Y8Y5_BRAFL|Branchiostoma        HCLWVNCCIGGLNHRLFLGFLISLCCLCGYISYATWKVALLIVEANKLWSAHYVD-RYGR
F6UP47_XENTR|Xenopus              HCVWVNNCVGGLNIRYFLIYLISLTLTAVSLAAVIMAFLLKVVLLSHMMSAAYID-PEGH
F1QAM1_DANRE|Danio                HCVWVNNCIGAQNTRYFMLYLLSVCAMAGNIAVLTTDMLLQTVLRTGLLHAHYID-EQGI
G3P3E7_GASAC|Gasterosteus         HCVWVNNCIGARNTRYFLLYLFSVCAMAGDMAVLTGDMLFHAVLRSGLLRASYVD-EYGE
I3KUW6_ORENI|Oreochromis          HCVWVNNCIGAQNTRYFLLYLFSVCAMAFDIALLTVDMLLHVVLRTGLLGASYLD-ENGQ
H2V266_TAKRU|Takifugu             HCIWVNNCIGGQNTRYFLLYLFSVCAMAGDIALLTGEMLLHAVLRSGLLMASYID-DYGE
Q4S4G0_TETNG|Tetraodon            HCIWVNNCIGGRNTRYFLLYLFSVCAMAGDIALLTGDMLLHAVLHSGLLMSSYID-EYGQ
L5JRT7_PTEAL|Pteropus             HCVWVNNYIVAWNAKYFLLYFLMSTASAATVA---TVFLVQLVVWLNLYLETYVN-DLGH
H3B8Z0_LATCH|Latimeria            HCVWVNNCIGALNTRYFLIYLITLSAMAVNIAALTLSLLIQVVVMSNMMQGSYID-ADGQ
G1TQU5_RABIT|Oryctolagus          HCVWVNNCIGAWNARYFLIYLATLAASAASVAAVSTTFLIHLVALSDLHQETYVD-DRGH
E2QWM7_CANFA|Canis                LCIWF--CFCTVVGKYGLPFLKTIS----FVAVIKSLFFVTSVLRERLISSVHLDFILMH
ZDHC4_MOUSE|Mus                   HCVWVNNCIGAWNTRYFLIYLLTLTASAATIATVTAAFLLRLVTVSDLYQETYLD-DVGH
ZDHC4_RAT|Rattus                  HCVWVNNCIGAWNTGYFLIYLLTLTASAATIAILSAAFLLRLVAVSNLYQETYLD-DLGR
G3T697_LOXAF|Loxodonta            HCVWVNNCIGAWNARYFLIYLLTLTASAATMASVITAFLVQVVVFSDLYLETYID-THGH
H0V622_CAVPO|Cavia                HCVWVNNCIGAWNTRYFLIYLLTLSASAATMAILSATFLVRLVMMSNLYQEMYRD-DFGQ
G5BF44_HETGA|Heterocephalus       HCVWVNNCIGAWNIRYFLIYLLTLTSSATTMAVLSTAFLVHLVVVSDLYQEMYID-DFGH
H0WGE9_OTOGA|Otolemur             HCVWVNNCIGAWNIRYFLIYLLTLTASAVTLTIVCTAFLVHLVVVSDLYQETYID-DLGH
F7CZA7_HORSE|Equus                HCVWMNNCIGAWNARYFLIYLLTLTASAVTMAVVSAVFLVRLVVVSGLYQETYVD-DLGH
G1PVW3_MYOLU|Myotis               HCVWVNNCIGAWNARYFLTYLLTLTASAATMAIVTTVFLVRLVVLSDLHLETYVD-DLGQ
ZDHC4_BOVIN|Bos                   HCVWVNNCIGAWNTRYFLSYLFTLTASAATMAVVSTVFLVRLVVMSDVYLQTYVD-DLGH
D2H4A4_AILME|Ailuropoda           HCVWVNNCIGAWNAKYFLLYLLTLTASAATMAVVSTVFLVQLVMLSDLYLETYID-DLGH
G9KYT7_MUSPF|Mustela              HCVWVNNCIGAWNARYFLLYLLTLTASAGTMAVVSTVFLVQLVVLSDLYLETYVD-DLGH
I3MHN2_SPETR|Spermophilus         HCVWVNTCIGAWNTRYFLIYLLTLTASAAVMAIISTMFLVRLVTMSDLYQETYID-DLGH
F6Z4M3_CALJA|Callithrix           HCVWVNNCIGAWNIRYFLIYLLTLTASAATVAIVSTAFLVHLVVMSDLYQETYID-DFGR
G7P086_MACFA|Macaca               HCVWVNNCIGAWNIRYFLIYLLTLTASAATVAIVSTTFLIHLVVMSDLYQETYVD-DLGH
F6RN23_MACMU|Macaca               HCVWVNNCIGAWNIRYFLIYLLTLTASAATVAIVSTTFLIHLVVMSDLYQETYVD-DLGH
H2PLG1_PONAB|Pongo                HCVWVNNCIGAWNIRYFLIYLLTLTASAATVAIVSTTFLVHLVVMSDLYQETYTD-DLGH
ZDHC4_HUMAN|Homo                  HCVWVNNCIGAWNIRYFLIYVLTLTASAATVAIVSTTFLVHLVVMSDLYQETYID-DLGH
G1S0D5_NOMLE|Nomascus             HCVWVNNCIGAWNIRYFLIYLLTLTASAATVAIVSTTFLVHLVVMSDLYQETYID-DLGH
H2QU60_PANTR|Pan                  HCVWVNNCIGAWNIRYFLIYLLTLTASAATVAIVSTTFLVHLVVMSDLYQETYID-DLGH
H0ZYN2_TAEGU|Taeniopygia          HCVWVNNCIGAANAGVFLLYLLSLTATAGAVAAVTAALLLQLLLLSNLLHGTYLD-AQGQ
E1C0F2_CHICK|Gallus               HCVWVNNCIGAFNAKYFFLYLFTLTVMAATIASITAAFLIQVVLLSNMMHGSYID-DQGQ
G1N3D2_MELGA|Meleagris            HCVWVNNCIGAFNAKYFFLYLFTLTVMAATIAIITTAFLIQVVLLSNMMHGSYID-DQGQ
K7FM17_PELSI|Pelodiscus           HCVWVNNCIGAFNIRYFLLYLFTVTALAADLAFVTAAFLIQVVLLSNMMLGSYID-DQGQ
F7F2T2_ORNAN|Ornithorhynchus      HCVWVNNCIGAFNAKYFLLYLFTLTAMAADIAIITTAFLVHLVFLSNMTLGSYID-DEGQ
F7BGJ5_MONDO|Monodelphis          HCIWVNNCIGALNARYFLIYLLTLTAMAADIAIITTAFLIHLVLISGMTSGTYFD-DYGQ
G3VIW1_SARHA|Sarcophilus          HCIWVNNCIGALNARYFLIYLLTLTAMAADIAIITAAFLTRLVLLSGMTMGTYFD-DHGN
                                   * *.   .        . :.                                       

Q7PZ51_ANOGA|Anopheles            WSALQAIGSCNPWVGWVMGNALLHMSWVTVLT------ICQSYQVVCLGMTTNERLNR--
L7M222_9ACAR|Rhipicephalus        ------------WVAWVAFNTLLHSAWVSCL------LLCQLYQMVWLAMTTNERMNC--
G3SEE3_GORGO|Gorilla              WTYITQIATCSPWMFWMFLNSVFHFMWVAVL------LMCQMYQISCLGITTNERMNA--
H2M9Y0_ORYLA|Oryzias              WLYLTQIASCSPWIFWMFLNSIFHFMWVAVL------IMCQLYQIAALGITTNERMNA--
A7T1Q5_NEMVE|Nematostella         EYSITIRHVVQ-FLLVNFPAIFTLFMVVLIFGIFLTLFTIFHFYLLLTNQTTNELFK---
C3Y8Y5_BRAFL|Branchiostoma        PQPMDLRTLYL-YLFMQHPRMIFLLVSLSLLTVLLVGFTLYHLYLTLNNVTTNELYKK--
F6UP47_XENTR|Xenopus              EQMVNIAFIIQ-HLFLTFPRIVFTLGFLGILVLLLGGYSSFLLYLCLSNQTTNEWHKQ--
F1QAM1_DANRE|Danio                QQPAGPLFIIQ-HLFLTFPRIVFMLGFLVFVFFLLAGYCLFHFYLVLVNQTSNEWFKA--
G3P3E7_GASAC|Gasterosteus         QQPAGPLFVAQ-HLFLTFPRIVFMLGFLVFVFLLLAGYALFHFYLALVNQTSNEWYKS--
I3KUW6_ORENI|Oreochromis          RQPAGFLFVVQ-HLFLTFPRIIFMLGFLLFVFFLLAGYTMFHSFLAVVNQTSNEWYKS--
H2V266_TAKRU|Takifugu             KQQAGPLFVIQ-HLFLTFPRIVFMLGFLVFVFLLLAGYALFHTFLAVINQTSNEWYKS--
Q4S4G0_TETNG|Tetraodon            KQPAGPLFVVQ-HLFLTFPRIVFMLGFLVFVVLLLAGYTLFHTFLAVINQTSNEWYKS--
L5JRT7_PTEAL|Pteropus             FQVIDTIFLIQ-HLFLTFPRTVFLLGLVLVLSCLPSGYLCFALYLATTNQTTDQWYRAPN
H3B8Z0_LATCH|Latimeria            QRAVELTFVIQ-HLFLTFPRIVFMLGFLIVLFLLLGGYSCFHVYLILINQTSNEWYKS--
G1TQU5_RABIT|Oryctolagus          LQAVGVFFLVQ-SLFLAFPKIVLLLGFVVVLSILLGGYLCFVLYLAVTNQTTFEWFRW--
E2QWM7_CANFA|Canis                ELRSVFVFILQ-YLFLTFPRIIFMLGFVMMLSFLLGGYLCFILYLAATNQTTNEWHNG--
ZDHC4_MOUSE|Mus                   FQAVDTVFLIQ-HLFLAFPRIVFLLGFVIVLSMLLAGYLCFALYLAATNQTTNEWYKG--
ZDHC4_RAT|Rattus                  FQAVDTGFLIQ-HLFLAFPRIIFLLGFVIVLSLLLAGYLCFALYLAATNQTTNEWYRG--
G3T697_LOXAF|Loxodonta            SQVVDTVFLVQ-YLFLLFPRIVFLLGFLVVLSFLLGGYLCFALYLAATNQTTNEWYRA--
H0V622_CAVPO|Cavia                FQAVNTIFLIQ-YLYLTFPRIVFLLGFVVVLSFLLGGYLCFAVYLAATNQTTNEWTRG--
G5BF44_HETGA|Heterocephalus       FQAVDTVFLIQ-YLFLTFPRIVFLLGFVVVLSFLLGGYLCFAVYLAATNQTTNEWYKG--
H0WGE9_OTOGA|Otolemur             LQIMDTVFLIQ-YLFVTFPRIVFMLGFVLVLSFLLGGYLCLALYLAATNQTTNEWFRG--
F7CZA7_HORSE|Equus                LQVMDTIFLIQ-YLYLTFPRIVFMLGFVMMLSLLLGGYLCFVLYLTATNQTTNEWYRG--
G1PVW3_MYOLU|Myotis               SQVIDTVFLIQ-YLFLTFPRIVFLLGFVLVLSFLLGGFLCFALYLAATNQTTNEWCRG--
ZDHC4_BOVIN|Bos                   LQVVDTVFLVQ-YLFLTFPRIVFLVGFVVVLSFLLGGYLCFCLYLAATNQTTNEWYKG--
D2H4A4_AILME|Ailuropoda           FQVIDIVFLIQ-YLFLTFPRIVFMLGFVAMLSFLLGGYLCFTLYLASTNQTTNEWYRG--
G9KYT7_MUSPF|Mustela              FQVVDIVFLIQ-YLFVTFPRIVFMLGFVVMLSLLLGGYLCFALYLAATNQTTNEWYRG--
I3MHN2_SPETR|Spermophilus         SQAVDTAFLIQ-YLFLTFPRIVFLLGFVMVLSFLLGGYLCFALYLAATNQTTNEWYKG--
F6Z4M3_CALJA|Callithrix           LHIMDTVFLIQ-YLFLTFPRIVFMLGFVVVLSFLLGGYLCFAVYLAATNQTTNEWHRG--
G7P086_MACFA|Macaca               LHVMDTVFLIQ-YLFLTFPRIVFMLGFVVVLSFLLGGYLCFALYLAATNQTTNEWYRG--
F6RN23_MACMU|Macaca               LHVMDTVFLIQ-YLFLTFPRIVFMLGFVVVLSFLLGGYLCFALYLAATNQTTNEWYRG--
H2PLG1_PONAB|Pongo                LHVMDTVFLIQ-YLFLTFPRIVFMLGFVVVLSFLLGGYLCFALYLAATNQTTNEWYRG--
ZDHC4_HUMAN|Homo                  LHVMDTVFLIQ-YLFLTFPRIVFMLGFVVVLSFLLGGYLLFVLYLAATNQTTNEWYRG--
G1S0D5_NOMLE|Nomascus             LHVMDTVFLIQ-YLFLTFPRIVFMLGFVVVLSFLLGGYLCFALYLAATNQTTNEWYRG--
H2QU60_PANTR|Pan                  LRVMDTVFLIQ-YLFLTFPRIVFMLGFVVVLSFLLGGYLLFVLYLAATNQTTNEWYRG--
H0ZYN2_TAEGU|Taeniopygia          EQPVEIPVLVQ-HLFLTFPRIVFMLGFVILLTLVLGGYCSFSLYLALTNQTTNEWCKS--
E1C0F2_CHICK|Gallus               EHAVEIPFLVQ-HLFL--------------------------------------------
G1N3D2_MELGA|Meleagris            EHAVEIFFLVQ-HLFLTFPRIVFMLGFVILLTLILGAYFCFNLYLALTNQTFNEWYKF--
K7FM17_PELSI|Pelodiscus           EHAIDILFLIQ-HLFLTFPRIVFMLGFVVVLSLVLGAYCCFSLYLALTNQTSNEWYKS--
F7F2T2_ORNAN|Ornithorhynchus      EKAVDVVFLIQ-HLFLTFPRIVFMLGFVIVLCLLLGGYFCFSLYLAVTNQTTNEWYKS--
F7BGJ5_MONDO|Monodelphis          EQPVDIAFLIQ-YLFLTFPRIIFMLGFIIVLCVLLGGYVCFTLYLAVTNQTSNEWYKS--
G3VIW1_SARHA|Sarcophilus          EQPVDIAFLIQ-YLFLTFPRIVFMLGFVIVLCLLLGGYVCFTLYLAVTNQTSNEWYKS--
                                               :                                              

Q7PZ51_ANOGA|Anopheles            -------------------GRYRHF---QAKGGKS-----------------PFNRGPVK
L7M222_9ACAR|Rhipicephalus        -------------------NRYPHFRRASSGRVIS-----------------PFNMGPLK
G3SEE3_GORGO|Gorilla              -------------------RRYKHFKV-TTTSIES-----------------PFNHGCVR
H2M9Y0_ORYLA|Oryzias              -------------------RRYKHFKV-TATSIES-----------------PFNHGCFR
A7T1Q5_NEMVE|Nematostella         ------------------------------------------------------------
C3Y8Y5_BRAFL|Branchiostoma        ----------------------------------------------------P-------
F6UP47_XENTR|Xenopus              ----------------------------KGRSLAL-------------------------
F1QAM1_DANRE|Danio                -------------------KGHNCQ---HCHPYSG-----------------H---NCRT
G3P3E7_GASAC|Gasterosteus         -------------------RGYTCQ---HCHPDAT-----------------ADRLRGPA
I3KUW6_ORENI|Oreochromis          -------------------RGYVCQ---HCHPSTV-----------------ADILCSPV
H2V266_TAKRU|Takifugu             -------------------RGYVCQ---HCHPATA-----------------D-RLCNPA
Q4S4G0_TETNG|Tetraodon            -------------------RGYVCQ---HCRPAT------------------ADRLCNPA
L5JRT7_PTEAL|Pteropus             QMKAKEGRNVYSSSRYDDYDRYRRS---RSRSYERRRSRSRSFDYNYRRSYSPRNSRPTG
H3B8Z0_LATCH|Latimeria            -------------------RSYSYQQSMQCQQFSE-----------------G----YRH
G1TQU5_RABIT|Oryctolagus          -------------------DWARRQ---RCPLVAQ-----------------P-------
E2QWM7_CANFA|Canis                -------------------DRAWCH---HCRHVAR-----------------P----LSA
ZDHC4_MOUSE|Mus                   -------------------DWAWCQ---RWPLVAW-----------------S----PSA
ZDHC4_RAT|Rattus                  -------------------DWAWCQ---HWPLVAW-----------------S----PSA
G3T697_LOXAF|Loxodonta            -------------------GRVLCQ---HCRHEAQ-----------------P----PPT
H0V622_CAVPO|Cavia                -------------------DWAWCQ---HCPLVAR-----------------P----SSA
G5BF44_HETGA|Heterocephalus       -------------------DWARFQ---HCPLVAR-----------------P----SLA
H0WGE9_OTOGA|Otolemur             -------------------AWDWCQ---HCPLVAG-----------------A----PSA
F7CZA7_HORSE|Equus                -------------------HQG-C-----CPHVAR-----------------P----PSA
G1PVW3_MYOLU|Myotis               -------------------DRAWCQ---HCPQGAG-----------------A----PSV
ZDHC4_BOVIN|Bos                   -------------------DRAWCQ---HCPHVAR-----------------P----PAA
D2H4A4_AILME|Ailuropoda           -------------------DRTWCQ---HCPHAAR-----------------P----PSA
G9KYT7_MUSPF|Mustela              -------------------DRAWCQ---HCPHAAR-----------------P----PSA
I3MHN2_SPETR|Spermophilus         -------------------DWAWCQ---LCPVVVR-----------------P----PSA
F6Z4M3_CALJA|Callithrix           -------------------DRAWCW---RCPLVAW-----------------C----PSA
G7P086_MACFA|Macaca               -------------------DWAWCQ---RCPLVAW-----------------P----PSA
F6RN23_MACMU|Macaca               -------------------DWAWCQ---RCPLVAW-----------------P----PSA
H2PLG1_PONAB|Pongo                -------------------DWAWCQ---HCPLVAR-----------------P----PSA
ZDHC4_HUMAN|Homo                  -------------------DWAWCQ---RCPLVAW-----------------P----PSA
G1S0D5_NOMLE|Nomascus             -------------------DWAWCQ---RCPLVAW-----------------P----PSA
H2QU60_PANTR|Pan                  -------------------DWAWCQ---RCPLVAW-----------------P----PSA
H0ZYN2_TAEGU|Taeniopygia          -------------------RRFG-----GSPHLPS-----------------Q----PHD
E1C0F2_CHICK|Gallus               ------------------------------------------------------------
G1N3D2_MELGA|Meleagris            -------------------RRYR-----HSHHLTS-----------------Q----PCD
K7FM17_PELSI|Pelodiscus           -------------------RRYECS---CCRALE-----------------------PHD
F7F2T2_ORNAN|Ornithorhynchus      -------------------SRTKGH---PCQ-TSE-----------------P----RLE
F7BGJ5_MONDO|Monodelphis          -------------------SRAKCH---RC-HNSD-----------------P----VQE
G3VIW1_SARHA|Sarcophilus          -------------------SRAKCH---RCHNSD------------------P----VKE
                                                                                              

Q7PZ51_ANOGA|Anopheles            NLFDFLECSCFGLVQPQRTDW---------------------------------------
L7M222_9ACAR|Rhipicephalus        NLADFCEWRCLGANP---RDW---------------------------------------
G3SEE3_GORGO|Gorilla              NIIDFFEFRCCGLFRPVIVDW---------------------------------------
H2M9Y0_ORYLA|Oryzias              NLVDFFEIRCCGLIRPVTVDW---------------------------------------
A7T1Q5_NEMVE|Nematostella         ------------------------------------------------------------
C3Y8Y5_BRAFL|Branchiostoma        ------------------------------------------------------------
F6UP47_XENTR|Xenopus              ---DSRKGYSKGLWG----NI---------------------------------------
F1QAM1_DANRE|Danio                SYNPFRGFYHRGILK----NI---------------------------------------
G3P3E7_GASAC|Gasterosteus         PDHFKRNHYSRGLLR----NL---------------------------------------
I3KUW6_ORENI|Oreochromis          PDHSKRYYYSRGVLR----NL---------------------------------------
H2V266_TAKRU|Takifugu             PDHSKRYYYSRGLLR----NL---------------------------------------
Q4S4G0_TETNG|Tetraodon            PEHSKRHYYSRGLLR----NL---------------------------------------
L5JRT7_PTEAL|Pteropus             RPRRSRSHSDNDRFKHRNRSFSRSKSNSRSRSKSQPKKEMKAKSRSRSASHTKTRGTSKT
H3B8Z0_LATCH|Latimeria            APH-KKNTYSKGLLK----NI---------------------------------------
G1TQU5_RABIT|Oryctolagus          --RVYRNIHRHGLGS----NL---------------------------------------
E2QWM7_CANFA|Canis                DTQVNRNIHSHGLWS----NL---------------------------------------
ZDHC4_MOUSE|Mus                   EPRIHQNIHSHGFRS----NL---------------------------------------
ZDHC4_RAT|Rattus                  EPQIHQNIYSHGLWS----NL---------------------------------------
G3T697_LOXAF|Loxodonta            EPRVFQNIYSHGAWS----NL---------------------------------------
H0V622_CAVPO|Cavia                ESQSNQNIYSQGLWR----NL---------------------------------------
G5BF44_HETGA|Heterocephalus       ESQIYQNIYSHGLWS----NL---------------------------------------
H0WGE9_OTOGA|Otolemur             KHQVYQNIYSRGLWS----NF---------------------------------------
F7CZA7_HORSE|Equus                HPQVYQNIHSHGLWS----NL---------------------------------------
G1PVW3_MYOLU|Myotis               EPRVHRNIHSHGLWS----NL---------------------------------------
ZDHC4_BOVIN|Bos                   EPQAYRNIHSHGLWS----NL---------------------------------------
D2H4A4_AILME|Ailuropoda           EPQVHRNIHSRGLWS----NL---------------------------------------
G9KYT7_MUSPF|Mustela              EPQVYRNIHSHGLWS----NL---------------------------------------
I3MHN2_SPETR|Spermophilus         EPQIYQNIHSHGLWS----NL---------------------------------------
F6Z4M3_CALJA|Callithrix           EPQIHQNIHSHGLWS----NL---------------------------------------
G7P086_MACFA|Macaca               EPQVHRNIHSHGLRS----NL---------------------------------------
F6RN23_MACMU|Macaca               EPQVHRNIHSHGLRS----NL---------------------------------------
H2PLG1_PONAB|Pongo                EPQVHRNIHSHGLRS----NL---------------------------------------
ZDHC4_HUMAN|Homo                  EPQVHRNIHSHGLRS----NL---------------------------------------
G1S0D5_NOMLE|Nomascus             EPQVHQNIHSHGLRS----NL---------------------------------------
H2QU60_PANTR|Pan                  EPQVHRNIHSHGLRS----NL---------------------------------------
H0ZYN2_TAEGU|Taeniopygia          RPLVYKNIYSKGIWR----NL---------------------------------------
E1C0F2_CHICK|Gallus               ------------------------------------------------------------
G1N3D2_MELGA|Meleagris            RKAVYKNAYTKGVWM----NL---------------------------------------
K7FM17_PELSI|Pelodiscus           RHIVYRNVYSQGVWV----NL---------------------------------------
F7F2T2_ORNAN|Ornithorhynchus      KPHVSRNIYSKDFWS----NL---------------------------------------
F7BGJ5_MONDO|Monodelphis          NPSAYRNIYTKGAWA----NL---------------------------------------
G3VIW1_SARHA|Sarcophilus          KPSAYRNIYAKSAWT----NL---------------------------------------
                                                                                              

Q7PZ51_ANOGA|Anopheles            -MQFFEFDKHVEHEPLLRPDNFQYV--------------------------
L7M222_9ACAR|Rhipicephalus        -RHVYNANDDDE----EKQTLLHYV--------------------------
G3SEE3_GORGO|Gorilla              -TRQYTIEYDQI----SGSGYQLV---------------------------
H2M9Y0_ORYLA|Oryzias              -TTQYTIEYDQT----SGSGYQLV---------------------------
A7T1Q5_NEMVE|Nematostella         ---------------------------------------------------
C3Y8Y5_BRAFL|Branchiostoma        ----------------ARQQQH-----------------------------
F6UP47_XENTR|Xenopus              -QEIFQPPI-CH----KKDR-------------------------------
F1QAM1_DANRE|Danio                -GEIFWPLRPVQ----KKEN-------------------------------
G3P3E7_GASAC|Gasterosteus         -EEILFPPKPVQ----KKLS-------------------------------
I3KUW6_ORENI|Oreochromis          -GEIFFPPQPVQ----KKDN-------------------------------
H2V266_TAKRU|Takifugu             -GEIFFPPQPTQ----KKDK-------------------------------
Q4S4G0_TETNG|Tetraodon            -GEIFFPLLPTQ----KKDK-------------------------------
L5JRT7_PTEAL|Pteropus             DSKTHYKSGSRYEKESRKKEPPRSKSQSRSQSRSRSKSRSRSWTSPKSSGH
H3B8Z0_LATCH|Latimeria            -LEIIKPLAGEE----KNKKDD-----------------------------
G1TQU5_RABIT|Oryctolagus          -REIFLPVVPDC----EGKKK------------------------------
E2QWM7_CANFA|Canis                -GEVFLPATAPY----ERKK-------------------------------
ZDHC4_MOUSE|Mus                   -REIFLPATPSY----KKKEK------------------------------
ZDHC4_RAT|Rattus                  -QEVFIPATPSY----KKKKR------------------------------
G3T697_LOXAF|Loxodonta            -REIFLPAAPYK----KKKK-------------------------------
H0V622_CAVPO|Cavia                -QEIFLPAGPSY----ERKKK------------------------------
G5BF44_HETGA|Heterocephalus       -QEIFLPASPCY----ERKKK------------------------------
H0WGE9_OTOGA|Otolemur             -REIFLPVFLHY----ETKKK------------------------------
F7CZA7_HORSE|Equus                -REIFLPAAVHY----GGKKK------------------------------
G1PVW3_MYOLU|Myotis               -REIFLPAAAHY----ERKKK------------------------------
ZDHC4_BOVIN|Bos                   -REIFLPATACY----ERKEK------------------------------
D2H4A4_AILME|Ailuropoda           -GEIFLPATAHY----ERKK-------------------------------
G9KYT7_MUSPF|Mustela              -REIFLPATAHY----ERKK-------------------------------
I3MHN2_SPETR|Spermophilus         -REIFLPAVPYY----ERKK-------------------------------
F6Z4M3_CALJA|Callithrix           -QEIFLPAFPYH----ERKKQE-----------------------------
G7P086_MACFA|Macaca               -QEIFLPAFPCH----GRKKQE-----------------------------
F6RN23_MACMU|Macaca               -QEIFLPAFPCH----GRKKQE-----------------------------
H2PLG1_PONAB|Pongo                -QEIFLPAFPCH----ERKKQE-----------------------------
ZDHC4_HUMAN|Homo                  -QEIFLPAFPCH----ERKKQE-----------------------------
G1S0D5_NOMLE|Nomascus             -QEIFLPAFPCH----ERKKQE-----------------------------
H2QU60_PANTR|Pan                  -QEIFLPAFPCH----ERKKQE-----------------------------
H0ZYN2_TAEGU|Taeniopygia          -KEIFNPPAVLE----RKKK-------------------------------
E1C0F2_CHICK|Gallus               ---------------------------------------------------
G1N3D2_MELGA|Meleagris            -KEIFKSPAVLE----RKKK-------------------------------
K7FM17_PELSI|Pelodiscus           -KEIFKPTSSEK----KKKT-------------------------------
F7F2T2_ORNAN|Ornithorhynchus      -QEIFKPTVEYE----VKKKF------------------------------
F7BGJ5_MONDO|Monodelphis          -QEIFKPITDCE----KKK--------------------------------
G3VIW1_SARHA|Sarcophilus          -QEIFNPVTYYE----KKK--------------------------------
                                                                                     
