MUSCLE (3.8) multiple sequence alignment


A7S6A3_NEMVE|Nematostella         ------------------------------------------------------------
G1KF61_ANOCA|Anolis               ------------------------------------------------------------
H3AQ09_LATCH|Latimeria            ------------------------------------------------------------
Q0VFI0_XENTR|Xenopus              ------------------------------------------------------------
F7AXP5_MONDO|Monodelphis          ------------------------------------------------------------
F6ZIT6_ORNAN|Ornithorhynchus      ------------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          ------------------------------------------------------------
G5E7C4_LOXAF|Loxodonta            ------------------------------------------------------------
ZDHC2_MOUSE|Mus                   ------------------------------------------------------------
ZDHC2_RAT|Rattus                  ------------------------------------------------------------
G1T7P7_RABIT|Oryctolagus          ------------------------------------------------------------
H0V4C6_CAVPO|Cavia                ------------------------------------------------------------
G3MXF3_BOVIN|Bos                  ------------------------------------------------------------
J9P566_CANFA|Canis                ------------------------------------------------------------
H0WS46_OTOGA|Otolemur             ------------------------------------------------------------
G5B8F0_HETGA|Heterocephalus       ------------------------------------------------------------
I3MD11_SPETR|Spermophilus         ------------------------------------------------------------
F6TF01_CALJA|Callithrix           ------------------------------------------------------------
G7PCM0_MACFA|Macaca               ------------------------------------------------------------
I2CX55_MACMU|Macaca               ------------------------------------------------------------
G1QPY3_NOMLE|Nomascus             ------------------------------------------------------------
G3RL61_GORGO|Gorilla              ------------------------------------------------------------
ZDHC2_HUMAN|Homo                  ------------------------------------------------------------
H2QVS6_PANTR|Pan                  ------------------------------------------------------------
H2PPM5_PONAB|Pongo                ------------------------------------------------------------
F7CAZ8_HORSE|Equus                ------------------------------------------------------------
G1NW00_MYOLU|Myotis               ------------------------------------------------------------
G9KYT2_MUSPF|Mustela              ------------------------------------------------------------
G1M5B0_AILME|Ailuropoda           ------------------------------------------------------------
F1SET7_PIG|Sus                    ------------------------------------------------------------
K7FYZ2_PELSI|Pelodiscus           ------------------------------------------------------------
F1NVH3_CHICK|Gallus               ------------------------------------------------------------
H0ZA87_TAEGU|Taeniopygia          ------------------------------------------------------------
H2S209_TAKRU|Takifugu             ------------------------------------------------------------
Q5BLG4_DANRE|Danio                ------------------------------------------------------------
G3Q3Z4_GASAC|Gasterosteus         ------------------------------------------------------------
I3KM57_ORENI|Oreochromis          ------------------------------------------------------------
H2LTT9_ORYLA|Oryzias              ------------------------------------------------------------
H3CRV3_TETNG|Tetraodon            ------------------------------------------------------------
G1NQF0_MELGA|Meleagris            ------------------------------------------------------------
L5L6V4_PTEAL|Pteropus             MSPHCGGLCLIYPSSESLDNKGGGFTTPQPKEKEWRARCSVISHAKNLGRSRMSRDSGRD
C3XW62_BRAFL|Branchiostoma        ------------------------------------------------------------
L7MB41_9ACAR|Rhipicephalus        ------------------------------------------------------------
G6DE89_DANPL|Danaus               ------------------------------------------------------------
E2A927_CAMFO|Camponotus           ------------------------------------------------------------
K7J025_NASVI|Nasonia              ------------------------------------------------------------
B4KLJ9_DROMO|Drosophila           ------------------------------------------------------------
B4LM13_DROVI|Drosophila           ------------------------------------------------------------
B4J5A2_DROGR|Drosophila           ------------------------------------------------------------
B4GB93_DROPE|Drosophila           ------------------------------------------------------------
B5E0C5_DROPS|Drosophila           ------------------------------------------------------------
B4MQW5_DROWI|Drosophila           ------------------------------------------------------------
B3MD30_DROAN|Drosophila           ------------------------------------------------------------
B3N6S2_DROER|Drosophila           ------------------------------------------------------------
Q7K2V5_DROME|Drosophila           ------------------------------------------------------------
B4NX32_DROYA|Drosophila           ------------------------------------------------------------
Q7Q7Z4_ANOGA|Anopheles            ------------------------------------------------------------
B0WC84_CULQU|Culex                ------------------------------------------------------------
                                                                                              

A7S6A3_NEMVE|Nematostella         ---------------------------MSA-----------------CTVVLACMV----
G1KF61_ANOCA|Anolis               --------------------------------------------------VRRRCQ----
H3AQ09_LATCH|Latimeria            ------------------------SSPQEP-----------------HSKLKKCDI----
Q0VFI0_XENTR|Xenopus              ------------------------MAPSGP-----------------SS-VRRRCR----
F7AXP5_MONDO|Monodelphis          ------------------------------------------------------------
F6ZIT6_ORNAN|Ornithorhynchus      ------------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          --------------------------------DV-------------KGTPNFIC-----
G5E7C4_LOXAF|Loxodonta            ------------------------------------------------------CG----
ZDHC2_MOUSE|Mus                   ------------------------MAPSG------------------SGGVRRRCR----
ZDHC2_RAT|Rattus                  ------------------------MAPSGP-----------------GG-VRRRCR----
G1T7P7_RABIT|Oryctolagus          ------------------------------------------------------------
H0V4C6_CAVPO|Cavia                ------------------------------------------------------------
G3MXF3_BOVIN|Bos                  ------------------------SSPSET-----------------AVSRAPRCT----
J9P566_CANFA|Canis                ------------------------PGALG------------------PGSVRRRCR----
H0WS46_OTOGA|Otolemur             ------------------------------------------------------------
G5B8F0_HETGA|Heterocephalus       ------------------------------------------------------------
I3MD11_SPETR|Spermophilus         ------------------------MAPSG------------------PGSIRRRCR----
F6TF01_CALJA|Callithrix           ------------------------MAPSGP-----------------GSSARLQCP----
G7PCM0_MACFA|Macaca               ------------------------------------------------------------
I2CX55_MACMU|Macaca               ------------------------MAPSGP-----------------GSSARRRCR----
G1QPY3_NOMLE|Nomascus             ------------------------MAPSGP-----------------GSSARRRCR----
G3RL61_GORGO|Gorilla              ------------------------MAPSGP-----------------GSSARRRCR----
ZDHC2_HUMAN|Homo                  ------------------------MAPSGP-----------------GSSARRRCR----
H2QVS6_PANTR|Pan                  ------------------------MAPSGP-----------------GSSARRRCR----
H2PPM5_PONAB|Pongo                ------------------------MAPSGP-----------------GSSARRRCR----
F7CAZ8_HORSE|Equus                ------------------------------------------------------------
G1NW00_MYOLU|Myotis               ------------------------------TT---------------VGSPLRKEV----
G9KYT2_MUSPF|Mustela              ------------------------------------------------------------
G1M5B0_AILME|Ailuropoda           -------------------------------------------------------R----
F1SET7_PIG|Sus                    ------------------------------------------------------------
K7FYZ2_PELSI|Pelodiscus           ------------------------------------------------------------
F1NVH3_CHICK|Gallus               ------------------------AAPSAPAAGAAGG----------WGGVRRRCQ----
H0ZA87_TAEGU|Taeniopygia          ------------------------------------------------------------
H2S209_TAKRU|Takifugu             ------------------------MAPTG------------------SRTIRNGCE----
Q5BLG4_DANRE|Danio                --------------------------MAP------------------SGSRSFDCW----
G3Q3Z4_GASAC|Gasterosteus         ----------------------------P------------------HKHLILLCQ----
I3KM57_ORENI|Oreochromis          ------------------------MAPSG------------------SRSIKRGCQ----
H2LTT9_ORYLA|Oryzias              --------------------------RKMA-----------------PTHVLRCCQ----
H3CRV3_TETNG|Tetraodon            ----------------------------MA-----------------PVHVLRCCQ----
G1NQF0_MELGA|Meleagris            ------------------------------------------------------------
L5L6V4_PTEAL|Pteropus             GRDAAGCWAAVATVNECIPSSELRVAKLTSLCPAPLHSRLLRDARQDKSQRRWACKGAGT
C3XW62_BRAFL|Branchiostoma        -----------------------------M-----------------SNPVLNFCI----
L7MB41_9ACAR|Rhipicephalus        -------------------------MPPGLFKM--------------QGTVCSVCV----
G6DE89_DANPL|Danaus               ----------------------------------------------------MWCW----
E2A927_CAMFO|Camponotus           ---------------------------MGK-----------------QNGSCWWCV----
K7J025_NASVI|Nasonia              ---------------------------MDN-----------------RGSGCWWCV----
B4KLJ9_DROMO|Drosophila           ----------------------MGNDDNRR-----------------RKSPCNCCL----
B4LM13_DROVI|Drosophila           ----------------------MGNEDNRR-----------------RKTPCGCCM----
B4J5A2_DROGR|Drosophila           ---------------------MGNEDIHRR-----------------RQTPCGCCM----
B4GB93_DROPE|Drosophila           ----------------------MGNDDHRR-----------------RKTPCGFCM----
B5E0C5_DROPS|Drosophila           ----------------------MGNDDHRR-----------------RKTPCGFCM----
B4MQW5_DROWI|Drosophila           ----------------------MGNEDNRR-----------------RKTPCGFCM----
B3MD30_DROAN|Drosophila           ----------------------MGNDDHRR-----------------RKTPCGFCM----
B3N6S2_DROER|Drosophila           ----------------------MGNDDHRR-----------------RKTPCGFCM----
Q7K2V5_DROME|Drosophila           ----------------------MGNDDHRR-----------------RKTPCGFCM----
B4NX32_DROYA|Drosophila           ----------------------MGNDDHRR-----------------RKTPCGFCM----
Q7Q7Z4_ANOGA|Anopheles            -------------------------MPHGQSYDYHRTTFDGE-----RNERCGCCV----
B0WC84_CULQU|Culex                -----MSVAGNYDHYHRNSSHSSGSSGGGP-----------------RAERCACCV----
                                                                                              

A7S6A3_NEMVE|Nematostella         RGFQWIPVIF----------------INSVIVWSYYAYVF--------------------
G1KF61_ANOCA|Anolis               WLLSWVPVLF----------------IASILAWSYYAYVA--------------------
H3AQ09_LATCH|Latimeria            LITYCMFTIQ----------------LTLLVCSRAYTSHC--------------------
Q0VFI0_XENTR|Xenopus              RCLYWIPVLF----------------ISIIVCWSYYAYVI--------------------
F7AXP5_MONDO|Monodelphis          ------------------------------------------------------------
F6ZIT6_ORNAN|Ornithorhynchus      ------------------------------------------------------------
G3WFR2_SARHA|Sarcophilus          RILWRSPTVY----------------KGNRLGWFVTVPST--------------------
G5E7C4_LOXAF|Loxodonta            RVLYWIRCLH-----------------RPPAGWSYYAYAI--------------------
ZDHC2_MOUSE|Mus                   RVLYWIPVVF----------------ISLLLGWSYYAYAI--------------------
ZDHC2_RAT|Rattus                  RVLYWIPVVF----------------ISLLLGWSYYAYAI--------------------
G1T7P7_RABIT|Oryctolagus          -------SLF--------------------------------------------------
H0V4C6_CAVPO|Cavia                ------------------------------------ASFL--------------------
G3MXF3_BOVIN|Bos                  KFSYWRAKPC----------------VCYKLHITYCLSLF--------------------
J9P566_CANFA|Canis                RVLYWVPGVF----------------ISLLLGRSHYAYAV--------------------
H0WS46_OTOGA|Otolemur             ------------------------------------------------------------
G5B8F0_HETGA|Heterocephalus       ----WIPVVF----------------ISLLLGWSYYAYAI--------------------
I3MD11_SPETR|Spermophilus         RVLYWIPVVF----------------ISLLLGWSYYAYAV--------------------
F6TF01_CALJA|Callithrix           RVLYWIPGV-----------------ISLMLGWSYYAYAI--------------------
G7PCM0_MACFA|Macaca               ------------------------------------------------------------
I2CX55_MACMU|Macaca               RVLYWIPVVF----------------ITLLLGWSYYAYAI--------------------
G1QPY3_NOMLE|Nomascus             RVLYWIPVVF----------------ITLLLGWSYYAYAI--------------------
G3RL61_GORGO|Gorilla              RVLYWIPVVF----------------ITLLLGWSYYAYAI--------------------
ZDHC2_HUMAN|Homo                  RVLYWIPVVF----------------ITLLLGWSYYAYAI--------------------
H2QVS6_PANTR|Pan                  RVLYWIPVVF----------------ITLLLGWSYYAYAI--------------------
H2PPM5_PONAB|Pongo                RVLYWIPVVF----------------ITLLLGWSYYAYAI--------------------
F7CAZ8_HORSE|Equus                ------------------------------------------------------------
G1NW00_MYOLU|Myotis               GLIRKSPPFF-----------------SLLMKYVFFLTLS--------------------
G9KYT2_MUSPF|Mustela              ------------------------------------------------------------
G1M5B0_AILME|Ailuropoda           RVLYWIPVVF----------------ISLLLGWSYYAYAX--------------------
F1SET7_PIG|Sus                    ------------------------------------------------------------
K7FYZ2_PELSI|Pelodiscus           ------------------------------------------------------------
F1NVH3_CHICK|Gallus               RLLYWVPVLF----------------ISSILCWSYYAYVT--------------------
H0ZA87_TAEGU|Taeniopygia          ------------------------------------------------------------
H2S209_TAKRU|Takifugu             RVLYWIPVLF----------------IVLIVAWSYYAYVL--------------------
Q5BLG4_DANRE|Danio                RVLYWIPVLF----------------ISLIVAWSYYAYVV--------------------
G3Q3Z4_GASAC|Gasterosteus         T----LGLLL----------------LERTHAHGCWLHAL--------------------
I3KM57_ORENI|Oreochromis          RVLYWIPVLF----------------IALIVAWSYYAYVL--------------------
H2LTT9_ORYLA|Oryzias              RGLSWIPVVF----------------IALVVCWSYYAYVV--------------------
H3CRV3_TETNG|Tetraodon            RGLAWIPVIF----------------IALVVCWSYYAYVV--------------------
G1NQF0_MELGA|Meleagris            -------MLF----------------LVVVFCFAFSLFIE--------------------
L5L6V4_PTEAL|Pteropus             RPAAWDPASVPSRSLTPAAVGTSSPRVLLLLFWHHQNQLVVSSWRTGTSWPAPAPSRTRL
C3XW62_BRAFL|Branchiostoma        RLMKWLPVVF----------------ITLIVLWSYYAYVV--------------------
L7MB41_9ACAR|Rhipicephalus        RVFKWCPVLF----------------ITTIVAWSYYAYVI--------------------
G6DE89_DANPL|Danaus               RAFKWLPVLL----------------IVSIVTWSYYAYVI--------------------
E2A927_CAMFO|Camponotus           KAVKWIPVIF----------------ILTIVAWSYYAYVV--------------------
K7J025_NASVI|Nasonia              KAVKWIPVVF----------------ILSIVFWSYYAYVV--------------------
B4KLJ9_DROMO|Drosophila           SAFKWIPVLF----------------IFGVIAWSYYAYVV--------------------
B4LM13_DROVI|Drosophila           SVFKWIPVLF----------------IFAVIGWSYYAYVV--------------------
B4J5A2_DROGR|Drosophila           SVFKWIPVLF----------------IFAVIGWSYYAYVV--------------------
B4GB93_DROPE|Drosophila           AVFKWIPVVF----------------ITAVIAWSYYAYVV--------------------
B5E0C5_DROPS|Drosophila           AVFKWIPVVF----------------ITAVIAWSYYAYVV--------------------
B4MQW5_DROWI|Drosophila           SVFKWIPVLF----------------ITSVICWSYYAYVV--------------------
B3MD30_DROAN|Drosophila           AVFKWIPVLF----------------ISAVIAWSYYAYVV--------------------
B3N6S2_DROER|Drosophila           AVFKWIPVLF----------------ITAVIAWSYYAYVV--------------------
Q7K2V5_DROME|Drosophila           AVFKWIPVLF----------------ITAVIAWSYYAYVV--------------------
B4NX32_DROYA|Drosophila           AVFKWIPVLF----------------ITAVIAWSYYAYVV--------------------
Q7Q7Z4_ANOGA|Anopheles            RTMKWFPVLF----------------IASVIGWSYYAFVI--------------------
B0WC84_CULQU|Culex                RTMKWFPVLF----------------IVAVIAWSYYAFVV--------------------
                                                                                              

A7S6A3_NEMVE|Nematostella         ------------------------------------------------V-----LCFENV
G1KF61_ANOCA|Anolis               ------------------------------------------------Q-----LCIRES
H3AQ09_LATCH|Latimeria            ------------------------------------------------E-----LPIKSM
Q0VFI0_XENTR|Xenopus              ------------------------------------------------Q-----LCIVTM
F7AXP5_MONDO|Monodelphis          ---------------------------------------------------------VSM
F6ZIT6_ORNAN|Ornithorhynchus      ---------------------------------------------------------VSM
G3WFR2_SARHA|Sarcophilus          ------------------------------------------------H-----LCAVSM
G5E7C4_LOXAF|Loxodonta            ------------------------------------------------Q-----LCVGEC
ZDHC2_MOUSE|Mus                   ------------------------------------------------Q-----LCIVSM
ZDHC2_RAT|Rattus                  ------------------------------------------------Q-----LCIVSM
G1T7P7_RABIT|Oryctolagus          ------------------------------------------------------ISIVSM
H0V4C6_CAVPO|Cavia                ------------------------------------------------S-----ISLVSM
G3MXF3_BOVIN|Bos                  ------------------------------------------------S-----ISIVSM
J9P566_CANFA|Canis                ------------------------------------------------Q-----LRIVSM
H0WS46_OTOGA|Otolemur             --------------------------------------------------------IVSM
G5B8F0_HETGA|Heterocephalus       ------------------------------------------------Q-----LCIVSM
I3MD11_SPETR|Spermophilus         ------------------------------------------------Q-----LCIVSM
F6TF01_CALJA|Callithrix           ------------------------------------------------X-----LFIVSM
G7PCM0_MACFA|Macaca               ---------------------------------------------------------VSM
I2CX55_MACMU|Macaca               ------------------------------------------------Q-----LCIVSM
G1QPY3_NOMLE|Nomascus             ------------------------------------------------Q-----LCIVSM
G3RL61_GORGO|Gorilla              ------------------------------------------------Q-----LCIVSM
ZDHC2_HUMAN|Homo                  ------------------------------------------------Q-----LCIVSM
H2QVS6_PANTR|Pan                  ------------------------------------------------Q-----LCIVSM
H2PPM5_PONAB|Pongo                ------------------------------------------------Q-----LCIVSM
F7CAZ8_HORSE|Equus                --------------------------------------------------------VVSM
G1NW00_MYOLU|Myotis               ------------------------------------------------------LLLVSM
G9KYT2_MUSPF|Mustela              -----------------------------------------------------------M
G1M5B0_AILME|Ailuropoda           ------------------------------------------------F-----ISVVSM
F1SET7_PIG|Sus                    ------------------------------------------------------LSVVSM
K7FYZ2_PELSI|Pelodiscus           -----------------------------------------------------------M
F1NVH3_CHICK|Gallus               ------------------------------------------------Q-----LCLLTM
H0ZA87_TAEGU|Taeniopygia          ---------------------------------------------------------VTM
H2S209_TAKRU|Takifugu             ------------------------------------------------Q-----LCVGEI
Q5BLG4_DANRE|Danio                ------------------------------------------------Q-----LCIETI
G3Q3Z4_GASAC|Gasterosteus         ------------------------------------------------RLGPLFLCFESI
I3KM57_ORENI|Oreochromis          ------------------------------------------------Q-----LCIESI
H2LTT9_ORYLA|Oryzias              ------------------------------------------------E-----LCIFTI
H3CRV3_TETNG|Tetraodon            ------------------------------------------------E-----LCVFTI
G1NQF0_MELGA|Meleagris            ------------------------------------------------S-----RSSFLL
L5L6V4_PTEAL|Pteropus             PPPPCPELRILPPPTSSPLAGPWAASPPAAQVRSLMFLSPLTPVKPVPHIDSSSVEILNV
C3XW62_BRAFL|Branchiostoma        ------------------------------------------------E-----MCVFAI
L7MB41_9ACAR|Rhipicephalus        ------------------------------------------------Q-----LCLFTI
G6DE89_DANPL|Danaus               ------------------------------------------------Q-----LCIFTI
E2A927_CAMFO|Camponotus           ------------------------------------------------Q-----LCYYTI
K7J025_NASVI|Nasonia              ------------------------------------------------P-----LCYETI
B4KLJ9_DROMO|Drosophila           ------------------------------------------------E-----LCVLKT
B4LM13_DROVI|Drosophila           ------------------------------------------------E-----LCVLKT
B4J5A2_DROGR|Drosophila           ------------------------------------------------E-----LCVLNT
B4GB93_DROPE|Drosophila           ------------------------------------------------E-----LCIRNS
B5E0C5_DROPS|Drosophila           ------------------------------------------------E-----LCIRNS
B4MQW5_DROWI|Drosophila           ------------------------------------------------E-----LCIRNV
B3MD30_DROAN|Drosophila           ------------------------------------------------E-----LCIHNS
B3N6S2_DROER|Drosophila           ------------------------------------------------E-----LCIRNS
Q7K2V5_DROME|Drosophila           ------------------------------------------------E-----LCIRNS
B4NX32_DROYA|Drosophila           ------------------------------------------------E-----LCIRNS
Q7Q7Z4_ANOGA|Anopheles            ------------------------------------------------Q-----LSFFTV
B0WC84_CULQU|Culex                ------------------------------------------------Q-----LTFFTV
                                                                                              

A7S6A3_NEMVE|Nematostella         Q----------SNIEKAAYLVAFHPFFFMLIISYWRTILADQGIVPSQFALSKTDKDLVE
G1KF61_ANOCA|Anolis               C----------GWGRVVMCLITYHLFFMMFLWSYWKTIFTLPMNPSKEFHLTYAHKEFLE
H3AQ09_LATCH|Latimeria            T----------NVGEKVVCLICYHMFFIMFVWSYWKSIFTMPMNPSKEFHLSYADREQLE
Q0VFI0_XENTR|Xenopus              D----------NIAEKILCLIAYHFFLLHFVWSYWKTIFTLPMNPAKEFHLSYSDKELLE
F7AXP5_MONDO|Monodelphis          E----------NIGEQVVCLTVYHFLFAMFIWSYWKTIFTLPMNPSKEFHLSYAEKELLE
F6ZIT6_ORNAN|Ornithorhynchus      G----------NVGEKVVCLIAYHLFFMLFVWSYWKTIFTLPMNPSKEFHLSYADKELLE
G3WFR2_SARHA|Sarcophilus          E----------NIGEQVVCLIVYHLLFAMFVWSYWKTIFTMPMNPSKEFHLSYAEKELLE
G5E7C4_LOXAF|Loxodonta            A----------PPTRPVLCLIAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
ZDHC2_MOUSE|Mus                   E----------NIGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
ZDHC2_RAT|Rattus                  E----------NIGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
G1T7P7_RABIT|Oryctolagus          E----------NIGEQVVCLLAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
H0V4C6_CAVPO|Cavia                E----------NIGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
G3MXF3_BOVIN|Bos                  E----------NIGEQVVCLIAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
J9P566_CANFA|Canis                E----------NVGEQVVCLTAYHLLFAMFVWSYWKTIFTSPMNPSREFHLSYAEKELLE
H0WS46_OTOGA|Otolemur             E----------NIGEQAVCLLAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
G5B8F0_HETGA|Heterocephalus       E----------NIGEQVVCLMAYHLLFAMFVWSYWKTIFTLPVNPSKEFHLSYAEKELLE
I3MD11_SPETR|Spermophilus         E----------NIGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKDLLE
F6TF01_CALJA|Callithrix           E----------NTGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYSEKELLE
G7PCM0_MACFA|Macaca               E----------NTGEQVVCLMAYHLLFGMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
I2CX55_MACMU|Macaca               E----------NTGEQVVCLMAYHLLFGMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
G1QPY3_NOMLE|Nomascus             E----------NTGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKDLLE
G3RL61_GORGO|Gorilla              E----------NTGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKDLLE
ZDHC2_HUMAN|Homo                  E----------NTGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKDLLE
H2QVS6_PANTR|Pan                  E----------NTGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKDLLE
H2PPM5_PONAB|Pongo                E----------NTGEQVVCLMAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKDLLE
F7CAZ8_HORSE|Equus                E----------DIGEQVVCLIAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
G1NW00_MYOLU|Myotis               E----------NIGEQVVCLIAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
G9KYT2_MUSPF|Mustela              E----------NVGEQVVCLIAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
G1M5B0_AILME|Ailuropoda           E----------NVGEQVVCLIAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
F1SET7_PIG|Sus                    E----------NIGEQVVCLIAYHLLFAMFVWSYWKTIFTLPMNPSKEFHLSYAEKELLE
K7FYZ2_PELSI|Pelodiscus           A----------SIGEKAVCLIAYHLFFMLFVWSYWKTIFTLPMNPSKEFHLSYADKELLE
F1NVH3_CHICK|Gallus               T----------NIGEKVVCLVAYHIFFMLFVWSYWKTIFTLPMNPSKEFHLSYSDKESLE
H0ZA87_TAEGU|Taeniopygia          T----------NIGEKVVCLVAYHIFFMLFVWSYWKTIFTLPMNPSKEFHLSYSDKESLE
H2S209_TAKRU|Takifugu             K----------SNQSVFVYLLVYHLIFIMFIWTYWQTIFTKPMTPLKEFHLSHADKELLQ
Q5BLG4_DANRE|Danio                E----------NMGEKTVYLLIYHLLFLMFVWSYWQTIYSKPMNPLKEFHLSHVDKELLE
G3Q3Z4_GASAC|Gasterosteus         E----------HTGEKVIYLLVYHVVFIMFVWAYWQTIFTRPMNPLKEFHLSYSDKELLE
I3KM57_ORENI|Oreochromis          E----------DTGEKVVYLLVYHVIFIMFVWAYWQTIFTKPMNPLKEFHLSHSDKELLE
H2LTT9_ORYLA|Oryzias              P----------SRAEQIFYLIFFHLSFIMFVWSYWKTIFTKPANPSKEFCLPKAEKECYE
H3CRV3_TETNG|Tetraodon            T----------SIGEQVVYLFFFHLSFIMFVWSYWKTIFTKPSNPSKEFCLPKAEKERYE
G1NQF0_MELGA|Meleagris            P----------AT-EKVVYLVIFHLSFVMFVWSYGKTIFTSPASPSNEFCLSKADKEQYE
L5L6V4_PTEAL|Pteropus             DLDWCSHHKPGSTGKAVVYLVAFHLFFVMFVWSYWMTIFTSPASPSKEFYLSSSEKERYE
C3XW62_BRAFL|Branchiostoma        T----------SLPQKVVYLVLYHVFFLIFVWSYYQTIFAPVGKPAQEFYLSKADVDRLE
L7MB41_9ACAR|Rhipicephalus        D----------NVIQKIFYLIGFHACFAMFAWSYWQTIFTEPGTIPKQFYLSPADAEHLE
G6DE89_DANPL|Danaus               D----------GTAQKCIYLVLYHILLIMFLWSYWRTIFADIKPIPDKYKLPETELEKLL
E2A927_CAMFO|Camponotus           D----------NYVQKAFYLLFFHLLILMFLWSYWQTVYTNLMPVPDKFKIPDVEMEKLQ
K7J025_NASVI|Nasonia              E----------SNVQKVFYLIFFHIFFFLFLWSYWQTIATDLVKVPDKFKLPAAEMEKLL
B4KLJ9_DROMO|Drosophila           E----------NNVAKIFLLIFYHIALVLFLWSYWQTINTPVGRVPDQWRIPDEEVNQLF
B4LM13_DROVI|Drosophila           E----------NRVAMAFMLLFYHIALLLFLWSYWQTISTSVGRVPDQWRIPDEEVNQLF
B4J5A2_DROGR|Drosophila           E----------NRIAMVFMLLFYHVALVLFLWSYWQTINTSVGRVPDLWRIPDEEVNHLF
B4GB93_DROPE|Drosophila           E----------NLVGMILMLFFYHIALILFMWSYWRTIMTSVGRVPDQWRIPDEEVTRLF
B5E0C5_DROPS|Drosophila           E----------NLVGMILMLFFYHIALILFMWSYWRTIMTSVGRVPDQWRIPDEEVTRLF
B4MQW5_DROWI|Drosophila           E----------NRVAMSFMLLFYHIALVLLLWSYWRTIMTSVGRVPDQWRIPDEEVTRLF
B3MD30_DROAN|Drosophila           E----------NRIGMIFMLIFYHISLTLFMWSYWRTIMTSVGRIPEQWRIPDEEVSRLL
B3N6S2_DROER|Drosophila           Q----------NGIAMIFMLLFYHLFLTLFMWSYWRTIMTSVGRIPDQWRIPDEEVSRLF
Q7K2V5_DROME|Drosophila           E----------NRIGMIFMLLFYHLFLTLFMWSYWRTIMTSVGRIPDQWRIPDEEVSRLF
B4NX32_DROYA|Drosophila           Q----------NRISMIFMLLFYHLFLTLFMWSYWRTIMTSVGRIPDQWRIPDEEVSRLF
Q7Q7Z4_ANOGA|Anopheles            T----------NIVQRILFLLFYHAVLVMFLWSYYQTVFTDIGRVPSRFHVPRAELDRIV
B0WC84_CULQU|Culex                T----------GVLQRILFLLFYHLILVMFLWSYYRTVFTDIGRVPARFRVPRSELDRLL
                                                     *  :*  :  :  :*  :: :        : :.        

A7S6A3_NEMVE|Nematostella         ---NGENVREVLTRVSKNLPTATRTLSGGVRYCDICCHI--KPDRCHHCSMCRKCI-LKM
G1KF61_ANOCA|Anolis               KEPRSEIHQEILRRAAKDLPIYTRTMSGAIRYCDRCQLV--KPDRCHHCSVCDKCI-LKM
H3AQ09_LATCH|Latimeria            REERGEAQQEVLRRVAKDLPIYTRTMSGAIRYCDRCQLV--KPDRCHHCSVCDKCI-LKM
Q0VFI0_XENTR|Xenopus              REPRGESQQDILRRLAKDLPVYTRTMSGAIRYCDRCQLV--KPDRCHHCSVCDKCI-LKM
F7AXP5_MONDO|Monodelphis          REPRGETHQEILKRAAKDLPIYTRTMSGVWAFLSACSSLEFRQQICQGSLWGRGCI-LKM
F6ZIT6_ORNAN|Ornithorhynchus      RESRGEGQQEVLRRAARDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDNCLRLKL
G3WFR2_SARHA|Sarcophilus          REPRGETHQEILKRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G5E7C4_LOXAF|Loxodonta            KEPRGEAHQEILRRAGKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
ZDHC2_MOUSE|Mus                   REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
ZDHC2_RAT|Rattus                  REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCRLI--KPDRCHHCSVCDKCI-LKM
G1T7P7_RABIT|Oryctolagus          REPRGEAHQEVLRRAARDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
H0V4C6_CAVPO|Cavia                REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G3MXF3_BOVIN|Bos                  REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
J9P566_CANFA|Canis                REPRGEAHQEVLRRAAKDLPIYTRTVSGAIRYCDRCQLL--KPDRCHHCSVCDKCI-LRM
H0WS46_OTOGA|Otolemur             REPRGEAHQEILRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G5B8F0_HETGA|Heterocephalus       REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
I3MD11_SPETR|Spermophilus         REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
F6TF01_CALJA|Callithrix           REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G7PCM0_MACFA|Macaca               REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
I2CX55_MACMU|Macaca               REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G1QPY3_NOMLE|Nomascus             REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLV--KPDRCHHCSVCDKCI-LKM
G3RL61_GORGO|Gorilla              REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
ZDHC2_HUMAN|Homo                  REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
H2QVS6_PANTR|Pan                  REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
H2PPM5_PONAB|Pongo                RESRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
F7CAZ8_HORSE|Equus                REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G1NW00_MYOLU|Myotis               REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G9KYT2_MUSPF|Mustela              REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
G1M5B0_AILME|Ailuropoda           REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
F1SET7_PIG|Sus                    REPRGEAHQEVLRRAAKDLPIYTRTMSGAIRYCDRCQLI--KPDRCHHCSVCDKCI-LKM
K7FYZ2_PELSI|Pelodiscus           REPRGEAQQEIFRRAAKDLPIYTRTMSGAIRYCDRCQLV--KPDRCHHCSVCDKCI-LKM
F1NVH3_CHICK|Gallus               REPRGESQQEVLRRAAKDLPIYTRTMSGAIRYCDRCHLV--KPDRCHHCSVCDKCI-LKM
H0ZA87_TAEGU|Taeniopygia          REPRGESQQEVLRRAAKDLPIYTRTMSGAIRYCDRCHLV--KPDRCHHCSVCDKCI-LKM
H2S209_TAKRU|Takifugu             REDREESQQEILRRIAKDLPIYTRTNSGVLSTDAASRRA--SIERCFLCS----CM-SRA
Q5BLG4_DANRE|Danio                REDRRESQQEILRRIAKDLPIYTRTMSGAIRYCDRCLLL--KPDRCHHCSACDMCI-LKM
G3Q3Z4_GASAC|Gasterosteus         REDRGESQQEILRRIARDLPIYTRTNSGAIRFCDRCQLL--KPDRCHHCSVCNKCI-LKM
I3KM57_ORENI|Oreochromis          REDRGESQQEILRRIAKDLPIYTRTNSGAIRFCDRCQLL--KPDRCHHCSVCDKCI-LKM
H2LTT9_ORYLA|Oryzias              KEARPESQQEILWRVATSLPLYTRTGTGGIRYCDRCQVI--KPDRCHHCSACDTCV-LKM
H3CRV3_TETNG|Tetraodon            KEERPESQQEILWRAASSLPLYTRTGAGAIRYCDRCQVI--KPDRCHHCSACDMCV-LKM
G1NQF0_MELGA|Meleagris            KEERPESQQEILRRAAKDLPIYTTTASRAIRYCDRCQLI--KPDRCHHCSACDICV-LKM
L5L6V4_PTEAL|Pteropus             KEFSQERQQAILRRTARDLPIYTTSASKTIRYCERCQLM--KPDRAHHCSACDTCI-LKM
C3XW62_BRAFL|Branchiostoma        HEDREDRQQQYLAQMAKDLPLVTRTIGGSIRYCEPCQLI--KPDRCHHCSMCGTCV-LKM
L7MB41_9ACAR|Rhipicephalus        KELSEDNQRQMLERLAKNLPVSCRTMNGMVRYCEKCHLI--KPDRAHHCSVCGRCI-LKM
G6DE89_DANPL|Danaus               SAETEDGQRTILENFAKDLPIVTRTMSGSVRYCNRCVLV--KPDRAHHCSICARCV-LKM
E2A927_CAMFO|Camponotus           QAETEEAQRQILERFAQDLPVTNRTIKGAMRFCEKCQLI--KPDRAHHCSVCSTCV-LKM
K7J025_NASVI|Nasonia              QAESESTHRQILERFAQDLPITNRTIKGEIRFCEQCQVV--KPDRAHHCSVCGTCV-LKM
B4KLJ9_DROMO|Drosophila           RADNQETQKRILNNFARNLPVTNRTINGSVRFCEKCKII--KPDRSHHCSVCSCCV-LKM
B4LM13_DROVI|Drosophila           RADNQETQKRILNNFARNLPVTNRTINGSVRFCEKCKIV--KPDRSHHCSVCSCCV-LKM
B4J5A2_DROGR|Drosophila           RADNTETQKRILNNFARNLPVTNRTMNGSVRFCEKCKII--KPDRSHHCSVCSCCV-LKM
B4GB93_DROPE|Drosophila           RADNPETQKRILNSFARSLPVTNRTMNGSVRFCEKCKII--KPDRAHHCSVCNSCV-LKM
B5E0C5_DROPS|Drosophila           RADNPETQKRILNSFARSLPVTNRTMNGSVRFCEKCKII--KPDRAHHCSVCNSCV-LKM
B4MQW5_DROWI|Drosophila           RADNPETQKRILNNFARNLPVTNRTMNGSVRFCEKCKII--KPDRSHHCSVCSCCV-LKM
B3MD30_DROAN|Drosophila           RADSQEAQKRILNNFARNLPVTNRTMNGSVRFCEKCKII--KPDRAHHCSVCSCCV-LKM
B3N6S2_DROER|Drosophila           RADSPETQKRILNNFARDLPVTNRTMNGSVRFCEKCKII--KPDRAHHCSVCSCCV-LKM
Q7K2V5_DROME|Drosophila           RADSPDTQKRILNNFARDLPVTNRTMNGSVRFCEKCKII--KPDRAHHCSVCSCCV-LKM
B4NX32_DROYA|Drosophila           RADSPDTQKRILNNFARDLPVTNRTMNGSVRFCEKCKII--KPDRAHHCSVCSCCV-LKM
Q7Q7Z4_ANOGA|Anopheles            RATNEVEQKEILETFAKELPVVTRTLNASVRFCDKCRLI--KPDRAHHCSVCGVCV-LKL
B0WC84_CULQU|Culex                RAQSEDEQKQILEAFAKQLPIVTRTLNASVRFCEKCRLI--KPDRAHHCSVCGVCV-LKL
                                          .  :   . .**    :          .       : .  .     *:  . 

A7S6A3_NEMVE|Nematostella         DHH-C---P-W--VNNCVGYSNYKFFLLFLFYAILYTFYVTGTVTKYFIAFWS-------
G1KF61_ANOCA|Anolis               DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAASDLHYFIKFWT-------
H3AQ09_LATCH|Latimeria            DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFITATDLQYFIKFWT-------
Q0VFI0_XENTR|Xenopus              DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIVATDLQYFVKFWT-------
F7AXP5_MONDO|Monodelphis          DHH-C---PLWNLVNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
F6ZIT6_ORNAN|Ornithorhynchus      SHHLCLSPP----VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G3WFR2_SARHA|Sarcophilus          DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G5E7C4_LOXAF|Loxodonta            DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCVFIAATDLQYFIKFWT-------
ZDHC2_MOUSE|Mus                   DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIRFWT-------
ZDHC2_RAT|Rattus                  DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIRFWT-------
G1T7P7_RABIT|Oryctolagus          DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFVKFWT-------
H0V4C6_CAVPO|Cavia                DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G3MXF3_BOVIN|Bos                  DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCVFIAATDLQYFIKFWT-------
J9P566_CANFA|Canis                DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
H0WS46_OTOGA|Otolemur             DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G5B8F0_HETGA|Heterocephalus       DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
I3MD11_SPETR|Spermophilus         DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
F6TF01_CALJA|Callithrix           DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G7PCM0_MACFA|Macaca               DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
I2CX55_MACMU|Macaca               DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G1QPY3_NOMLE|Nomascus             DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDIQYFIKFWT-------
G3RL61_GORGO|Gorilla              DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
ZDHC2_HUMAN|Homo                  DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
H2QVS6_PANTR|Pan                  DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
H2PPM5_PONAB|Pongo                DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
F7CAZ8_HORSE|Equus                DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G1NW00_MYOLU|Myotis               DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G9KYT2_MUSPF|Mustela              DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
G1M5B0_AILME|Ailuropoda           DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
F1SET7_PIG|Sus                    DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
K7FYZ2_PELSI|Pelodiscus           DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
F1NVH3_CHICK|Gallus               DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
H0ZA87_TAEGU|Taeniopygia          DHH-C---P-W--VNNCVGFSNYKFFLLFLAYSLLYCLFIAATDLQYFIKFWT-------
H2S209_TAKRU|Takifugu             SHAYR---PSL--VNNCVGFSNYKFFMQFLAYSLLYCLFITATDFQYFIKFWM-------
Q5BLG4_DANRE|Danio                DHH-C---P-W--VNNCVGFANYKFFMLFLAYSLLYCLFVTATDMQYFIQFWT-------
G3Q3Z4_GASAC|Gasterosteus         DHH-C---P-W--VNNCVGFSNYKFFMLFLAYSLLYCLFITATDLQYFIKFWL-------
I3KM57_ORENI|Oreochromis          DHH-C---P-W--VNNCVGFANYKFFMLFLLYSLLYCLFITATDLQYFIKFWT-------
H2LTT9_ORYLA|Oryzias              DHH-C---P-W--VNNCVGFSNYKFFILFLAYSLAYCLFIAATVLQYFIKFWT-------
H3CRV3_TETNG|Tetraodon            DHH-C---P-W--VNNCVGFSNYKFFILFLAYSLVYCLFIAATVLQYFIKFWT-------
G1NQF0_MELGA|Meleagris            DHH-C---P-W--VNNCVGFSNYKFFLLFLMYSLLYCLFVAATVLQYFIKFWT-------
L5L6V4_PTEAL|Pteropus             DHH-C---P-W--VNNCVGFSNYKFFLLFLLYSLLYCLFVAATVLQYFIKFWT-------
C3XW62_BRAFL|Branchiostoma        DHH-C---P-W--VNNCVGYSNYKFFVLFLGYGLLYCIYVAGTSVEYFIKFWN-------
L7MB41_9ACAR|Rhipicephalus        DHH-C---P-W--VNNCVSFTNYKYFILFLAYSLIYCLFVAATTLQFFIKFWT-------
G6DE89_DANPL|Danaus               DHH-C---P-W--VNNCVCFHNYKFFMLFLGYALLYCLFIMSTCLPYFIRFWKMYQEYNQ
E2A927_CAMFO|Camponotus           DHH-C---P-W--VNNCVGFHNYKFFMLFLAYALLYCMFITATSLQYFIRFWK-------
K7J025_NASVI|Nasonia              DHH-C---P-W--VNNCVGFHNYKFFMLFLAYALLYCIFIVATSLQYFIMFWR-------
B4KLJ9_DROMO|Drosophila           DHH-C---P-W--VNNCVNFSNYKFFVLFLGYALVYCLYVAFTTLNDFIMFVQ-------
B4LM13_DROVI|Drosophila           DHH-C---P-W--VNNCVNFSNYKFFVLFLGYALIYCLYVALTTLHDFIQFVK-------
B4J5A2_DROGR|Drosophila           DHH-C---P-W--VNNCVNFNNYKFFVLFLGYALIYCLYVALTTLHDFVQFWK-------
B4GB93_DROPE|Drosophila           DHH-C---P-W--VNNCVNFYNYKFFVLFLGYALIYCLYVAFTTLHDFVQFWK-------
B5E0C5_DROPS|Drosophila           DHH-C---P-W--VNNCVNFYNYKFFVLFLGYALIYCLYVAFTTLHDFVQFWK-------
B4MQW5_DROWI|Drosophila           DHH-C---P-W--VNNCVNFYNYKFFVLFLGYALIYCLYVALTTLHDFVQFWK-------
B3MD30_DROAN|Drosophila           DHH-C---P-W--VNNCVNFYNYKFFVLFLGYALVYCLYVAFTTLHDFVQFWK-------
B3N6S2_DROER|Drosophila           DHH-C---P-W--VNNCVNFYNYKYFVLFLGYALVYCLYVAFTSLHDFVEFWK-------
Q7K2V5_DROME|Drosophila           DHH-C---P-W--VNNCVNFYNYKYFVLFLGYALVYCLYVAFTSLHDFVEFWK-------
B4NX32_DROYA|Drosophila           DHH-C---P-W--VNNCVNFYNYKYFVLFLGYALVYCLYVAFTSLHDFVEFWK-------
Q7Q7Z4_ANOGA|Anopheles            DHH-C---P-W--VNNCINFTNYKYFILFLGYALLYCVYVACSTIPYMELLWT-------
B0WC84_CULQU|Culex                DHH-C---P-W--VNNCINFTNYKFFILFLGYALVYCLYVAFSTVMYMELIWS-------
                                  .*      *    ****: : ***:*: ** *.: * .::  :    :  :         

A7S6A3_NEMVE|Nematostella         -----------------------NSL-----EG--EGKLHILFLFFVALMFCISLWSLFG
G1KF61_ANOCA|Anolis               -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
H3AQ09_LATCH|Latimeria            -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
Q0VFI0_XENTR|Xenopus              -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
F7AXP5_MONDO|Monodelphis          -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
F6ZIT6_ORNAN|Ornithorhynchus      -----------------------NDLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G3WFR2_SARHA|Sarcophilus          -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G5E7C4_LOXAF|Loxodonta            -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
ZDHC2_MOUSE|Mus                   -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
ZDHC2_RAT|Rattus                  -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G1T7P7_RABIT|Oryctolagus          -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
H0V4C6_CAVPO|Cavia                -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G3MXF3_BOVIN|Bos                  -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
J9P566_CANFA|Canis                -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
H0WS46_OTOGA|Otolemur             -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLFSLFG
G5B8F0_HETGA|Heterocephalus       -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
I3MD11_SPETR|Spermophilus         -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
F6TF01_CALJA|Callithrix           -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G7PCM0_MACFA|Macaca               -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
I2CX55_MACMU|Macaca               -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G1QPY3_NOMLE|Nomascus             -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G3RL61_GORGO|Gorilla              -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
ZDHC2_HUMAN|Homo                  -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
H2QVS6_PANTR|Pan                  -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
H2PPM5_PONAB|Pongo                -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
F7CAZ8_HORSE|Equus                -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G1NW00_MYOLU|Myotis               -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G9KYT2_MUSPF|Mustela              -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
G1M5B0_AILME|Ailuropoda           -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
F1SET7_PIG|Sus                    -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
K7FYZ2_PELSI|Pelodiscus           -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
F1NVH3_CHICK|Gallus               -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
H0ZA87_TAEGU|Taeniopygia          -----------------------NGLP----DT--QAKFHIMFLFFAAAMFSVSLSSLFG
H2S209_TAKRU|Takifugu             -----------------------NKLP----DT--QAKFHILFLFFSASMFSVSLAALFI
Q5BLG4_DANRE|Danio                -----------------------NGLP----DT--QAKFHIMFLFFAASTFSVSLAFLFA
G3Q3Z4_GASAC|Gasterosteus         -----------------------NGLP----DT--QAKFHILFLFFSACMFSVSLASLLT
I3KM57_ORENI|Oreochromis          -----------------------NGLP----DT--QAKFHILFLFFSASMFSVSLASLFI
H2LTT9_ORYLA|Oryzias              -----------------------NELD----GT--HAKFHVLFLFFVAAMFCISILSLFS
H3CRV3_TETNG|Tetraodon            -----------------------NELP----ES--PAKFHVLFLFFVAAMFCISILSLFS
G1NQF0_MELGA|Meleagris            -----------------------NELP----DT--HAKFHVLFLFFVAAMFFISILSLFS
L5L6V4_PTEAL|Pteropus             -----------------------NELP----DT--RAKFHVLFLFFVSTMFLVSVLSLFS
C3XW62_BRAFL|Branchiostoma        -----------------------KELD----DTIGNGRFHILFLFFAAAMFSISLVSLFG
L7MB41_9ACAR|Rhipicephalus        -----------------------NDL-----EG--WGRFHILFLFFVAFMFAISLVSLFG
G6DE89_DANPL|Danaus               AHCDSLIGIGTYTKQCMDLLSGDFGTS----GS--AGRYHIVFAFFVALMFAISLGSLFG
E2A927_CAMFO|Camponotus           -----------------------GEL-----DG--MGRFHLLFLFFVALMFAVSLNSLFF
K7J025_NASVI|Nasonia              -----------------------GELP-----G--MGKFHLLFLFFVALMFAISLNSLFF
B4KLJ9_DROMO|Drosophila           ------------------------GQPGG--SG--MGRFHILFLFFISIMFAISLVSLFG
B4LM13_DROVI|Drosophila           ------------------------GQPTG--NG--MGRFHILFLFFISIMFAISLVSLFG
B4J5A2_DROGR|Drosophila           -----------------------GQLT----GTG-MGRFHILFLFFISIMFAISLVSLFG
B4GB93_DROPE|Drosophila           -----------------------VGAGQLNGSG--VGRFHILFLFFISIMFAISLVSLFG
B5E0C5_DROPS|Drosophila           -----------------------VGAGQLNGSG--VGRFHILFLFFISIMFAISLVSLFG
B4MQW5_DROWI|Drosophila           -----------------------GQLN----GG--VGRFHILFLFFIAIMFAISLVSLFG
B3MD30_DROAN|Drosophila           -----------------------VGAGQLNGGG--MGRFHILFLFFIAIMFAISLVSLFG
B3N6S2_DROER|Drosophila           -----------------------GQL-----NASGMGRFHILFLFFIAIMFAISLVSLFG
Q7K2V5_DROME|Drosophila           -----------------------VGAGQLNASG--MGRFHILFLFFIAIMFAISLVSLFG
B4NX32_DROYA|Drosophila           -----------------------GQLNA---SG--MGRFHILFLFFIAIMFAISLVSLFG
Q7Q7Z4_ANOGA|Anopheles            -----------------------GKI---------DGRFHILFLFFVSVMFAISLVSLFG
B0WC84_CULQU|Culex                -----------------------ASGREG--KI--DGRFHILFLFFVSLMFAISLVSLFG
                                                                      .. *::* ** :  * :*:  *: 

A7S6A3_NEMVE|Nematostella         YHIYLVSQNKTTLESFRVPHLRY-GPSKDAFHLGTRLKNVEQVFGTSVIMWFLPVFTRYD
G1KF61_ANOCA|Anolis               YHCWLVSKNKSTLEAFRAPIFRH-GMDKNGFSLGFT-KNLLQVFGDEKKLWLLPIFSSQG
H3AQ09_LATCH|Latimeria            YHCWLVSKNRSTLEAFRAPAFRH-GTDKNGFSLGFS-KNLRQVFGDEKKYWLLPIFTSLG
Q0VFI0_XENTR|Xenopus              YHCWLVCKNRSTLEAFRAPVFRH-GTDKNGFSLGFS-KNLRQVFGDEKKYWLLPVFTSLG
F7AXP5_MONDO|Monodelphis          YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFR-KNLCQVFGDEKKYWLLPVFSSLG
F6ZIT6_ORNAN|Ornithorhynchus      YHCWLVSKNKSTLEAFRAPAFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPVFSSLG
G3WFR2_SARHA|Sarcophilus          YHCWLVSKNKSTLEAFRSPIFRH-GTDKNGFSLGFS-KNLRQVFGDEKKYWPLPVFSSLG
G5E7C4_LOXAF|Loxodonta            YHCWLVSKNKSTLEAFRSPIFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
ZDHC2_MOUSE|Mus                   YHCWLVSKNKSTLEAFRNPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPVFSSQG
ZDHC2_RAT|Rattus                  YHCWLVSKNKSTLEAFRNPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSQG
G1T7P7_RABIT|Oryctolagus          YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
H0V4C6_CAVPO|Cavia                YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
G3MXF3_BOVIN|Bos                  YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFG-KNMLQVFGDEKRYWLLPIFSSLG
J9P566_CANFA|Canis                YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
H0WS46_OTOGA|Otolemur             YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPVFSSLG
G5B8F0_HETGA|Heterocephalus       YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
I3MD11_SPETR|Spermophilus         YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
F6TF01_CALJA|Callithrix           YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
G7PCM0_MACFA|Macaca               YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
I2CX55_MACMU|Macaca               YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
G1QPY3_NOMLE|Nomascus             YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
G3RL61_GORGO|Gorilla              YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
ZDHC2_HUMAN|Homo                  YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
H2QVS6_PANTR|Pan                  YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
H2PPM5_PONAB|Pongo                YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
F7CAZ8_HORSE|Equus                YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEEKYWLLPIFSSLG
G1NW00_MYOLU|Myotis               YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPVFSSLG
G9KYT2_MUSPF|Mustela              YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
G1M5B0_AILME|Ailuropoda           YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPVFSSLG
F1SET7_PIG|Sus                    YHCWLVSKNKSTLEAFRSPVFRH-GTDKNGFSLGFS-KNMRQVFGDEKKYWLLPIFSSLG
K7FYZ2_PELSI|Pelodiscus           YHCWLVSKNKSTLEAFRAPIFRH-GTDKNGFSLGFS-KNLRQVFGDEKKFWLLPVFSSLG
F1NVH3_CHICK|Gallus               YHCWLVSKNKSTLEVFRAPIFHH-RTDKNGFSLGFS-KNLRQVFGDEKKYWLLPVFSSLG
H0ZA87_TAEGU|Taeniopygia          YHCWLVSKNKSTLEVFRAPIFRH-RTDKNGFSLGFS-KNLRQVFGDEKKYWLLPVFSSLG
H2S209_TAKRU|Takifugu             YHCWLVCKNRSTLEAVRSPVFGH-GTDKNGFSLGFS-KNLLQVFGDESKYWPVPVFSSLG
Q5BLG4_DANRE|Danio                YHCWLVCKNRSTLEAFRAPAFQH-GTDKNGFSLGAY-KNFRQVFGDEKKYWLLPIFSSLG
G3Q3Z4_GASAC|Gasterosteus         YHCWLVCRNRSTLEVVRAPVFRH-GTDKSGFSLGFS-KNFRQVFGDEVKYWPIPVFSGLG
I3KM57_ORENI|Oreochromis          YHCWLVCKNRSTLEAVRSPVFRH-GTDKNGFSLGFS-KNFRQVFGDEVKYWPIPVFSSLG
H2LTT9_ORYLA|Oryzias              YHLWLVGKNRSTIEAFRAPVFRS-GSDKNGFSLGFR-KNIAQVFGDQKKYWLLPVFTSQG
H3CRV3_TETNG|Tetraodon            YHLWLVGKNRSTIEAFRAPVFRT-GSDKNGFSLGFK-KNIAQVFGDQKKYWFLPVFTSQG
G1NQF0_MELGA|Meleagris            YHCWLVGKNRSTIETFRAPTFRN-GPDKNGFSLGCS-KNLREVFGDEKKYWLLPIFTSLG
L5L6V4_PTEAL|Pteropus             YHCWLVGKNRTTIESFRAPTFSY-GPDGNGFSLGYR-KNWRQVFGDEKKYWLLPVFSSLG
C3XW62_BRAFL|Branchiostoma        YHLYLVFSNRTTLESFRTPMFRH-GPDKDGFNLGSS-NNLKEVFGEDRRLWFLPVFTSLG
L7MB41_9ACAR|Rhipicephalus        YHCFLVMVNRSTLEAFRPPIFRT-GPDKHGFSLGHQ-ANVAEVFGDNRRLWLLPVFTSLG
G6DE89_DANPL|Danaus               YHCYLVAHNRTTLEAFRAPMFRG-GADKNGFSIGAF-NNFKEVFGASPDLWAIPVFTSLG
E2A927_CAMFO|Camponotus           YHCYLVVHNRSTLEAFRTPMFRT-GKDKDGFSLGKY-NNFQEVFGDNPRLWFLPIFSSLG
K7J025_NASVI|Nasonia              YHCYLILHNRSTLEAFRPPMFRT-GKDKDGFSLGKY-NNFQEVFGDNSRLWFLPVFTSLG
B4KLJ9_DROMO|Drosophila           YHIYLVLVNRTTLEAFRAPIFRVGGPDKNGYNLGRF-ANFCEVFGDKWQYWFLPVFTSKG
B4LM13_DROVI|Drosophila           YHIYLVLVNRTTLEAFRAPIFRVGGPDKNGYNLGRY-ANFCEVFGDKWELWFLPVFTSKG
B4J5A2_DROGR|Drosophila           YHIYLVLVNRTTLEAFRAPIFRVGGPDKNGYNLGRY-ANFCEVFGDKWELWFLPVFTSKG
B4GB93_DROPE|Drosophila           YHIYLVLVNRTTLESFRAPVFRVGGPDKNGFNLGRY-ANFCEVFGDDWQYWPLPIFTSFG
B5E0C5_DROPS|Drosophila           YHIYLVLVNRTTLESFRAPVFRVGGPDKNGFNLGRY-ANFCEVFGDDWQYWPLPIFTSFG
B4MQW5_DROWI|Drosophila           YHIYLVLVNRTTLEAFRAPIFRVGGPDKNGYNLGRF-ANFCEVFGDDWQYWFLPIFTSRG
B3MD30_DROAN|Drosophila           YHIYLVLVNRTTLESFRAPIFRVGGPDKNGYNLGRY-ANFCEVFGDDWQYWFLPVFSSFG
B3N6S2_DROER|Drosophila           YHIYLVLVNRTTLESFRAPIFRVGGPDKNGYNLGRY-ANFCEVFGDDWQYWFLPVFSSRG
Q7K2V5_DROME|Drosophila           YHIYLVLVNRTTLESFRAPIFRVGGPDKNGYNLGRY-ANFCEVFGDDWQYWFLPVFSSFG
B4NX32_DROYA|Drosophila           YHIYLVLVNRTTLESFRAPIFRVGGPDKNGYNLGRY-ANFCEVFGDDWQYWFLPVFSSRG
Q7Q7Z4_ANOGA|Anopheles            YHVYLVLLNRTTLESFRTPIFRFGGPDKNGFSLGKL-NNFQEVFGDDWRLWFVPVYTSLG
B0WC84_CULQU|Culex                YHVYLVLLNRTTLESFRTPIFRYGGPDKNGFSLGKM-NNFQEVFGDNRKLWFVPVYTSLG
                                  ** :*:  *.:*:* .* * :     .  .: :*    *  :*** .   * :*:::  .

A7S6A3_NEMVE|Nematostella         D-----------------------------------------------------------
G1KF61_ANOCA|Anolis               DGCSFPTCLVN------QDLERA-VSPAGRSNPNKNE---------------------NN
H3AQ09_LATCH|Latimeria            DGCAFPTCLVN------QDPEQP-STPAGHNPTTKNI---------------------EG
Q0VFI0_XENTR|Xenopus              DGCSFPTCLVN------QDLEQA-STPTGANTATKSI---------------------EN
F7AXP5_MONDO|Monodelphis          DGCSFPTCLVN------QDLEQP-SAPAGLTPAVKNL---------------------EA
F6ZIT6_ORNAN|Ornithorhynchus      DGCSFPTCLVN------QDPEQP-STPAALTSTTRNP---------------------ES
G3WFR2_SARHA|Sarcophilus          DGCSFPTCLVN------QDLEQQ-STPAGLTPAVKNL---------------------EG
G5E7C4_LOXAF|Loxodonta            DGCSFPTCLVN------QDPEQP-STPAGLNSTAKNL---------------------EN
ZDHC2_MOUSE|Mus                   DGCSFPTCLVN------QDPEQP-STPAGLNSTVKNP---------------------EN
ZDHC2_RAT|Rattus                  DGCSFPTCLVN------QDPEQP-STPAGLNSTAKNP---------------------EN
G1T7P7_RABIT|Oryctolagus          DGCSFPTCLVN------QDPEQP-STPAGLNSTTKNP---------------------EN
H0V4C6_CAVPO|Cavia                DGCSFPTCLVN------QDPEQP-ATPAGLNSTAKNP---------------------EN
G3MXF3_BOVIN|Bos                  DGCSFPTCLVN------QDPEQP-STPAGLNSSSKNP---------------------EN
J9P566_CANFA|Canis                DGCSFPTCLVN------QDPEQA-STPAGLNSTSKNP---------------------EN
H0WS46_OTOGA|Otolemur             DGCSFPTCLVN------QDPEQP-STPAGLNSAAKNP---------------------EN
G5B8F0_HETGA|Heterocephalus       DGCSFPTCLVN------QDPEQP-ATPAGLNSTAKNP---------------------EN
I3MD11_SPETR|Spermophilus         DGCSFPTCLVN------QDPEQP-STPAGLNSTAKNP---------------------EN
F6TF01_CALJA|Callithrix           DGCSFPTCLVN------QDPEQP-STPAGLNSTAKNP---------------------EN
G7PCM0_MACFA|Macaca               DGCSFPTCLVN------QDPEQP-STPAGLSSTAKNS---------------------EN
I2CX55_MACMU|Macaca               DGCSFPTCLVN------QDPEQL-STPAGLSSTAKNS---------------------EN
G1QPY3_NOMLE|Nomascus             DGCSFPTCLVN------QDPEQA-STPAGLNSTAKNL---------------------EN
G3RL61_GORGO|Gorilla              DGCSFPTCLVN------QDPEQA-STPAGLNSTAKNL---------------------EN
ZDHC2_HUMAN|Homo                  DGCSFPTCLVN------QDPEQA-STPAGLNSTAKNL---------------------EN
H2QVS6_PANTR|Pan                  DGCSFPTCLVN------QDPEQA-STPAGLNSTAKNL---------------------EN
H2PPM5_PONAB|Pongo                DGCSFPTCLVN------QDPEQA-STPAGLNSTAKNL---------------------EN
F7CAZ8_HORSE|Equus                DGCSFPTCLVN------QDPEQP-STPAGLNSTSKNP---------------------EN
G1NW00_MYOLU|Myotis               DGCSFPTCLVN------QDPEQP-STPAGLNPASKNP---------------------EN
G9KYT2_MUSPF|Mustela              DGCSFPTCLVN------QDPEQA-STPAGLNSTSKNP---------------------EN
G1M5B0_AILME|Ailuropoda           DGCSFPTCLVN------QDPEQA-STPAGLNSSLKNP---------------------EN
F1SET7_PIG|Sus                    DGCSFPTCLVN------QDPEQP-STPAGLNSSSKNP---------------------EN
K7FYZ2_PELSI|Pelodiscus           DGCSFPTCLVN------QDPEQV-STPVGLNSTTKN----------------------EN
F1NVH3_CHICK|Gallus               DGCSFPTCLVN------QDPEQA-STPGGLNSTCKN----------------------EN
H0ZA87_TAEGU|Taeniopygia          DGCSFPTCLVN------QDPEQA-STPDGLNSTSKS----------------------EN
H2S209_TAKRU|Takifugu             DGCSFPTGPVN------LDPEQP-SSPSGSSLNGAT----------------------EA
Q5BLG4_DANRE|Danio                DGCSFPTCLVN------PDPEQP-SIPPGRNPSVKSA--------------------GES
G3Q3Z4_GASAC|Gasterosteus         DGCSFPTCLVN------LDPEQPSSSPTRSHPVSKSA--------------------ADG
I3KM57_ORENI|Oreochromis          DGCSFPTCLVN------LDPEQP-SSPTGSNPANKSA--------------------AEG
H2LTT9_ORYLA|Oryzias              DGLTFPTRLVN------ADAEQA-AVTLHQEPNKSTA-----------------------
H3CRV3_TETNG|Tetraodon            DGLAFPTRLVN------TDVEQP---AVTLQPEAKL----------------------SA
G1NQF0_MELGA|Meleagris            DGCNFPTRLVI------MDPEQL-TVSSQNEPAKSSG---------------------AN
L5L6V4_PTEAL|Pteropus             DGCSFPTRLVG------MDPEQA-SVTAQDECARSIG---------------------SN
C3XW62_BRAFL|Branchiostoma        DGLKFPTQVQY-------DPSEPAPTDSPATESPDSP---------------DSVGFGDG
L7MB41_9ACAR|Rhipicephalus        DGVTYPTR---------TQLASS-YNSMGSTEQASLG---------------------DG
G6DE89_DANPL|Danaus               DGCEYPVRREH------QLQTFTTPQDGGGYESMGTT----------------RSSFGDG
E2A927_CAMFO|Camponotus           NGVVYPVRSQH------QGTPNT-YDSMGSTQNRSTI-----------------------
K7J025_NASVI|Nasonia              NGVVFPVRSQH------QGVSNT-YNSMGS------------------------------
B4KLJ9_DROMO|Drosophila           DGLYFVTSTDQFGNGNAQRYEAMGRTAAGAATSNSFG---------------------DG
B4LM13_DROVI|Drosophila           DGLSYRTSSDQ------TGPGQR-YEAMGNTTANAAS----NRLDVQATDKLIDAIPLNN
B4J5A2_DROGR|Drosophila           DGLSYPTANEQMGN---GNANGQRYEAMGQTTTATTANVGSNRLEGQPTDKLIEAIPLNN
B4GB93_DROPE|Drosophila           DGISYPIRHLE------DDSETL----LGYHSDTRIE--------------------LDE
B5E0C5_DROPS|Drosophila           DGISYPIRHLE------DDSETL----LGYHSDTRIE--------------------LDE
B4MQW5_DROWI|Drosophila           DGLTYPTSTDQNG----DIPAQR-YDTMGQTTTSSFG---------------------DG
B3MD30_DROAN|Drosophila           DGIRYPIRHLE------EDTESL----LGYHSDTRIE---------------------LE
B3N6S2_DROER|Drosophila           DGYSYPTSSDQSRVST-TSPVQR-YDAMGDTATSRLD------GNPTDKLIGASPLDTTN
Q7K2V5_DROME|Drosophila           DGKTFPIRHME------EDTESL----LGYHSDTRIE---------------------LE
B4NX32_DROYA|Drosophila           DGYSYPTSSDQSRVST-TSPVQR-YDAMGDTAASRLD------GNPTDKLIGASPLDNTN
Q7Q7Z4_ANOGA|Anopheles            DGIVFPCRDVA-----------P-----------------------------------YS
B0WC84_CULQU|Culex                DGMVYPVHASH------LAASTP---PPGMTTLVMSP---------------------SH
                                  :                                                           

A7S6A3_NEMVE|Nematostella         ------------------------------------------------------------
G1KF61_ANOCA|Anolis               PHF---------------------PS----KPL-RDSQ-----------SHLLTDTQ--S
H3AQ09_LATCH|Latimeria            HPF---------------------PA----KPL-RESQ-----------SHLLGSAQ--S
Q0VFI0_XENTR|Xenopus              HPF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
F7AXP5_MONDO|Monodelphis          HQF---------------------PS----KPL-RESQ-----------SHLLTDSQ--S
F6ZIT6_ORNAN|Ornithorhynchus      HHF---------------------PA----KPL-RESQ-----------SHLLTDTQ--S
G3WFR2_SARHA|Sarcophilus          HQF---------------------PS----KPL-RESQ-----------SHLLTDPH--S
G5E7C4_LOXAF|Loxodonta            HPF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
ZDHC2_MOUSE|Mus                   HQF---------------------PA----KPL-RESQ-----------SHLLKDSQ--T
ZDHC2_RAT|Rattus                  HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--T
G1T7P7_RABIT|Oryctolagus          HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
H0V4C6_CAVPO|Cavia                HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--P
G3MXF3_BOVIN|Bos                  HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
J9P566_CANFA|Canis                HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
H0WS46_OTOGA|Otolemur             HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
G5B8F0_HETGA|Heterocephalus       HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--P
I3MD11_SPETR|Spermophilus         HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
F6TF01_CALJA|Callithrix           HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
G7PCM0_MACFA|Macaca               HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
I2CX55_MACMU|Macaca               HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
G1QPY3_NOMLE|Nomascus             HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
G3RL61_GORGO|Gorilla              HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
ZDHC2_HUMAN|Homo                  HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
H2QVS6_PANTR|Pan                  HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
H2PPM5_PONAB|Pongo                HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
F7CAZ8_HORSE|Equus                HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
G1NW00_MYOLU|Myotis               HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
G9KYT2_MUSPF|Mustela              HPF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
G1M5B0_AILME|Ailuropoda           HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
F1SET7_PIG|Sus                    HQF---------------------PA----KPL-RESQ-----------SHLLTDSQ--S
K7FYZ2_PELSI|Pelodiscus           HLF---------------------PA----KTL-RDSQ-----------SHLLTDTQ--S
F1NVH3_CHICK|Gallus               HLF---------------------PA----KPL-RDSQ-----------SHLLTDTH--S
H0ZA87_TAEGU|Taeniopygia          HLF---------------------PA----KPL-RDSQ-----------SHLLTDAP--S
H2S209_TAKRU|Takifugu             RHY---------------------P-----KPL-RESQ-----------SRLLISAH--S
Q5BLG4_DANRE|Danio                HPF---------------------PP----KPL-RESQ-----------SRLLNNG----
G3Q3Z4_GASAC|Gasterosteus         RQ-----------------------S----KPL-TESQ-----------SRLLTSTI--C
I3KM57_ORENI|Oreochromis          RQF---------------------PS----KPL-RESQ-----------SRLLTSTP--S
H2LTT9_ORYLA|Oryzias              -DV---------------------PA----GPF-SDSQ-----------NHLLGDEQRGH
H3CRV3_TETNG|Tetraodon            ADV---------------------PS----SPL-SESQ-----------NRLLSSEQDAN
G1NQF0_MELGA|Meleagris            QPF---------------------PT----RPL-SESK-----------NRLLASDS--Q
L5L6V4_PTEAL|Pteropus             QPF---------------------PV----KPL-SESK-----------NRLLEAES--A
C3XW62_BRAFL|Branchiostoma        MSF---------------------PT----RRT-SEDS-----------HQLLNDRQ--R
L7MB41_9ACAR|Rhipicephalus        VTF---------------------PQ----KIV-DEDT-----------DGLLNQRQ--R
G6DE89_DANPL|Danaus               FVY---------------------PQ----RTT-DEDT-----------ESLLSSERWER
E2A927_CAMFO|Camponotus           ------------------------------------DQ-----------MTLVQEATILA
K7J025_NASVI|Nasonia              ----------------------------------TQNR----------------------
B4KLJ9_DROMO|Drosophila           ISY---------------------PI----RHL-EEDT-----------ESLLGYH----
B4LM13_DROVI|Drosophila           HQ----------------------PH----LEL-DNGQSSSHNHPLIPPSQVVVNIEQTA
B4J5A2_DROGR|Drosophila           HH----------------------PH----VEL-ENGQSSSNNHPLIPSSQIIVNVEQAA
B4GB93_DROPE|Drosophila           DCL---------------------PE-----------------------SRFLHSIP---
B5E0C5_DROPS|Drosophila           DCL---------------------PE-----------------------SRFLHSIP---
B4MQW5_DROWI|Drosophila           ISY---------------------PI----RHLEEEDT-----------ESLLGYH----
B3MD30_DROAN|Drosophila           EDF---------------------LP----EPRFQDSI----------------------
B3N6S2_DROER|Drosophila           HHHNQS------------------PHQVRSTSV-QPTQLLQVQPSSPYQDELNGRQE--Q
Q7K2V5_DROME|Drosophila           EDF---------------------LP----EPRFQDSI----------------------
B4NX32_DROYA|Drosophila           HHHNQSPHQVRSTSVQPTQLLQVQPPSPFRDEL-NERQ-----------EQLANDQSLNC
Q7Q7Z4_ANOGA|Anopheles            IEF---------------------AA----------------------------------
B0WC84_CULQU|Culex                HHQ---------------------------QPL---QL-----------PPPISAAGRRN
                                                                                              

A7S6A3_NEMVE|Nematostella         WSYR--------------------------------------------------------
G1KF61_ANOCA|Anolis               WTETSASI-EKN--------------K--------------------------------L
H3AQ09_LATCH|Latimeria            WTEAAGDE-QKD--------------K--------------------------------L
Q0VFI0_XENTR|Xenopus              WNENNGNS-EKG--------------K--------------------------------L
F7AXP5_MONDO|Monodelphis          WTDSSTNS-DKG--------------K--------------------------------I
F6ZIT6_ORNAN|Ornithorhynchus      WAESSTNSDGRC--------------R--------------------------------R
G3WFR2_SARHA|Sarcophilus          WADSSTNS-DKG--------------K--------------------------------V
G5E7C4_LOXAF|Loxodonta            WTDSCTHP-AKG--------------K--------------------------------V
ZDHC2_MOUSE|Mus                   WTESSANP-GKG--------------K--------------------------------A
ZDHC2_RAT|Rattus                  WTENSSNS-GRC--------------K--------------------------------A
G1T7P7_RABIT|Oryctolagus          WTESNINP-GRG--------------K--------------------------------A
H0V4C6_CAVPO|Cavia                WTESSTHL-GKG--------------K--------------------------------A
G3MXF3_BOVIN|Bos                  WTENSTSL-GKG--------------K--------------------------------A
J9P566_CANFA|Canis                WTESSTNP-GKG--------------K--------------------------------A
H0WS46_OTOGA|Otolemur             WTESGTNP-GKC--------------K--------------------------------A
G5B8F0_HETGA|Heterocephalus       WTENSTNP-GKG--------------K--------------------------------A
I3MD11_SPETR|Spermophilus         WTESSTNP-GKG--------------K--------------------------------A
F6TF01_CALJA|Callithrix           WTESSTNA-GKC--------------K--------------------------------T
G7PCM0_MACFA|Macaca               WTESSTNP-GKC--------------K--------------------------------A
I2CX55_MACMU|Macaca               WTESSTNP-GKC--------------K--------------------------------A
G1QPY3_NOMLE|Nomascus             WTESSINP-GKC--------------K--------------------------------A
G3RL61_GORGO|Gorilla              WTESSINP-GKC--------------K--------------------------------A
ZDHC2_HUMAN|Homo                  WTESSINP-GKC--------------K--------------------------------A
H2QVS6_PANTR|Pan                  WTESSINP-GKC--------------K--------------------------------A
H2PPM5_PONAB|Pongo                WTESSINP-GKC--------------K--------------------------------A
F7CAZ8_HORSE|Equus                WTEGSTNL-GKD--------------K--------------------------------A
G1NW00_MYOLU|Myotis               WTESSTNP-GKD--------------K--------------------------------A
G9KYT2_MUSPF|Mustela              WTGSSTNP-GKG--------------K--------------------------------A
G1M5B0_AILME|Ailuropoda           WTESSTNP-GKG--------------K--------------------------------A
F1SET7_PIG|Sus                    WTESSTNP-GKG--------------K--------------------------------S
K7FYZ2_PELSI|Pelodiscus           WTESSANN-ENG--------------K--------------------------------V
F1NVH3_CHICK|Gallus               WSDIGAKA-EKG--------------K--------------------------------V
H0ZA87_TAEGU|Taeniopygia          WPETAAKA-DKG--------------K--------------------------------V
H2S209_TAKRU|Takifugu             WSERDNAT-DKD--------------R---------------------------------
Q5BLG4_DANRE|Danio                --QTDGSE-DRD--------------K--------------------------------R
G3Q3Z4_GASAC|Gasterosteus         WSEIDSAT---D--------------R--------------------------------K
I3KM57_ORENI|Oreochromis          WSENETAT-DKD--------------R--------------------------------K
H2LTT9_ORYLA|Oryzias              NMEDSLAD-GAL--------------E--------------------------------S
H3CRV3_TETNG|Tetraodon            SVGAHVEN-ETL--------------Q--------------------------------S
G1NQF0_MELGA|Meleagris            WVESGPED-ENV--------------K--------------------------------S
L5L6V4_PTEAL|Pteropus             WAGNGSEDAGRP------------------------------------------------
C3XW62_BRAFL|Branchiostoma        WAEE-----GEG------------------------------------------------
L7MB41_9ACAR|Rhipicephalus        WAETDEEA-GHS--------------D--------------------------------E
G6DE89_DANPL|Danaus               WGQRARPF-DGS--------------S--------------------------------S
E2A927_CAMFO|Camponotus           LGAGTAVI-GPS-----------------------------------------------V
K7J025_NASVI|Nasonia              ------------------------------------------------------------
B4KLJ9_DROMO|Drosophila           ---------SDT--------------R--------------------------------I
B4LM13_DROVI|Drosophila           AAAAAASPAAAGGASTAGAHATNHVIDMIGDQVMTAPAPAAKDVNVPNGGPPAIPTHNVV
B4J5A2_DROGR|Drosophila           AKLDPNHHSGTAIDMIGDRMAPFTAKE-------------------TNGAPPSSPANHIV
B4GB93_DROPE|Drosophila           ------------------------------------------------------------
B5E0C5_DROPS|Drosophila           ------------------------------------------------------------
B4MQW5_DROWI|Drosophila           -SDTRIEM-EED------------------------------------------------
B3MD30_DROAN|Drosophila           ------------------------------------------------------------
B3N6S2_DROER|Drosophila           LANGSTAAASFG--------------D---------------------------------
Q7K2V5_DROME|Drosophila           ------------------------------------------------------------
B4NX32_DROYA|Drosophila           ITAAARSRPGECGVNGAAVYIDMIGDH--------------------------------P
Q7Q7Z4_ANOGA|Anopheles            ------------------------------------------------------------
B0WC84_CULQU|Culex                HNDDDGAE-NDG--------------E--------------------------------E
                                                                                              

A7S6A3_NEMVE|Nematostella         -----------------------------------------------------------
G1KF61_ANOCA|Anolis               ---GTSNP-ALTMENET------------------------------------------
H3AQ09_LATCH|Latimeria            ---GMNNP-AMNIENET------------------------------------------
Q0VFI0_XENTR|Xenopus              ---GMSNP-GLTIENET------------------------------------------
F7AXP5_MONDO|Monodelphis          ---GMSNP-GLTIENET------------------------------------------
F6ZIT6_ORNAN|Ornithorhynchus      ---GMSNP-ALTMENET------------------------------------------
G3WFR2_SARHA|Sarcophilus          ---GMSNP-ALTIENET------------------------------------------
G5E7C4_LOXAF|Loxodonta            ---GMSNP-ALTMENET------------------------------------------
ZDHC2_MOUSE|Mus                   ---GMSNP-ALTMENET------------------------------------------
ZDHC2_RAT|Rattus                  ---GMSNP-ALTMENET------------------------------------------
G1T7P7_RABIT|Oryctolagus          ---GMSNP-ALTMENET------------------------------------------
H0V4C6_CAVPO|Cavia                ---GLSNP-ALTMENET------------------------------------------
G3MXF3_BOVIN|Bos                  ---GMSNP-ALTMENET------------------------------------------
J9P566_CANFA|Canis                ---GMSNP-ALTMENET------------------------------------------
H0WS46_OTOGA|Otolemur             ---GMSNP-ALTMENET------------------------------------------
G5B8F0_HETGA|Heterocephalus       ---G-------------------------------------------------------
I3MD11_SPETR|Spermophilus         ---GMSNP-ALTMENET------------------------------------------
F6TF01_CALJA|Callithrix           ---GMSNP-ALTMENET------------------------------------------
G7PCM0_MACFA|Macaca               ---GMSNP-ALTMENET------------------------------------------
I2CX55_MACMU|Macaca               ---GMSNP-ALTMENET------------------------------------------
G1QPY3_NOMLE|Nomascus             ---GMSNP-ALTMENES------------------------------------------
G3RL61_GORGO|Gorilla              ---GMSNP-ALTMENET------------------------------------------
ZDHC2_HUMAN|Homo                  ---GMSNP-ALTMENET------------------------------------------
H2QVS6_PANTR|Pan                  ---GMSNP-ALTMENET------------------------------------------
H2PPM5_PONAB|Pongo                ---GMSNP-ALTMENET------------------------------------------
F7CAZ8_HORSE|Equus                ---GMSNP-ALTMENET------------------------------------------
G1NW00_MYOLU|Myotis               ---GMSNP-ALTMENET------------------------------------------
G9KYT2_MUSPF|Mustela              ---GMSNP-ALTMENET------------------------------------------
G1M5B0_AILME|Ailuropoda           ---GMSNP-ALTMENET------------------------------------------
F1SET7_PIG|Sus                    ---GMSNP-ALTMENET------------------------------------------
K7FYZ2_PELSI|Pelodiscus           VPKGMSNP-ALIMENET------------------------------------------
F1NVH3_CHICK|Gallus               ---GMSNP-ALTMENET------------------------------------------
H0ZA87_TAEGU|Taeniopygia          ---GMSNP-ALTMENET------------------------------------------
H2S209_TAKRU|Takifugu             ---GASNP-GMVMEN--------------------------------------------
Q5BLG4_DANRE|Danio                ---GTSNP-ALTIEKET------------------------------------------
G3Q3Z4_GASAC|Gasterosteus         ---GASNQ-GMTIEHEA------------------------------------------
I3KM57_ORENI|Oreochromis          ---GASNP-GMTIENEA------------------------------------------
H2LTT9_ORYLA|Oryzias              ---GDHTPFGLTAETCT------------------------------------------
H3CRV3_TETNG|Tetraodon            ---AESES-IIYIEK--------------------------------------------
G1NQF0_MELGA|Meleagris            ---GTKKHIIVSLES--------------------------------------------
L5L6V4_PTEAL|Pteropus             ---GTHNHGTVAIGNGAPLVHN-------------------------------------
C3XW62_BRAFL|Branchiostoma        ---DVSDRETVPLR---------------------------------------------
L7MB41_9ACAR|Rhipicephalus        ---GMPAP-VSRAEKMHIADGDHPV----------------------------------
G6DE89_DANPL|Danaus               ---FDEL----------------------------------------------------
E2A927_CAMFO|Camponotus           ---DADQP-LMNTTESV------------------------------------------
K7J025_NASVI|Nasonia              -----------------------------------------------------------
B4KLJ9_DROMO|Drosophila           ELEEDFLP-EARFQDSIIP----------------------------------------
B4LM13_DROVI|Drosophila           FGDGISYP-IRHLEEDTESLLGYHSDTRIELEEDFLPEARFQDSIIP------------
B4J5A2_DROGR|Drosophila           FGDGISYP-IRHLEEDTESLLGYHSDTRIELEEDFLPEARFQDSIIP------------
B4GB93_DROPE|Drosophila           -----------------------------------------------------------
B5E0C5_DROPS|Drosophila           -----------------------------------------------------------
B4MQW5_DROWI|Drosophila           ---FLPEP-RFPDQIP-------------------------------------------
B3MD30_DROAN|Drosophila           -------P---------------------------------------------------
B3N6S2_DROER|Drosophila           ---GKTFP-IRHMEEDTESLLGYHSDTRIELEEDFLPEPRFQDSIP-------------
Q7K2V5_DROME|Drosophila           -------P---------------------------------------------------
B4NX32_DROYA|Drosophila           FGDGKTFP-IRHMEEDTESLLGYHSDTRIELEEDFLPEPRFQDSIP-------------
Q7Q7Z4_ANOGA|Anopheles            -----------------------------------------------------------
B0WC84_CULQU|Culex                FTTTTTTS-KLETVNEHKYNHHHHLYDNVQAPVVPPVRHNGTVPNGDVAGGRRRPEDVV
                                                                                             
